import type { Dilemma } from '../types';

export const dilemmas: Dilemma[] = [
  // ——— Fun ———
  { a: 'Parler comme un pirate toute ta vie', b: 'Chanter au lieu de parler toute ta vie', theme: 'fun' },
  { a: 'Avoir un rire de dauphin', b: 'Éternuer comme un lion qui rugit', theme: 'fun' },
  { a: 'Avoir une queue de chat', b: 'Avoir des oreilles de lapin', theme: 'fun' },
  { a: 'Que ta vie soit une comédie musicale', b: 'Que ta vie soit un dessin animé', theme: 'fun' },
  { a: 'Avoir un narrateur qui commente ta vie à voix haute', b: 'Avoir une musique de fond qui suit tes émotions', theme: 'fun' },
  { a: 'Ne plus jamais pouvoir faire de selfie', b: 'Ne plus jamais pouvoir envoyer d\'emoji', theme: 'fun' },
  { a: 'Avoir des cheveux qui changent de couleur selon ton humeur', b: 'Avoir une voix qui change selon ton humeur', theme: 'fun' },
  { a: 'Être le meilleur danseur du monde', b: 'Être le meilleur chanteur du monde', theme: 'fun' },
  { a: 'Faire un câlin à un ours polaire', b: 'Faire un bisou à un crocodile', theme: 'fun' },
  { a: 'Marcher toujours en crabe', b: 'Toujours sautiller au lieu de marcher', theme: 'fun' },
  { a: 'Avoir un pingouin comme meilleur ami', b: 'Avoir un paresseux comme colocataire', theme: 'fun' },
  { a: 'Gagner à tous les jeux de société', b: 'Gagner à tous les jeux vidéo', theme: 'fun' },
  // ——— Anime ———
  { a: 'Vivre dans l\'univers de One Piece', b: 'Vivre dans l\'univers de Naruto', theme: 'anime' },
  { a: 'Avoir le Sharingan', b: 'Avoir les Six Yeux de Gojo', theme: 'anime' },
  { a: 'Manger le fruit du démon de Luffy', b: 'Avoir le Death Note', theme: 'anime' },
  { a: 'Être entraîné par Kakashi', b: 'Être entraîné par All Might', theme: 'anime' },
  { a: 'Faire partie de l\'équipage du Chapeau de paille', b: 'Faire partie du Bataillon d\'exploration', theme: 'anime' },
  { a: 'Avoir Goku comme grand frère', b: 'Avoir Vegeta comme grand frère', theme: 'anime' },
  { a: 'Maîtriser le Nen', b: 'Maîtriser le Souffle de l\'eau', theme: 'anime' },
  { a: 'Aller à l\'Académie Yuei', b: 'Aller au Lycée Jujutsu de Tokyo', theme: 'anime' },
  { a: 'Affronter Madara', b: 'Affronter Sukuna', theme: 'anime' },
  { a: 'Avoir Pikachu comme compagnon', b: 'Avoir Totoro comme voisin', theme: 'anime' },
  { a: 'Manger chez Ichiraku tous les jours', b: 'Manger la cuisine de Sanji tous les jours', theme: 'anime' },
  { a: 'Avoir le cerveau de L', b: 'Avoir la force de Saitama', theme: 'anime' },
  // ——— Pouvoirs ———
  { a: 'Pouvoir voler', b: 'Pouvoir te téléporter', theme: 'pouvoirs' },
  { a: 'Lire dans les pensées', b: 'Voir 10 secondes dans le futur', theme: 'pouvoirs' },
  { a: 'Être invisible quand tu veux', b: 'Pouvoir arrêter le temps 1 minute par jour', theme: 'pouvoirs' },
  { a: 'Parler toutes les langues du monde', b: 'Parler avec les animaux', theme: 'pouvoirs' },
  { a: 'Avoir une super-force', b: 'Avoir une super-vitesse', theme: 'pouvoirs' },
  { a: 'Pouvoir respirer sous l\'eau', b: 'Pouvoir voir dans le noir', theme: 'pouvoirs' },
  { a: 'Pouvoir te cloner', b: 'Pouvoir changer d\'apparence', theme: 'pouvoirs' },
  { a: 'Ne jamais avoir besoin de dormir', b: 'Ne jamais avoir besoin de manger', theme: 'pouvoirs' },
  { a: 'Contrôler le feu', b: 'Contrôler l\'eau', theme: 'pouvoirs' },
  { a: 'Remonter le temps une seule fois', b: 'Voir ton futur une seule fois', theme: 'pouvoirs' },
  { a: 'Avoir un sac sans fond', b: 'Avoir une porte vers n\'importe où', theme: 'pouvoirs' },
  { a: 'Pouvoir apprendre n\'importe quelle compétence en une heure', b: 'Pouvoir revivre n\'importe quelle journée passée', theme: 'pouvoirs' },
  // ——— Quotidien ———
  { a: 'Te lever à 5 h tous les jours', b: 'Te coucher à 21 h tous les jours', theme: 'quotidien' },
  { a: 'Ne plus jamais avoir de devoirs', b: 'Avoir 3 mois de vacances en plus', theme: 'quotidien' },
  { a: 'Avoir toujours 10 % de batterie', b: 'Avoir toujours une connexion lente', theme: 'quotidien' },
  { a: 'Vivre à la campagne', b: 'Vivre en plein centre-ville', theme: 'quotidien' },
  { a: 'Toujours arriver 30 minutes en avance', b: 'Toujours arriver 10 minutes en retard', theme: 'quotidien' },
  { a: 'Avoir un chien', b: 'Avoir un chat', theme: 'quotidien' },
  { a: 'Ne plus jamais utiliser les transports en commun', b: 'Ne plus jamais utiliser de voiture', theme: 'quotidien' },
  { a: 'Faire le ménage pour toute la maison', b: 'Faire la cuisine pour toute la famille', theme: 'quotidien' },
  { a: 'Avoir des voisins très bruyants', b: 'Avoir des voisins très curieux', theme: 'quotidien' },
  { a: 'Porter les mêmes vêtements toute l\'année', b: 'Ne jamais pouvoir porter deux fois la même tenue', theme: 'quotidien' },
  { a: 'Être toujours en été', b: 'Être toujours en hiver', theme: 'quotidien' },
  { a: 'Oublier ton téléphone à la maison', b: 'Oublier tes clés à la maison', theme: 'quotidien' },
  // ——— Extrême ———
  { a: 'Faire un saut en parachute', b: 'Nager avec des requins', theme: 'extrême' },
  { a: 'Passer une nuit seul dans une maison hantée', b: 'Passer une nuit seul dans une forêt', theme: 'extrême' },
  { a: 'Aller dans l\'espace', b: 'Explorer le fond de l\'océan', theme: 'extrême' },
  { a: 'Survivre un mois sur une île déserte', b: 'Survivre un mois au pôle Nord', theme: 'extrême' },
  { a: 'Faire les montagnes russes les plus hautes du monde', b: 'Marcher sur un fil entre deux immeubles (attaché)', theme: 'extrême' },
  { a: 'Être poursuivi par un zombie lent pour toujours', b: 'Être poursuivi par un zombie rapide pendant une heure', theme: 'extrême' },
  { a: 'Vivre sans musique', b: 'Vivre sans films ni séries', theme: 'extrême' },
  { a: 'Gravir l\'Everest', b: 'Traverser le Sahara à pied', theme: 'extrême' },
  { a: 'Ne plus jamais pouvoir mentir', b: 'Ne plus jamais pouvoir garder un secret', theme: 'extrême' },
  { a: 'Perdre tous tes souvenirs', b: 'Ne plus jamais pouvoir créer de nouveaux souvenirs', theme: 'extrême' },
  { a: 'Vivre 200 ans', b: 'Vivre 80 ans mais en étant riche', theme: 'extrême' },
  { a: 'Tout savoir sur tout le monde', b: 'Que personne ne sache rien sur toi', theme: 'extrême' },
  // ——— Bouffe ———
  { a: 'Manger que de la pizza toute ta vie', b: 'Manger que des burgers toute ta vie', theme: 'bouffe' },
  { a: 'Ne plus jamais manger de chocolat', b: 'Ne plus jamais manger de fromage', theme: 'bouffe' },
  { a: 'Manger du thiéboudienne tous les jours', b: 'Manger des sushis tous les jours', theme: 'bouffe' },
  { a: 'Ne plus jamais boire de soda', b: 'Ne plus jamais manger de bonbons', theme: 'bouffe' },
  { a: 'Tout manger trop épicé', b: 'Tout manger sans sel', theme: 'bouffe' },
  { a: 'Un tacos XL tous les jours', b: 'Un bol de ramen tous les jours', theme: 'bouffe' },
  { a: 'Avoir un chef cuisinier personnel', b: 'Avoir un pâtissier personnel', theme: 'bouffe' },
  { a: 'Manger que des plats froids', b: 'Manger que des plats tièdes', theme: 'bouffe' },
  { a: 'Ne plus jamais manger de frites', b: 'Ne plus jamais manger de riz', theme: 'bouffe' },
  { a: 'Petit-déjeuner avec des crêpes à vie', b: 'Petit-déjeuner avec des croissants à vie', theme: 'bouffe' },
  { a: 'Boire que du bissap', b: 'Boire que du jus d\'orange', theme: 'bouffe' },
  { a: 'Manger une glace en plein hiver', b: 'Boire un chocolat chaud en pleine canicule', theme: 'bouffe' },
  // ——— Tech ———
  { a: 'Ne plus jamais utiliser TikTok', b: 'Ne plus jamais utiliser YouTube', theme: 'tech' },
  { a: 'Avoir la meilleure console du monde', b: 'Avoir le meilleur PC gamer du monde', theme: 'tech' },
  { a: 'Que tout le monde voie ton historique de recherche', b: 'Que tout le monde lise tes messages', theme: 'tech' },
  { a: 'Avoir un robot qui fait tes devoirs', b: 'Avoir un robot qui range ta chambre', theme: 'tech' },
  { a: 'Avoir un million d\'abonnés', b: 'Avoir un million d\'euros', theme: 'tech' },
  { a: 'Vivre sans téléphone', b: 'Vivre sans ordinateur', theme: 'tech' },
  { a: 'Être un streamer célèbre', b: 'Être un joueur e-sport champion du monde', theme: 'tech' },
  { a: 'Ne jouer qu\'à un seul jeu vidéo pour toujours', b: 'Changer de jeu vidéo chaque jour sans jamais finir', theme: 'tech' },
];
