import type { PersonaFacts } from '../types';

export const personaFacts: Record<string, PersonaFacts> = {
  parano: {
    truths: [
      'Je vérifie trois fois que la porte est fermée avant de dormir.',
      'J\'ai mis un scotch sur la caméra de mon ordinateur.',
      'Je change mes mots de passe tous les mois.',
      'Je m\'assois toujours face à la porte au restaurant.',
      'J\'ai déjà quitté un groupe WhatsApp parce que je trouvais ça louche.',
      'Je garde une lampe torche sous mon lit.',
      'Je n\'accepte jamais les cookies sur les sites internet.',
      'J\'ai déjà cru qu\'un pigeon me suivait dans la rue.',
    ],
    lies: [
      'J\'ai déjà prêté mon téléphone déverrouillé à un inconnu.',
      'Je poste ma localisation en story tous les jours.',
      'J\'ai déjà dormi la fenêtre grande ouverte en ville.',
      'Je laisse toujours mes clés sur la porte.',
      'J\'ai déjà fait du stop tout seul à l\'étranger.',
      'Je n\'ai aucun mot de passe sur mon téléphone.',
      'J\'ai déjà ouvert un lien reçu par un numéro inconnu.',
      'Je donne mon vrai nom à tout le monde en ligne.',
    ],
  },
  discret: {
    truths: [
      'Je suis déjà parti d\'une soirée sans dire au revoir.',
      'J\'ai déjà mangé tout seul dans les toilettes pour être tranquille.',
      'Je mets mon téléphone en silencieux en permanence.',
      'J\'ai déjà passé une journée entière sans dire un mot.',
      'Je préfère écrire un message plutôt qu\'appeler.',
      'J\'ai un compte Instagram sans aucune photo.',
      'Je m\'assois toujours au fond de la classe.',
      'J\'ai déjà fait semblant de téléphoner pour éviter quelqu\'un.',
    ],
    lies: [
      'J\'ai déjà chanté seul sur scène devant tout le lycée.',
      'J\'ai déjà été délégué de classe trois années de suite.',
      'J\'adore être le centre de l\'attention aux anniversaires.',
      'J\'ai déjà fait une vidéo TikTok qui a fait un million de vues.',
      'J\'ai déjà pris la parole à un mariage devant 200 personnes.',
      'J\'ai déjà organisé une fête surprise pour 50 personnes.',
      'Je parle facilement aux inconnus dans le bus.',
      'J\'ai déjà fait un discours au micro dans un stade.',
    ],
  },
  bluffeur: {
    truths: [
      'J\'ai déjà gagné une partie de poker avec une main nulle.',
      'J\'ai déjà fait croire à ma famille que j\'avais un cousin célèbre.',
      'J\'ai déjà réussi un oral sans avoir révisé.',
      'J\'ai déjà convaincu un ami que les pingouins pouvaient voler.',
      'J\'ai déjà fait semblant de connaître une chanson pendant tout un concert.',
      'J\'ai déjà bluffé à Loup-Garou et survécu jusqu\'à la fin.',
      'J\'ai déjà négocié le prix d\'un t-shirt en magasin.',
      'J\'ai déjà prétendu avoir vu un film pour participer à la discussion.',
    ],
    lies: [
      'Je rougis dès que je dis un mensonge.',
      'Je perds toujours au jeu du Menteur.',
      'Je n\'ai jamais inventé d\'excuse pour un retard.',
      'Je suis incapable de garder mon sérieux quand je blague.',
      'J\'avoue toujours tout à mes parents tout de suite.',
      'Je n\'ai jamais joué au poker de ma vie.',
      'Je déteste les jeux où il faut mentir.',
      'Mes amis devinent toujours quand je leur cache quelque chose.',
    ],
  },
  leader: {
    truths: [
      'J\'ai été capitaine de mon équipe de foot pendant deux ans.',
      'J\'ai déjà organisé un voyage entre amis de A à Z.',
      'Je suis toujours celui qui choisit le restaurant.',
      'J\'ai été délégué de classe au collège.',
      'J\'ai déjà mené un exposé de groupe tout seul parce que personne ne bossait.',
      'Je fais toujours les plannings de révision pour tout le monde.',
      'J\'ai déjà créé un club à mon lycée.',
      'J\'ai déjà arbitré une dispute entre deux amis.',
    ],
    lies: [
      'Je laisse toujours les autres décider à ma place.',
      'Je n\'ai jamais pris la parole en réunion.',
      'Je déteste organiser quoi que ce soit.',
      'J\'ai toujours été remplaçant dans mes équipes de sport.',
      'Je suis souvent en retard aux rendez-vous que je fixe.',
      'Je n\'ai jamais été choisi comme chef d\'équipe.',
      'J\'ai peur de donner mon avis en groupe.',
      'Je suis toujours le dernier à savoir ce qui se passe.',
    ],
  },
  suiveur: {
    truths: [
      'J\'ai commencé une série uniquement parce que tout le monde en parlait.',
      'Je commande souvent la même chose que la personne avant moi.',
      'J\'ai déjà changé de coiffure parce que mon ami l\'avait fait.',
      'J\'ai acheté les mêmes baskets que mon meilleur ami.',
      'Je dis souvent « comme vous voulez » quand on choisit un film.',
      'Je me suis inscrit au basket parce que mes potes y allaient.',
      'J\'ai déjà voté pour une idée juste parce que la majorité était d\'accord.',
      'J\'écoute surtout les musiques qui sont dans les tendances.',
    ],
    lies: [
      'J\'ai déjà convaincu toute ma classe de changer de sortie scolaire.',
      'Je choisis toujours le restaurant quand on sort entre amis.',
      'J\'ai lancé une mode vestimentaire dans mon lycée.',
      'Je refuse de regarder une série si elle est populaire.',
      'J\'ai été chef scout pendant trois ans.',
      'Je suis toujours le premier à essayer les nouveaux trucs.',
      'J\'ai déjà créé une association tout seul.',
      'Je contredis souvent mes amis pour le plaisir.',
    ],
  },
  chaotique: {
    truths: [
      'J\'ai déjà mis du ketchup sur des crêpes pour voir.',
      'J\'ai déjà pris un train sans savoir où il allait.',
      'J\'ai déjà teint mes cheveux en bleu sur un coup de tête.',
      'J\'ai déjà cassé une fenêtre en jouant au foot dans le salon.',
      'Je fais mes devoirs la veille à minuit, toujours.',
      'J\'ai déjà adopté un poisson rouge sans prévenir mes parents.',
      'J\'ai déjà perdu trois téléphones en une seule année.',
      'J\'ai déjà mangé une pizza au petit-déjeuner avant un examen.',
    ],
    lies: [
      'Je range ma chambre tous les dimanches matin.',
      'J\'ai un agenda où je note tout avec des couleurs.',
      'Je n\'ai jamais perdu mes clés.',
      'Je prépare mon sac la veille au soir.',
      'Je suis toujours en avance à l\'école.',
      'Je fais un planning de mes repas pour la semaine.',
      'Je n\'ai jamais cassé d\'objet chez quelqu\'un.',
      'Je plie mes vêtements par couleur dans mon armoire.',
    ],
  },
  intello: {
    truths: [
      'J\'ai déjà lu tout One Piece en une semaine.',
      'Je connais les capitales de tous les pays d\'Afrique.',
      'J\'ai déjà gagné un concours de calcul mental.',
      'J\'ai lu Harry Potter en anglais avant la traduction.',
      'Je regarde des documentaires sur l\'espace pour m\'endormir.',
      'J\'ai appris à coder tout seul à 12 ans.',
      'J\'ai déjà corrigé une faute de mon prof de français.',
      'Je sais résoudre un Rubik\'s Cube en moins de deux minutes.',
    ],
    lies: [
      'J\'ai déjà redoublé une classe.',
      'Je n\'ai jamais fini un livre en entier.',
      'J\'ai eu 4 sur 20 à mon dernier contrôle de maths.',
      'Je ne sais pas placer le Japon sur une carte.',
      'Je déteste les musées.',
      'Je n\'ai jamais regardé un seul documentaire.',
      'J\'ai triché à mon dernier examen.',
      'Je trouve les échecs trop compliqués.',
    ],
  },
  drole: {
    truths: [
      'J\'ai déjà fait rire un prof pendant qu\'il me grondait.',
      'J\'ai une collection de blagues nulles dans mes notes.',
      'J\'ai déjà imité le directeur devant toute la classe.',
      'J\'ai déjà fait un spectacle de stand-up à une fête de famille.',
      'Je fais des imitations de personnages d\'anime.',
      'J\'ai déjà ri tellement fort au cinéma qu\'on m\'a demandé de sortir.',
      'J\'ai déjà mis un déguisement de banane pour un pari.',
      'Mon surnom au collège était « le comique ».',
    ],
    lies: [
      'Je ne comprends jamais les blagues du premier coup.',
      'Je déteste les comédies.',
      'Je n\'ai jamais fait de farce à personne.',
      'Je reste sérieux même quand tout le monde rigole.',
      'On m\'a déjà dit que j\'étais trop sérieux.',
      'Je n\'ai jamais eu de fou rire en classe.',
      'Je trouve les mèmes pas drôles.',
      'Je n\'aime pas faire l\'intéressant en soirée.',
    ],
  },
  timide: {
    truths: [
      'J\'ai déjà répété une commande dix fois dans ma tête avant de la dire.',
      'Je rougis quand on me dit bonjour dans la rue.',
      'J\'ai déjà raté mon arrêt de bus parce que je n\'osais pas appuyer.',
      'J\'ai déjà mangé un plat que je n\'avais pas commandé sans rien dire.',
      'Je préfère envoyer un message vocal que parler en face.',
      'J\'ai déjà fait semblant de dormir pour éviter une conversation.',
      'Je n\'ose jamais lever la main en classe.',
      'J\'ai déjà attendu que le vendeur parte pour regarder un rayon.',
    ],
    lies: [
      'J\'ai déjà demandé un autographe à une star en pleine rue.',
      'J\'ai déjà fait du karaoké seul devant des inconnus.',
      'J\'adore faire des exposés à l\'oral.',
      'J\'ai déjà été présentateur d\'un spectacle d\'école.',
      'Je parle facilement aux nouveaux élèves.',
      'J\'ai déjà réclamé au serveur un plat mal cuit.',
      'J\'ai déjà dansé seul au milieu d\'une piste.',
      'J\'ai déjà passé un casting pour une pub.',
    ],
  },
  competitif: {
    truths: [
      'J\'ai déjà boudé une journée entière après une défaite au Uno.',
      'J\'ai gagné un tournoi de FIFA dans mon quartier.',
      'Je chronomètre mes trajets pour battre mon record.',
      'J\'ai déjà recommencé un niveau cinquante fois pour avoir trois étoiles.',
      'J\'ai déjà refusé de laisser gagner mon petit cousin.',
      'Je compte les points même quand on joue juste pour s\'amuser.',
      'J\'ai déjà couru pour arriver le premier à la cantine.',
      'J\'ai un classement de mes amis au Mario Kart.',
    ],
    lies: [
      'Je laisse souvent gagner les autres pour leur faire plaisir.',
      'Je n\'ai jamais joué à un jeu vidéo en ligne.',
      'Perdre ne me dérange pas du tout.',
      'Je n\'ai jamais participé à un tournoi.',
      'Je ne connais pas mes propres scores.',
      'J\'abandonne vite quand un jeu est trop dur.',
      'Je déteste le sport.',
      'Je ne regarde jamais le classement à la fin d\'une partie.',
    ],
  },
};
