import type { Pack } from '../types';

export const pack: Pack = {
  id: 'anime-pouvoirs',
  name: 'Pouvoirs & objets d’anime',
  emoji: '✨',
  category: 'anime',
  description: 'Techniques, pouvoirs, objets mythiques et organisations des animes cultes.',
  attributes: [
    { tag: 'technique', question: 'Est-ce une technique de combat ?' },
    { tag: 'pouvoir', question: 'Est-ce un pouvoir ou une capacité ?' },
    { tag: 'objet', question: 'Est-ce un objet ?' },
    { tag: 'organisation', question: 'Est-ce un groupe ou une organisation ?' },
    { tag: 'transformation', question: 'Est-ce une transformation ?' },
    { tag: 'créature', question: 'Est-ce une créature ou un être vivant ?' },
    { tag: 'oculaire', question: 'Est-ce lié aux yeux ?' },
    { tag: 'énergie', question: 'Est-ce basé sur une énergie intérieure ?' },
    { tag: 'feu', question: 'Est-ce lié au feu ?' },
    { tag: 'signature', question: 'Est-ce la technique signature d’un héros ?' },
    { tag: 'entraînement', question: 'S’obtient-il par l’entraînement ?' },
    { tag: 'quête', question: 'Est-ce l’objet d’une quête ?' },
    { tag: 'dangereux', question: 'Est-ce une menace dangereuse ?' },
    { tag: 'épée', question: 'Est-ce lié aux épées ?' },
    { tag: 'méchants', question: 'Est-ce associé aux méchants ?' },
    { tag: 'héros', question: 'Est-ce associé aux héros ?' },
    { tag: 'héréditaire', question: 'Se transmet-il par le sang ou l’héritage ?' },
    { tag: 'ultime', question: 'Est-ce le niveau ultime ou le plus puissant de son univers ?' },
    { tag: 'contrôle-mental', question: 'Permet-il de contrôler ou manipuler l’esprit ?' },
    { tag: 'immortalité', question: 'Est-ce lié à l’immortalité ou à la résurrection ?' },
    { tag: 'invocation', question: 'Permet-il d’invoquer quelque chose ?' },
    { tag: 'magie', question: 'Est-ce de la magie ou de la sorcellerie ?' },
    { tag: 'projectile', question: 'Est-ce une attaque lancée à distance ?' },
    { tag: 'force', question: 'Augmente-t-il la force physique ?' },
    { tag: 'collection', question: 'Faut-il en rassembler plusieurs ?' },
    { tag: 'mort', question: 'Est-ce lié à la mort ?' },
    { tag: 'vitesse', question: 'Est-ce lié à la vitesse ?' },
    { tag: 'rare', question: 'Est-ce extrêmement rare ?' },
    { tag: 'naruto', question: 'Vient-il de Naruto ?' },
    { tag: 'one-piece', question: 'Vient-il de One Piece ?' },
    { tag: 'dragon-ball', question: 'Vient-il de Dragon Ball ?' },
    { tag: 'bleach', question: 'Vient-il de Bleach ?' },
    { tag: 'jujutsu-kaisen', question: 'Vient-il de Jujutsu Kaisen ?' },
    { tag: 'demon-slayer', question: 'Vient-il de Demon Slayer ?' },
    { tag: 'attaque-des-titans', question: 'Vient-il de L’Attaque des Titans ?' },
    { tag: 'my-hero-academia', question: 'Vient-il de My Hero Academia ?' },
    { tag: 'hunter-x-hunter', question: 'Vient-il de Hunter x Hunter ?' },
    { tag: 'fullmetal-alchemist', question: 'Vient-il de Fullmetal Alchemist ?' },
    { tag: 'jojo', question: 'Vient-il de JoJo’s Bizarre Adventure ?' },
    { tag: 'pokemon', question: 'Vient-il de Pokémon ?' },
  ],
  items: [
    // ——— Naruto ———
    {
      name: 'Sharingan',
      aliases: ['Mangekyō Sharingan', 'Mangekyo Sharingan'],
      emoji: '👁️🔴🌀',
      group: 'Naruto',
      tags: ['pouvoir', 'oculaire', 'héréditaire', 'contrôle-mental', 'rare', 'méchants', 'héros', 'naruto'],
      clues: [
        'Un œil qui change de couleur',
        'Permet de copier les techniques',
        'Se transmet dans un seul clan',
        'Tomoe noirs sur fond rouge',
        'Pouvoir oculaire des Uchiha',
      ],
    },
    {
      name: 'Rasengan',
      aliases: ['Orbe tourbillonnant'],
      emoji: '🌀🔵✋',
      group: 'Naruto',
      tags: ['technique', 'énergie', 'héros', 'projectile', 'naruto', 'signature', 'offensif'],
      clues: [
        'Une sphère d’énergie dans la paume',
        'Inventée par le Quatrième Hokage',
        'Sa version améliorée ressemble à un shuriken',
        'Souvent faite avec l’aide d’un clone',
        'Technique signature de Naruto',
      ],
    },
    {
      name: 'Chidori',
      aliases: ['Raikiri'],
      emoji: '⚡🐦✋',
      group: 'Naruto',
      tags: ['technique', 'énergie', 'foudre', 'vitesse', 'naruto', 'signature', 'offensif', 'héros'],
      clues: [
        'Le bruit de mille oiseaux',
        'Une main chargée d’électricité',
        'Créée par Kakashi',
        'Enseignée à Sasuke',
        'Technique de foudre de Naruto',
      ],
    },
    {
      name: 'Akatsuki',
      aliases: ['L’Aube'],
      emoji: '☁️🔴🖤',
      group: 'Naruto',
      tags: ['organisation', 'méchants', 'rare', 'naruto', 'dangereux', 'légendaire', 'collection'],
      clues: [
        'Des manteaux noirs à nuages rouges',
        'Des criminels de rang S',
        'Chasse les démons à queues',
        'Itachi, Deidara et Pain en font partie',
        'Organisation ennemie de Naruto',
      ],
    },
    {
      name: 'Kyûbi',
      aliases: ['Kyubi', 'Kurama', 'Démon renard à neuf queues'],
      emoji: '🦊🔥9️⃣',
      group: 'Naruto',
      tags: ['créature', 'énergie', 'force', 'transformation', 'rare', 'naruto', 'dangereux', 'légendaire'],
      clues: [
        'Une bête gigantesque et furieuse',
        'A attaqué un village le jour d’une naissance',
        'Scellée dans le ventre d’un enfant',
        'Le plus puissant des démons à queues',
        'Partenaire de Naruto',
      ],
    },
    {
      name: 'Multi-clonage',
      aliases: ['Kage Bunshin', 'Clonage de l’ombre', 'Multi Clonage'],
      emoji: '👥👥💨',
      group: 'Naruto',
      tags: ['technique', 'invocation', 'énergie', 'héros', 'naruto', 'signature', 'entraînement'],
      clues: [
        'Une technique interdite apprise dans un rouleau',
        'Crée des copies de soi',
        'Les souvenirs reviennent à l’original',
        'Disparaît dans un nuage de fumée',
        'Technique préférée de Naruto',
      ],
    },
    // ——— One Piece ———
    {
      name: 'Gomu Gomu no Mi',
      aliases: ['Fruit du Gum-Gum', 'Hito Hito no Mi modèle Nika'],
      emoji: '🍈🌀💪',
      group: 'One Piece',
      tags: ['objet', 'pouvoir', 'transformation', 'héros', 'rare', 'one-piece', 'signature', 'corps'],
      clues: [
        'Un fruit au goût horrible',
        'Rend le corps élastique',
        'Protège de l’électricité',
        'Cache une forme divine',
        'Pouvoir de Luffy dans One Piece',
      ],
    },
    {
      name: 'Fruit du Démon',
      aliases: ['Akuma no Mi', 'Fruits du Démon'],
      emoji: '🍎🌀🌊',
      group: 'One Piece',
      tags: ['objet', 'pouvoir', 'rare', 'collection', 'méchants', 'héros', 'one-piece'],
      clues: [
        'Un aliment aux motifs en spirale',
        'Donne un pouvoir unique',
        'Rend incapable de nager',
        'Logia, Paramecia ou Zoan',
        'Objets mythiques de One Piece',
      ],
    },
    {
      name: 'Haki',
      aliases: ['Fluide'],
      emoji: '👑⚫💢',
      group: 'One Piece',
      tags: ['pouvoir', 'énergie', 'force', 'rare', 'héros', 'méchants', 'one-piece'],
      clues: [
        'Une volonté transformée en force',
        'Existe en trois types',
        'Peut noircir les membres',
        'Celui des rois assomme les faibles',
        'Force spirituelle de One Piece',
      ],
    },
    {
      name: 'Le One Piece',
      aliases: ['One Piece'],
      emoji: '💰🗺️🏝️',
      group: 'One Piece',
      tags: ['objet', 'rare', 'ultime', 'one-piece', 'légendaire', 'quête', 'emblème'],
      clues: [
        'Un trésor légendaire',
        'Caché sur la dernière île',
        'Annoncé par un roi avant son exécution',
        'Laissé par Gol D. Roger',
        'Donne son nom à la série',
      ],
    },
    {
      name: 'Équipage du Chapeau de paille',
      aliases: ['Mugiwara', 'Chapeaux de paille'],
      emoji: '👒🏴‍☠️⛵',
      group: 'One Piece',
      tags: ['organisation', 'héros', 'one-piece', 'amitié', 'emblème', 'légendaire', 'quête'],
      clues: [
        'Une bande hétéroclite de marginaux',
        'Un cuisinier, un renne, un squelette musicien',
        'Navigue sur le Thousand Sunny',
        'Mené par un garçon élastique',
        'Équipage de Luffy',
      ],
    },
    // ——— Dragon Ball ———
    {
      name: 'Super Saiyan',
      aliases: ['Super Saïyen', 'SSJ', 'Super Guerrier'],
      emoji: '💛⚡😤',
      group: 'Dragon Ball',
      tags: ['transformation', 'énergie', 'force', 'héréditaire', 'héros', 'dragon-ball', 'légendaire', 'signature'],
      clues: [
        'Déclenchée par une immense colère',
        'Les yeux deviennent turquoise',
        'Cheveux dorés dressés',
        'Apparue face à Freezer sur Namek',
        'Transformation de Goku',
      ],
    },
    {
      name: 'Kamehameha',
      aliases: ['Kaméhaméha', 'Kame Hame Ha'],
      emoji: '🐢🔵💥',
      group: 'Dragon Ball',
      tags: ['technique', 'énergie', 'projectile', 'héros', 'dragon-ball', 'signature', 'offensif', 'entraînement'],
      clues: [
        'Un rayon lancé à deux mains',
        'On le charge au niveau des hanches',
        'Inventé par un vieil ermite',
        'Tortue Géniale l’a enseigné',
        'Attaque signature de Goku',
      ],
    },
    {
      name: 'Dragon Balls',
      aliases: ['Boules de cristal', 'Boules du dragon'],
      emoji: '🟠⭐🐉',
      group: 'Dragon Ball',
      tags: ['objet', 'collection', 'immortalité', 'invocation', 'rare', 'dragon-ball', 'quête', 'légendaire'],
      clues: [
        'Des sphères orange étoilées',
        'Il en faut sept',
        'Invoquent un dragon',
        'Exaucent un vœu, même ressusciter',
        'Objets qui nomment Dragon Ball',
      ],
    },
    {
      name: 'Nuage magique',
      aliases: ['Kinto-un', 'Kintoun', 'Nimbus'],
      emoji: '☁️🟡🧒',
      group: 'Dragon Ball',
      tags: ['objet', 'vitesse', 'héros', 'rare', 'dragon-ball', 'légendaire', 'emblème'],
      clues: [
        'Un moyen de transport jaune',
        'Seuls les cœurs purs peuvent monter dessus',
        'Appelé en criant son nom',
        'Offert par Tortue Géniale',
        'Véhicule de Goku enfant',
      ],
    },
    {
      name: 'Fusion',
      aliases: ['Fusion Metamor'],
      emoji: '👉👈🕺',
      group: 'Dragon Ball',
      tags: ['technique', 'transformation', 'force', 'héros', 'dragon-ball', 'entraînement', 'rare'],
      clues: [
        'Deux guerriers n’en font plus qu’un',
        'Une danse synchronisée',
        'Les doigts doivent se toucher',
        'Ou des boucles d’oreilles Potara',
        'Donne Gotenks ou Gogeta',
      ],
    },
    {
      name: 'Genkidama',
      aliases: ['Spirit Bomb', 'Genki Dama'],
      emoji: '🙌🌍🔵',
      group: 'Dragon Ball',
      tags: ['technique', 'énergie', 'projectile', 'ultime', 'héros', 'dragon-ball', 'offensif', 'entraînement'],
      clues: [
        'Demande de lever les bras au ciel',
        'Rassemble l’énergie de tous les êtres vivants',
        'Longue à préparer',
        'Apprise auprès de Maître Kaio',
        'A vaincu Boo',
      ],
    },
    // ——— Bleach ———
    {
      name: 'Bankai',
      aliases: ['Ban-kai'],
      emoji: '⚔️🌑💥',
      group: 'Bleach',
      tags: ['technique', 'transformation', 'épée', 'ultime', 'rare', 'bleach', 'entraînement', 'offensif'],
      clues: [
        'Un nom crié avant de se transformer',
        'Libération finale d’un sabre',
        'Demande dix ans d’entraînement',
        'Tensa Zangetsu en est un exemple',
        'Pouvoir ultime des shinigamis de Bleach',
      ],
    },
    {
      name: 'Gotei 13',
      aliases: ['Les 13 divisions', 'Treize divisions de la cour'],
      emoji: '1️⃣3️⃣🏯⚔️',
      group: 'Bleach',
      tags: ['organisation', 'épée', 'héros', 'mort', 'bleach', 'emblème', 'légendaire'],
      clues: [
        'Une armée divisée en unités',
        'Chaque unité a un capitaine',
        'Protège la Soul Society',
        'Uniforme noir et haori blanc',
        'Armée des shinigamis de Bleach',
      ],
    },
    {
      name: 'Hollow',
      aliases: ['Hollows'],
      emoji: '💀🕳️👹',
      group: 'Bleach',
      tags: ['créature', 'transformation', 'méchants', 'mort', 'bleach', 'dangereux', 'démoniaque'],
      clues: [
        'Âmes corrompues',
        'Un trou dans la poitrine',
        'Portent un masque blanc',
        'Dévorent les âmes des vivants',
        'Monstres de Bleach',
      ],
    },
    // ——— Jujutsu Kaisen ———
    {
      name: 'Extension du territoire',
      aliases: ['Domain Expansion', 'Ryōiki Tenkai', 'Extension de territoire'],
      emoji: '🌌🤞🏯',
      group: 'Jujutsu Kaisen',
      tags: ['technique', 'magie', 'ultime', 'rare', 'jujutsu-kaisen', 'offensif', 'entraînement'],
      clues: [
        'Crée un espace fermé',
        'Les attaques y touchent à coup sûr',
        'Se lance avec un signe des mains',
        'Sanctuaire malveillant, Vide infini',
        'Technique ultime de Jujutsu Kaisen',
      ],
    },
    {
      name: 'Énergie occulte',
      aliases: ['Cursed Energy', 'Énergie maudite'],
      emoji: '🟣😡🌀',
      group: 'Jujutsu Kaisen',
      tags: ['pouvoir', 'énergie', 'magie', 'jujutsu-kaisen', 'dangereux', 'inné', 'démoniaque'],
      clues: [
        'Née des émotions négatives',
        'Tout le monde en produit un peu',
        'Carburant des techniques des exorcistes',
        'Donne naissance aux fléaux',
        'Base du système de Jujutsu Kaisen',
      ],
    },
    {
      name: 'Doigts de Sukuna',
      aliases: ['Doigt de Sukuna', 'Doigts maudits'],
      emoji: '☝️🩸📦',
      group: 'Jujutsu Kaisen',
      tags: ['objet', 'collection', 'méchants', 'rare', 'jujutsu-kaisen', 'quête', 'dangereux', 'démoniaque'],
      clues: [
        'Une relique momifiée',
        'Il en existe vingt',
        'Poison mortel pour les humains',
        'Avalé par un lycéen',
        'Restes du roi des fléaux',
      ],
    },
    {
      name: 'Infini',
      aliases: ['Mugen', 'Limitless', 'Illimité'],
      emoji: '♾️✋🛑',
      group: 'Jujutsu Kaisen',
      tags: ['pouvoir', 'magie', 'héréditaire', 'rare', 'héros', 'jujutsu-kaisen', 'défensif', 'inné'],
      clues: [
        'Rien ne peut le toucher',
        'Ralentit tout à l’approche',
        'Couplé aux Six Yeux',
        'Bleu, Rouge et Violet',
        'Pouvoir de Satoru Gojo',
      ],
    },
    // ——— Demon Slayer ———
    {
      name: 'Souffle',
      aliases: ['Respiration', 'Kokyū'],
      emoji: '🌬️🌊🔥',
      group: 'Demon Slayer',
      tags: ['technique', 'épée', 'énergie', 'héros', 'demon-slayer', 'feu', 'entraînement', 'signature'],
      clues: [
        'Tout commence par l’inspiration',
        'Décuple les capacités physiques',
        'Eau, flamme, foudre, bête…',
        'Le premier était celui du soleil',
        'Art martial des pourfendeurs',
      ],
    },
    {
      name: 'Corps des pourfendeurs de démons',
      aliases: ['Pourfendeurs de démons', 'Demon Slayer Corps', 'Kisatsutai'],
      emoji: '🗡️👹🐦‍⬛',
      group: 'Demon Slayer',
      tags: ['organisation', 'héros', 'épée', 'demon-slayer', 'amitié', 'emblème', 'entraînement'],
      clues: [
        'Organisation non officielle',
        'Des corbeaux transmettent les missions',
        'Les Piliers sont les plus forts',
        'Dirigée par la famille Ubuyashiki',
        'Organisation de Tanjiro',
      ],
    },
    {
      name: 'Lunes démoniaques',
      aliases: ['Kizuki'],
      emoji: '🌙👹1️⃣2️⃣',
      group: 'Demon Slayer',
      tags: ['organisation', 'méchants', 'immortalité', 'rare', 'demon-slayer', 'dangereux', 'démoniaque'],
      clues: [
        'Douze membres classés',
        'Leur rang est gravé dans leurs yeux',
        'Supérieures et inférieures',
        'Akaza et Kokushibo en font partie',
        'Démons d’élite de Muzan',
      ],
    },
    {
      name: 'Sabre Nichirin',
      aliases: ['Nichirin', 'Lame Nichirin'],
      emoji: '🗡️☀️🎨',
      group: 'Demon Slayer',
      tags: ['objet', 'arme', 'épée', 'héros', 'demon-slayer', 'emblème', 'offensif'],
      clues: [
        'Forgé dans un minerai spécial',
        'Change de couleur selon son porteur',
        'Seule arme qui tue en décapitant',
        'Absorbe la lumière du soleil',
        'Arme des pourfendeurs',
      ],
    },
    // ——— L'Attaque des Titans ———
    {
      name: 'Titan Colossal',
      aliases: ['Colossal'],
      emoji: '🧱🔥🦴',
      group: 'L’Attaque des Titans',
      tags: ['créature', 'transformation', 'feu', 'force', 'héréditaire', 'rare', 'attaque-des-titans'],
      clues: [
        'Apparaît au-dessus d’un mur',
        'Plus de 60 mètres de haut',
        'Sans peau, dégage une vapeur brûlante',
        'L’un des neuf Titans',
        'Porté par Berthold puis Armin',
      ],
    },
    {
      name: 'Titan Assaillant',
      aliases: ['Attack Titan'],
      emoji: '🦷💢🔑',
      group: 'L’Attaque des Titans',
      tags: ['créature', 'transformation', 'force', 'héréditaire', 'rare', 'héros', 'attaque-des-titans'],
      clues: [
        'A toujours combattu pour la liberté',
        'Voit les souvenirs de ses héritiers futurs',
        'Longs cheveux et dents apparentes',
        'L’un des neuf Titans',
        'Pouvoir d’Eren',
      ],
    },
    {
      name: 'Bataillon d’exploration',
      aliases: ['Survey Corps', 'Légion d’exploration', 'Bataillon d’Exploration'],
      emoji: '🪽🐎🧭',
      group: 'L’Attaque des Titans',
      tags: ['organisation', 'héros', 'épée', 'attaque-des-titans', 'amitié', 'emblème', 'légendaire'],
      clues: [
        'Ose sortir de derrière les murs',
        'Taux de mortalité énorme',
        'Emblème : les ailes de la liberté',
        'Dirigé par Erwin Smith',
        'Livai en est le caporal',
      ],
    },
    {
      name: 'Équipement tridimensionnel',
      aliases: ['Équipement de manœuvre tridimensionnelle', 'ODM', '3DMG'],
      emoji: '🪝💨🗡️',
      group: 'L’Attaque des Titans',
      tags: ['objet', 'arme', 'épée', 'vitesse', 'héros', 'attaque-des-titans', 'entraînement'],
      clues: [
        'Fonctionne au gaz',
        'Des grappins accrochés aux murs',
        'Permet de voler entre les arbres',
        'Lames pour trancher les nuques',
        'Matériel des soldats face aux Titans',
      ],
    },
    // ——— My Hero Academia ———
    {
      name: 'One For All',
      aliases: ['OFA'],
      emoji: '💪⚡🔁',
      group: 'My Hero Academia',
      tags: ['pouvoir', 'force', 'énergie', 'héros', 'rare', 'my-hero-academia', 'héréditaire', 'signature'],
      clues: [
        'Un pouvoir qui se transmet',
        'Il faut manger un cheveu',
        'Accumule la force de chaque porteur',
        'Brise les os au début',
        'Hérité par Deku d’All Might',
      ],
    },
    {
      name: 'All For One',
      aliases: ['AFO'],
      emoji: '🖐️🎭😈',
      group: 'My Hero Academia',
      tags: ['pouvoir', 'méchants', 'rare', 'ultime', 'my-hero-academia', 'dangereux', 'légendaire'],
      clues: [
        'Vole les pouvoirs des autres',
        'Peut aussi les donner',
        'Son porteur vit depuis des siècles',
        'Grand ennemi d’All Might',
        'Opposé de One For All',
      ],
    },
    {
      name: 'Alter',
      aliases: ['Quirk', 'Kosei', 'Alters'],
      emoji: '🧬🦸✨',
      group: 'My Hero Academia',
      tags: ['pouvoir', 'héréditaire', 'héros', 'méchants', 'my-hero-academia', 'inné', 'offensif'],
      clues: [
        'Apparaît vers 4 ans',
        '80 % de la population en possède',
        'Se transmet souvent des parents',
        'Explosion, Demi-froid demi-chaud…',
        'Nom des super-pouvoirs dans My Hero Academia',
      ],
    },
    // ——— Hunter x Hunter ———
    {
      name: 'Nen',
      emoji: '🌀💧🃏',
      group: 'Hunter x Hunter',
      tags: ['pouvoir', 'énergie', 'rare', 'hunter-x-hunter', 'entraînement', 'offensif', 'défensif'],
      clues: [
        'L’aura vitale maîtrisée',
        'Six catégories',
        'Test du verre d’eau et de la feuille',
        'Ten, Zetsu, Ren, Hatsu',
        'Système de pouvoir de Hunter x Hunter',
      ],
    },
    {
      name: 'Brigade fantôme',
      aliases: ['Genei Ryodan', 'Troupe fantôme', 'Phantom Troupe'],
      emoji: '🕷️1️⃣3️⃣💀',
      group: 'Hunter x Hunter',
      tags: ['organisation', 'méchants', 'rare', 'hunter-x-hunter', 'dangereux', 'légendaire', 'emblème'],
      clues: [
        'Voleurs légendaires',
        'Treize membres',
        'Tatouage d’araignée numérotée',
        'Ont massacré le clan Kuruta',
        'Dirigée par Chrollo',
      ],
    },
    {
      name: 'Licence de Hunter',
      aliases: ['Hunter Licence'],
      emoji: '🪪🎣🏆',
      group: 'Hunter x Hunter',
      tags: ['objet', 'rare', 'héros', 'hunter-x-hunter', 'quête', 'emblème', 'entraînement'],
      clues: [
        'Une simple carte très précieuse',
        'Peut se revendre une fortune',
        'Obtenue après un examen mortel',
        'Gon et Killua la convoitent',
        'Titre de Hunter x Hunter',
      ],
    },
    // ——— Death Note ———
    {
      name: 'Death Note',
      aliases: ['Cahier de la mort'],
      emoji: '📓🖊️💀',
      group: 'Death Note',
      tags: ['objet', 'mort', 'rare', 'méchants', 'death-note', 'contrôle-mental', 'dangereux'],
      clues: [
        'Un carnet noir tombé du ciel',
        'Des règles écrites en anglais',
        'Il faut connaître le visage de la victime',
        'Crise cardiaque en 40 secondes',
        'Carnet de Light et Ryuk',
      ],
    },
    {
      name: 'Yeux de shinigami',
      aliases: ['Yeux du dieu de la mort', 'Shinigami Eyes'],
      emoji: '👁️🔴⏳',
      group: 'Death Note',
      tags: ['pouvoir', 'oculaire', 'mort', 'rare', 'méchants', 'death-note', 'pacte'],
      clues: [
        'Un marché contre la moitié de sa vie',
        'Permet de voir un nom au-dessus des têtes',
        'Montre aussi la durée de vie restante',
        'Misa accepte le pacte',
        'Pouvoir oculaire de Death Note',
      ],
    },
    // ——— Fullmetal Alchemist ———
    {
      name: 'Alchimie',
      aliases: ['Transmutation', 'Alchimie d’État'],
      emoji: '⚗️⭕👏',
      group: 'Fullmetal Alchemist',
      tags: ['pouvoir', 'magie', 'héros', 'fullmetal-alchemist', 'entraînement', 'offensif', 'signature'],
      clues: [
        'Science plus que magie',
        'Loi de l’échange équivalent',
        'Nécessite un cercle',
        'Ressusciter un humain est tabou',
        'Pouvoir des frères Elric',
      ],
    },
    {
      name: 'Pierre philosophale',
      aliases: ['Pierre Philosophale'],
      emoji: '🔴💎🩸',
      group: 'Fullmetal Alchemist',
      tags: ['objet', 'immortalité', 'rare', 'ultime', 'méchants', 'fullmetal-alchemist', 'quête'],
      clues: [
        'Objet rouge sang légendaire',
        'Contourne l’échange équivalent',
        'Faite d’âmes humaines',
        'Cœur des homoncules',
        'Quête des frères Elric',
      ],
    },
    {
      name: 'Homoncules',
      aliases: ['Homonculus', 'Homunculus'],
      emoji: '🐍7️⃣😈',
      group: 'Fullmetal Alchemist',
      tags: ['créature', 'organisation', 'méchants', 'immortalité', 'fullmetal-alchemist', 'dangereux', 'légendaire'],
      clues: [
        'Êtres artificiels',
        'Tatouage d’ouroboros',
        'Nommés d’après les sept péchés capitaux',
        'Envy, Lust, Gluttony…',
        'Ennemis de Fullmetal Alchemist',
      ],
    },
    // ——— JoJo ———
    {
      name: 'Stand',
      aliases: ['Stands'],
      emoji: '👻👊⭐',
      group: 'JoJo',
      tags: ['pouvoir', 'invocation', 'énergie', 'force', 'héros', 'méchants', 'jojo'],
      clues: [
        'Un esprit combattant visible par ses pairs',
        'Nommé souvent d’après un groupe de musique',
        'Blesser l’esprit blesse son porteur',
        'Star Platinum en est un',
        'Pouvoir signature de JoJo',
      ],
    },
    {
      name: 'The World',
      aliases: ['Za Warudo', 'Za Warudo !'],
      emoji: '⏱️🧛🛑',
      group: 'JoJo',
      tags: ['pouvoir', 'invocation', 'méchants', 'ultime', 'vitesse', 'jojo', 'dangereux'],
      clues: [
        'Crié avec un fort accent',
        'Arrête le cours du temps',
        'Quelques secondes suffisent',
        'Stand de Dio',
        '« Toki wo tomare ! »',
      ],
    },
    {
      name: 'Hamon',
      aliases: ['Onde', 'Onde Hamon', 'Onde lumineuse'],
      emoji: '☀️🫁⚡',
      group: 'JoJo',
      tags: ['technique', 'énergie', 'héros', 'jojo', 'entraînement', 'offensif', 'signature'],
      clues: [
        'Maîtrise particulière de la respiration',
        'Énergie semblable au soleil',
        'Efficace contre les vampires',
        'Enseignée par Zeppeli',
        'Technique des premières parties de JoJo',
      ],
    },
    // ——— Pokémon ———
    {
      name: 'Poké Ball',
      aliases: ['Pokéball', 'Pokeball'],
      emoji: '🔴⚪🎯',
      group: 'Pokémon',
      tags: ['objet', 'collection', 'héros', 'pokemon', 'emblème', 'signature', 'invocation'],
      clues: [
        'Tient dans une poche',
        'Moitié rouge, moitié blanche',
        'Se lance pour capturer',
        'Existe en version Super et Hyper',
        'Objet des dresseurs Pokémon',
      ],
    },
    {
      name: 'Team Rocket',
      aliases: ['Team Rocket'],
      emoji: '🚀❌😼',
      group: 'Pokémon',
      tags: ['organisation', 'méchants', 'pokemon', 'emblème', 'légendaire', 'collection', 'quête'],
      clues: [
        'Un trio qui s’envole à chaque défaite',
        'Une devise récitée à chaque apparition',
        'Veut voler une souris électrique',
        'Jessie, James et un chat qui parle',
        'Méchants de l’anime Pokémon',
      ],
    },
    {
      name: 'Évolution',
      aliases: ['Evolution'],
      emoji: '✨🐛🦋',
      group: 'Pokémon',
      tags: ['transformation', 'force', 'pokemon', 'emblème', 'inné', 'signature', 'légendaire'],
      clues: [
        'Une lumière blanche enveloppe la créature',
        'Parfois déclenchée par une pierre',
        'Chenipan devient Papilusion',
        'Arrêtable avec la touche B',
        'Transformation des Pokémon',
      ],
    },
    // ——— Divers ———
    {
      name: 'Geass',
      emoji: '👁️🔴🪽',
      group: 'Code Geass',
      tags: ['pouvoir', 'oculaire', 'contrôle-mental', 'rare', 'code-geass', 'pacte', 'méchants'],
      clues: [
        'Un symbole d’oiseau rouge dans l’œil',
        'Obtenu par un contrat avec une immortelle',
        'Chaque porteur a un effet différent',
        'Force quelqu’un à obéir à un ordre',
        'Pouvoir de Lelouch',
      ],
    },
    {
      name: 'Armée des ombres',
      aliases: ['Arise', 'Extraction d’ombre'],
      emoji: '🌑⚔️🧟',
      group: 'Solo Leveling',
      tags: ['pouvoir', 'invocation', 'organisation', 'immortalité', 'héros', 'solo-leveling', 'signature'],
      clues: [
        'Ressuscite les ennemis vaincus',
        'Des soldats noirs aux yeux bleus',
        'Commande : « Lève-toi »',
        'Igris et Beru en font partie',
        'Pouvoir de Sung Jin-woo',
      ],
    },
    {
      name: 'Chasseur de dragons',
      aliases: ['Dragon Slayer', 'Magie du chasseur de dragons'],
      emoji: '🐉🔥🍽️',
      group: 'Fairy Tail',
      tags: ['pouvoir', 'magie', 'feu', 'héros', 'rare', 'fairy-tail', 'entraînement'],
      clues: [
        'Une magie apprise d’un dragon',
        'On mange son propre élément',
        'Mal des transports garanti',
        'Rugissement du dragon de feu',
        'Magie de Natsu',
      ],
    },
    {
      name: 'Anti-magie',
      aliases: ['Anti-Magic', 'Épées anti-magie'],
      emoji: '🗡️⬛🍀',
      group: 'Black Clover',
      tags: ['pouvoir', 'épée', 'magie', 'rare', 'héros', 'black-clover', 'démoniaque', 'signature'],
      clues: [
        'Annule tous les sorts',
        'Sortie d’un grimoire à cinq feuilles',
        'Des lames noires géantes',
        'Liée à un démon',
        'Pouvoir d’Asta',
      ],
    },
    {
      name: 'Pochita',
      aliases: ['Démon Tronçonneuse', 'Chainsaw Devil'],
      emoji: '🐶🪚❤️',
      group: 'Chainsaw Man',
      tags: ['créature', 'transformation', 'arme', 'héros', 'chainsaw-man', 'démoniaque', 'pacte'],
      clues: [
        'Petit chien orange adorable',
        'Une lame qui sort de son museau',
        'Devient le cœur de son maître',
        'Démon redouté par les autres démons',
        'Démon de Denji',
      ],
    },
    {
      name: 'Kagune',
      aliases: ['Kagunes'],
      emoji: '🦑🩸👁️',
      group: 'Tokyo Ghoul',
      tags: ['pouvoir', 'arme', 'méchants', 'transformation', 'tokyo-ghoul', 'inné', 'dangereux'],
      clues: [
        'Sort du dos de son porteur',
        'Organe prédateur rouge',
        'Existe en quatre types : ukaku, koukaku, rinkaku, bikaku',
        'Transformé en arme par les enquêteurs',
        'Arme naturelle des goules',
      ],
    },
    {
      name: 'Cristal d’argent',
      aliases: ['Cristal d’Argent', 'Silver Crystal'],
      emoji: '💎🌙👑',
      group: 'Sailor Moon',
      tags: ['objet', 'magie', 'transformation', 'immortalité', 'rare', 'héros', 'sailor-moon'],
      clues: [
        'Un joyau lunaire légendaire',
        'Convoité par tous les ennemis',
        'Peut ressusciter les morts',
        'Trésor de la princesse Serenity',
        'Source des pouvoirs de Sailor Moon',
      ],
    },
  ],
};
