import type { Pack } from '../types';

export const pack: Pack = {
  id: 'anime-univers',
  name: 'Séries anime',
  emoji: '📺',
  category: 'anime',
  description: 'Les séries animes et mangas cultes, des classiques du Club Dorothée aux hits récents.',
  attributes: [
    { tag: 'shonen', question: 'Est-ce un shōnen ?' },
    { tag: 'seinen', question: 'Est-ce un seinen (public adulte) ?' },
    { tag: 'shojo', question: 'Est-ce un shōjo ?' },
    { tag: 'combat', question: 'Y a-t-il beaucoup de combats ?' },
    { tag: 'sport', question: 'Est-ce un anime de sport ?' },
    { tag: 'isekai', question: 'Le héros est-il transporté dans un autre monde ?' },
    { tag: 'romance', question: 'L’histoire d’amour est-elle au centre ?' },
    { tag: 'horreur', question: 'Est-ce un anime d’horreur ?' },
    { tag: 'comédie', question: 'Est-ce une série très drôle ?' },
    { tag: 'fantasy', question: 'Est-ce dans un univers de fantasy ?' },
    { tag: 'science-fiction', question: 'Est-ce de la science-fiction ?' },
    { tag: 'thriller', question: 'Est-ce un thriller à suspense ?' },
    { tag: 'école', question: 'L’histoire se passe-t-elle en partie dans une école ?' },
    { tag: 'magie', question: 'Y a-t-il de la magie ?' },
    { tag: 'super-pouvoirs', question: 'Les personnages ont-ils des super-pouvoirs ?' },
    { tag: 'démons', question: 'Y a-t-il des démons ou des monstres surnaturels ?' },
    { tag: 'mecha', question: 'Y a-t-il des robots géants ?' },
    { tag: 'historique', question: 'Se passe-t-il dans un cadre historique ?' },
    { tag: 'aventure', question: 'Est-ce une grande aventure / un voyage ?' },
    { tag: 'sombre', question: 'L’ambiance est-elle sombre ou violente ?' },
    { tag: 'culte', question: 'Est-ce une série culte connue de tous ?' },
    { tag: 'longue-série', question: 'La série compte-t-elle plus de 200 épisodes ?' },
    { tag: 'club-dorothée', question: 'Est-il passé au Club Dorothée ?' },
    { tag: 'années-80', question: 'L’anime a-t-il commencé dans les années 80 ?' },
    { tag: 'années-90', question: 'L’anime a-t-il commencé dans les années 90 ?' },
    { tag: 'années-2000', question: 'L’anime a-t-il commencé dans les années 2000 ?' },
    { tag: 'années-2010', question: 'L’anime a-t-il commencé dans les années 2010 ?' },
    { tag: 'années-2020', question: 'L’anime a-t-il commencé dans les années 2020 ?' },
    { tag: 'épées', question: 'Les personnages se battent-ils à l’épée ?' },
    { tag: 'héroïne', question: 'Le personnage principal est-il une fille ?' },
    { tag: 'tournoi', question: 'Y a-t-il des tournois ou des compétitions ?' },
    { tag: 'psychologique', question: 'Est-ce une série très psychologique ?' },
    { tag: 'famille', question: 'La famille est-elle un thème central ?' },
    { tag: 'lycéen', question: 'Le héros est-il lycéen ?' },
    { tag: 'enquête', question: 'Y a-t-il une enquête, un détective ou un espion ?' },
    { tag: 'ballon', question: 'Joue-t-on avec un ballon ?' },
    { tag: 'guerre', question: 'Y a-t-il une guerre au cœur de l’histoire ?' },
  ],
  items: [
    // ——— Shōnen combat ———
    {
      name: 'Naruto',
      aliases: ['Naruto Shippuden'],
      emoji: '🍥🥷🦊',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'démons', 'aventure', 'culte', 'longue-série', 'années-2000', 'école', 'tournoi'],
      clues: [
        'Un orphelin rejeté par son village',
        'Villages cachés et bandeaux frontaux',
        'Un démon renard scellé dans un enfant',
        'Ninjas et Hokage',
        'Créé par Masashi Kishimoto',
      ],
    },
    {
      name: 'One Piece',
      aliases: ['OP'],
      emoji: '🏴‍☠️👒🌊',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'aventure', 'comédie', 'culte', 'longue-série', 'années-90', 'fantasy'],
      clues: [
        'Plus de mille épisodes',
        'Un équipage parcourt les mers',
        'Des fruits donnent des pouvoirs',
        'La quête d’un trésor légendaire',
        'Créé par Eiichirō Oda',
      ],
    },
    {
      name: 'Dragon Ball',
      aliases: ['Dragon Ball Z', 'DBZ', 'Dragon Ball Super'],
      emoji: '🐉🟠☁️',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'aventure', 'culte', 'longue-série', 'années-80', 'club-dorothée', 'tournoi', 'science-fiction'],
      clues: [
        'Des cris qui durent plusieurs épisodes',
        'Des guerriers venus de l’espace',
        'Sept boules exaucent un vœu',
        'Cheveux blonds dressés quand on se transforme',
        'Créé par Akira Toriyama',
      ],
    },
    {
      name: 'Bleach',
      aliases: ['Bleach TYBW'],
      emoji: '💀⚔️🍓',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'démons', 'épées', 'longue-série', 'années-2000', 'école', 'lycéen'],
      clues: [
        'Un lycéen qui voit les fantômes',
        'Des sabres qui ont un nom',
        'Faucheurs d’âmes en kimono noir',
        'Bankai et Hollows',
        'Créé par Tite Kubo',
      ],
    },
    {
      name: 'Jujutsu Kaisen',
      aliases: ['JJK'],
      emoji: '👁️‍🗨️🖐️🩸',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'démons', 'école', 'sombre', 'années-2020', 'magie', 'lycéen'],
      clues: [
        'Des émotions négatives prennent forme',
        'Une école d’exorcistes à Tokyo',
        'Un lycéen avale un doigt maudit',
        'Extensions du territoire',
        'Créé par Gege Akutami',
      ],
    },
    {
      name: 'Demon Slayer',
      aliases: ['Kimetsu no Yaiba'],
      emoji: '🗡️👹🌊',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'démons', 'épées', 'historique', 'famille', 'sombre', 'années-2010', 'culte'],
      clues: [
        'Se passe à l’ère Taishō',
        'Une famille massacrée une nuit d’hiver',
        'Des techniques de respiration',
        'Une sœur transformée qui dort dans une boîte',
        'Créé par Koyoharu Gotōge',
      ],
    },
    {
      name: 'My Hero Academia',
      aliases: ['Boku no Hero Academia', 'MHA'],
      emoji: '🦸🏫💥',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'école', 'tournoi', 'années-2010', 'culte'],
      clues: [
        '80 % de la population a un pouvoir',
        'Une école qui forme des justiciers',
        'Un garçon né sans don',
        'Héritage du One For All',
        'Créé par Kōhei Horikoshi',
      ],
    },
    {
      name: 'Hunter x Hunter',
      aliases: ['HxH', 'Hunter Hunter'],
      emoji: '🎣⚡🃏',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'aventure', 'tournoi', 'sombre', 'années-90', 'culte'],
      clues: [
        'Un examen très dangereux',
        'Un garçon cherche son père',
        'L’aura se contrôle en six catégories',
        'Le Nen et les fourmis chimères',
        'Créé par Yoshihiro Togashi',
      ],
    },
    {
      name: 'Black Clover',
      aliases: ['BC'],
      emoji: '🍀📖🗡️',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'magie', 'fantasy', 'épées', 'années-2010', 'tournoi'],
      clues: [
        'Deux orphelins rivaux',
        'Des grimoires offerts à 15 ans',
        'Un héros sans magie dans un monde de mages',
        'Chevaliers-mages et Taureaux noirs',
        'Créé par Yūki Tabata',
      ],
    },
    {
      name: 'Fairy Tail',
      aliases: ['FT'],
      emoji: '🧚🔥🐉',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'magie', 'fantasy', 'comédie', 'longue-série', 'années-2000', 'tournoi'],
      clues: [
        'L’amitié avant tout',
        'Des guildes de magiciens',
        'Un garçon qui mange du feu',
        'Chasseurs de dragons et esprits stellaires',
        'Créé par Hiro Mashima',
      ],
    },
    {
      name: 'Chainsaw Man',
      aliases: ['CSM'],
      emoji: '🪚🩸😈',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'démons', 'sombre', 'horreur', 'comédie', 'années-2020'],
      clues: [
        'Un ado pauvre rêve de pain beurré',
        'Les peurs des humains créent des monstres',
        'Pacte avec un chien démon',
        'Des tronçonneuses sortent d’une tête',
        'Créé par Tatsuki Fujimoto',
      ],
    },
    {
      name: 'JoJo’s Bizarre Adventure',
      aliases: ['JoJo', 'JJBA'],
      emoji: '⭐🕺⏱️',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'aventure', 'famille', 'culte', 'années-2010', 'démons'],
      clues: [
        'Des poses improbables',
        'Une lignée familiale sur plusieurs générations',
        'Des esprits combattants appelés Stands',
        '« Ora ora ora ! »',
        'Créé par Hirohiko Araki',
      ],
    },
    {
      name: 'Fullmetal Alchemist',
      aliases: ['FMA', 'Fullmetal Alchemist Brotherhood', 'FMAB'],
      emoji: '⚗️🦾🛡️',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'magie', 'fantasy', 'aventure', 'famille', 'sombre', 'culte', 'années-2000', 'guerre'],
      clues: [
        'Deux frères ont voulu ressusciter leur mère',
        'Échange équivalent',
        'Un bras mécanique et une armure vivante',
        'La quête de la pierre philosophale',
        'Créé par Hiromu Arakawa',
      ],
    },
    {
      name: 'Les Chevaliers du Zodiaque',
      aliases: ['Saint Seiya'],
      emoji: '♈🛡️🌌',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'culte', 'club-dorothée', 'années-80', 'tournoi', 'fantasy'],
      clues: [
        'Des armures liées aux constellations',
        'Protéger la réincarnation d’une déesse',
        'Traverser les douze maisons',
        'Pégase, Dragon, Cygne, Andromède, Phénix',
        'Créé par Masami Kurumada',
      ],
    },
    {
      name: 'Dandadan',
      aliases: ['Dan Da Dan'],
      emoji: '👽👻👵',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'démons', 'comédie', 'romance', 'école', 'années-2020', 'science-fiction', 'lycéen'],
      clues: [
        'Un pari sur les fantômes et les extraterrestres',
        'Deux lycéens très différents',
        'Une vieille dame ultra rapide',
        'Médium, yōkai et OVNI',
        'Créé par Yukinobu Tatsu',
      ],
    },
    {
      name: 'Solo Leveling',
      aliases: ['Na Honjaman Level Up'],
      emoji: '🗡️🌑📈',
      group: 'Shōnen combat',
      tags: ['combat', 'super-pouvoirs', 'démons', 'fantasy', 'sombre', 'années-2020', 'épées'],
      clues: [
        'À l’origine un webtoon coréen',
        'Des portails vers des donjons',
        'Le chasseur le plus faible du monde',
        'Une armée des ombres',
        'Héros : Sung Jin-woo',
      ],
    },
    {
      name: 'Ken le Survivant',
      aliases: ['Hokuto no Ken', 'Fist of the North Star'],
      emoji: '💥✋☢️',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'sombre', 'culte', 'club-dorothée', 'années-80', 'science-fiction'],
      clues: [
        'Un monde dévasté par la guerre nucléaire',
        'Sept cicatrices sur la poitrine',
        'Frapper les points vitaux',
        '« Tu ne le sais pas encore mais tu es déjà mort »',
        'Kenshirō contre Raoh',
      ],
    },
    {
      name: 'Yu Yu Hakusho',
      aliases: ['YYH'],
      emoji: '👻👉🦊',
      group: 'Shōnen combat',
      tags: ['shonen', 'combat', 'super-pouvoirs', 'démons', 'tournoi', 'années-90', 'club-dorothée', 'enquête'],
      clues: [
        'Un délinquant meurt en sauvant un enfant',
        'Détective du monde des esprits',
        'Tirer avec son index',
        'Un tournoi des ténèbres',
        'Créé par Yoshihiro Togashi',
      ],
    },
    // ——— Fantasy & épopée ———
    {
      name: 'L’Attaque des Titans',
      aliases: ['Attack on Titan', 'Shingeki no Kyojin', 'SNK', 'AOT'],
      emoji: '🧱🦷⚔️',
      group: 'Fantasy & épopée',
      tags: ['shonen', 'combat', 'sombre', 'fantasy', 'épées', 'culte', 'années-2010', 'psychologique', 'guerre'],
      clues: [
        'L’humanité vit derrière d’immenses murs',
        'Des géants dévorent les humains',
        'Des soldats volent avec des câbles',
        '« Offrez vos cœurs ! »',
        'Créé par Hajime Isayama',
      ],
    },
    {
      name: 'Berserk',
      aliases: ['Berserk manga'],
      emoji: '🗡️🦅🌑',
      group: 'Fantasy & épopée',
      tags: ['seinen', 'combat', 'sombre', 'fantasy', 'démons', 'épées', 'culte', 'années-90', 'horreur'],
      clues: [
        'Un guerrier solitaire marqué au cou',
        'Une épée gigantesque',
        'Une troupe de mercenaires trahie',
        'La Main de Dieu et l’Éclipse',
        'Créé par Kentarō Miura',
      ],
    },
    {
      name: 'Vinland Saga',
      aliases: ['Vinland'],
      emoji: '⛵🪓🌾',
      group: 'Fantasy & épopée',
      tags: ['seinen', 'combat', 'historique', 'sombre', 'aventure', 'épées', 'années-2010', 'psychologique', 'guerre'],
      clues: [
        'Europe du Nord au XIe siècle',
        'Un enfant veut venger son père',
        'Mercenaires, rois et esclaves',
        'Vikings en quête d’une terre promise',
        'Créé par Makoto Yukimura',
      ],
    },
    {
      name: 'Frieren',
      aliases: ['Sousou no Frieren', 'Frieren: Beyond Journey’s End'],
      emoji: '🧝‍♀️🌸🪄',
      group: 'Fantasy & épopée',
      tags: ['shonen', 'fantasy', 'magie', 'aventure', 'héroïne', 'années-2020', 'psychologique'],
      clues: [
        'Commence après la victoire contre le roi démon',
        'Réflexion sur le temps qui passe',
        'Une elfe apprend à connaître les humains',
        'Collectionne les sorts inutiles',
        'Avec Fern et Stark',
      ],
    },
    {
      name: 'Made in Abyss',
      aliases: ['MiA'],
      emoji: '🕳️🤖🧭',
      group: 'Fantasy & épopée',
      tags: ['seinen', 'fantasy', 'aventure', 'sombre', 'horreur', 'héroïne', 'années-2010'],
      clues: [
        'Un dessin mignon trompeur',
        'Un gouffre gigantesque inexploré',
        'Plus on descend, plus remonter est mortel',
        'Riko et un garçon robot',
        'Créé par Akihito Tsukushi',
      ],
    },
    // ——— Thriller psychologique ———
    {
      name: 'Death Note',
      aliases: ['DN'],
      emoji: '📓🍎💀',
      group: 'Thriller psychologique',
      tags: ['shonen', 'thriller', 'psychologique', 'démons', 'sombre', 'culte', 'années-2000', 'école', 'lycéen', 'enquête'],
      clues: [
        'Un duel d’intelligence',
        'Un justicier contre un détective',
        'Un dieu de la mort qui aime les pommes',
        'Écrire un nom suffit à tuer',
        'Créé par Tsugumi Ōba et Takeshi Obata',
      ],
    },
    {
      name: 'Code Geass',
      aliases: ['Code Geass R2'],
      emoji: '♟️👁️🤖',
      group: 'Thriller psychologique',
      tags: ['thriller', 'psychologique', 'mecha', 'science-fiction', 'école', 'super-pouvoirs', 'années-2000', 'lycéen', 'guerre'],
      clues: [
        'Un Japon conquis par un empire',
        'Un prince exilé veut se venger',
        'Un regard qui force l’obéissance',
        'Un masque noir et des Knightmares',
        'Héros : Lelouch',
      ],
    },
    {
      name: 'Monster',
      aliases: ['Monster anime'],
      emoji: '🩺🔪🇩🇪',
      group: 'Thriller psychologique',
      tags: ['seinen', 'thriller', 'psychologique', 'sombre', 'années-2000', 'enquête', 'culte'],
      clues: [
        'Allemagne des années 80-90',
        'Un chirurgien sauve un enfant',
        'L’enfant devient un tueur manipulateur',
        'Le docteur Tenma accusé de meurtres',
        'Créé par Naoki Urasawa',
      ],
    },
    {
      name: 'The Promised Neverland',
      aliases: ['Yakusoku no Neverland', 'TPN'],
      emoji: '🏠🧒🔢',
      group: 'Thriller psychologique',
      tags: ['shonen', 'thriller', 'psychologique', 'horreur', 'démons', 'héroïne', 'années-2010'],
      clues: [
        'Un orphelinat trop parfait',
        'Des enfants numérotés sur le cou',
        'Une « maman » qui cache un secret',
        'Un plan d’évasion',
        'Héroïne : Emma',
      ],
    },
    {
      name: 'Steins;Gate',
      aliases: ['Steins Gate'],
      emoji: '📱⏳🍌',
      group: 'Thriller psychologique',
      tags: ['thriller', 'science-fiction', 'psychologique', 'années-2010', 'culte', 'comédie', 'romance'],
      clues: [
        'Un savant fou autoproclamé',
        'Un micro-ondes modifié',
        'Des messages envoyés dans le passé',
        'Lignes temporelles et « El Psy Kongroo »',
        'Se passe à Akihabara',
      ],
    },
    // ——— Sport ———
    {
      name: 'Haikyuu!!',
      aliases: ['Haikyuu', 'Haikyu'],
      emoji: '🏐🐦‍⬛🍊',
      group: 'Sport',
      tags: ['shonen', 'sport', 'école', 'tournoi', 'comédie', 'années-2010', 'lycéen', 'ballon'],
      clues: [
        'Un petit gabarit qui rêve de hauteur',
        'Le lycée Karasuno',
        'Les corbeaux contre les chats',
        'Duo passeur-attaquant',
        'Manga de volley-ball',
      ],
    },
    {
      name: 'Blue Lock',
      aliases: ['BL'],
      emoji: '⚽🔒🏆',
      group: 'Sport',
      tags: ['shonen', 'sport', 'tournoi', 'psychologique', 'années-2020', 'lycéen', 'ballon'],
      clues: [
        'Un projet pour gagner la Coupe du monde',
        '300 attaquants enfermés',
        'L’égoïsme comme qualité',
        'Isagi et Ego Jinpachi',
        'Manga de football',
      ],
    },
    {
      name: 'Kuroko’s Basket',
      aliases: ['Kuroko no Basket', 'Kuroko'],
      emoji: '🏀👻🌈',
      group: 'Sport',
      tags: ['shonen', 'sport', 'école', 'tournoi', 'années-2010', 'lycéen', 'ballon'],
      clues: [
        'Un joueur que personne ne remarque',
        'La Génération des miracles',
        'Chaque rival a une couleur de cheveux',
        'Le lycée Seirin',
        'Manga de basket',
      ],
    },
    {
      name: 'Olive et Tom',
      aliases: ['Captain Tsubasa'],
      emoji: '⚽🌅📏',
      group: 'Sport',
      tags: ['shonen', 'sport', 'tournoi', 'école', 'culte', 'club-dorothée', 'années-80', 'ballon'],
      clues: [
        'Des terrains qui semblent infinis',
        'Des tirs qui déforment le ballon',
        'Un gardien avec une casquette',
        'Rêve de gagner la Coupe du monde',
        'Créé par Yōichi Takahashi',
      ],
    },
    {
      name: 'Slam Dunk',
      aliases: ['Slam Dunk anime'],
      emoji: '🏀🔴💪',
      group: 'Sport',
      tags: ['shonen', 'sport', 'école', 'tournoi', 'comédie', 'culte', 'années-90', 'lycéen', 'ballon'],
      clues: [
        'Un voyou roux veut séduire une fille',
        'Il rejoint un club pour elle',
        'Le lycée Shōhoku',
        'Hanamichi Sakuragi',
        'Manga de basket de Takehiko Inoue',
      ],
    },
    // ——— Isekai ———
    {
      name: 'Sword Art Online',
      aliases: ['SAO'],
      emoji: '🎮⚔️🥽',
      group: 'Isekai',
      tags: ['isekai', 'fantasy', 'science-fiction', 'combat', 'épées', 'romance', 'années-2010'],
      clues: [
        'Des joueurs piégés dans un jeu',
        'Mourir dans le jeu tue en vrai',
        'Un casque de réalité virtuelle',
        'Kirito et Asuna',
        'Nom abrégé en trois lettres',
      ],
    },
    {
      name: 'Re:Zero',
      aliases: ['Re Zero', 'Re:Zero kara Hajimeru Isekai Seikatsu'],
      emoji: '🔁💙💀',
      group: 'Isekai',
      tags: ['isekai', 'fantasy', 'magie', 'sombre', 'psychologique', 'années-2010', 'romance'],
      clues: [
        'Un garçon sorti d’une supérette',
        'Revient en arrière à chaque mort',
        'Une demi-elfe aux cheveux argentés',
        'Rem et Ram, deux servantes',
        'Héros : Subaru',
      ],
    },
    {
      name: 'Moi, quand je me réincarne en Slime',
      aliases: ['That Time I Got Reincarnated as a Slime', 'Tensura', 'Slime'],
      emoji: '💧🐉🏰',
      group: 'Isekai',
      tags: ['isekai', 'fantasy', 'magie', 'comédie', 'aventure', 'années-2010', 'combat'],
      clues: [
        'Un employé poignardé dans la rue',
        'Renaît en petite créature gluante',
        'Se lie d’amitié avec un dragon',
        'Fonde une nation de monstres',
        'Héros : Rimuru',
      ],
    },
    {
      name: 'KonoSuba',
      aliases: ['Kono Subarashii Sekai ni Shukufuku wo!'],
      emoji: '💥🍻💧',
      group: 'Isekai',
      tags: ['isekai', 'fantasy', 'magie', 'comédie', 'années-2010', 'aventure', 'démons'],
      clues: [
        'Mort de façon ridicule',
        'Emmène une déesse inutile avec lui',
        'Une mage qui ne connaît qu’un sort',
        'Explosion !',
        'Héros : Kazuma',
      ],
    },
    // ——— Romance ———
    {
      name: 'Kaguya-sama: Love is War',
      aliases: ['Kaguya-sama', 'Love is War'],
      emoji: '💘🧠🏫',
      group: 'Romance',
      tags: ['seinen', 'romance', 'comédie', 'école', 'psychologique', 'années-2010', 'lycéen'],
      clues: [
        'Deux génies trop fiers',
        'Chacun veut que l’autre avoue en premier',
        'Le conseil des élèves',
        'Stratégies amoureuses absurdes',
        'Shirogane contre Shinomiya',
      ],
    },
    {
      name: 'Fruits Basket',
      aliases: ['Furuba'],
      emoji: '🍙🐭🐱',
      group: 'Romance',
      tags: ['shojo', 'romance', 'famille', 'comédie', 'école', 'héroïne', 'magie', 'années-2000'],
      clues: [
        'Une orpheline vit sous une tente',
        'Une famille frappée d’une malédiction',
        'Un câlin transforme en animal',
        'Les douze signes du zodiaque chinois',
        'Héroïne : Tohru Honda',
      ],
    },
    {
      name: 'Toradora!',
      aliases: ['Toradora'],
      emoji: '🐯🐉🏫',
      group: 'Romance',
      tags: ['romance', 'comédie', 'école', 'héroïne', 'années-2000', 'lycéen', 'famille'],
      clues: [
        'Un garçon au regard effrayant',
        'Une petite fille très agressive',
        'Ils s’aident à séduire leurs meilleurs amis',
        'Le tigre et le dragon',
        'Taiga et Ryūji',
      ],
    },
    // ——— Horreur ———
    {
      name: 'Tokyo Ghoul',
      aliases: ['TG', 'Tokyo Ghoul:re'],
      emoji: '☕👁️🎭',
      group: 'Horreur',
      tags: ['seinen', 'horreur', 'sombre', 'combat', 'démons', 'psychologique', 'années-2010'],
      clues: [
        'Un étudiant timide victime d’un rendez-vous',
        'Des créatures qui mangent des humains',
        'Un café servant de refuge',
        'Un œil rouge et noir',
        'Héros : Ken Kaneki',
      ],
    },
    {
      name: 'Parasite',
      aliases: ['Kiseiju', 'Parasyte'],
      emoji: '🖐️👁️🐛',
      group: 'Horreur',
      tags: ['seinen', 'horreur', 'science-fiction', 'combat', 'sombre', 'psychologique', 'années-2010', 'lycéen'],
      clues: [
        'Des créatures tombées du ciel',
        'Elles prennent le contrôle des cerveaux',
        'Une a échoué et vit dans une main',
        'Un lycéen et sa main droite Migi',
        'Créé par Hitoshi Iwaaki',
      ],
    },
    {
      name: 'Another',
      aliases: ['Another anime'],
      emoji: '🪆👁️☂️',
      group: 'Horreur',
      tags: ['horreur', 'thriller', 'école', 'sombre', 'années-2010', 'psychologique', 'enquête'],
      clues: [
        'Une classe maudite',
        'Des morts accidentelles en série',
        'Une fille au cache-œil qu’on ignore',
        'Poupées et parapluie meurtrier',
        'Classe de 3e 3 du collège Yomiyama',
      ],
    },
    // ——— Comédie ———
    {
      name: 'Spy x Family',
      aliases: ['Spy Family', 'SxF'],
      emoji: '🕵️🗡️🥜',
      group: 'Comédie',
      tags: ['shonen', 'comédie', 'famille', 'école', 'super-pouvoirs', 'années-2020', 'enquête'],
      clues: [
        'Une fausse famille',
        'Chacun cache un secret aux autres',
        'Une fillette qui lit les pensées',
        'Un espion, une tueuse et une télépathe',
        'La famille Forger',
      ],
    },
    {
      name: 'One Punch Man',
      aliases: ['OPM'],
      emoji: '👊🥚🦸',
      group: 'Comédie',
      tags: ['seinen', 'comédie', 'combat', 'super-pouvoirs', 'démons', 'années-2010', 'culte'],
      clues: [
        'Parodie de super-héros',
        'Un homme chauve s’ennuie',
        'Il gagne toujours en un coup',
        'Association des héros et Genos',
        'Héros : Saitama',
      ],
    },
    {
      name: 'Nicky Larson',
      aliases: ['City Hunter'],
      emoji: '🔫🔨🌆',
      group: 'Comédie',
      tags: ['seinen', 'comédie', 'thriller', 'culte', 'club-dorothée', 'années-80', 'enquête'],
      clues: [
        'Un détective privé à Tokyo',
        'Un tireur d’élite coureur de jupons',
        'Une partenaire qui frappe avec une massue',
        'Contact via un tableau à la gare',
        'Créé par Tsukasa Hōjō',
      ],
    },
    {
      name: 'Gintama',
      aliases: ['Gin Tama'],
      emoji: '🍓🥛🗡️',
      group: 'Comédie',
      tags: ['shonen', 'comédie', 'combat', 'épées', 'historique', 'science-fiction', 'longue-série', 'années-2000'],
      clues: [
        'Un samouraï paresseux',
        'Le Japon d’Edo envahi par des extraterrestres',
        'Adore le lait à la fraise',
        'Parodies et brisures du quatrième mur',
        'Héros : Gintoki',
      ],
    },
    // ——— Science-fiction ———
    {
      name: 'Neon Genesis Evangelion',
      aliases: ['Evangelion', 'Eva', 'NGE'],
      emoji: '🤖💜✝️',
      group: 'Science-fiction',
      tags: ['mecha', 'science-fiction', 'psychologique', 'sombre', 'culte', 'années-90', 'combat'],
      clues: [
        'Des adolescents pilotent des géants',
        'Des « Anges » attaquent Tokyo-3',
        'Un père froid qui dirige la NERV',
        '« Monte dans ce robot, Shinji ! »',
        'Créé par Hideaki Anno',
      ],
    },
    {
      name: 'Cowboy Bebop',
      aliases: ['Bebop'],
      emoji: '🚀🎷🚬',
      group: 'Science-fiction',
      tags: ['seinen', 'science-fiction', 'aventure', 'culte', 'années-90', 'combat', 'sombre'],
      clues: [
        'Une bande-son jazz légendaire',
        'Des chasseurs de primes dans l’espace',
        'Un corgi génial',
        'Spike Spiegel',
        '« See you, space cowboy »',
      ],
    },
    {
      name: 'Mobile Suit Gundam',
      aliases: ['Gundam'],
      emoji: '🤖🚀⚔️',
      group: 'Science-fiction',
      tags: ['mecha', 'science-fiction', 'combat', 'culte', 'sombre', 'guerre', 'psychologique'],
      clues: [
        'Une guerre entre la Terre et les colonies',
        'Des maquettes vendues par millions',
        'Des robots de combat pilotés',
        'Amuro Ray et Char Aznable',
        'Franchise de mecha née en 1979',
      ],
    },
    // ——— Magical girl ———
    {
      name: 'Sailor Moon',
      aliases: ['Bishōjo Senshi Sailor Moon'],
      emoji: '🌙🎀✨',
      group: 'Magical girl',
      tags: ['shojo', 'magie', 'héroïne', 'romance', 'école', 'super-pouvoirs', 'culte', 'club-dorothée', 'années-90'],
      clues: [
        'Des collégiennes qui se transforment',
        'Un chat noir avec un croissant sur le front',
        'Un mystérieux homme en smoking',
        'Guerrières des planètes',
        '« Au nom de la Lune, je vais te punir ! »',
      ],
    },
    {
      name: 'Cardcaptor Sakura',
      aliases: ['Sakura chasseuse de cartes'],
      emoji: '🃏🪄🧸',
      group: 'Magical girl',
      tags: ['shojo', 'magie', 'héroïne', 'école', 'aventure', 'années-90', 'comédie'],
      clues: [
        'Une écolière qui fait du roller',
        'Un livre magique ouvert par erreur',
        'Une meilleure amie qui fabrique ses costumes',
        'Capturer les cartes de Clow',
        'Réalisé par le collectif CLAMP',
      ],
    },
    {
      name: 'Puella Magi Madoka Magica',
      aliases: ['Madoka Magica', 'Madoka'],
      emoji: '🎀🐱💎',
      group: 'Magical girl',
      tags: ['magie', 'héroïne', 'sombre', 'psychologique', 'horreur', 'école', 'années-2010'],
      clues: [
        'Un univers mignon qui cache l’horreur',
        'Un petit animal propose un contrat',
        'Un vœu contre un destin terrible',
        'Des gemmes de l’âme',
        'Kyubey et Homura',
      ],
    },
    // ——— Aventure jeunesse ———
    {
      name: 'Pokémon',
      aliases: ['Pokemon'],
      emoji: '⚡🔴⚪',
      group: 'Aventure jeunesse',
      tags: ['aventure', 'tournoi', 'culte', 'longue-série', 'années-90', 'comédie', 'combat'],
      clues: [
        'Adapté d’un jeu vidéo',
        'Un garçon de 10 ans part de chez lui',
        'Des créatures capturées dans des boules',
        'Attrapez-les tous !',
        'Sacha et Pikachu',
      ],
    },
    {
      name: 'Yu-Gi-Oh!',
      aliases: ['Yu-Gi-Oh', 'Yugioh'],
      emoji: '🃏🔺🐉',
      group: 'Aventure jeunesse',
      tags: ['shonen', 'tournoi', 'école', 'culte', 'longue-série', 'années-2000', 'démons'],
      clues: [
        'Un puzzle égyptien millénaire',
        'Un esprit pharaon dans un lycéen',
        'Des duels de cartes à enjeux',
        'Dragon Blanc aux Yeux Bleus',
        '« C’est l’heure du duel ! »',
      ],
    },
    {
      name: 'Digimon',
      aliases: ['Digimon Adventure'],
      emoji: '🦖💻📟',
      group: 'Aventure jeunesse',
      tags: ['aventure', 'science-fiction', 'culte', 'années-90', 'combat', 'fantasy', 'comédie'],
      clues: [
        'Des enfants en colonie de vacances',
        'Aspirés dans un monde numérique',
        'Des partenaires qui digivoluent',
        'Agumon et le Digivice',
        'Souvent comparé à Pokémon',
      ],
    },
  ],
};
