import type { Pack } from '../types';

export const pack: Pack = {
  id: 'animaux',
  name: 'Animaux',
  emoji: '🦁',
  category: 'animaux',
  description: 'Des animaux de la savane, de la ferme, des océans et de la maison.',
  attributes: [
    { tag: 'mammifère', question: 'Est-ce un mammifère ?' },
    { tag: 'oiseau', question: 'Est-ce un oiseau ?' },
    { tag: 'reptile', question: 'Est-ce un reptile ?' },
    { tag: 'poisson', question: 'Est-ce un poisson ?' },
    { tag: 'insecte', question: 'Est-ce un insecte ?' },
    { tag: 'carnivore', question: 'Mange-t-il de la viande ?' },
    { tag: 'herbivore', question: 'Est-il herbivore ?' },
    { tag: 'omnivore', question: 'Mange-t-il un peu de tout ?' },
    { tag: 'afrique', question: 'Vit-il en Afrique ?' },
    { tag: 'asie', question: 'Vit-il en Asie ?' },
    { tag: 'amerique', question: 'Vit-il en Amérique ?' },
    { tag: 'mer', question: 'Vit-il dans la mer ou l\'océan ?' },
    { tag: 'domestique', question: 'Peut-on l\'avoir comme animal de compagnie ?' },
    { tag: 'ferme', question: 'Le trouve-t-on dans une ferme ?' },
    { tag: 'sauvage', question: 'Est-ce un animal sauvage ?' },
    { tag: 'nage', question: 'Sait-il nager ?' },
    { tag: 'vole', question: 'Peut-il voler ?' },
    { tag: 'dangereux', question: 'Est-il dangereux pour l\'homme ?' },
    { tag: 'venimeux', question: 'Est-il venimeux ?' },
    { tag: 'petit', question: 'Est-il petit (plus petit qu\'un chat) ?' },
    { tag: 'grand', question: 'Est-il plus grand qu\'un humain ?' },
    { tag: 'rayures', question: 'A-t-il des rayures ?' },
    { tag: 'taches', question: 'A-t-il des taches ?' },
    { tag: 'poils', question: 'A-t-il des poils ou de la fourrure ?' },
    { tag: 'plumes', question: 'A-t-il des plumes ?' },
    { tag: 'écailles', question: 'A-t-il des écailles ?' },
    { tag: 'nocturne', question: 'Est-il surtout actif la nuit ?' },
    { tag: 'rapide', question: 'Est-il très rapide ?' },
    { tag: 'lent', question: 'Est-il plutôt lent ?' },
    { tag: 'savane', question: 'Vit-il dans la savane ?' },
    { tag: 'jungle', question: 'Vit-il dans la jungle ou la forêt tropicale ?' },
    { tag: 'forêt', question: 'Vit-il dans les forêts ?' },
    { tag: 'froid', question: 'Vit-il dans des régions froides ?' },
    { tag: 'noir', question: 'Est-il (en partie) noir ?' },
    { tag: 'blanc', question: 'Est-il (en partie) blanc ?' },
    { tag: 'coloré', question: 'Est-il très coloré ?' },
    { tag: 'cornes', question: 'A-t-il des cornes ou des bois ?' },
    { tag: 'arbre', question: 'Grimpe-t-il aux arbres ?' },
    { tag: 'saute', question: 'Est-il connu pour sauter ?' },
    { tag: 'groupe', question: 'Vit-il en groupe (troupeau, meute, colonie) ?' },
  ],
  items: [
    // ——— Mammifères sauvages ———
    { name: 'Lion', emoji: '🦁👑🌅', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'afrique', 'savane', 'sauvage', 'dangereux', 'grand', 'poils', 'groupe'], clues: ['Grand félin', 'Vit en troupe dans la savane', 'Rugit très fort', 'Le mâle a une crinière', 'Roi des animaux'] },
    { name: 'Tigre', emoji: '🐅🟧🌿', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'asie', 'jungle', 'sauvage', 'dangereux', 'grand', 'rayures', 'poils', 'nage'], clues: ['Grand félin solitaire', 'Adore l\'eau', 'Vit en Asie', 'Pelage orange rayé de noir', 'Shere Khan dans Le Livre de la jungle'] },
    { name: 'Éléphant', emoji: '🐘🌍💧', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'asie', 'savane', 'sauvage', 'grand', 'groupe', 'lent', 'nage'], clues: ['Animal énorme', 'Grandes oreilles', 'Mémoire légendaire', 'Défenses en ivoire', 'Possède une trompe'] },
    { name: 'Girafe', emoji: '🦒🌳🌍', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'savane', 'sauvage', 'grand', 'taches', 'poils', 'cornes', 'groupe'], clues: ['Animal de la savane', 'Mange les feuilles d\'acacia', 'Langue bleue très longue', 'Plus grand animal terrestre en hauteur', 'Cou immense'] },
    { name: 'Zèbre', emoji: '🦓⚫⚪', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'savane', 'sauvage', 'rayures', 'noir', 'blanc', 'groupe', 'rapide'], clues: ['Cousin du cheval', 'Vit en troupeau', 'Proie préférée des lions', 'Marty dans Madagascar', 'Rayé noir et blanc'] },
    { name: 'Hippopotame', emoji: '🦛💧🌍', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'savane', 'sauvage', 'dangereux', 'grand', 'nage', 'groupe'], clues: ['Animal très lourd', 'Passe la journée dans l\'eau', 'Bouche gigantesque', 'Parmi les plus dangereux d\'Afrique', 'Son nom veut dire « cheval de rivière »'] },
    { name: 'Rhinocéros', emoji: '🦏🌍⚠️', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'asie', 'savane', 'sauvage', 'dangereux', 'grand', 'cornes'], clues: ['Animal massif', 'Peau épaisse et grise', 'Très mauvaise vue', 'Menacé par le braconnage', 'Corne sur le nez'] },
    { name: 'Gorille', emoji: '🦍🌿💪', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'jungle', 'sauvage', 'grand', 'poils', 'noir', 'groupe', 'arbre'], clues: ['Primate imposant', 'Vit dans la forêt tropicale', 'Le mâle a le dos argenté', 'Se tape la poitrine', 'Plus grand des singes'] },
    { name: 'Chimpanzé', emoji: '🐒🍌🌳', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'afrique', 'jungle', 'sauvage', 'poils', 'noir', 'groupe', 'arbre'], clues: ['Primate très intelligent', 'Utilise des outils', 'Notre plus proche cousin', 'Étudié par Jane Goodall', 'Singe d\'Afrique'] },
    { name: 'Guépard', emoji: '🐆💨🌍', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'afrique', 'savane', 'sauvage', 'rapide', 'taches', 'poils'], clues: ['Félin élancé', 'Chasse en plein jour', 'Lignes noires sous les yeux', 'Plus de 100 km/h', 'Animal terrestre le plus rapide'] },
    { name: 'Léopard', emoji: '🐆🌳🌙', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'afrique', 'asie', 'savane', 'sauvage', 'dangereux', 'taches', 'poils', 'arbre', 'nocturne'], clues: ['Félin discret', 'Monte ses proies dans les arbres', 'Chasse surtout la nuit', 'Taches en forme de rosettes', 'Sa version noire s\'appelle panthère'] },
    { name: 'Hyène', emoji: '🐕😂🌙', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'afrique', 'savane', 'sauvage', 'dangereux', 'taches', 'groupe', 'nocturne', 'poils'], clues: ['Charognard de la savane', 'Vit en clan', 'Mâchoires très puissantes', 'Semble rire', 'Méchantes dans Le Roi Lion'] },
    { name: 'Chameau', aliases: ['Dromadaire'], emoji: '🐪🏜️☀️', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'afrique', 'asie', 'ferme', 'grand', 'poils', 'lent', 'groupe'], clues: ['Animal du désert', 'Peut rester longtemps sans boire', 'Crache parfois', 'Transporte des gens et des marchandises', 'Possède des bosses'] },
    { name: 'Ours brun', aliases: ['Ours', 'Grizzly'], emoji: '🐻🍯🌲', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'amerique', 'forêt', 'sauvage', 'dangereux', 'grand', 'poils', 'nage', 'froid'], clues: ['Gros animal des forêts', 'Hiberne en hiver', 'Pêche le saumon', 'Adore le miel', 'Grizzly en Amérique'] },
    { name: 'Ours polaire', aliases: ['Ours blanc'], emoji: '🐻‍❄️❄️🧊', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'froid', 'sauvage', 'dangereux', 'grand', 'poils', 'blanc', 'nage', 'mer'], clues: ['Grand carnivore', 'Vit sur la banquise', 'Chasse les phoques', 'Peau noire sous la fourrure', 'Tout blanc, au pôle Nord'] },
    { name: 'Panda', aliases: ['Panda géant'], emoji: '🐼🎋🇨🇳', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'asie', 'forêt', 'sauvage', 'grand', 'poils', 'noir', 'blanc', 'lent', 'arbre'], clues: ['Animal très mignon', 'Mange presque que du bambou', 'Symbole du WWF', 'Po dans Kung Fu Panda', 'Noir et blanc, vit en Chine'] },
    { name: 'Loup', emoji: '🐺🌕🌲', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'forêt', 'sauvage', 'dangereux', 'poils', 'groupe', 'nocturne', 'froid', 'amerique'], clues: ['Ancêtre du chien', 'Vit en meute', 'Hurle à la lune', 'Méchant du Petit Chaperon rouge', 'Grand canidé sauvage'] },
    { name: 'Renard', emoji: '🦊🍂🌙', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'forêt', 'sauvage', 'poils', 'nocturne', 'petit', 'rapide'], clues: ['Petit canidé sauvage', 'Réputé rusé', 'Queue touffue', 'Pelage roux', 'Ami du Petit Prince'] },
    { name: 'Écureuil', emoji: '🐿️🌰🌳', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'forêt', 'sauvage', 'petit', 'poils', 'arbre', 'saute', 'rapide'], clues: ['Petit rongeur', 'Grande queue en panache', 'Cache des provisions pour l\'hiver', 'Adore les noisettes', 'Saute de branche en branche'] },
    { name: 'Kangourou', emoji: '🦘🇦🇺👶', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'sauvage', 'grand', 'poils', 'saute', 'rapide', 'groupe'], clues: ['Animal d\'Océanie', 'Marsupial', 'Boxe parfois', 'Porte son bébé dans une poche', 'Se déplace en sautant'] },
    { name: 'Koala', emoji: '🐨🌿😴', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'sauvage', 'petit', 'poils', 'arbre', 'lent', 'nocturne'], clues: ['Petit marsupial', 'Dort jusqu\'à 20 heures par jour', 'Ne mange que de l\'eucalyptus', 'Grandes oreilles duveteuses', 'Emblème de l\'Australie'] },
    { name: 'Paresseux', emoji: '🦥🌳💤', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'amerique', 'jungle', 'sauvage', 'lent', 'arbre', 'poils'], clues: ['Vit la tête en bas', 'Accroché aux branches', 'Descend rarement au sol', 'Sid dans L\'Âge de glace', 'Animal le plus lent'] },
    { name: 'Chauve-souris', emoji: '🦇🌙🦇', group: 'Mammifère', tags: ['mammifère', 'vole', 'nocturne', 'sauvage', 'petit', 'poils', 'noir', 'groupe', 'insectivore'], clues: ['Dort la tête en bas', 'Se repère grâce aux ultrasons', 'Vit dans les grottes', 'Symbole de Batman', 'Seul mammifère qui vole vraiment'] },
    { name: 'Castor', emoji: '🦫🪵💧', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'amerique', 'forêt', 'sauvage', 'nage', 'poils', 'petit'], clues: ['Rongeur bâtisseur', 'Dents orange très fortes', 'Queue plate', 'Construit des barrages', 'Emblème du Canada'] },
    { name: 'Hérisson', emoji: '🦔🍂🌙', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'forêt', 'sauvage', 'petit', 'nocturne', 'lent', 'domestique'], clues: ['Petit animal des jardins', 'Se roule en boule', 'Mange limaces et insectes', 'Sonic en est un', 'Couvert de piquants'] },
    { name: 'Dauphin', emoji: '🐬🌊😄', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'mer', 'nage', 'sauvage', 'grand', 'groupe', 'rapide', 'saute'], clues: ['Animal marin très intelligent', 'Respire par un évent', 'Communique avec des clics', 'Fait des sauts hors de l\'eau', 'Flipper en est un'] },
    { name: 'Baleine', emoji: '🐋🌊💦', group: 'Mammifère', tags: ['mammifère', 'mer', 'nage', 'sauvage', 'grand', 'lent', 'froid', 'groupe'], clues: ['Géant des océans', 'Chante sous l\'eau', 'Crache un jet d\'eau', 'A avalé Pinocchio', 'Plus grand animal du monde'] },
    { name: 'Phoque', emoji: '🦭🧊🐟', group: 'Mammifère', tags: ['mammifère', 'carnivore', 'mer', 'nage', 'sauvage', 'froid', 'groupe', 'poils'], clues: ['Mammifère marin', 'Maladroit sur la glace', 'Mange du poisson', 'Proie des ours polaires', 'Se prélasse sur la banquise'] },
    // ——— Domestiques & ferme ———
    { name: 'Chien', emoji: '🐕🦴🐾', group: 'Mammifère', tags: ['mammifère', 'domestique', 'carnivore', 'poils', 'nage', 'rapide', 'groupe', 'omnivore'], clues: ['Animal de compagnie', 'Remue la queue', 'Aboie', 'Meilleur ami de l\'homme', 'Ancêtre : le loup'] },
    { name: 'Chat', emoji: '🐈😺🧶', group: 'Mammifère', tags: ['mammifère', 'domestique', 'carnivore', 'poils', 'petit', 'nocturne', 'arbre', 'saute'], clues: ['Animal de compagnie', 'Ronronne', 'Retombe toujours sur ses pattes', 'Star d\'Internet', 'Miaule'] },
    { name: 'Lapin', emoji: '🐇🥕🐣', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'domestique', 'ferme', 'petit', 'poils', 'saute', 'rapide', 'blanc'], clues: ['Petit animal aux longues oreilles', 'Adore les carottes', 'Vit dans un terrier', 'Porte les œufs à Pâques', 'Bugs Bunny en est un'] },
    { name: 'Hamster', emoji: '🐹🎡🌻', group: 'Mammifère', tags: ['mammifère', 'domestique', 'herbivore', 'petit', 'poils', 'nocturne', 'rapide'], clues: ['Petit rongeur de compagnie', 'Court dans une roue', 'Stocke la nourriture dans ses joues', 'Vit dans une cage', 'Adore les graines de tournesol'] },
    { name: 'Souris', emoji: '🐭🧀🕳️', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'petit', 'poils', 'nocturne', 'rapide', 'domestique', 'gris'], clues: ['Tout petit rongeur', 'Fait peur à certains', 'Adore le fromage', 'Poursuivie par le chat', 'Mickey en est une'] },
    { name: 'Cheval', emoji: '🐎🏇🌾', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'ferme', 'domestique', 'grand', 'poils', 'rapide', 'groupe', 'saute'], clues: ['Animal qu\'on monte', 'Crinière et sabots', 'Hennit', 'Galope', 'Porte des fers aux pieds'] },
    { name: 'Âne', emoji: '🫏🌾🥕', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'ferme', 'domestique', 'poils', 'lent', 'gris', 'groupe'], clues: ['Animal de la ferme', 'Réputé têtu', 'Longues oreilles', 'Fait « hi-han »', 'Ami de Shrek'] },
    { name: 'Vache', emoji: '🐄🥛🌾', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'ferme', 'domestique', 'grand', 'taches', 'noir', 'blanc', 'cornes', 'groupe'], clues: ['Animal de la ferme', 'Rumine toute la journée', 'Fait « meuh »', 'Porte une cloche en montagne', 'Donne du lait'] },
    { name: 'Cochon', aliases: ['Porc'], emoji: '🐷🐽💩', group: 'Mammifère', tags: ['mammifère', 'omnivore', 'ferme', 'domestique', 'poils', 'groupe', 'lent'], clues: ['Animal de la ferme', 'Se roule dans la boue', 'Queue en tire-bouchon', 'Grogne', 'Rose avec un groin'] },
    { name: 'Mouton', emoji: '🐑☁️🧶', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'ferme', 'domestique', 'poils', 'blanc', 'groupe', 'cornes'], clues: ['Animal de la ferme', 'On le compte pour s\'endormir', 'Fait « bêê »', 'Suit le troupeau', 'Donne de la laine'] },
    { name: 'Chèvre', emoji: '🐐🧀⛰️', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'ferme', 'domestique', 'poils', 'cornes', 'saute', 'groupe'], clues: ['Animal de la ferme', 'Grimpe partout', 'Mange de tout, même le papier', 'Petite barbichette', 'Son lait donne du fromage'] },
    { name: 'Lama', emoji: '🦙🏔️💦', group: 'Mammifère', tags: ['mammifère', 'herbivore', 'amerique', 'ferme', 'domestique', 'poils', 'groupe', 'froid'], clues: ['Animal des montagnes', 'Cou long et laine épaisse', 'Crache quand il est énervé', 'Cousin du chameau', 'Vit dans les Andes'] },
    // ——— Oiseaux ———
    { name: 'Poule', emoji: '🐔🥚🌾', group: 'Oiseau', tags: ['oiseau', 'ferme', 'domestique', 'plumes', 'omnivore', 'petit', 'groupe'], clues: ['Oiseau de la ferme', 'Picore des graines', 'Caquette', 'Vit dans un poulailler', 'Pond des œufs'] },
    { name: 'Canard', emoji: '🦆💧🌾', group: 'Oiseau', tags: ['oiseau', 'ferme', 'domestique', 'plumes', 'nage', 'vole', 'omnivore', 'groupe'], clues: ['Oiseau de la mare', 'Pattes palmées', 'Fait « coin-coin »', 'Donald en est un', 'Nage et vole'] },
    { name: 'Aigle', emoji: '🦅🏔️👁️', group: 'Oiseau', tags: ['oiseau', 'carnivore', 'vole', 'sauvage', 'plumes', 'grand', 'rapide', 'amerique'], clues: ['Rapace', 'Vue exceptionnelle', 'Serres puissantes', 'Niche en haut des falaises', 'Symbole des États-Unis'] },
    { name: 'Perroquet', emoji: '🦜🌈🗣️', group: 'Oiseau', tags: ['oiseau', 'vole', 'plumes', 'coloré', 'jungle', 'domestique', 'herbivore', 'arbre', 'amerique'], clues: ['Oiseau exotique', 'Plumes très colorées', 'Bec crochu', 'Compagnon des pirates', 'Répète ce qu\'on dit'] },
    { name: 'Manchot', aliases: ['Pingouin'], emoji: '🐧❄️🐟', group: 'Oiseau', tags: ['oiseau', 'plumes', 'nage', 'froid', 'mer', 'noir', 'blanc', 'groupe', 'carnivore', 'lent'], clues: ['Oiseau qui ne vole pas', 'Marche en se dandinant', 'Excellent nageur', 'Vit en Antarctique', 'Noir et blanc, comme en smoking'] },
    { name: 'Hibou', aliases: ['Chouette'], emoji: '🦉🌙🌲', group: 'Oiseau', tags: ['oiseau', 'carnivore', 'vole', 'nocturne', 'forêt', 'sauvage', 'plumes', 'arbre'], clues: ['Oiseau de nuit', 'Tourne la tête presque en entier', 'Grands yeux ronds', 'Hedwige dans Harry Potter', 'Fait « hou-hou »'] },
    { name: 'Flamant rose', emoji: '🦩💗🌊', group: 'Oiseau', tags: ['oiseau', 'vole', 'plumes', 'coloré', 'afrique', 'sauvage', 'groupe', 'grand'], clues: ['Oiseau élégant', 'Dort sur une patte', 'Vit dans les lagunes', 'Sa couleur vient des crevettes', 'Tout rose'] },
    { name: 'Autruche', emoji: '🪶🏃🥚', group: 'Oiseau', tags: ['oiseau', 'afrique', 'savane', 'sauvage', 'plumes', 'grand', 'rapide', 'omnivore'], clues: ['Oiseau qui ne vole pas', 'Court très vite', 'Pond des œufs énormes', 'Soi-disant met la tête dans le sable', 'Plus grand oiseau du monde'] },
    { name: 'Pigeon', emoji: '🐦🏙️🍞', group: 'Oiseau', tags: ['oiseau', 'vole', 'plumes', 'gris', 'petit', 'groupe', 'omnivore', 'domestique'], clues: ['Oiseau des villes', 'Envahit les places', 'Roucoule', 'Portait des messages autrefois', 'Gris et partout à Paris'] },
    { name: 'Paon', emoji: '🦚✨💙', group: 'Oiseau', tags: ['oiseau', 'plumes', 'coloré', 'asie', 'ferme', 'grand', 'omnivore'], clues: ['Oiseau très fier', 'Cri strident', 'Motifs en forme d\'yeux', 'Fait la roue', 'Queue bleue et verte magnifique'] },
    // ——— Reptiles & amphibiens ———
    { name: 'Crocodile', emoji: '🐊💧🦷', group: 'Reptile', tags: ['reptile', 'carnivore', 'afrique', 'nage', 'sauvage', 'dangereux', 'grand', 'écailles', 'lent'], clues: ['Reptile préhistorique', 'Guette ses proies sous l\'eau', 'Mâchoire redoutable', 'Pleure de faux larmes', 'Cousin de l\'alligator'] },
    { name: 'Serpent', aliases: ['Python', 'Cobra'], emoji: '🐍🌿⚠️', group: 'Reptile', tags: ['reptile', 'carnivore', 'sauvage', 'dangereux', 'venimeux', 'écailles', 'jungle', 'afrique', 'asie'], clues: ['Reptile sans pattes', 'Mue régulièrement', 'Langue fourchue', 'Siffle', 'Kaa dans Le Livre de la jungle'] },
    { name: 'Tortue', emoji: '🐢🐌🌊', group: 'Reptile', tags: ['reptile', 'herbivore', 'lent', 'nage', 'mer', 'domestique', 'écailles'], clues: ['Reptile qui vit très longtemps', 'Carapace', 'Rentre la tête', 'A battu le lièvre dans une fable', 'Symbole de lenteur'] },
    { name: 'Caméléon', emoji: '🦎🌈👀', group: 'Reptile', tags: ['reptile', 'carnivore', 'afrique', 'jungle', 'sauvage', 'petit', 'coloré', 'arbre', 'lent', 'écailles'], clues: ['Petit reptile', 'Yeux qui bougent séparément', 'Langue très longue', 'Pascal dans Raiponce', 'Change de couleur'] },
    { name: 'Lézard', aliases: ['Gecko'], emoji: '🦎☀️🪨', group: 'Reptile', tags: ['reptile', 'carnivore', 'petit', 'sauvage', 'rapide', 'écailles', 'domestique'], clues: ['Petit reptile', 'Se chauffe au soleil sur les murs', 'Sa queue repousse', 'Mange des insectes', 'Gecko ou iguane'] },
    { name: 'Grenouille', emoji: '🐸💧👑', group: 'Amphibien', tags: ['amphibien', 'carnivore', 'petit', 'nage', 'saute', 'sauvage', 'insectivore', 'coloré'], clues: ['Amphibien', 'Naît têtard', 'Coasse', 'Un prince transformé dans les contes', 'Saute de nénuphar en nénuphar'] },
    // ——— Mer ———
    { name: 'Requin', emoji: '🦈🌊🦷', group: 'Poisson', tags: ['poisson', 'carnivore', 'mer', 'nage', 'sauvage', 'dangereux', 'grand', 'rapide', 'gris'], clues: ['Prédateur des océans', 'Aileron qui dépasse de l\'eau', 'Plusieurs rangées de dents', 'Star du film Les Dents de la mer', 'Requin blanc ou marteau'] },
    { name: 'Poisson-clown', emoji: '🐠🧡🪸', group: 'Poisson', tags: ['poisson', 'mer', 'nage', 'petit', 'coloré', 'omnivore', 'sauvage', 'blanc'], clues: ['Petit poisson tropical', 'Vit dans les coraux', 'Cache dans une anémone', 'Orange avec des bandes blanches', 'Nemo en est un'] },
    { name: 'Saumon', emoji: '🐟🍣🌊', group: 'Poisson', tags: ['poisson', 'carnivore', 'mer', 'nage', 'sauvage', 'saute', 'froid', 'coloré'], clues: ['Poisson migrateur', 'Remonte les rivières', 'Saute les cascades', 'Pêché par les ours', 'Chair rose dans les sushis'] },
    { name: 'Pieuvre', aliases: ['Poulpe'], emoji: '🐙🌊🖤', group: 'Mollusque', tags: ['mollusque', 'carnivore', 'mer', 'nage', 'sauvage', 'noir', 'nocturne', 'coloré'], clues: ['Animal marin sans os', 'Trois cœurs', 'Crache de l\'encre', 'Très intelligente', 'Huit tentacules'] },
    { name: 'Méduse', emoji: '🪼🌊⚡', group: 'Invertébré marin', tags: ['mer', 'nage', 'sauvage', 'dangereux', 'venimeux', 'petit', 'blanc', 'groupe', 'carnivore'], clues: ['Animal marin gélatineux', 'Transparente', 'Aucun cerveau', 'Pique quand on la touche', 'Envahit les plages l\'été'] },
    { name: 'Crabe', emoji: '🦀🏖️🌊', group: 'Crustacé', tags: ['crustacé', 'omnivore', 'mer', 'nage', 'petit', 'sauvage', 'coloré'], clues: ['Animal des plages', 'Carapace dure', 'Pinces', 'Marche de côté', 'Sébastien dans La Petite Sirène'] },
    // ——— Insectes & arachnides ———
    { name: 'Abeille', emoji: '🐝🍯🌸', group: 'Insecte', tags: ['insecte', 'vole', 'petit', 'rayures', 'noir', 'groupe', 'venimeux', 'herbivore', 'ferme'], clues: ['Insecte travailleur', 'Vit dans une ruche', 'Butine les fleurs', 'Pique', 'Fabrique du miel'] },
    { name: 'Papillon', emoji: '🦋🌸🌈', group: 'Insecte', tags: ['insecte', 'vole', 'petit', 'coloré', 'herbivore', 'sauvage', 'forêt'], clues: ['Insecte élégant', 'Était une chenille', 'Sort d\'un cocon', 'Ailes très colorées', 'Butine en voletant'] },
    { name: 'Fourmi', emoji: '🐜🏔️💪', group: 'Insecte', tags: ['insecte', 'petit', 'noir', 'groupe', 'omnivore', 'sauvage', 'rapide'], clues: ['Insecte minuscule', 'Porte plusieurs fois son poids', 'Vit en colonie', 'Travaille pour sa reine', 'Face à la cigale dans la fable'] },
    { name: 'Moustique', emoji: '🦟🩸😤', group: 'Insecte', tags: ['insecte', 'vole', 'petit', 'dangereux', 'nocturne', 'carnivore', 'noir'], clues: ['Insecte énervant', 'Bourdonne à l\'oreille la nuit', 'Laisse des boutons', 'Peut transmettre le paludisme', 'Pique et suce le sang'] },
    { name: 'Coccinelle', emoji: '🐞🍀🔴', group: 'Insecte', tags: ['insecte', 'vole', 'petit', 'taches', 'noir', 'coloré', 'carnivore'], clues: ['Petit insecte porte-bonheur', 'Mange les pucerons', 'Carapace ronde', 'Rouge à points noirs', 'Surnommée « bête à bon Dieu »'] },
    { name: 'Araignée', emoji: '🕷️🕸️😱', group: 'Arachnide', tags: ['arachnide', 'carnivore', 'petit', 'venimeux', 'noir', 'nocturne', 'domestique', 'sauvage'], clues: ['Fait peur à beaucoup de monde', 'Huit pattes', 'Tisse une toile', 'A donné ses pouvoirs à Peter Parker', 'Attrape les mouches'] },
    { name: 'Scorpion', emoji: '🦂🏜️⚠️', group: 'Arachnide', tags: ['arachnide', 'carnivore', 'petit', 'venimeux', 'dangereux', 'nocturne', 'afrique', 'sauvage'], clues: ['Animal du désert', 'Huit pattes et deux pinces', 'Brille sous la lumière UV', 'Signe du zodiaque', 'Dard au bout de la queue'] },
  ],
};
