import type { Pack } from '../types';

export const pack: Pack = {
  id: 'anime-personnages',
  name: 'Personnages d’anime',
  emoji: '🍥',
  category: 'anime',
  description: 'Les héros, rivaux et méchants les plus célèbres des animes et mangas.',
  attributes: [
    { tag: 'homme', question: 'Est-ce un homme ?' },
    { tag: 'femme', question: 'Est-ce une femme ?' },
    { tag: 'héros', question: 'Est-ce un héros ?' },
    { tag: 'méchant', question: 'Est-ce un méchant ?' },
    { tag: 'anti-héros', question: 'Est-ce un anti-héros ?' },
    { tag: 'non-humain', question: 'Est-ce un être non humain ?' },
    { tag: 'démon', question: 'Est-ce un démon ou une créature maléfique ?' },
    { tag: 'protagoniste', question: 'Est-ce le personnage principal de sa série ?' },
    { tag: 'cheveux-noirs', question: 'A-t-il/elle les cheveux noirs ?' },
    { tag: 'cheveux-blonds', question: 'A-t-il/elle les cheveux blonds ?' },
    { tag: 'cheveux-roses', question: 'A-t-il/elle les cheveux roses ?' },
    { tag: 'cheveux-blancs', question: 'A-t-il/elle les cheveux blancs ou argentés ?' },
    { tag: 'cheveux-roux', question: 'A-t-il/elle les cheveux roux, orange ou rouges ?' },
    { tag: 'cheveux-bleus', question: 'A-t-il/elle les cheveux bleus ?' },
    { tag: 'cheveux-verts', question: 'A-t-il/elle les cheveux verts ?' },
    { tag: 'épéiste', question: 'Se bat-il/elle avec une épée ?' },
    { tag: 'ninja', question: 'Est-ce un ninja ?' },
    { tag: 'pirate', question: 'Est-ce un pirate ?' },
    { tag: 'sorcier', question: 'Utilise-t-il/elle la magie ou la sorcellerie ?' },
    { tag: 'combattant-mains-nues', question: 'Se bat-il/elle surtout à mains nues ?' },
    { tag: 'pouvoir-oculaire', question: 'A-t-il/elle un pouvoir lié aux yeux ?' },
    { tag: 'feu', question: 'Maîtrise-t-il/elle le feu ?' },
    { tag: 'glace', question: 'Maîtrise-t-il/elle la glace ?' },
    { tag: 'foudre', question: 'Maîtrise-t-il/elle la foudre ?' },
    { tag: 'transformation', question: 'Peut-il/elle se transformer ?' },
    { tag: 'génie', question: 'Est-il/elle connu(e) pour son intelligence ?' },
    { tag: 'drôle', question: 'Est-ce un personnage comique ?' },
    { tag: 'sérieux', question: 'Est-ce un personnage froid ou sérieux ?' },
    { tag: 'enfant', question: 'Est-ce un enfant ?' },
    { tag: 'adulte', question: 'Est-ce un adulte ?' },
    { tag: 'lycéen', question: 'Est-il/elle lycéen(ne) ou étudiant(e) ?' },
    { tag: 'mentor', question: 'Est-ce un mentor pour d’autres personnages ?' },
    { tag: 'rival', question: 'Est-ce le rival du héros ?' },
    { tag: 'leader', question: 'Dirige-t-il/elle un groupe ?' },
    { tag: 'chasseur', question: 'Est-ce un chasseur (de démons, de monstres, de trésors…) ?' },
    { tag: 'naruto', question: 'Vient-il/elle de Naruto ?' },
    { tag: 'one-piece', question: 'Vient-il/elle de One Piece ?' },
    { tag: 'dragon-ball', question: 'Vient-il/elle de Dragon Ball ?' },
    { tag: 'jujutsu-kaisen', question: 'Vient-il/elle de Jujutsu Kaisen ?' },
    { tag: 'attaque-des-titans', question: 'Vient-il/elle de L’Attaque des Titans ?' },
  ],
  items: [
    // ——— Naruto ———
    {
      name: 'Naruto Uzumaki',
      aliases: ['Naruto', 'Uzumaki'],
      emoji: '🍜🦊🌀',
      group: 'Naruto',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-blonds', 'ninja', 'transformation', 'drôle', 'adolescent', 'naruto'],
      clues: [
        'Un garçon bruyant rejeté par son village',
        'Adore les ramens',
        'Porte un démon renard scellé en lui',
        'Rêve de devenir Hokage',
        'Ninja de Konoha à la tenue orange',
      ],
    },
    {
      name: 'Sasuke Uchiha',
      aliases: ['Sasuke', 'Uchiha Sasuke'],
      emoji: '⚡👁️🗡️',
      group: 'Naruto',
      tags: ['homme', 'anti-héros', 'humain', 'cheveux-noirs', 'ninja', 'épéiste', 'pouvoir-oculaire', 'foudre', 'feu', 'sérieux', 'rival', 'naruto'],
      clues: [
        'Dernier survivant d’un clan massacré',
        'Obsédé par la vengeance contre son frère',
        'Maîtrise le Chidori',
        'Possède le Sharingan',
        'Rival et meilleur ami de Naruto',
      ],
    },
    {
      name: 'Kakashi Hatake',
      aliases: ['Kakashi'],
      emoji: '📖😷⚡',
      group: 'Naruto',
      tags: ['homme', 'héros', 'humain', 'cheveux-blancs', 'ninja', 'pouvoir-oculaire', 'foudre', 'adulte', 'mentor', 'naruto'],
      clues: [
        'Toujours en retard',
        'Cache le bas de son visage',
        'Lit des romans coquins en public',
        'Surnommé le ninja copieur',
        'Professeur de l’équipe 7 dans Naruto',
      ],
    },
    {
      name: 'Sakura Haruno',
      aliases: ['Sakura'],
      emoji: '🌸👊💚',
      group: 'Naruto',
      tags: ['femme', 'héros', 'humain', 'cheveux-roses', 'ninja', 'combattant-mains-nues', 'adolescent', 'naruto'],
      clues: [
        'Longtemps amoureuse d’un garçon ténébreux',
        'Force surhumaine dans les poings',
        'Devient une grande ninja médecin',
        'Élève de Tsunade',
        'Seule fille de l’équipe 7 de Naruto',
      ],
    },
    {
      name: 'Itachi Uchiha',
      aliases: ['Itachi'],
      emoji: '🐦‍⬛👁️🔥',
      group: 'Naruto',
      tags: ['homme', 'anti-héros', 'méchant', 'humain', 'cheveux-noirs', 'ninja', 'pouvoir-oculaire', 'feu', 'sérieux', 'génie', 'naruto'],
      clues: [
        'Un prodige au passé tragique',
        'A anéanti son propre clan',
        'Membre de l’Akatsuki',
        'Maîtrise l’Amaterasu et le Tsukuyomi',
        'Grand frère de Sasuke',
      ],
    },
    {
      name: 'Gaara',
      aliases: ['Gaara du Désert'],
      emoji: '🏜️🐾❤️',
      group: 'Naruto',
      tags: ['homme', 'héros', 'humain', 'cheveux-roux', 'ninja', 'sérieux', 'leader', 'naruto'],
      clues: [
        'Un enfant autrefois solitaire et redouté',
        'Porte une grande gourde sur le dos',
        'Contrôle le sable',
        'Kanji « amour » sur le front',
        'Devient Kazekage dans Naruto',
      ],
    },
    // ——— One Piece ———
    {
      name: 'Monkey D. Luffy',
      aliases: ['Luffy', 'Luffy au chapeau de paille'],
      emoji: '👒🍖🏴‍☠️',
      group: 'One Piece',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'pirate', 'combattant-mains-nues', 'transformation', 'drôle', 'leader', 'one-piece'],
      clues: [
        'Mange sans jamais s’arrêter',
        'Son corps est élastique',
        'Capitaine d’un équipage',
        'Veut devenir le roi des pirates',
        'Porte un chapeau de paille dans One Piece',
      ],
    },
    {
      name: 'Roronoa Zoro',
      aliases: ['Zoro'],
      emoji: '⚔️⚔️⚔️🧭',
      group: 'One Piece',
      tags: ['homme', 'héros', 'humain', 'cheveux-verts', 'pirate', 'épéiste', 'sérieux', 'adulte', 'one-piece'],
      clues: [
        'Se perd tout le temps',
        'Dort dès qu’il peut',
        'Se bat avec trois sabres',
        'Veut devenir le meilleur bretteur du monde',
        'Second de Luffy dans One Piece',
      ],
    },
    {
      name: 'Nami',
      aliases: ['Chatte Voleuse'],
      emoji: '🍊🗺️💰',
      group: 'One Piece',
      tags: ['femme', 'héros', 'humain', 'cheveux-roux', 'pirate', 'génie', 'foudre', 'adulte', 'one-piece'],
      clues: [
        'Adore l’argent',
        'Détrousse volontiers les pirates',
        'Dessine des cartes marines',
        'Contrôle la météo avec un bâton',
        'Navigatrice de l’équipage de Luffy',
      ],
    },
    {
      name: 'Vinsmoke Sanji',
      aliases: ['Sanji'],
      emoji: '🚬🍳🦵',
      group: 'One Piece',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'pirate', 'combattant-mains-nues', 'feu', 'drôle', 'adulte', 'one-piece'],
      clues: [
        'Sourcil en spirale',
        'Fond devant toutes les femmes',
        'Ne se bat qu’avec les jambes',
        'Cuisinier de génie',
        'Chef du Thousand Sunny dans One Piece',
      ],
    },
    {
      name: 'Shanks le Roux',
      aliases: ['Shanks'],
      emoji: '🍶🦾👒',
      group: 'One Piece',
      tags: ['homme', 'héros', 'humain', 'cheveux-roux', 'pirate', 'épéiste', 'adulte', 'mentor', 'leader', 'one-piece'],
      clues: [
        'Un pirate légendaire et bon vivant',
        'A perdu un bras pour sauver un enfant',
        'L’un des quatre Empereurs',
        'A offert son chapeau de paille',
        'Modèle de Luffy dans One Piece',
      ],
    },
    {
      name: 'Tony Tony Chopper',
      aliases: ['Chopper'],
      emoji: '🦌🩺🍬',
      group: 'One Piece',
      tags: ['homme', 'héros', 'non-humain', 'animal', 'pirate', 'transformation', 'drôle', 'enfant', 'one-piece'],
      clues: [
        'Adore la barbe à papa',
        'Un animal qui parle',
        'Nez bleu et chapeau rose',
        'Médecin d’un équipage',
        'Renne de l’équipage de Luffy',
      ],
    },
    // ——— Dragon Ball ———
    {
      name: 'Son Goku',
      aliases: ['Goku', 'Sangoku', 'Kakarot'],
      emoji: '🐒☁️🟠',
      group: 'Dragon Ball',
      tags: ['homme', 'héros', 'extraterrestre', 'non-humain', 'protagoniste', 'cheveux-noirs', 'combattant-mains-nues', 'transformation', 'drôle', 'adulte', 'dragon-ball'],
      clues: [
        'Naïf mais toujours affamé',
        'Avait une queue de singe enfant',
        'Vole sur un nuage magique',
        'Maître du Kamehameha',
        'Saiyan héros de Dragon Ball',
      ],
    },
    {
      name: 'Vegeta',
      aliases: ['Végéta'],
      emoji: '👑💪😤',
      group: 'Dragon Ball',
      tags: ['homme', 'anti-héros', 'extraterrestre', 'non-humain', 'noble', 'cheveux-noirs', 'combattant-mains-nues', 'transformation', 'sérieux', 'rival', 'adulte', 'dragon-ball'],
      clues: [
        'Fier et arrogant',
        'Prince d’un peuple guerrier',
        'Ancien méchant devenu allié',
        'Rêve de dépasser Kakarot',
        'Éternel rival de Goku',
      ],
    },
    {
      name: 'Son Gohan',
      aliases: ['Gohan', 'Sangohan'],
      emoji: '📚🐉🧒',
      group: 'Dragon Ball',
      tags: ['homme', 'héros', 'extraterrestre', 'cheveux-noirs', 'combattant-mains-nues', 'transformation', 'génie', 'dragon-ball'],
      clues: [
        'Préfère les études au combat',
        'Potentiel caché immense',
        'Élève de Piccolo',
        'A vaincu Cell enfant',
        'Fils aîné de Goku',
      ],
    },
    {
      name: 'Freezer',
      aliases: ['Frieza', 'Freeza'],
      emoji: '👽❄️🪐',
      group: 'Dragon Ball',
      tags: ['homme', 'méchant', 'extraterrestre', 'non-humain', 'transformation', 'leader', 'adulte', 'dragon-ball'],
      clues: [
        'Un tyran cruel et poli',
        'Détruit des planètes entières',
        'Possède plusieurs formes',
        'A anéanti la planète Vegeta',
        'Grand ennemi de Goku sur Namek',
      ],
    },
    {
      name: 'Piccolo',
      aliases: ['Petit-Cœur'],
      emoji: '🟢🧘🪄',
      group: 'Dragon Ball',
      tags: ['homme', 'héros', 'extraterrestre', 'non-humain', 'sérieux', 'mentor', 'adulte', 'dragon-ball'],
      clues: [
        'Peau verte et antennes',
        'Ancien ennemi devenu protecteur',
        'Porte une cape et un turban',
        'Namek qui entraîne Gohan',
        'Personnage de Dragon Ball',
      ],
    },
    {
      name: 'Bulma',
      aliases: ['Bulma Brief'],
      emoji: '🔧💊🏍️',
      group: 'Dragon Ball',
      tags: ['femme', 'héros', 'humain', 'cheveux-bleus', 'génie', 'drôle', 'adulte', 'dragon-ball'],
      clues: [
        'Riche héritière au caractère explosif',
        'Invente des gadgets incroyables',
        'A créé le détecteur de boules',
        'Épouse de Vegeta',
        'Amie d’enfance de Goku',
      ],
    },
    // ——— Bleach ———
    {
      name: 'Ichigo Kurosaki',
      aliases: ['Ichigo'],
      emoji: '🍓⚔️💀',
      group: 'Bleach',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-roux', 'épéiste', 'shinigami', 'transformation', 'lycéen', 'bleach'],
      clues: [
        'Lycéen qui voit les fantômes',
        'Toujours les sourcils froncés',
        'Brandit une immense épée noire',
        'Devient shinigami remplaçant',
        'Héros de Bleach',
      ],
    },
    {
      name: 'Rukia Kuchiki',
      aliases: ['Rukia'],
      emoji: '🐰❄️⚔️',
      group: 'Bleach',
      tags: ['femme', 'héros', 'non-humain', 'cheveux-noirs', 'épéiste', 'shinigami', 'glace', 'noble', 'bleach'],
      clues: [
        'Dessine très mal des lapins',
        'Plus âgée qu’elle n’en a l’air',
        'Son sabre est lié à la glace',
        'A donné ses pouvoirs à Ichigo',
        'Shinigami de Bleach',
      ],
    },
    {
      name: 'Sōsuke Aizen',
      aliases: ['Aizen', 'Sosuke Aizen'],
      emoji: '👓🦋🧠',
      group: 'Bleach',
      tags: ['homme', 'méchant', 'non-humain', 'cheveux-bruns', 'épéiste', 'shinigami', 'génie', 'lunettes', 'leader', 'adulte', 'bleach'],
      clues: [
        'Un capitaine au sourire bienveillant',
        'Maître de l’illusion',
        'A trahi la Soul Society',
        'Veut prendre la place du roi',
        'Grand manipulateur de Bleach',
      ],
    },
    {
      name: 'Byakuya Kuchiki',
      aliases: ['Byakuya'],
      emoji: '🌸⚔️🧣',
      group: 'Bleach',
      tags: ['homme', 'héros', 'non-humain', 'cheveux-noirs', 'épéiste', 'shinigami', 'noble', 'sérieux', 'leader', 'adulte', 'bleach'],
      clues: [
        'Aristocrate froid et fier',
        'Sa lame se change en pétales de cerisier',
        'Capitaine de la 6e division',
        'Grand frère adoptif de Rukia',
        'Personnage de Bleach',
      ],
    },
    // ——— Jujutsu Kaisen ———
    {
      name: 'Yuji Itadori',
      aliases: ['Yuji', 'Itadori'],
      emoji: '👊🩸👄',
      group: 'Jujutsu Kaisen',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-roses', 'combattant-mains-nues', 'sorcier', 'lycéen', 'drôle', 'jujutsu-kaisen'],
      clues: [
        'Lycéen à la force physique hors norme',
        'A avalé un doigt maudit',
        'Héberge un roi des fléaux',
        'Maîtrise le Black Flash',
        'Héros de Jujutsu Kaisen',
      ],
    },
    {
      name: 'Satoru Gojo',
      aliases: ['Gojo', 'Gojo Satoru'],
      emoji: '🕶️♾️💙',
      group: 'Jujutsu Kaisen',
      tags: ['homme', 'héros', 'humain', 'cheveux-blancs', 'sorcier', 'pouvoir-oculaire', 'drôle', 'adulte', 'mentor', 'jujutsu-kaisen'],
      clues: [
        'Se proclame le plus fort',
        'Cache ses yeux sous un bandeau',
        'Maîtrise l’Infini',
        'Possède les Six Yeux',
        'Professeur de Yuji dans Jujutsu Kaisen',
      ],
    },
    {
      name: 'Megumi Fushiguro',
      aliases: ['Megumi', 'Fushiguro'],
      emoji: '🐺🐕🌑',
      group: 'Jujutsu Kaisen',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'sorcier', 'sérieux', 'lycéen', 'rival', 'jujutsu-kaisen'],
      clues: [
        'Garçon calme aux cheveux en pétard',
        'Invoque des chiens d’ombre',
        'Utilise la technique des Dix Ombres',
        'Élève prodige de Gojo',
        'Camarade de Yuji dans Jujutsu Kaisen',
      ],
    },
    {
      name: 'Nobara Kugisaki',
      aliases: ['Nobara', 'Kugisaki'],
      emoji: '🔨📌🪆',
      group: 'Jujutsu Kaisen',
      tags: ['femme', 'héros', 'humain', 'cheveux-roux', 'sorcier', 'lycéen', 'drôle', 'jujutsu-kaisen'],
      clues: [
        'Fille de la campagne fan de Tokyo',
        'Caractère bien trempé',
        'Se bat avec un marteau et des clous',
        'Utilise une poupée de paille',
        'Seule fille du trio de Jujutsu Kaisen',
      ],
    },
    {
      name: 'Ryōmen Sukuna',
      aliases: ['Sukuna', 'Ryomen Sukuna'],
      emoji: '👹🖐️🔥',
      group: 'Jujutsu Kaisen',
      tags: ['homme', 'méchant', 'démon', 'non-humain', 'cheveux-roses', 'sorcier', 'feu', 'adulte', 'jujutsu-kaisen'],
      clues: [
        'Un être millénaire cruel',
        'Quatre bras et deux visages',
        'Ses doigts sont dispersés',
        'Roi des fléaux',
        'Occupe le corps de Yuji Itadori',
      ],
    },
    // ——— Demon Slayer ———
    {
      name: 'Tanjiro Kamado',
      aliases: ['Tanjiro'],
      emoji: '🌊🔥🎴',
      group: 'Demon Slayer',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'épéiste', 'chasseur', 'eau', 'feu', 'adolescent', 'demon-slayer'],
      clues: [
        'Garçon au cœur d’or',
        'Odorat exceptionnel',
        'Boucles d’oreilles hanafuda',
        'Cherche à guérir sa petite sœur',
        'Pourfendeur de démons, héros de Demon Slayer',
      ],
    },
    {
      name: 'Nezuko Kamado',
      aliases: ['Nezuko'],
      emoji: '🎋📦🌸',
      group: 'Demon Slayer',
      tags: ['femme', 'héros', 'démon', 'non-humain', 'cheveux-noirs', 'transformation', 'feu', 'adolescent', 'demon-slayer'],
      clues: [
        'Ne parle presque jamais',
        'Porte un bambou dans la bouche',
        'Voyage dans une boîte en bois',
        'Démone qui protège les humains',
        'Petite sœur de Tanjiro',
      ],
    },
    {
      name: 'Zenitsu Agatsuma',
      aliases: ['Zenitsu'],
      emoji: '⚡😱💤',
      group: 'Demon Slayer',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'épéiste', 'chasseur', 'foudre', 'drôle', 'adolescent', 'demon-slayer'],
      clues: [
        'Froussard qui pleure tout le temps',
        'Obsédé par les filles',
        'Devient redoutable en dormant',
        'Maîtrise le Souffle de la foudre',
        'Compagnon de Tanjiro dans Demon Slayer',
      ],
    },
    {
      name: 'Inosuke Hashibira',
      aliases: ['Inosuke'],
      emoji: '🐗🗡️🗡️',
      group: 'Demon Slayer',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'épéiste', 'chasseur', 'drôle', 'adolescent', 'demon-slayer'],
      clues: [
        'Élevé par des animaux sauvages',
        'Torse nu en permanence',
        'Porte une tête de sanglier',
        'Se bat avec deux lames ébréchées',
        'Compagnon de Tanjiro dans Demon Slayer',
      ],
    },
    {
      name: 'Muzan Kibutsuji',
      aliases: ['Muzan'],
      emoji: '🎩🩸🌑',
      group: 'Demon Slayer',
      tags: ['homme', 'méchant', 'démon', 'non-humain', 'cheveux-noirs', 'transformation', 'leader', 'adulte', 'demon-slayer'],
      clues: [
        'Élégant gentleman au chapeau',
        'Craint la lumière du soleil',
        'A créé tous les autres de son espèce',
        'Commande les Lunes démoniaques',
        'Grand méchant de Demon Slayer',
      ],
    },
    // ——— L'Attaque des Titans ———
    {
      name: 'Eren Jäger',
      aliases: ['Eren', 'Eren Yeager', 'Eren Jaeger'],
      emoji: '🧱🗝️🦷',
      group: 'L’Attaque des Titans',
      tags: ['homme', 'anti-héros', 'humain', 'protagoniste', 'cheveux-bruns', 'militaire', 'transformation', 'sérieux', 'attaque-des-titans'],
      clues: [
        'Rêve de voir la mer',
        'Porte une clé autour du cou',
        'A vu sa mère dévorée',
        'Peut se changer en géant',
        'Héros de L’Attaque des Titans',
      ],
    },
    {
      name: 'Mikasa Ackerman',
      aliases: ['Mikasa'],
      emoji: '🧣⚔️🖤',
      group: 'L’Attaque des Titans',
      tags: ['femme', 'héros', 'humain', 'cheveux-noirs', 'épéiste', 'militaire', 'sérieux', 'attaque-des-titans'],
      clues: [
        'Ne quitte jamais son écharpe rouge',
        'Soldate d’élite surdouée',
        'Protège son frère adoptif',
        'Issue d’un clan aux capacités hors normes',
        'Amie d’enfance d’Eren',
      ],
    },
    {
      name: 'Livai Ackerman',
      aliases: ['Livai', 'Levi'],
      emoji: '🧹🍵⚔️',
      group: 'L’Attaque des Titans',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'épéiste', 'militaire', 'sérieux', 'adulte', 'leader', 'attaque-des-titans'],
      clues: [
        'Petit mais redoutable',
        'Maniaque de la propreté',
        'Tient sa tasse de façon étrange',
        'Le soldat le plus fort de l’humanité',
        'Caporal du Bataillon d’exploration',
      ],
    },
    {
      name: 'Armin Arlert',
      aliases: ['Armin'],
      emoji: '📘🌊🧠',
      group: 'L’Attaque des Titans',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'militaire', 'génie', 'transformation', 'attaque-des-titans'],
      clues: [
        'Physiquement faible mais brillant',
        'Grand stratège',
        'Lisait des livres interdits sur l’océan',
        'Hérite du Titan Colossal',
        'Ami d’enfance d’Eren et Mikasa',
      ],
    },
    {
      name: 'Erwin Smith',
      aliases: ['Erwin'],
      emoji: '🫡💪📣',
      group: 'L’Attaque des Titans',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'militaire', 'génie', 'adulte', 'leader', 'attaque-des-titans'],
      clues: [
        'Un chef charismatique',
        'A perdu un bras au combat',
        'Célèbre discours « Offrez vos cœurs ! »',
        'Commandant du Bataillon d’exploration',
        'Supérieur de Livai',
      ],
    },
    // ——— My Hero Academia ———
    {
      name: 'Izuku Midoriya',
      aliases: ['Deku', 'Izuku', 'Midoriya'],
      emoji: '🥦👊📓',
      group: 'My Hero Academia',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-verts', 'combattant-mains-nues', 'lycéen', 'my-hero-academia'],
      clues: [
        'Né sans pouvoir dans un monde de pouvoirs',
        'Remplit des carnets d’analyse',
        'Pleure très facilement',
        'Hérite du One For All',
        'Héros de My Hero Academia',
      ],
    },
    {
      name: 'Katsuki Bakugo',
      aliases: ['Bakugo', 'Kacchan', 'Bakugou'],
      emoji: '💥😡🧨',
      group: 'My Hero Academia',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'combattant-mains-nues', 'feu', 'lycéen', 'rival', 'my-hero-academia'],
      clues: [
        'Hurle en permanence',
        'Arrogant mais talentueux',
        'Ses paumes produisent des explosions',
        'Ami d’enfance tyrannique de Deku',
        'Élève de Yuei dans My Hero Academia',
      ],
    },
    {
      name: 'All Might',
      aliases: ['Toshinori Yagi'],
      emoji: '💪😁🇺🇸',
      group: 'My Hero Academia',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'combattant-mains-nues', 'transformation', 'adulte', 'mentor', 'my-hero-academia'],
      clues: [
        'Symbole de la paix',
        'Sourit toujours',
        'Dit « Je suis là ! »',
        'Maigrit quand il perd sa forme musclée',
        'Mentor de Deku',
      ],
    },
    {
      name: 'Shoto Todoroki',
      aliases: ['Todoroki', 'Shōto Todoroki'],
      emoji: '🔥❄️🌓',
      group: 'My Hero Academia',
      tags: ['homme', 'héros', 'humain', 'cheveux-blancs', 'cheveux-roux', 'feu', 'glace', 'sérieux', 'lycéen', 'my-hero-academia'],
      clues: [
        'Cheveux de deux couleurs',
        'Une cicatrice autour de l’œil',
        'Fils d’un héros numéro un',
        'Contrôle le feu et la glace',
        'Élève de Yuei dans My Hero Academia',
      ],
    },
    {
      name: 'Ochaco Uraraka',
      aliases: ['Uraraka', 'Ochaco'],
      emoji: '🎈🌸🪐',
      group: 'My Hero Academia',
      tags: ['femme', 'héros', 'humain', 'cheveux-bruns', 'lycéen', 'combattant-mains-nues', 'my-hero-academia'],
      clues: [
        'Toujours souriante',
        'Veut aider ses parents financièrement',
        'Annule la gravité en touchant',
        'Nom de héroïne Uravity',
        'Amie de Deku dans My Hero Academia',
      ],
    },
    // ——— Hunter x Hunter ———
    {
      name: 'Gon Freecss',
      aliases: ['Gon'],
      emoji: '🎣🌳👦',
      group: 'Hunter x Hunter',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'combattant-mains-nues', 'chasseur', 'enfant', 'hunter-x-hunter'],
      clues: [
        'Garçon de la campagne très joyeux',
        'Se bat avec une canne à pêche',
        'Part à la recherche de son père',
        'Maîtrise le Jajanken',
        'Héros de Hunter x Hunter',
      ],
    },
    {
      name: 'Killua Zoldyck',
      aliases: ['Killua'],
      emoji: '⚡🛹🍫',
      group: 'Hunter x Hunter',
      tags: ['homme', 'héros', 'humain', 'cheveux-blancs', 'foudre', 'assassin', 'chasseur', 'enfant', 'génie', 'hunter-x-hunter'],
      clues: [
        'Fan de chocolat',
        'Issu d’une famille d’assassins',
        'Transforme son aura en électricité',
        'Meilleur ami de Gon',
        'Personnage de Hunter x Hunter',
      ],
    },
    {
      name: 'Hisoka Morow',
      aliases: ['Hisoka'],
      emoji: '🃏🤡🍬',
      group: 'Hunter x Hunter',
      tags: ['homme', 'méchant', 'humain', 'cheveux-roux', 'chasseur', 'adulte', 'drôle', 'hunter-x-hunter'],
      clues: [
        'Maquillé comme un magicien',
        'Joue avec des cartes',
        'Ne vit que pour les combats',
        'Son aura est élastique comme du chewing-gum',
        'Clown inquiétant de Hunter x Hunter',
      ],
    },
    {
      name: 'Kurapika',
      aliases: ['Kurapika Kurta'],
      emoji: '⛓️👁️‍🗨️❤️‍🔥',
      group: 'Hunter x Hunter',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'pouvoir-oculaire', 'chasseur', 'génie', 'sérieux', 'hunter-x-hunter'],
      clues: [
        'Dernier survivant de son peuple',
        'Ses yeux deviennent écarlates',
        'Combat avec des chaînes',
        'Traque la Brigade fantôme',
        'Ami de Gon dans Hunter x Hunter',
      ],
    },
    // ——— Death Note ———
    {
      name: 'Light Yagami',
      aliases: ['Light', 'Kira'],
      emoji: '📓🍎⚖️',
      group: 'Death Note',
      tags: ['homme', 'méchant', 'anti-héros', 'humain', 'protagoniste', 'cheveux-bruns', 'génie', 'sérieux', 'lycéen', 'death-note'],
      clues: [
        'Élève parfait et brillant',
        'Se prend pour un dieu justicier',
        'Trouve un cahier tombé du ciel',
        'Signe ses meurtres d’un pseudonyme divin',
        'Héros de Death Note',
      ],
    },
    {
      name: 'L',
      aliases: ['L Lawliet', 'Ryuzaki'],
      emoji: '🍰🕵️🪑',
      group: 'Death Note',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'génie', 'rival', 'adulte', 'death-note'],
      clues: [
        'Adore les sucreries',
        'S’assoit accroupi sur les chaises',
        'Plus grand détective du monde',
        'Identité représentée par une seule lettre',
        'Traque Kira dans Death Note',
      ],
    },
    {
      name: 'Ryuk',
      aliases: ['Ryûk'],
      emoji: '🍎💀🪽',
      group: 'Death Note',
      tags: ['homme', 'non-humain', 'shinigami', 'démon', 'drôle', 'death-note', 'adulte'],
      clues: [
        'S’ennuie terriblement',
        'Adore les pommes',
        'A laissé tomber un cahier par jeu',
        'Dieu de la mort',
        'Suit Light partout dans Death Note',
      ],
    },
    {
      name: 'Misa Amane',
      aliases: ['Misa'],
      emoji: '🎀🖤📓',
      group: 'Death Note',
      tags: ['femme', 'méchant', 'humain', 'cheveux-blonds', 'pouvoir-oculaire', 'drôle', 'adulte', 'death-note'],
      clues: [
        'Mannequin au style gothique',
        'Amoureuse folle d’un meurtrier',
        'A les yeux de shinigami',
        'Le second Kira',
        'Petite amie de Light',
      ],
    },
    // ——— Fullmetal Alchemist ———
    {
      name: 'Edward Elric',
      aliases: ['Edward', 'Ed', 'Fullmetal'],
      emoji: '🦾👏⚗️',
      group: 'Fullmetal Alchemist',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-blonds', 'sorcier', 'génie', 'adolescent', 'militaire', 'fullmetal-alchemist'],
      clues: [
        'Déteste qu’on le traite de petit',
        'Porte un bras mécanique',
        'Transmute sans cercle en frappant des mains',
        'Plus jeune alchimiste d’État',
        'Héros de Fullmetal Alchemist',
      ],
    },
    {
      name: 'Alphonse Elric',
      aliases: ['Alphonse', 'Al'],
      emoji: '🛡️🐈🤖',
      group: 'Fullmetal Alchemist',
      tags: ['homme', 'héros', 'non-humain', 'sorcier', 'adolescent', 'génie', 'fullmetal-alchemist'],
      clues: [
        'Doux et gentil malgré sa taille',
        'Recueille souvent des chatons',
        'Son âme est liée à une armure',
        'A perdu son corps dans une transmutation',
        'Petit frère d’Edward',
      ],
    },
    {
      name: 'Roy Mustang',
      aliases: ['Mustang'],
      emoji: '🔥🧤🫰',
      group: 'Fullmetal Alchemist',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'sorcier', 'feu', 'militaire', 'adulte', 'leader', 'fullmetal-alchemist'],
      clues: [
        'Rêve de devenir président',
        'Inutile quand il pleut',
        'Claque des doigts pour attaquer',
        'Alchimiste de flamme',
        'Colonel de Fullmetal Alchemist',
      ],
    },
    {
      name: 'Riza Hawkeye',
      aliases: ['Riza', 'Hawkeye'],
      emoji: '🔫🎯🐕',
      group: 'Fullmetal Alchemist',
      tags: ['femme', 'héros', 'humain', 'cheveux-blonds', 'tireur', 'militaire', 'sérieux', 'adulte', 'fullmetal-alchemist'],
      clues: [
        'Tireuse d’élite infaillible',
        'Possède un chien nommé Black Hayate',
        'Porte un secret tatoué dans le dos',
        'Lieutenant fidèle de Mustang',
        'Personnage de Fullmetal Alchemist',
      ],
    },
    // ——— Tokyo Ghoul ———
    {
      name: 'Ken Kaneki',
      aliases: ['Kaneki'],
      emoji: '☕👁️🦑',
      group: 'Tokyo Ghoul',
      tags: ['homme', 'anti-héros', 'non-humain', 'goule', 'protagoniste', 'cheveux-blancs', 'pouvoir-oculaire', 'transformation', 'tokyo-ghoul'],
      clues: [
        'Étudiant timide qui aime lire',
        'Survit à un rendez-vous meurtrier',
        'Un œil devient rouge et noir',
        'Ses cheveux blanchissent sous la torture',
        'Héros de Tokyo Ghoul',
      ],
    },
    {
      name: 'Touka Kirishima',
      aliases: ['Touka'],
      emoji: '🐰☕🦋',
      group: 'Tokyo Ghoul',
      tags: ['femme', 'héros', 'non-humain', 'goule', 'cheveux-bleus', 'pouvoir-oculaire', 'lycéen', 'tokyo-ghoul'],
      clues: [
        'Serveuse au caractère difficile',
        'Mèche qui cache un œil',
        'Porte un masque de lapin',
        'Travaille au café Anteiku',
        'Personnage de Tokyo Ghoul',
      ],
    },
    {
      name: 'Rize Kamishiro',
      aliases: ['Rize'],
      emoji: '📚🍽️💜',
      group: 'Tokyo Ghoul',
      tags: ['femme', 'méchant', 'non-humain', 'goule', 'cheveux-violets', 'pouvoir-oculaire', 'adulte', 'tokyo-ghoul'],
      clues: [
        'Belle lectrice à lunettes',
        'Surnommée la gloutonne',
        'Séduit ses proies avant de les dévorer',
        'Ses organes ont été greffés sur le héros',
        'Personnage de Tokyo Ghoul',
      ],
    },
    // ——— Chainsaw Man ———
    {
      name: 'Denji',
      aliases: ['Chainsaw Man'],
      emoji: '🪚🍞🐶',
      group: 'Chainsaw Man',
      tags: ['homme', 'anti-héros', 'démon', 'protagoniste', 'cheveux-blonds', 'chasseur', 'transformation', 'drôle', 'adolescent', 'chainsaw-man'],
      clues: [
        'Adolescent criblé de dettes',
        'Rêve d’une vie simple avec du pain beurré',
        'Son meilleur ami était un chien démon',
        'Des tronçonneuses sortent de sa tête',
        'Héros de Chainsaw Man',
      ],
    },
    {
      name: 'Power',
      aliases: ['Démon du Sang'],
      emoji: '🩸😈🐈',
      group: 'Chainsaw Man',
      tags: ['femme', 'anti-héros', 'démon', 'non-humain', 'cheveux-blonds', 'chasseur', 'drôle', 'chainsaw-man'],
      clues: [
        'Menteuse et égocentrique',
        'Refuse de prendre des bains',
        'A deux petites cornes rouges',
        'Adore son chat Miaou',
        'Démone du sang de Chainsaw Man',
      ],
    },
    {
      name: 'Makima',
      aliases: ['Démon du Contrôle'],
      emoji: '🐕‍🦺👁️⛓️',
      group: 'Chainsaw Man',
      tags: ['femme', 'méchant', 'démon', 'non-humain', 'cheveux-roux', 'pouvoir-oculaire', 'leader', 'adulte', 'chainsaw-man'],
      clues: [
        'Femme calme et fascinante',
        'Yeux aux cercles concentriques',
        'Traite les autres comme des chiens',
        'Dirige une section de chasseurs',
        'Patronne de Denji',
      ],
    },
    {
      name: 'Aki Hayakawa',
      aliases: ['Aki'],
      emoji: '🦊🚬⚔️',
      group: 'Chainsaw Man',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'épéiste', 'chasseur', 'sérieux', 'adulte', 'chainsaw-man'],
      clues: [
        'Porte les cheveux en chignon',
        'Veut venger sa famille',
        'A un pacte avec un démon renard',
        'Colocataire de Denji et Power',
        'Chasseur de Chainsaw Man',
      ],
    },
    // ——— Spy x Family ———
    {
      name: 'Loid Forger',
      aliases: ['Loid', 'Twilight'],
      emoji: '🕵️🎭🔫',
      group: 'Spy x Family',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-blonds', 'tireur', 'génie', 'adulte', 'spy-x-family'],
      clues: [
        'Maître du déguisement',
        'Se fait passer pour un psychiatre',
        'Monte une fausse famille pour une mission',
        'Agent secret de Westalis',
        'Espion de Spy x Family',
      ],
    },
    {
      name: 'Yor Forger',
      aliases: ['Yor', 'Princesse Épine'],
      emoji: '🌹🗡️💐',
      group: 'Spy x Family',
      tags: ['femme', 'héros', 'humain', 'cheveux-noirs', 'assassin', 'drôle', 'adulte', 'spy-x-family'],
      clues: [
        'Employée de mairie timide',
        'Cuisinière catastrophique',
        'Tueuse à gages redoutable',
        'Assassin au service du Jardin',
        'Fausse épouse de Loid',
      ],
    },
    {
      name: 'Anya Forger',
      aliases: ['Anya'],
      emoji: '🥜🧠😏',
      group: 'Spy x Family',
      tags: ['femme', 'héros', 'humain', 'cheveux-roses', 'enfant', 'drôle', 'spy-x-family'],
      clues: [
        'Adore les cacahuètes',
        'Fait des grimaces mémorables',
        'Lit dans les pensées',
        'Adoptée par un espion',
        'Petite fille de Spy x Family',
      ],
    },
    // ——— Solo Leveling ———
    {
      name: 'Sung Jin-woo',
      aliases: ['Jin-woo', 'Sung Jinwoo', 'Jinwoo'],
      emoji: '🗡️🌑🎮',
      group: 'Solo Leveling',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'chasseur', 'sorcier', 'leader', 'adulte', 'solo-leveling'],
      clues: [
        'Était le plus faible de sa profession',
        'Survit à un donjon double',
        'Monte de niveau grâce à un système',
        'Commande une armée des ombres',
        'Héros de Solo Leveling',
      ],
    },
    {
      name: 'Cha Hae-in',
      aliases: ['Hae-in', 'Cha Haein'],
      emoji: '⚔️🌸👃',
      group: 'Solo Leveling',
      tags: ['femme', 'héros', 'humain', 'cheveux-blonds', 'épéiste', 'chasseur', 'adulte', 'solo-leveling'],
      clues: [
        'Épéiste de rang S',
        'Sent l’odeur de la magie des autres',
        'Vice-présidente d’une guilde',
        'Tombe sous le charme du héros',
        'Personnage de Solo Leveling',
      ],
    },
    {
      name: 'Igris',
      aliases: ['Igris le Sanglant'],
      emoji: '🛡️🔴🌑',
      group: 'Solo Leveling',
      tags: ['homme', 'héros', 'non-humain', 'épéiste', 'sérieux', 'solo-leveling', 'adulte', 'militaire'],
      clues: [
        'Chevalier en armure au panache rouge',
        'Ancien gardien d’un donjon',
        'Loyal jusqu’à la mort',
        'Première ombre de chevalier du héros',
        'Soldat de l’ombre de Solo Leveling',
      ],
    },
    // ——— Black Clover ———
    {
      name: 'Asta',
      aliases: ['Asta de Black Clover'],
      emoji: '🗡️🍀😤',
      group: 'Black Clover',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-blancs', 'épéiste', 'drôle', 'adolescent', 'black-clover'],
      clues: [
        'Crie tout le temps',
        'Né sans aucune magie',
        'Muscles entraînés à l’extrême',
        'Grimoire à cinq feuilles',
        'Veut devenir Empereur-Mage dans Black Clover',
      ],
    },
    {
      name: 'Yuno',
      aliases: ['Yuno Grinberryall'],
      emoji: '🌪️🍀🐦',
      group: 'Black Clover',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'sorcier', 'sérieux', 'rival', 'adolescent', 'black-clover'],
      clues: [
        'Prodige calme et doué',
        'Abandonné dans une église',
        'Maîtrise la magie du vent',
        'Grimoire à quatre feuilles',
        'Rival d’Asta',
      ],
    },
    {
      name: 'Noelle Silva',
      aliases: ['Noelle'],
      emoji: '💧👑🫧',
      group: 'Black Clover',
      tags: ['femme', 'héros', 'humain', 'cheveux-blancs', 'sorcier', 'eau', 'noble', 'adolescent', 'black-clover'],
      clues: [
        'Princesse orgueilleuse',
        'Longtemps incapable de viser',
        'Maîtrise la magie de l’eau',
        'Membre des Taureaux noirs',
        'Amie d’Asta dans Black Clover',
      ],
    },
    // ——— Fairy Tail ———
    {
      name: 'Natsu Dragneel',
      aliases: ['Natsu'],
      emoji: '🔥🐉🧣',
      group: 'Fairy Tail',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-roses', 'sorcier', 'feu', 'combattant-mains-nues', 'drôle', 'fairy-tail'],
      clues: [
        'Malade dans tous les transports',
        'Mange des flammes',
        'Porte une écharpe en écailles',
        'Chasseur de dragons de feu',
        'Mage de Fairy Tail',
      ],
    },
    {
      name: 'Lucy Heartfilia',
      aliases: ['Lucy'],
      emoji: '🗝️⭐📜',
      group: 'Fairy Tail',
      tags: ['femme', 'héros', 'humain', 'cheveux-blonds', 'sorcier', 'noble', 'drôle', 'fairy-tail'],
      clues: [
        'Fille de riche en fuite',
        'Rêve d’écrire un roman',
        'Invoque des esprits avec des clés',
        'Constellationniste',
        'Partenaire de Natsu dans Fairy Tail',
      ],
    },
    {
      name: 'Erza Scarlet',
      aliases: ['Erza', 'Titania'],
      emoji: '🛡️🍰⚔️',
      group: 'Fairy Tail',
      tags: ['femme', 'héros', 'humain', 'cheveux-roux', 'épéiste', 'sorcier', 'transformation', 'sérieux', 'leader', 'fairy-tail'],
      clues: [
        'Adore les fraisiers',
        'Terrifie ses propres amis',
        'Change d’armure en un instant',
        'Surnommée la reine des fées',
        'Mage de Fairy Tail',
      ],
    },
    {
      name: 'Grey Fullbuster',
      aliases: ['Grey', 'Gray'],
      emoji: '🧊👕❄️',
      group: 'Fairy Tail',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'sorcier', 'glace', 'rival', 'drôle', 'fairy-tail'],
      clues: [
        'Se déshabille sans s’en rendre compte',
        'Façonne des objets gelés',
        'Mage de glace',
        'Se dispute sans cesse avec Natsu',
        'Membre de Fairy Tail',
      ],
    },
    // ——— One Punch Man ———
    {
      name: 'Saitama',
      aliases: ['One Punch Man', 'Chauve à cape'],
      emoji: '🥚👊🛒',
      group: 'One Punch Man',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'chauve', 'combattant-mains-nues', 'drôle', 'adulte', 'one-punch-man'],
      clues: [
        'S’ennuie car il est trop fort',
        'Chasse les promotions au supermarché',
        'A perdu tous ses cheveux à l’entraînement',
        'Gagne chaque combat en un coup',
        'Héros de One Punch Man',
      ],
    },
    {
      name: 'Genos',
      aliases: ['Cyborg démoniaque'],
      emoji: '🤖🔥📝',
      group: 'One Punch Man',
      tags: ['homme', 'héros', 'robot', 'non-humain', 'cheveux-blonds', 'feu', 'sérieux', 'one-punch-man'],
      clues: [
        'Prend des notes sur tout',
        'Corps presque entièrement mécanique',
        'Se fait souvent détruire en combat',
        'Disciple dévoué d’un chauve',
        'Cyborg de One Punch Man',
      ],
    },
    {
      name: 'Tatsumaki',
      aliases: ['Tornade Terrible'],
      emoji: '🌪️🟢😤',
      group: 'One Punch Man',
      tags: ['femme', 'héros', 'humain', 'cheveux-verts', 'sorcier', 'adulte', 'one-punch-man'],
      clues: [
        'Petite mais extrêmement puissante',
        'Caractère exécrable',
        'Télékinésie surpuissante',
        'Héroïne de classe S numéro 2',
        'Personnage de One Punch Man',
      ],
    },
    // ——— Blue Lock ———
    {
      name: 'Yoichi Isagi',
      aliases: ['Isagi'],
      emoji: '⚽👁️🧩',
      group: 'Blue Lock',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'sport', 'génie', 'lycéen', 'blue-lock'],
      clues: [
        'Lycéen éliminé d’un tournoi',
        'Vision spatiale exceptionnelle',
        'Invité dans un programme d’entraînement fermé',
        'Veut devenir le meilleur attaquant',
        'Héros de Blue Lock',
      ],
    },
    {
      name: 'Meguru Bachira',
      aliases: ['Bachira'],
      emoji: '⚽👹🕺',
      group: 'Blue Lock',
      tags: ['homme', 'héros', 'humain', 'sport', 'drôle', 'lycéen', 'blue-lock'],
      clues: [
        'Excentrique et joyeux',
        'Parle d’un monstre qui vit en lui',
        'Dribbleur imprévisible',
        'Premier allié d’Isagi',
        'Joueur de Blue Lock',
      ],
    },
    {
      name: 'Rin Itoshi',
      aliases: ['Rin'],
      emoji: '⚽😒🏆',
      group: 'Blue Lock',
      tags: ['homme', 'anti-héros', 'humain', 'cheveux-noirs', 'sport', 'sérieux', 'rival', 'lycéen', 'blue-lock'],
      clues: [
        'Froid et méprisant',
        'Veut surpasser son grand frère',
        'Classé numéro un du programme',
        'Rival d’Isagi',
        'Attaquant de Blue Lock',
      ],
    },
    // ——— Haikyuu ———
    {
      name: 'Shoyo Hinata',
      aliases: ['Hinata', 'Shōyō Hinata'],
      emoji: '🏐🍊🦅',
      group: 'Haikyuu',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-roux', 'sport', 'drôle', 'lycéen', 'haikyuu'],
      clues: [
        'Petit mais saute très haut',
        'Toujours plein d’énergie',
        'Surnommé le petit géant',
        'Forme un duo « attaque rapide »',
        'Héros de Haikyuu',
      ],
    },
    {
      name: 'Tobio Kageyama',
      aliases: ['Kageyama'],
      emoji: '🏐👑🥛',
      group: 'Haikyuu',
      tags: ['homme', 'héros', 'humain', 'cheveux-noirs', 'sport', 'génie', 'sérieux', 'rival', 'lycéen', 'haikyuu'],
      clues: [
        'Boit toujours du lait',
        'Surnommé le roi du terrain',
        'Passeur de génie',
        'Partenaire colérique d’Hinata',
        'Joueur de Karasuno dans Haikyuu',
      ],
    },
    {
      name: 'Kei Tsukishima',
      aliases: ['Tsukishima', 'Tsukki'],
      emoji: '🏐🌙🦕',
      group: 'Haikyuu',
      tags: ['homme', 'héros', 'humain', 'cheveux-blonds', 'sport', 'lunettes', 'génie', 'lycéen', 'haikyuu'],
      clues: [
        'Grand, sarcastique et moqueur',
        'Passionné de dinosaures',
        'Contreur très stratège',
        'Porte des lunettes',
        'Joueur de Karasuno dans Haikyuu',
      ],
    },
    // ——— JoJo ———
    {
      name: 'Jotaro Kujo',
      aliases: ['Jotaro'],
      emoji: '🧢⭐👊',
      group: 'JoJo',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'combattant-mains-nues', 'sérieux', 'lycéen', 'jojo'],
      clues: [
        'Lycéen délinquant au long manteau',
        'Dit souvent « Yare yare daze »',
        'Son esprit combattant frappe à toute vitesse',
        'Stand Star Platinum',
        'Héros de la 3e partie de JoJo',
      ],
    },
    {
      name: 'Dio Brando',
      aliases: ['Dio', 'DIO'],
      emoji: '🧛⏱️🚧',
      group: 'JoJo',
      tags: ['homme', 'méchant', 'non-humain', 'démon', 'cheveux-blonds', 'leader', 'adulte', 'jojo'],
      clues: [
        'Ambitieux et sans scrupules',
        'Devenu vampire grâce à un masque',
        'Peut arrêter le temps',
        'Écrase ses ennemis avec un rouleau compresseur',
        'Ennemi juré des Joestar',
      ],
    },
    {
      name: 'Joseph Joestar',
      aliases: ['Joseph', 'JoJo'],
      emoji: '🥤🎩🧠',
      group: 'JoJo',
      tags: ['homme', 'héros', 'humain', 'cheveux-bruns', 'combattant-mains-nues', 'génie', 'drôle', 'jojo'],
      clues: [
        'Farceur roublard',
        'Devine ce que son ennemi va dire',
        'Maîtrise l’onde Hamon',
        'Grand-père de Jotaro',
        'Héros de la 2e partie de JoJo',
      ],
    },
    {
      name: 'Giorno Giovanna',
      aliases: ['Giorno'],
      emoji: '🐞🌱🎶',
      group: 'JoJo',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-blonds', 'leader', 'adolescent', 'jojo'],
      clues: [
        'Adolescent élégant et déterminé',
        'Coiffure à trois boucles',
        'Donne vie aux objets',
        'Rêve de devenir chef de gang',
        'Héros de la 5e partie de JoJo',
      ],
    },
    // ——— Frieren ———
    {
      name: 'Frieren',
      emoji: '🧝‍♀️📜🌸',
      group: 'Frieren',
      tags: ['femme', 'héros', 'non-humain', 'protagoniste', 'cheveux-blancs', 'sorcier', 'mentor', 'drôle', 'frieren'],
      clues: [
        'Vit depuis plus de mille ans',
        'Collectionne les sorts inutiles',
        'Membre d’un groupe qui a vaincu le roi démon',
        'Elfe magicienne',
        'Héroïne de son propre manga',
      ],
    },
    {
      name: 'Fern',
      emoji: '💜🪄😤',
      group: 'Frieren',
      tags: ['femme', 'héros', 'humain', 'cheveux-violets', 'sorcier', 'sérieux', 'adolescent', 'frieren'],
      clues: [
        'Jeune fille sérieuse qui boude souvent',
        'Tire des sorts à une vitesse folle',
        'Orpheline recueillie par un prêtre',
        'Apprentie d’une elfe',
        'Compagne de route de Frieren',
      ],
    },
    {
      name: 'Himmel',
      emoji: '🗡️🌌💐',
      group: 'Frieren',
      tags: ['homme', 'héros', 'humain', 'cheveux-bleus', 'épéiste', 'leader', 'drôle', 'frieren'],
      clues: [
        'Un héros un peu narcissique',
        'Fait ériger des statues de lui-même',
        'A vaincu le roi démon',
        'Mort de vieillesse au début de l’histoire',
        'Ancien compagnon de Frieren',
      ],
    },
    // ——— Dandadan ———
    {
      name: 'Momo Ayase',
      aliases: ['Momo'],
      emoji: '👻🤚💅',
      group: 'Dandadan',
      tags: ['femme', 'héros', 'humain', 'protagoniste', 'cheveux-bruns', 'sorcier', 'lycéen', 'drôle', 'dandadan'],
      clues: [
        'Lycéenne au fort caractère',
        'Croit aux fantômes mais pas aux aliens',
        'Petite-fille d’une médium',
        'Pouvoirs psychiques',
        'Héroïne de Dandadan',
      ],
    },
    {
      name: 'Okarun',
      aliases: ['Ken Takakura'],
      emoji: '👽👓🏃',
      group: 'Dandadan',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'lunettes', 'transformation', 'lycéen', 'dandadan'],
      clues: [
        'Lycéen timide fan d’OVNI',
        'Porte de grosses lunettes',
        'Maudit par un esprit',
        'Devient ultra rapide transformé',
        'Héros de Dandadan',
      ],
    },
    {
      name: 'Mamie Turbo',
      aliases: ['Turbo Granny', 'Turbo Mamie'],
      emoji: '👵💨🐈',
      group: 'Dandadan',
      tags: ['femme', 'méchant', 'non-humain', 'démon', 'drôle', 'adulte', 'dandadan'],
      clues: [
        'Une vieille dame terriblement rapide',
        'Légende urbaine japonaise',
        'Vole une partie intime du héros',
        'Finit coincée dans une peluche',
        'Esprit de Dandadan',
      ],
    },
    // ——— Sailor Moon ———
    {
      name: 'Usagi Tsukino',
      aliases: ['Sailor Moon', 'Bunny', 'Usagi'],
      emoji: '🌙🎀🍡',
      group: 'Sailor Moon',
      tags: ['femme', 'héros', 'humain', 'protagoniste', 'cheveux-blonds', 'sorcier', 'transformation', 'drôle', 'lycéen', 'sailor-moon'],
      clues: [
        'Pleurnicheuse et gourmande',
        'Coiffure à deux chignons',
        'Guidée par un chat noir',
        'Combat au nom de la Lune',
        'Héroïne de Sailor Moon',
      ],
    },
    {
      name: 'Rei Hino',
      aliases: ['Sailor Mars', 'Raya'],
      emoji: '⛩️🔥🐦‍⬛',
      group: 'Sailor Moon',
      tags: ['femme', 'héros', 'humain', 'cheveux-noirs', 'sorcier', 'feu', 'transformation', 'lycéen', 'sailor-moon'],
      clues: [
        'Prêtresse dans un temple shinto',
        'Se chamaille avec l’héroïne',
        'Possède deux corbeaux',
        'Guerrière de la planète rouge',
        'Personnage de Sailor Moon',
      ],
    },
    {
      name: 'Ami Mizuno',
      aliases: ['Sailor Mercury', 'Molly'],
      emoji: '💧📚💻',
      group: 'Sailor Moon',
      tags: ['femme', 'héros', 'humain', 'cheveux-bleus', 'sorcier', 'eau', 'glace', 'génie', 'transformation', 'lycéen', 'sailor-moon'],
      clues: [
        'Élève la plus brillante de l’école',
        'Timide et studieuse',
        'Analyse les ennemis avec un mini-ordinateur',
        'Guerrière de l’eau',
        'Personnage de Sailor Moon',
      ],
    },
    // ——— Pokémon ———
    {
      name: 'Sacha',
      aliases: ['Ash', 'Sacha Ketchum', 'Ash Ketchum'],
      emoji: '🧢🔴⚪',
      group: 'Pokémon',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-noirs', 'enfant', 'drôle', 'pokemon'],
      clues: [
        'Garçon de 10 ans éternellement',
        'Quitte le Bourg Palette',
        'Porte une casquette',
        'Veut devenir un grand Maître',
        'Dresseur héros de l’anime Pokémon',
      ],
    },
    {
      name: 'Pikachu',
      aliases: ['Pika'],
      emoji: '⚡🐭💛',
      group: 'Pokémon',
      tags: ['non-humain', 'animal', 'héros', 'foudre', 'drôle', 'pokemon', 'homme'],
      clues: [
        'Petite créature aux joues rouges',
        'Refuse d’entrer dans sa boule',
        'Suit son dresseur partout',
        'Type électrique',
        'Mascotte de Pokémon',
      ],
    },
    {
      name: 'Ondine',
      aliases: ['Misty'],
      emoji: '💧🚲⭐',
      group: 'Pokémon',
      tags: ['femme', 'héros', 'humain', 'cheveux-roux', 'eau', 'leader', 'enfant', 'pokemon'],
      clues: [
        'Réclame qu’on lui rembourse son vélo',
        'Déteste les insectes',
        'Spécialiste du type eau',
        'Championne d’arène d’Azuria',
        'Amie de Sacha dans Pokémon',
      ],
    },
    {
      name: 'Pierre',
      aliases: ['Brock'],
      emoji: '🪨🍳😍',
      group: 'Pokémon',
      tags: ['homme', 'héros', 'humain', 'cheveux-bruns', 'drôle', 'leader', 'mentor', 'pokemon'],
      clues: [
        'Tombe amoureux de chaque fille',
        'Yeux toujours plissés',
        'Excellent cuisinier',
        'Champion d’arène d’Argenta',
        'Ami de Sacha dans Pokémon',
      ],
    },
    {
      name: 'Miaouss',
      aliases: ['Meowth'],
      emoji: '🐱🪙🚀',
      group: 'Pokémon',
      tags: ['homme', 'méchant', 'non-humain', 'animal', 'drôle', 'pokemon', 'adulte'],
      clues: [
        'Une créature qui parle comme un humain',
        'Pièce dorée sur le front',
        'Membre d’un trio de bras cassés',
        'Chat de la Team Rocket',
        'Personnage de Pokémon',
      ],
    },
    // ——— Kuroko's Basket ———
    {
      name: 'Tetsuya Kuroko',
      aliases: ['Kuroko'],
      emoji: '🏀👻🥤',
      group: 'Kuroko’s Basket',
      tags: ['homme', 'héros', 'humain', 'protagoniste', 'cheveux-bleus', 'sport', 'sérieux', 'lycéen', 'kuroko'],
      clues: [
        'Passe totalement inaperçu',
        'Adore les milkshakes à la vanille',
        'Spécialiste des passes invisibles',
        'Sixième joueur fantôme',
        'Héros de Kuroko’s Basket',
      ],
    },
    {
      name: 'Taiga Kagami',
      aliases: ['Kagami'],
      emoji: '🏀🐯🍔',
      group: 'Kuroko’s Basket',
      tags: ['homme', 'héros', 'humain', 'cheveux-roux', 'sport', 'drôle', 'lycéen', 'kuroko'],
      clues: [
        'A grandi aux États-Unis',
        'Mange des montagnes de burgers',
        'Saute incroyablement haut',
        'Sourcils fendus en deux',
        'Partenaire de Kuroko',
      ],
    },
    {
      name: 'Seijūrō Akashi',
      aliases: ['Akashi', 'Seijuro Akashi'],
      emoji: '🏀✂️👑',
      group: 'Kuroko’s Basket',
      tags: ['homme', 'anti-héros', 'humain', 'cheveux-roux', 'sport', 'pouvoir-oculaire', 'génie', 'leader', 'lycéen', 'kuroko'],
      clues: [
        'Ne perd jamais',
        'Menace les gens avec des ciseaux',
        'Son œil voit l’avenir des mouvements',
        'Capitaine de la Génération des miracles',
        'Personnage de Kuroko’s Basket',
      ],
    },
    // ——— Code Geass ———
    {
      name: 'Lelouch Lamperouge',
      aliases: ['Lelouch', 'Zero', 'Lelouch vi Britannia'],
      emoji: '♟️👁️🎭',
      group: 'Code Geass',
      tags: ['homme', 'anti-héros', 'humain', 'protagoniste', 'cheveux-noirs', 'pouvoir-oculaire', 'génie', 'noble', 'leader', 'lycéen', 'code-geass'],
      clues: [
        'Lycéen champion d’échecs',
        'Prince exilé',
        'Peut imposer un ordre d’un regard',
        'Se cache sous un masque noir',
        'Héros de Code Geass',
      ],
    },
    {
      name: 'Suzaku Kururugi',
      aliases: ['Suzaku'],
      emoji: '🤖🗡️🇯🇵',
      group: 'Code Geass',
      tags: ['homme', 'héros', 'humain', 'cheveux-bruns', 'militaire', 'rival', 'sérieux', 'code-geass'],
      clues: [
        'Fils du dernier Premier ministre japonais',
        'Idéaliste qui veut changer le système',
        'Pilote d’élite du Lancelot',
        'Ami d’enfance devenu ennemi',
        'Rival de Lelouch',
      ],
    },
    {
      name: 'C.C.',
      aliases: ['CC', 'C2'],
      emoji: '🍕🧸💚',
      group: 'Code Geass',
      tags: ['femme', 'anti-héros', 'non-humain', 'cheveux-verts', 'drôle', 'code-geass', 'adulte', 'sorcier'],
      clues: [
        'Mystérieuse et immortelle',
        'Obsédée par la pizza',
        'Serre toujours une peluche',
        'A donné son pouvoir au héros',
        'Complice de Lelouch',
      ],
    },
    // ——— Vinland Saga ———
    {
      name: 'Thorfinn',
      aliases: ['Thorfinn Karlsefni'],
      emoji: '🗡️🌊🌾',
      group: 'Vinland Saga',
      tags: ['homme', 'anti-héros', 'humain', 'protagoniste', 'cheveux-blonds', 'assassin', 'sérieux', 'vinland-saga'],
      clues: [
        'Enfant guerrier rongé par la haine',
        'Se bat avec deux poignards',
        'Devient esclave dans une ferme',
        'Cherche une terre promise sans guerre',
        'Héros de Vinland Saga',
      ],
    },
    {
      name: 'Askeladd',
      aliases: ['Lucius Artorius Castus'],
      emoji: '🪓🏴🧔',
      group: 'Vinland Saga',
      tags: ['homme', 'anti-héros', 'méchant', 'humain', 'cheveux-blonds', 'épéiste', 'génie', 'leader', 'adulte', 'vinland-saga'],
      clues: [
        'Chef de mercenaires rusé',
        'A tué le père du héros',
        'Descendant caché d’Arthur',
        'Mentor malgré lui de son ennemi',
        'Viking de Vinland Saga',
      ],
    },
    {
      name: 'Canute',
      aliases: ['Knut', 'Cnut'],
      emoji: '👑🙏⚔️',
      group: 'Vinland Saga',
      tags: ['homme', 'anti-héros', 'humain', 'cheveux-blonds', 'noble', 'leader', 'sérieux', 'vinland-saga'],
      clues: [
        'Prince timide au départ',
        'Transformé par un deuil',
        'Veut bâtir un paradis sur terre',
        'Futur roi d’Angleterre et du Danemark',
        'Personnage de Vinland Saga',
      ],
    },
  ],
};
