import type { Pack } from '../types';

export const pack: Pack = {
  id: 'celebrites',
  name: 'Célébrités',
  emoji: '🌟',
  category: 'celebrites',
  description: 'Acteurs, youtubeurs, animateurs et entrepreneurs que tout le monde connaît.',
  attributes: [
    { tag: 'femme', question: 'Est-ce une femme ?' },
    { tag: 'français', question: 'Est-il/elle français(e) ?' },
    { tag: 'américain', question: 'Est-il/elle américain(e) ?' },
    { tag: 'britannique', question: 'Est-il/elle britannique ?' },
    { tag: 'europe', question: 'Vient-il/elle d’Europe ?' },
    { tag: 'amérique-du-nord', question: 'Vient-il/elle d’Amérique du Nord ?' },
    { tag: 'cinéma', question: 'Est-il/elle connu(e) pour le cinéma ?' },
    { tag: 'internet', question: 'Est-il/elle célèbre grâce à Internet ?' },
    { tag: 'télé', question: 'Est-il/elle connu(e) pour la télévision ?' },
    { tag: 'business', question: 'Est-ce un chef d’entreprise ?' },
    { tag: 'acteur', question: 'Est-ce un(e) acteur/actrice ?' },
    { tag: 'humoriste', question: 'Est-ce un(e) humoriste ?' },
    { tag: 'youtubeur', question: 'Est-ce un(e) youtubeur/youtubeuse ?' },
    { tag: 'streamer', question: 'Fait-il des lives sur Twitch ?' },
    { tag: 'gaming', question: 'Est-il lié aux jeux vidéo ?' },
    { tag: 'animateur', question: 'Présente-t-il/elle une émission ?' },
    { tag: 'chef-cuisinier', question: 'Est-ce un chef cuisinier ?' },
    { tag: 'tech', question: 'Travaille-t-il dans la tech ?' },
    { tag: 'milliardaire', question: 'Est-il/elle milliardaire ?' },
    { tag: 'réalisateur', question: 'Réalise-t-il des films ?' },
    { tag: 'comédie', question: 'Est-il/elle connu(e) pour des comédies ?' },
    { tag: 'action', question: 'Joue-t-il/elle dans des films d’action ?' },
    { tag: 'hollywood', question: 'A-t-il/elle fait carrière à Hollywood ?' },
    { tag: 'marvel', question: 'A-t-il/elle joué dans un film Marvel ?' },
    { tag: 'harry-potter', question: 'A-t-il/elle joué dans Harry Potter ?' },
    { tag: 'oscar', question: 'A-t-il/elle gagné un Oscar ?' },
    { tag: 'césar', question: 'A-t-il/elle gagné un César ?' },
    { tag: 'décédé', question: 'Est-il/elle décédé(e) ?' },
    { tag: 'jeune-génération', question: 'Est-il/elle né(e) après 1995 ?' },
  ],
  items: [
    // ── Cinéma français ──
    {
      name: 'Omar Sy',
      aliases: ['Omar'],
      emoji: '😁🎬🎩',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'humoriste', 'comédie', 'césar', 'hollywood', 'vivant'],
      clues: ['Acteur français au sourire éclatant', 'Duo comique avec Fred Testot à la télé', 'César du meilleur acteur pour « Intouchables »', 'Gentleman cambrioleur dans une série Netflix', 'Joue Assane Diop dans « Lupin »', 'Omar, ex-moitié du duo Omar et Fred'],
    },
    {
      name: 'Jean Dujardin',
      aliases: ['Dujardin', 'Jeannot'],
      emoji: '🕵️‍♂️🏄‍♂️🏆',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'humoriste', 'comédie', 'oscar', 'télé', 'vivant'],
      clues: ['Acteur français charmeur', 'Révélé par la série « Un gars, une fille »', 'Surfeur sans vagues dans une comédie culte', 'Joue l’agent secret OSS 117', 'Oscar du meilleur acteur pour « The Artist »', 'Jean, alias Brice de Nice'],
    },
    {
      name: 'Marion Cotillard',
      aliases: ['Cotillard', 'Marion'],
      emoji: '🎤🌹🏆',
      group: 'Cinéma',
      tags: ['femme', 'français', 'europe', 'cinéma', 'acteur', 'oscar', 'césar', 'hollywood', 'vivant'],
      clues: ['Actrice française à la carrière internationale', 'Révélée dans la saga « Taxi »', 'Incarne Édith Piaf dans « La Môme »', 'Oscar de la meilleure actrice en 2008', 'Joue dans « Inception »', 'Marion, égérie Dior'],
    },
    {
      name: 'Louis de Funès',
      aliases: ['De Funès', 'de Funes', 'Fufu'],
      emoji: '😠👮‍♂️🎭',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'comédie', 'décédé', 'légende'],
      clues: ['Acteur comique aux grimaces célèbres', 'Gendarme de Saint-Tropez', 'Duo avec Bourvil dans « La Grande Vadrouille »', 'Joue Rabbi Jacob', 'Mort en 1983', 'Louis, roi de la comédie française'],
    },
    {
      name: 'Jean Reno',
      aliases: ['Reno'],
      emoji: '🔫🪴🛡️',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'action', 'comédie', 'hollywood', 'vivant'],
      clues: ['Acteur français à la voix grave', 'Né à Casablanca', 'Tueur à gages avec une plante verte', 'Chevalier Godefroy dans « Les Visiteurs »', 'A joué dans « Mission impossible »', 'Jean, héros de « Léon »'],
    },
    {
      name: 'Audrey Tautou',
      aliases: ['Tautou', 'Audrey'],
      emoji: '🍓🥄🎠',
      group: 'Cinéma',
      tags: ['femme', 'français', 'europe', 'cinéma', 'acteur', 'comédie', 'césar', 'vivant'],
      clues: ['Actrice française aux grands yeux', 'Serveuse rêveuse à Montmartre', 'Aime briser la croûte des crèmes brûlées', 'Héroïne du « Fabuleux Destin d’Amélie Poulain »', 'Incarne Coco Chanel', 'Audrey, aussi dans « Da Vinci Code »'],
    },
    {
      name: 'Kev Adams',
      aliases: ['Kev', 'Kevin Adams'],
      emoji: '😜🎤🧞',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'humoriste', 'comédie', 'télé', 'vivant'],
      clues: ['Humoriste et acteur français', 'Très populaire auprès des ados', 'Révélé par la série « Soda »', 'Joue dans « Les Profs »', 'Incarne un Aladin moderne', 'Kev, star des comédies familiales'],
    },
    {
      name: 'Dany Boon',
      aliases: ['Boon', 'Dany'],
      emoji: '🍟🏠🗣️',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'humoriste', 'comédie', 'réalisateur', 'vivant'],
      clues: ['Humoriste et réalisateur du Nord', 'Parle volontiers le ch’ti', 'Film record au box-office français en 2008', 'Réalise « Bienvenue chez les Ch’tis »', 'Joue dans « Rien à déclarer »', 'Dany, né à Armentières'],
    },
    {
      name: 'Christian Clavier',
      aliases: ['Clavier'],
      emoji: '🏰🤪🥖',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'comédie', 'vivant', 'splendid'],
      clues: ['Membre de la troupe du Splendid', 'Joue dans « Les Bronzés »', 'Écuyer Jacquouille dans « Les Visiteurs »', 'A incarné Astérix au cinéma', 'Joue dans « Qu’est-ce qu’on a fait au Bon Dieu ? »', 'Christian, « Okaaaay ! »'],
    },
    {
      name: 'Léa Seydoux',
      aliases: ['Seydoux', 'Léa'],
      emoji: '🎬🍸🏜️',
      group: 'Cinéma',
      tags: ['femme', 'français', 'europe', 'cinéma', 'acteur', 'action', 'hollywood', 'césar', 'vivant'],
      clues: ['Actrice française au rayonnement mondial', 'Palme d’or pour « La Vie d’Adèle »', 'James Bond girl dans deux films', 'Joue dans la saga « Dune »', 'Madeleine Swann face à 007', 'Léa, héritière d’une famille du cinéma'],
    },
    {
      name: 'Jamel Debbouze',
      aliases: ['Jamel', 'Debbouze'],
      emoji: '😂🎤🏛️',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'humoriste', 'comédie', 'télé', 'vivant'],
      clues: ['Humoriste français au débit rapide', 'A grandi à Trappes', 'Fondateur d’un célèbre Comedy Club', 'Numérobis dans « Mission Cléopâtre »', 'Rôle dans « Amélie Poulain »', 'Jamel, star du stand-up'],
    },
    {
      name: 'Sophie Marceau',
      aliases: ['Marceau', 'Sophie'],
      emoji: '💃🎬🌹',
      group: 'Cinéma',
      tags: ['femme', 'français', 'europe', 'cinéma', 'acteur', 'césar', 'hollywood', 'vivant'],
      clues: ['Actrice française révélée adolescente', 'Première boum culte au cinéma', 'Princesse dans « Braveheart »', 'James Bond girl en 1999', 'César du meilleur espoir féminin', 'Sophie, héroïne de « La Boum »'],
    },
    {
      name: 'Jean-Paul Belmondo',
      aliases: ['Belmondo', 'Bébel'],
      emoji: '🤸‍♂️🔫🎬',
      group: 'Cinéma',
      tags: ['homme', 'français', 'europe', 'cinéma', 'acteur', 'action', 'décédé', 'légende'],
      clues: ['Acteur star de la Nouvelle Vague', 'Joue dans « À bout de souffle »', 'Faisait ses cascades lui-même', 'Joue dans « Le Magnifique »', 'Mort en 2021', 'Surnommé Bébel'],
    },
    // ── Cinéma international ──
    {
      name: 'Zendaya',
      aliases: ['Zendaya Coleman'],
      emoji: '🕷️💜🏜️',
      group: 'Cinéma',
      tags: ['femme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'marvel', 'jeune-génération', 'télé', 'vivant'],
      clues: ['Actrice américaine née en Californie', 'Débute sur Disney Channel', 'Joue MJ dans Spider-Man', 'Incarne Rue dans « Euphoria »', 'Joue Chani dans « Dune »', 'Un seul prénom suffit : Zendaya'],
    },
    {
      name: 'Dwayne Johnson',
      aliases: ['The Rock', 'Dwayne', 'Rock'],
      emoji: '💪🤨🌋',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'comédie', 'hollywood', 'vivant'],
      clues: ['Acteur américain très musclé', 'Ancien catcheur superstar', 'Sourcil levé légendaire', 'Voix de Maui dans « Vaiana »', 'Joue dans « Fast & Furious » et « Jumanji »', 'Surnommé The Rock'],
    },
    {
      name: 'Tom Holland',
      aliases: ['Holland'],
      emoji: '🕷️🇬🇧🕸️',
      group: 'Cinéma',
      tags: ['homme', 'britannique', 'europe', 'cinéma', 'acteur', 'action', 'hollywood', 'marvel', 'jeune-génération', 'vivant'],
      clues: ['Acteur britannique très souple', 'A débuté dans la comédie musicale « Billy Elliot »', 'Super-héros adolescent du MCU', 'Joue Peter Parker', 'Joue Nathan Drake dans « Uncharted »', 'Tom, Spider-Man depuis 2016'],
    },
    {
      name: 'Leonardo DiCaprio',
      aliases: ['DiCaprio', 'Leo', 'Léo'],
      emoji: '🚢❄️🐻',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'oscar', 'vivant'],
      clues: ['Acteur américain star depuis les années 1990', 'Roi du monde à la proue d’un paquebot', 'Joue Jack dans « Titanic »', 'Oscar pour « The Revenant », enfin', 'Joue dans « Le Loup de Wall Street »', 'Leo, engagé pour l’environnement'],
    },
    {
      name: 'Tom Cruise',
      aliases: ['Cruise'],
      emoji: '✈️🕶️🏃‍♂️',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'hollywood', 'vivant'],
      clues: ['Acteur américain qui fait ses cascades', 'Pilote de chasse dans « Top Gun »', 'Accroché à un avion qui décolle', 'Agent Ethan Hunt', 'Saga « Mission impossible »', 'Tom, toujours en train de courir'],
    },
    {
      name: 'Margot Robbie',
      aliases: ['Robbie', 'Margot'],
      emoji: '💖👠🃏',
      group: 'Cinéma',
      tags: ['femme', 'australien', 'océanie', 'cinéma', 'acteur', 'hollywood', 'comédie', 'vivant'],
      clues: ['Actrice australienne', 'Révélée dans « Le Loup de Wall Street »', 'Incarne Harley Quinn', 'Poupée iconique en rose en 2023', 'Rôle-titre de « Barbie »', 'Margot, aussi productrice'],
    },
    {
      name: 'Scarlett Johansson',
      aliases: ['Johansson', 'Scarlett', 'ScarJo'],
      emoji: '🕷️🖤🎙️',
      group: 'Cinéma',
      tags: ['femme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'hollywood', 'marvel', 'vivant'],
      clues: ['Actrice américaine née à New York', 'Joue dans « Lost in Translation »', 'Voix d’une IA dans « Her »', 'Espionne russe chez les Avengers', 'Incarne Black Widow', 'Surnommée ScarJo'],
    },
    {
      name: 'Keanu Reeves',
      aliases: ['Keanu', 'Reeves'],
      emoji: '💊🕶️🐶',
      group: 'Cinéma',
      tags: ['homme', 'canadien', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'hollywood', 'vivant'],
      clues: ['Acteur canadien né au Liban', 'Réputé pour sa grande gentillesse', 'Choisit la pilule rouge', 'Joue Neo dans « Matrix »', 'Tueur vengeant son chien dans « John Wick »', 'Keanu, l’Internet l’adore'],
    },
    {
      name: 'Timothée Chalamet',
      aliases: ['Chalamet', 'Timothée', 'Timmy'],
      emoji: '🏜️🍫🎸',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'français', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'jeune-génération', 'vivant'],
      clues: ['Acteur franco-américain né à New York', 'Révélé par « Call Me by Your Name »', 'Joue Paul Atréides dans « Dune »', 'Chocolatier fantasque en 2023', 'Incarne Bob Dylan', 'Timothée, alias Willy Wonka'],
    },
    {
      name: 'Jackie Chan',
      aliases: ['Jackie'],
      emoji: '🥋🤸‍♂️🇭🇰',
      group: 'Cinéma',
      tags: ['homme', 'chinois', 'asie', 'cinéma', 'acteur', 'action', 'comédie', 'hollywood', 'vivant'],
      clues: ['Acteur hongkongais d’arts martiaux', 'Fait ses propres cascades', 'Bêtisiers célèbres en fin de film', 'Duo avec Chris Tucker dans « Rush Hour »', 'Mêle kung-fu et humour', 'Jackie, maître des cascades'],
    },
    {
      name: 'Emma Watson',
      aliases: ['Watson', 'Emma'],
      emoji: '📚🪄🌹',
      group: 'Cinéma',
      tags: ['femme', 'britannique', 'europe', 'cinéma', 'acteur', 'hollywood', 'harry-potter', 'vivant'],
      clues: ['Actrice britannique née à Paris', 'Élève brillante d’une école de sorcellerie', 'Joue Hermione Granger', 'Belle dans « La Belle et la Bête » en 2017', 'Ambassadrice d’ONU Femmes', 'Emma, amie de Harry et Ron'],
    },
    {
      name: 'Daniel Radcliffe',
      aliases: ['Radcliffe', 'Daniel'],
      emoji: '⚡👓🪄',
      group: 'Cinéma',
      tags: ['homme', 'britannique', 'europe', 'cinéma', 'acteur', 'hollywood', 'harry-potter', 'vivant'],
      clues: ['Acteur britannique révélé enfant', 'Cicatrice en forme d’éclair', 'Sorcier à lunettes pendant dix ans', 'Huit films d’une saga culte', 'Cadavre farceur dans « Swiss Army Man »', 'Daniel, l’interprète de Harry Potter'],
    },
    {
      name: 'Rupert Grint',
      aliases: ['Grint', 'Rupert'],
      emoji: '🧡🪄🕷️',
      group: 'Cinéma',
      tags: ['homme', 'britannique', 'europe', 'cinéma', 'acteur', 'comédie', 'harry-potter', 'vivant'],
      clues: ['Acteur britannique roux', 'Révélé enfant dans une saga magique', 'Meilleur ami du héros à lunettes', 'Terrifié par les araignées à l’écran', 'Joue dans la série « Servant »', 'Rupert, alias Ron Weasley'],
    },
    {
      name: 'Ryan Reynolds',
      aliases: ['Reynolds', 'Ryan'],
      emoji: '🗡️❤️😏',
      group: 'Cinéma',
      tags: ['homme', 'canadien', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'comédie', 'hollywood', 'marvel', 'vivant'],
      clues: ['Acteur canadien plein d’autodérision', 'Antihéros en costume rouge', 'Joue Deadpool', 'Copropriétaire du club de foot de Wrexham', 'Personnage de jeu vidéo dans « Free Guy »', 'Ryan, roi des répliques'],
    },
    {
      name: 'Morgan Freeman',
      aliases: ['Freeman', 'Morgan'],
      emoji: '🎙️👴🏆',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'oscar', 'vivant'],
      clues: ['Acteur américain à la voix mythique', 'Narrateur de nombreux documentaires', 'A joué Dieu au cinéma', 'Joue dans « Les Évadés »', 'Oscar pour « Million Dollar Baby »', 'Morgan, Mandela dans « Invictus »'],
    },
    {
      name: 'Meryl Streep',
      aliases: ['Streep', 'Meryl'],
      emoji: '👠🏆🎭',
      group: 'Cinéma',
      tags: ['femme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'oscar', 'comédie', 'vivant'],
      clues: ['Actrice américaine ultra-récompensée', 'Record de nominations aux Oscars', 'Trois Oscars remportés', 'Rédactrice en chef dans « Le Diable s’habille en Prada »', 'Chante ABBA dans « Mamma Mia! »', 'Meryl, reine des accents'],
    },
    {
      name: 'Charlie Chaplin',
      aliases: ['Chaplin', 'Charlot'],
      emoji: '🎩🦯🎞️',
      group: 'Cinéma',
      tags: ['homme', 'britannique', 'europe', 'cinéma', 'acteur', 'comédie', 'réalisateur', 'décédé', 'légende', 'oscar'],
      clues: ['Star du cinéma muet', 'Chapeau melon, canne et petite moustache', 'Réalise « Les Temps modernes »', 'Parodie un dictateur en 1940', 'Personnage du vagabond Charlot', 'Charlie, génie du burlesque'],
    },
    {
      name: 'Marilyn Monroe',
      aliases: ['Marilyn', 'Monroe'],
      emoji: '💋👱‍♀️🤍',
      group: 'Cinéma',
      tags: ['femme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'hollywood', 'comédie', 'décédé', 'légende'],
      clues: ['Icône blonde des années 1950', 'Robe blanche soulevée par une bouche d’aération', 'Joue dans « Certains l’aiment chaud »', 'A chanté « Happy Birthday, Mr. President »', 'Née Norma Jeane', 'Marilyn, sex-symbol d’Hollywood'],
    },
    {
      name: 'Jason Statham',
      aliases: ['Statham', 'Jason'],
      emoji: '🚗💥👨‍🦲',
      group: 'Cinéma',
      tags: ['homme', 'britannique', 'europe', 'cinéma', 'acteur', 'action', 'hollywood', 'vivant'],
      clues: ['Acteur britannique au crâne rasé', 'Ancien plongeur de haut niveau', 'Chauffeur professionnel dans une saga', 'Joue dans « Le Transporteur »', 'Rejoint « Fast & Furious »', 'Jason, roi des films d’action'],
    },
    {
      name: 'Robert Downey Jr',
      aliases: ['Robert Downey Jr.', 'RDJ', 'Downey'],
      emoji: '🦾❤️🔴',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'hollywood', 'marvel', 'oscar', 'vivant'],
      clues: ['Acteur américain charismatique', 'Milliardaire en armure', 'Premier héros du MCU en 2008', 'Joue aussi Sherlock Holmes', 'Oscar pour « Oppenheimer »', 'RDJ, alias Iron Man'],
    },
    {
      name: 'Pedro Pascal',
      aliases: ['Pascal', 'Pedro'],
      emoji: '🪖🍄👶',
      group: 'Cinéma',
      tags: ['homme', 'américain', 'chilien', 'amérique-du-nord', 'cinéma', 'acteur', 'action', 'hollywood', 'marvel', 'télé', 'vivant'],
      clues: ['Acteur né au Chili', 'Joue dans « Game of Thrones »', 'Agent de la DEA dans « Narcos »', 'Chasseur de primes casqué dans « The Mandalorian »', 'Joue Joel dans « The Last of Us »', 'Pedro, l’Internet l’appelle « papa »'],
    },
    // ── Internet ──
    {
      name: 'Squeezie',
      aliases: ['Lucas Hauchard', 'Squeez'],
      emoji: '🎮🏎️🎤',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'streamer', 'gaming', 'jeune-génération', 'vivant'],
      clues: ['Youtubeur français parmi les plus suivis', 'A commencé par des vidéos de jeux vidéo', 'Organise une course de voitures entre créateurs', 'Fondateur du GP Explorer', 'A sorti l’album « Oxyz »', 'De son vrai nom Lucas Hauchard'],
    },
    {
      name: 'Cyprien',
      aliases: ['Cyprien Iov'],
      emoji: '🎥😂📚',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'humoriste', 'gaming', 'vivant'],
      clues: ['Pionnier du YouTube humoristique français', 'Vidéos sur la vie quotidienne', 'Coauteur de la BD « Roger et ses humains »', 'Parmi les premiers à 10 millions d’abonnés en France', 'Vidéos gaming sur une seconde chaîne', 'De son nom complet Cyprien Iov'],
    },
    {
      name: 'MrBeast',
      aliases: ['Mr Beast', 'Jimmy Donaldson', 'Mr. Beast'],
      emoji: '💸🐯🍫',
      group: 'Internet',
      tags: ['homme', 'américain', 'amérique-du-nord', 'internet', 'youtubeur', 'business', 'milliardaire', 'vivant'],
      clues: ['Youtubeur américain le plus suivi au monde', 'Défis avec des gains énormes', 'A recréé « Squid Game » en vrai', 'Lance les chocolats Feastables', 'Émission « Beast Games » sur Amazon', 'De son vrai nom Jimmy Donaldson'],
    },
    {
      name: 'Inoxtag',
      aliases: ['Inox', 'Inès Benazzouz'],
      emoji: '🏔️🎮🎬',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'streamer', 'gaming', 'jeune-génération', 'vivant'],
      clues: ['Youtubeur français né en 2002', 'Débute avec des vidéos de jeux vidéo', 'Préparation d’un an pour un défi fou', 'A gravi l’Everest', 'Documentaire « Kaizen » au cinéma', 'Inox, meilleur ami de Michou'],
    },
    {
      name: 'Michou',
      aliases: ['Michel'],
      emoji: '😆💙🕺',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'gaming', 'jeune-génération', 'télé', 'vivant'],
      clues: ['Youtubeur français originaire du Nord', 'Vidéos de défis et d’horreur', 'Inséparable d’Inoxtag', 'Finaliste de « Danse avec les stars »', 'Cheveux souvent teints', 'Michou, star des ados'],
    },
    {
      name: 'Tibo InShape',
      aliases: ['Tibo', 'TiboInShape', 'Thibaud Delapart'],
      emoji: '💪🏋️‍♂️🍗',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'sport', 'vivant', 'fitness'],
      clues: ['Youtubeur français de fitness', 'Muscles et défis sportifs', 'Originaire de Toulouse', 'Des millions d’abonnés sur YouTube', 'Vidéos d’immersion avec militaires et pompiers', 'Tibo, « InShape »'],
    },
    {
      name: 'Amixem',
      aliases: ['Maxime Chanet'],
      emoji: '📦🎮😄',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'gaming', 'humoriste', 'vivant'],
      clues: ['Youtubeur français de la première génération', 'Teste des objets et concepts insolites', 'Longtemps spécialiste des jeux vidéo', 'Participe au GP Explorer', 'De son vrai prénom Maxime', 'Amixem, ami de Squeezie'],
    },
    {
      name: 'McFly et Carlito',
      aliases: ['McFly & Carlito', 'Mcfly et Carlito', 'McFly', 'Carlito'],
      emoji: '👬🎤🏛️',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'humoriste', 'duo', 'vivant'],
      clues: ['Duo de youtubeurs français', 'Célèbres pour leurs concours d’anecdotes', 'Ont tourné une vidéo avec le président', 'Sortent aussi des chansons parodiques', 'Leur chaîne mêle défis et humour', 'Un duo : l’un s’appelle Carlito'],
    },
    {
      name: 'Léna Situations',
      aliases: ['Léna', 'Léna Mahfouf', 'Lena Situations'],
      emoji: '📹👗🌞',
      group: 'Internet',
      tags: ['femme', 'français', 'europe', 'internet', 'youtubeur', 'jeune-génération', 'business', 'vivant'],
      clues: ['Influenceuse française lifestyle', 'Vlogs quotidiens tout le mois d’août', 'A écrit le livre « Toujours plus »', 'Habituée des Fashion Weeks', 'A créé sa propre marque de vêtements', 'De son vrai nom Léna Mahfouf'],
    },
    {
      name: 'Kameto',
      aliases: ['Kamel Kebir'],
      emoji: '🎮💙🏆',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'streamer', 'gaming', 'business', 'vivant'],
      clues: ['Streamer français sur Twitch', 'Commentateur passionné d’esport', 'Cofondateur d’un club esport à succès', 'Supporters en bleu très bruyants', 'Fondateur de la Karmine Corp', 'De son vrai nom Kamel Kebir'],
    },
    {
      name: 'Gotaga',
      aliases: ['Corentin Houssein', 'Gota'],
      emoji: '🎮🔫🐐',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'streamer', 'gaming', 'youtubeur', 'vivant'],
      clues: ['Streamer français star des jeux de tir', 'Ancien champion de Call of Duty', 'Parmi les plus suivis sur Twitch en France', 'Joue à Fortnite et Warzone en live', 'Organise de grands événements en direct', 'De son vrai nom Corentin Houssein'],
    },
    {
      name: 'PewDiePie',
      aliases: ['Pewdiepie', 'Felix Kjellberg', 'Pewds'],
      emoji: '🇸🇪🎮👊',
      group: 'Internet',
      tags: ['homme', 'suédois', 'europe', 'internet', 'youtubeur', 'gaming', 'vivant', 'humoriste'],
      clues: ['Youtubeur suédois', 'Longtemps le plus abonné au monde', 'Célèbre pour ses vidéos de jeux d’horreur', 'Duel d’abonnés contre T-Series', 'A déménagé au Japon', 'De son vrai nom Felix Kjellberg'],
    },
    {
      name: 'Khaby Lame',
      aliases: ['Khaby', 'Khabane Lame'],
      emoji: '🤷‍♂️🙌📱',
      group: 'Internet',
      tags: ['homme', 'sénégalais', 'italien', 'afrique', 'europe', 'internet', 'humoriste', 'jeune-génération', 'vivant'],
      clues: ['Star de TikTok née au Sénégal', 'Vit en Italie', 'Ne parle jamais dans ses vidéos', 'Moque les astuces trop compliquées', 'Geste des mains devenu mème', 'Khaby, un temps n°1 de TikTok'],
    },
    {
      name: 'Natoo',
      aliases: ['Nathalie Odzierejko'],
      emoji: '😂🎭📕',
      group: 'Internet',
      tags: ['femme', 'français', 'europe', 'internet', 'youtubeur', 'humoriste', 'acteur', 'vivant'],
      clues: ['Youtubeuse humoristique française', 'Sketchs et parodies sur YouTube', 'Pionnière des créatrices comiques', 'A publié le livre « Icônne »', 'A aussi joué au cinéma', 'De son vrai nom Nathalie Odzierejko'],
    },
    {
      name: 'Mister V',
      aliases: ['MisterV', 'Yvick Letexier'],
      emoji: '🍕🎤😎',
      group: 'Internet',
      tags: ['homme', 'français', 'europe', 'internet', 'youtubeur', 'humoriste', 'business', 'acteur', 'vivant'],
      clues: ['Youtubeur, humoriste et rappeur', 'Originaire de Grenoble', 'Sketchs devenus cultes chez les ados', 'A lancé les pizzas Delamama', 'Spectacle et films à son actif', 'De son vrai nom Yvick Letexier'],
    },
    // ── Télé ──
    {
      name: 'Nagui',
      aliases: ['Nagui Fam'],
      emoji: '🎤📺🎶',
      group: 'Télé',
      tags: ['homme', 'français', 'europe', 'télé', 'animateur', 'vivant', 'musique', 'jeu-télé'],
      clues: ['Animateur télé français né en Égypte', 'Présente une émission musicale culte', 'Anime « Taratata »', 'Présente « N’oubliez pas les paroles »', 'Aussi « Tout le monde veut prendre sa place »', 'Nagui, tout simplement'],
    },
    {
      name: 'Michel Drucker',
      aliases: ['Drucker'],
      emoji: '🛋️❤️📺',
      group: 'Télé',
      tags: ['homme', 'français', 'europe', 'télé', 'animateur', 'légende', 'vivant', 'journaliste', 'sport'],
      clues: ['Figure historique de la télé française', 'Plus de soixante ans de carrière', 'Célèbre canapé rouge', 'Présente « Vivement dimanche »', 'Ancien journaliste sportif', 'Michel, l’homme du dimanche'],
    },
    {
      name: 'Philippe Etchebest',
      aliases: ['Etchebest'],
      emoji: '👨‍🍳😤🔪',
      group: 'Télé',
      tags: ['homme', 'français', 'europe', 'télé', 'chef-cuisinier', 'animateur', 'vivant', 'sport'],
      clues: ['Chef cuisinier français au crâne rasé', 'Ancien rugbyman amateur', 'Meilleur Ouvrier de France', 'Sauve des restaurants dans « Cauchemar en cuisine »', 'Juré de « Top Chef »', 'Philippe, chef bordelais'],
    },
    {
      name: 'Cyril Lignac',
      aliases: ['Lignac'],
      emoji: '👨‍🍳🍰📺',
      group: 'Télé',
      tags: ['homme', 'français', 'europe', 'télé', 'chef-cuisinier', 'animateur', 'business', 'vivant'],
      clues: ['Chef cuisinier et pâtissier français', 'Originaire de l’Aveyron', 'Juré du « Meilleur Pâtissier »', 'A cuisiné en direct pendant le confinement', 'Émission « Tous en cuisine »', 'Cyril, chef préféré des téléspectateurs'],
    },
    {
      name: 'Gordon Ramsay',
      aliases: ['Ramsay', 'Gordon'],
      emoji: '👨‍🍳🤬🥩',
      group: 'Télé',
      tags: ['homme', 'britannique', 'europe', 'télé', 'chef-cuisinier', 'animateur', 'business', 'vivant'],
      clues: ['Chef britannique connu pour ses colères', 'Plusieurs étoiles Michelin', 'Présente « Hell’s Kitchen »', 'Célèbre pour son bœuf Wellington', 'Ancien footballeur prometteur', 'Gordon, « It’s RAW ! »'],
    },
    {
      name: 'Oprah Winfrey',
      aliases: ['Oprah'],
      emoji: '🎙️📚💛',
      group: 'Télé',
      tags: ['femme', 'américain', 'amérique-du-nord', 'télé', 'animateur', 'business', 'milliardaire', 'acteur', 'vivant'],
      clues: ['Animatrice américaine de talk-show', 'Émission quotidienne pendant 25 ans', 'Ses conseils de lecture font des best-sellers', 'Entrepreneuse des médias', '« Vous gagnez une voiture ! »', 'Oprah, reine de la télé US'],
    },
    {
      name: 'Jean-Luc Reichmann',
      aliases: ['Reichmann'],
      emoji: '🎤⭐📺',
      group: 'Télé',
      tags: ['homme', 'français', 'europe', 'télé', 'animateur', 'acteur', 'vivant', 'jeu-télé'],
      clues: ['Animateur star de TF1', 'Présente un jeu à l’heure du déjeuner', 'Anime « Les 12 coups de midi »', 'Joue aussi dans une série policière', 'Incarne Léo Matteï', 'Jean-Luc, et son Étoile mystérieuse'],
    },
    {
      name: 'Florence Foresti',
      aliases: ['Foresti', 'Florence'],
      emoji: '😂🎭🎤',
      group: 'Télé',
      tags: ['femme', 'français', 'europe', 'télé', 'humoriste', 'acteur', 'comédie', 'vivant'],
      clues: ['Humoriste française originaire de Lyon', 'Célèbre pour ses imitations', 'A animé la cérémonie des César', 'Spectacles dans de grandes salles', 'Révélée sur France 2 et Canal+', 'Florence, reine du one-woman-show'],
    },
    // ── Business ──
    {
      name: 'Elon Musk',
      aliases: ['Musk', 'Elon'],
      emoji: '🚀🚗⚡',
      group: 'Business',
      tags: ['homme', 'américain', 'sud-africain', 'amérique-du-nord', 'business', 'tech', 'milliardaire', 'internet', 'vivant'],
      clues: ['Entrepreneur né en Afrique du Sud', 'Voitures électriques', 'Fusées réutilisables', 'Patron de Tesla et SpaceX', 'A racheté Twitter, renommé X', 'Elon, souvent l’homme le plus riche du monde'],
    },
    {
      name: 'Mark Zuckerberg',
      aliases: ['Zuckerberg', 'Zuck'],
      emoji: '👍💻🌐',
      group: 'Business',
      tags: ['homme', 'américain', 'amérique-du-nord', 'business', 'tech', 'milliardaire', 'internet', 'vivant'],
      clues: ['Entrepreneur américain de la tech', 'A lancé un réseau social depuis Harvard', 'Porte souvent un t-shirt gris', 'Fondateur de Facebook', 'Patron de Meta', 'Mark, surnommé Zuck'],
    },
    {
      name: 'Bill Gates',
      aliases: ['Gates', 'Bill'],
      emoji: '💻🪟🌍',
      group: 'Business',
      tags: ['homme', 'américain', 'amérique-du-nord', 'business', 'tech', 'milliardaire', 'vivant', 'philanthrope'],
      clues: ['Entrepreneur américain de l’informatique', 'Lunettes et pull sage', 'Cofondateur de Microsoft', 'Le système Windows', 'Grande fondation humanitaire', 'Bill, longtemps homme le plus riche du monde'],
    },
    {
      name: 'Steve Jobs',
      aliases: ['Jobs', 'Steve'],
      emoji: '🍎📱🖤',
      group: 'Business',
      tags: ['homme', 'américain', 'amérique-du-nord', 'business', 'tech', 'milliardaire', 'décédé'],
      clues: ['Visionnaire de la tech américaine', 'Toujours en col roulé noir', 'Cofondateur d’Apple', 'Présente l’iPhone en 2007', 'A aussi dirigé Pixar', 'Steve, mort en 2011'],
    },
    {
      name: 'Jeff Bezos',
      aliases: ['Bezos', 'Jeff'],
      emoji: '📦😁🚀',
      group: 'Business',
      tags: ['homme', 'américain', 'amérique-du-nord', 'business', 'tech', 'milliardaire', 'internet', 'vivant'],
      clues: ['Entrepreneur américain du e-commerce', 'A commencé par vendre des livres en ligne', 'Fondateur d’Amazon', 'Fusées Blue Origin', 'Propriétaire du « Washington Post »', 'Jeff, crâne rasé et grand rire'],
    },
    {
      name: 'Xavier Niel',
      aliases: ['Niel', 'Xavier'],
      emoji: '📡📱🏫',
      group: 'Business',
      tags: ['homme', 'français', 'europe', 'business', 'tech', 'milliardaire', 'internet', 'vivant'],
      clues: ['Entrepreneur français des télécoms', 'A créé une box Internet révolutionnaire', 'Fondateur de Free', 'A créé l’école 42', 'Station F, campus de start-up', 'Xavier, patron d’Iliad'],
    },
    {
      name: 'Walt Disney',
      aliases: ['Disney', 'Walt'],
      emoji: '🐭🏰✨',
      group: 'Business',
      tags: ['homme', 'américain', 'amérique-du-nord', 'business', 'cinéma', 'réalisateur', 'décédé', 'oscar', 'légende'],
      clues: ['Pionnier américain de l’animation', 'A créé une célèbre souris', 'Premier long métrage animé en 1937', 'Record d’Oscars remportés', 'A imaginé des parcs d’attractions', 'Walt, père de Mickey'],
    },
  ],
};
