import type { Pack } from '../types';

export const pack: Pack = {
  id: 'football',
  name: 'Football',
  emoji: '⚽',
  category: 'sport',
  description: 'Les stars du ballon rond, des légendes aux cracks d’aujourd’hui.',
  attributes: [
    { tag: 'femme', question: 'Est-ce une joueuse ?' },
    { tag: 'français', question: 'Est-il/elle français(e) ?' },
    { tag: 'brésilien', question: 'Est-il/elle brésilien(ne) ?' },
    { tag: 'argentin', question: 'Est-il argentin ?' },
    { tag: 'espagnol', question: 'Est-il/elle espagnol(e) ?' },
    { tag: 'anglais', question: 'Est-il anglais ?' },
    { tag: 'portugais', question: 'Est-il portugais ?' },
    { tag: 'europe', question: 'Vient-il/elle d’Europe ?' },
    { tag: 'afrique', question: 'Vient-il d’Afrique ?' },
    { tag: 'amérique-du-sud', question: 'Vient-il/elle d’Amérique du Sud ?' },
    { tag: 'attaquant', question: 'Est-ce un attaquant ?' },
    { tag: 'milieu', question: 'Joue-t-il/elle au milieu de terrain ?' },
    { tag: 'défenseur', question: 'Est-ce un défenseur ?' },
    { tag: 'gardien', question: 'Est-ce un gardien de but ?' },
    { tag: 'retraité', question: 'A-t-il/elle pris sa retraite ?' },
    { tag: 'en-activité', question: 'Joue-t-il/elle encore ?' },
    { tag: 'décédé', question: 'Est-il décédé ?' },
    { tag: 'psg', question: 'A-t-il joué au PSG ?' },
    { tag: 'real-madrid', question: 'A-t-il joué au Real Madrid ?' },
    { tag: 'barcelone', question: 'A-t-il/elle joué au FC Barcelone ?' },
    { tag: 'manchester-city', question: 'A-t-il joué à Manchester City ?' },
    { tag: 'manchester-united', question: 'A-t-il joué à Manchester United ?' },
    { tag: 'liverpool', question: 'A-t-il joué à Liverpool ?' },
    { tag: 'chelsea', question: 'A-t-il joué à Chelsea ?' },
    { tag: 'juventus', question: 'A-t-il joué à la Juventus ?' },
    { tag: 'milan-ac', question: 'A-t-il joué à l’AC Milan ?' },
    { tag: 'bayern', question: 'A-t-il joué au Bayern Munich ?' },
    { tag: 'marseille', question: 'A-t-il joué à l’OM ?' },
    { tag: 'ligue-1', question: 'A-t-il/elle joué en Ligue 1 ?' },
    { tag: 'premier-league', question: 'A-t-il joué en Premier League ?' },
    { tag: 'liga', question: 'A-t-il/elle joué en Liga espagnole ?' },
    { tag: 'serie-a', question: 'A-t-il joué en Serie A italienne ?' },
    { tag: 'bundesliga', question: 'A-t-il joué en Bundesliga ?' },
    { tag: 'championnat-américain', question: 'A-t-il/elle joué aux États-Unis ?' },
    { tag: 'championnat-saoudien', question: 'A-t-il joué en Arabie saoudite ?' },
    { tag: 'ballon-d-or', question: 'A-t-il/elle gagné le Ballon d’Or ?' },
    { tag: 'champion-du-monde', question: 'Est-il/elle champion(ne) du monde ?' },
    { tag: 'gaucher', question: 'Est-il gaucher ?' },
  ],
  items: [
    // ── France ──
    {
      name: 'Kylian Mbappé',
      aliases: ['Mbappé', 'Mbappe', 'Kylian', 'KM'],
      emoji: '⚡🇫🇷🐢',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'en-activité', 'psg', 'real-madrid', 'monaco', 'champion-du-monde', 'ligue-1', 'liga'],
      clues: ['Attaquant réputé pour sa vitesse folle', 'Champion du monde à seulement 19 ans', 'A grandi à Bondy, en banlieue parisienne', 'Rejoint le Real Madrid en 2024', 'Célèbre ses buts les bras croisés', 'Kylian, numéro 10 des Bleus'],
    },
    {
      name: 'Zinédine Zidane',
      aliases: ['Zidane', 'Zizou', 'ZZ'],
      emoji: '🇫🇷🏆🐐',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'milieu', 'retraité', 'juventus', 'real-madrid', 'ballon-d-or', 'champion-du-monde', 'ligue-1', 'serie-a', 'liga'],
      clues: ['Meneur de jeu élégant né à Marseille', 'Doublé de la tête en finale 1998', 'Ballon d’Or 1998', 'Coup de tête célèbre en finale 2006', 'Trois Ligues des champions de suite comme entraîneur', 'Surnommé Zizou'],
    },
    {
      name: 'Thierry Henry',
      aliases: ['Henry', 'Titi'],
      emoji: '🇫🇷🔴⚪',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'retraité', 'arsenal', 'barcelone', 'champion-du-monde', 'ligue-1', 'premier-league', 'liga', 'championnat-américain'],
      clues: ['Attaquant français élégant et rapide', 'Champion du monde 1998 et d’Europe 2000', 'Meilleur buteur de l’histoire d’Arsenal', 'Invaincu en Premier League avec les « Invincibles »', 'Statue devant l’Emirates Stadium', 'Surnommé Titi'],
    },
    {
      name: 'Antoine Griezmann',
      aliases: ['Griezmann', 'Grizou', 'Grizi'],
      emoji: '🇫🇷🔴⚪🕺',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'en-activité', 'barcelone', 'atletico', 'champion-du-monde', 'gaucher', 'liga'],
      clues: ['Attaquant gaucher, grand travailleur', 'Formé en Espagne, à la Real Sociedad', 'Champion du monde 2018', 'Meilleur buteur de l’histoire de l’Atlético', 'Célébration inspirée d’un jeu vidéo', 'Surnommé Grizou'],
    },
    {
      name: 'Karim Benzema',
      aliases: ['Benzema', 'KB9', 'Karim'],
      emoji: '🇫🇷🦁⚪',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'en-activité', 'real-madrid', 'lyon', 'championnat-saoudien', 'ballon-d-or', 'ligue-1', 'liga'],
      clues: ['Attaquant formé à l’Olympique lyonnais', 'Quatorze saisons au Real Madrid', 'Ballon d’Or 2022', 'Cinq Ligues des champions', 'Parti ensuite à Al-Ittihad', 'Surnommé KB9'],
    },
    {
      name: 'Paul Pogba',
      aliases: ['Pogba', 'La Pioche', 'Pogboom'],
      emoji: '🇫🇷💇‍♂️🕺',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'milieu', 'en-activité', 'juventus', 'manchester-united', 'monaco', 'champion-du-monde', 'premier-league', 'serie-a', 'ligue-1'],
      clues: ['Grand milieu technique aux coiffures colorées', 'Célèbre pour sa danse « dab »', 'Champion du monde 2018, buteur en finale', 'A joué deux fois à Manchester United', 'Quatre titres de champion d’Italie avec la Juventus', 'Surnommé La Pioche'],
    },
    {
      name: 'N’Golo Kanté',
      aliases: ['Kanté', 'Kante', 'NGolo'],
      emoji: '🇫🇷😊🔵',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'milieu', 'en-activité', 'chelsea', 'championnat-saoudien', 'champion-du-monde', 'ligue-1', 'premier-league'],
      clues: ['Petit milieu récupérateur infatigable', 'Réputé pour sa gentillesse et son sourire', 'Champion d’Angleterre surprise avec Leicester', 'Champion du monde 2018', 'Ligue des champions 2021 avec Chelsea', 'N’Golo, « il couvre 70 % de la Terre »'],
    },
    {
      name: 'Fabien Barthez',
      aliases: ['Barthez', 'Fabulous Fab'],
      emoji: '🧤🇫🇷👨‍🦲',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'gardien', 'retraité', 'marseille', 'monaco', 'manchester-united', 'champion-du-monde', 'ligue-1', 'premier-league'],
      clues: ['Gardien de but au crâne rasé', 'Laurent Blanc lui embrassait la tête', 'Champion du monde 1998', 'Ligue des champions 1993 avec l’OM', 'A joué à Manchester United', 'Barthez, reconverti en pilote automobile'],
    },
    {
      name: 'Michel Platini',
      aliases: ['Platini', 'Platoche'],
      emoji: '🇫🇷⚫⚪🏆',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'milieu', 'retraité', 'juventus', 'ballon-d-or', 'légende', 'ligue-1', 'serie-a'],
      clues: ['Meneur de jeu français des années 1980', 'Spécialiste des coups francs', 'Neuf buts à l’Euro 1984 gagné', 'Star de la Juventus', 'Trois Ballons d’Or consécutifs', 'Surnommé Platoche'],
    },
    {
      name: 'Ousmane Dembélé',
      aliases: ['Dembélé', 'Dembele', 'Dembouz'],
      emoji: '🇫🇷🔵🔴🏆',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'en-activité', 'psg', 'barcelone', 'ballon-d-or', 'champion-du-monde', 'ligue-1', 'bundesliga', 'liga'],
      clues: ['Ailier capable de frapper des deux pieds', 'Passé par Rennes et Dortmund', 'Champion du monde 2018', 'Ligue des champions 2025 avec Paris', 'Ballon d’Or 2025', 'Surnommé Dembouz'],
    },
    {
      name: 'Eric Cantona',
      aliases: ['Cantona', 'King Eric', 'Canto'],
      emoji: '👑🔴🇫🇷',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'retraité', 'manchester-united', 'marseille', 'légende', 'ligue-1', 'premier-league'],
      clues: ['Attaquant français au caractère bien trempé', 'Jouait le col du maillot relevé', 'Idole des supporters mancuniens', 'Surnommé « The King » en Angleterre', 'Devenu acteur après sa carrière', 'Eric, légende de Manchester United'],
    },
    {
      name: 'Franck Ribéry',
      aliases: ['Ribéry', 'Ribery', 'Kaiser Franck'],
      emoji: '🇫🇷🔴⚪🏆',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'attaquant', 'retraité', 'bayern', 'marseille', 'ligue-1', 'bundesliga', 'serie-a'],
      clues: ['Ailier virevoltant venu du Nord', 'Révélé à l’OM puis au Mondial 2006', 'Douze saisons au Bayern Munich', 'Ligue des champions 2013', 'Surnommé Kaiser Franck en Allemagne', 'Franck, originaire de Boulogne-sur-Mer'],
    },
    {
      name: 'Raphaël Varane',
      aliases: ['Varane', 'Rafa'],
      emoji: '🇫🇷🛡️⚪',
      group: 'France',
      tags: ['homme', 'français', 'europe', 'défenseur', 'retraité', 'real-madrid', 'manchester-united', 'champion-du-monde', 'ligue-1', 'liga', 'premier-league'],
      clues: ['Défenseur central élégant formé à Lens', 'Quatre Ligues des champions', 'Dix saisons au Real Madrid', 'Champion du monde 2018', 'A ensuite joué à Manchester United', 'Varane, retraité en 2024'],
    },
    // ── Brésil ──
    {
      name: 'Pelé',
      aliases: ['Pele', 'O Rei', 'Edson Arantes do Nascimento'],
      emoji: '👑🇧🇷⚽',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'attaquant', 'retraité', 'décédé', 'champion-du-monde', 'légende', 'santos', 'championnat-américain'],
      clues: ['Légende absolue du football mondial', 'Joueur de Santos pendant presque toute sa carrière', 'Seul joueur triple champion du monde', 'Titres en 1958, 1962 et 1970', 'Surnommé « le Roi »', 'Mort en 2022, Edson de son prénom'],
    },
    {
      name: 'Ronaldo Nazário',
      aliases: ['Ronaldo', 'R9', 'El Fenómeno', 'O Fenômeno'],
      emoji: '🇧🇷👽9️⃣',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'attaquant', 'retraité', 'barcelone', 'real-madrid', 'milan-ac', 'ballon-d-or', 'champion-du-monde', 'liga', 'serie-a'],
      clues: ['Attaquant brésilien surpuissant des années 1990-2000', 'Coupe de cheveux triangulaire en 2002', 'Doublé en finale de Coupe du monde 2002', 'Deux Ballons d’Or', 'Surnommé « le Phénomène »', 'On l’appelle R9'],
    },
    {
      name: 'Ronaldinho',
      aliases: ['Ronaldinho Gaúcho', 'Dinho'],
      emoji: '😁🇧🇷🪄',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'attaquant', 'retraité', 'psg', 'barcelone', 'milan-ac', 'ballon-d-or', 'champion-du-monde', 'ligue-1', 'liga'],
      clues: ['Magicien au sourire éclatant', 'Dribbles et passes sans regarder', 'A joué au PSG au début des années 2000', 'Champion du monde 2002', 'Ballon d’Or 2005 avec le Barça', 'Surnommé Dinho'],
    },
    {
      name: 'Neymar Jr',
      aliases: ['Neymar', 'Ney', 'Neymar Júnior'],
      emoji: '🇧🇷🤸‍♂️💛',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'attaquant', 'en-activité', 'psg', 'barcelone', 'championnat-saoudien', 'santos', 'liga', 'ligue-1'],
      clues: ['Dribbleur brésilien spectaculaire', 'Révélé au club de Santos', 'Trio « MSN » à Barcelone', 'Transfert record de 222 millions en 2017', 'Meilleur buteur de l’histoire de la Seleção', 'Ney, numéro 10 du Brésil'],
    },
    {
      name: 'Vinícius Jr',
      aliases: ['Vinícius', 'Vinicius', 'Vini', 'Vini Jr'],
      emoji: '🇧🇷⚪💃',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'attaquant', 'en-activité', 'real-madrid', 'liga'],
      clues: ['Ailier gauche brésilien très rapide', 'Formé à Flamengo', 'Célèbre ses buts en dansant', 'Buteur en finale de Ligue des champions 2022', 'Élu The Best FIFA 2024', 'Vini, numéro 7 du Real'],
    },
    {
      name: 'Kaká',
      aliases: ['Kaka', 'Ricardo Kaká'],
      emoji: '🇧🇷🔴⚫🙏',
      group: 'Brésil',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'milieu', 'retraité', 'milan-ac', 'real-madrid', 'ballon-d-or', 'champion-du-monde', 'serie-a', 'liga', 'championnat-américain'],
      clues: ['Meneur de jeu brésilien élégant', 'Grandes chevauchées balle au pied', 'Ligue des champions 2007 avec Milan', 'Ballon d’Or 2007', 'Champion du monde 2002', 'Kaká, dernier Ballon d’Or avant l’ère Messi-Ronaldo'],
    },
    {
      name: 'Marta',
      aliases: ['Marta Vieira da Silva'],
      emoji: '👑🇧🇷⚽',
      group: 'Brésil',
      tags: ['femme', 'brésilien', 'amérique-du-sud', 'attaquant', 'en-activité', 'légende', 'championnat-américain'],
      clues: ['Joueuse brésilienne légendaire', 'Six fois élue meilleure joueuse FIFA', 'Record de buts en Coupe du monde', 'Surnommée « la Reine »', 'A joué aux États-Unis à Orlando', 'Marta, souvent comparée à Pelé'],
    },
    // ── Argentine ──
    {
      name: 'Lionel Messi',
      aliases: ['Messi', 'Leo Messi', 'La Pulga', 'Leo'],
      emoji: '🐐🇦🇷🏆',
      group: 'Argentine',
      tags: ['homme', 'argentin', 'amérique-du-sud', 'attaquant', 'en-activité', 'barcelone', 'psg', 'ballon-d-or', 'champion-du-monde', 'gaucher', 'liga', 'championnat-américain', 'ligue-1'],
      clues: ['Petit génie gaucher né à Rosario', 'Recordman de Ballons d’Or', 'Champion du monde 2022 au Qatar', 'Légende absolue du FC Barcelone', 'Joue ensuite à l’Inter Miami', 'Surnommé la Pulga'],
    },
    {
      name: 'Diego Maradona',
      aliases: ['Maradona', 'El Pibe de Oro', 'Diego'],
      emoji: '🇦🇷✋🔟',
      group: 'Argentine',
      tags: ['homme', 'argentin', 'amérique-du-sud', 'attaquant', 'retraité', 'décédé', 'barcelone', 'champion-du-monde', 'gaucher', 'liga', 'serie-a'],
      clues: ['Génie gaucher argentin des années 1980', 'Idole absolue de la ville de Naples', 'Champion du monde 1986', 'But de la « main de Dieu »', 'Surnommé « el Pibe de Oro »', 'Diego, numéro 10 mort en 2020'],
    },
    {
      name: 'Ángel Di María',
      aliases: ['Di María', 'Di Maria', 'Fideo'],
      emoji: '🇦🇷🍝💘',
      group: 'Argentine',
      tags: ['homme', 'argentin', 'amérique-du-sud', 'attaquant', 'en-activité', 'real-madrid', 'psg', 'champion-du-monde', 'gaucher', 'liga', 'ligue-1', 'serie-a'],
      clues: ['Ailier gaucher très fin', 'Célèbre ses buts avec un cœur', 'Buteur en finale du Mondial 2022', 'Sept saisons au PSG', 'Surnommé « Fideo », le spaghetti', 'Ángel, passé par le Real et Benfica'],
    },
    {
      name: 'Emiliano Martínez',
      aliases: ['Emi Martínez', 'Dibu', 'Dibu Martínez'],
      emoji: '🧤🇦🇷🏆',
      group: 'Argentine',
      tags: ['homme', 'argentin', 'amérique-du-sud', 'gardien', 'en-activité', 'arsenal', 'champion-du-monde', 'premier-league', 'liga'],
      clues: ['Gardien argentin au fort caractère', 'Longtemps remplaçant à Arsenal', 'Héros des tirs au but en 2022', 'Meilleur gardien du Mondial 2022', 'Gardien d’Aston Villa', 'Surnommé Dibu'],
    },
    // ── Portugal ──
    {
      name: 'Cristiano Ronaldo',
      aliases: ['CR7', 'Ronaldo', 'Cristiano'],
      emoji: '🇵🇹7️⃣💪',
      group: 'Portugal',
      tags: ['homme', 'portugais', 'europe', 'attaquant', 'en-activité', 'real-madrid', 'manchester-united', 'juventus', 'championnat-saoudien', 'ballon-d-or', 'premier-league', 'liga'],
      clues: ['Attaquant ultra-athlétique né à Madère', 'Célébration « Siuuu » mondialement connue', 'Cinq Ballons d’Or', 'Recordman de buts en sélection', 'Euro 2016 avec son pays', 'Surnommé CR7'],
    },
    {
      name: 'Luís Figo',
      aliases: ['Figo'],
      emoji: '🇵🇹🔁⚪',
      group: 'Portugal',
      tags: ['homme', 'portugais', 'europe', 'attaquant', 'retraité', 'barcelone', 'real-madrid', 'inter', 'ballon-d-or', 'liga', 'serie-a'],
      clues: ['Ailier portugais des années 1990-2000', 'Formé au Sporting Portugal', 'Transfert explosif de Barcelone vers Madrid', 'Ballon d’Or 2000', 'A fini sa carrière à l’Inter', 'Figo, membre des « Galactiques »'],
    },
    {
      name: 'Bruno Fernandes',
      aliases: ['Bruno', 'Fernandes'],
      emoji: '🇵🇹🔴🎯',
      group: 'Portugal',
      tags: ['homme', 'portugais', 'europe', 'milieu', 'en-activité', 'manchester-united', 'serie-a', 'premier-league'],
      clues: ['Milieu offensif portugais', 'Spécialiste des penaltys avec petit saut', 'Révélé au Sporting Portugal', 'Capitaine de Manchester United', 'Ligue des nations avec son pays', 'Bruno, numéro 8 des Red Devils'],
    },
    // ── Espagne ──
    {
      name: 'Andrés Iniesta',
      aliases: ['Iniesta', 'Don Andrés'],
      emoji: '🇪🇸🧠🏆',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'milieu', 'retraité', 'barcelone', 'champion-du-monde', 'liga'],
      clues: ['Milieu discret au toucher de balle magique', 'Formé à la Masia', 'Buteur en finale du Mondial 2010', 'Quatre Ligues des champions avec le Barça', 'A joué au Japon, à Kobe', 'Surnommé Don Andrés'],
    },
    {
      name: 'Xavi Hernández',
      aliases: ['Xavi', 'Xavi Hernandez'],
      emoji: '🇪🇸🔵🔴🎼',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'milieu', 'retraité', 'barcelone', 'champion-du-monde', 'entraîneur', 'liga'],
      clues: ['Chef d’orchestre du tiki-taka', 'Maître de la passe courte', 'Champion du monde 2010', 'Plus de 700 matchs au Barça', 'Est devenu entraîneur du Barça', 'Xavi, duo mythique avec Iniesta'],
    },
    {
      name: 'Iker Casillas',
      aliases: ['Casillas', 'San Iker'],
      emoji: '🧤🇪🇸⚪',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'gardien', 'retraité', 'real-madrid', 'champion-du-monde', 'liga'],
      clues: ['Gardien espagnol aux réflexes incroyables', 'Formé au Real Madrid', 'Capitaine champion du monde 2010', 'Double champion d’Europe avec son pays', 'A fini sa carrière à Porto', 'Surnommé San Iker'],
    },
    {
      name: 'Sergio Ramos',
      aliases: ['Ramos', 'SR4'],
      emoji: '🇪🇸🛡️💪',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'défenseur', 'real-madrid', 'psg', 'champion-du-monde', 'liga', 'ligue-1'],
      clues: ['Défenseur central au caractère de guerrier', 'Formé au FC Séville', 'Buteur à la 93e minute en finale 2014', 'Champion du monde 2010', 'Seize saisons au Real Madrid', 'Ramos, numéro 4 légendaire'],
    },
    {
      name: 'Lamine Yamal',
      aliases: ['Yamal', 'Lamine'],
      emoji: '🇪🇸👦✨',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'attaquant', 'en-activité', 'barcelone', 'gaucher', 'liga'],
      clues: ['Ailier gaucher né en 2007', 'Formé à la Masia', 'Champion d’Europe à 17 ans en 2024', 'Plus jeune buteur de l’histoire de l’Euro', 'Porte le numéro 10 du Barça', 'Lamine, prodige catalan'],
    },
    {
      name: 'Pedri',
      aliases: ['Pedro González'],
      emoji: '🇪🇸🏝️🎩',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'milieu', 'en-activité', 'barcelone', 'liga'],
      clues: ['Milieu technique venu des Canaries', 'Recruté par le Barça à 17 ans', 'Golden Boy 2021', 'Champion d’Europe 2024', 'Souvent comparé à Iniesta', 'Pedri, numéro 8 blaugrana'],
    },
    {
      name: 'Rodri',
      aliases: ['Rodrigo Hernández'],
      emoji: '🇪🇸🩵🏆',
      group: 'Espagne',
      tags: ['homme', 'espagnol', 'europe', 'milieu', 'en-activité', 'manchester-city', 'atletico', 'ballon-d-or', 'liga', 'premier-league'],
      clues: ['Milieu défensif espagnol très calme', 'Passé par l’Atlético de Madrid', 'Buteur en finale de Ligue des champions 2023', 'Champion d’Europe 2024', 'Ballon d’Or 2024', 'Rodri, métronome de Manchester City'],
    },
    {
      name: 'Alexia Putellas',
      aliases: ['Putellas', 'Alexia', 'La Reina'],
      emoji: '🇪🇸👑🔵🔴',
      group: 'Espagne',
      tags: ['femme', 'espagnol', 'europe', 'milieu', 'en-activité', 'barcelone', 'ballon-d-or', 'champion-du-monde', 'liga'],
      clues: ['Milieu offensive espagnole', 'Fidèle au FC Barcelone depuis 2012', 'Deux Ballons d’Or en 2021 et 2022', 'Championne du monde 2023', 'Plusieurs Ligues des champions', 'Alexia, surnommée « la Reina »'],
    },
    {
      name: 'Aitana Bonmatí',
      aliases: ['Bonmatí', 'Bonmati', 'Aitana'],
      emoji: '🇪🇸🧠🏆',
      group: 'Espagne',
      tags: ['femme', 'espagnol', 'europe', 'milieu', 'en-activité', 'barcelone', 'ballon-d-or', 'champion-du-monde', 'liga'],
      clues: ['Milieu espagnole au jeu très intelligent', 'Formée à la Masia', 'Meilleure joueuse du Mondial 2023', 'Championne du monde 2023', 'Triple Ballon d’Or', 'Aitana, star du Barça'],
    },
    // ── États-Unis ──
    {
      name: 'Megan Rapinoe',
      aliases: ['Rapinoe', 'Pinoe'],
      emoji: '🇺🇸💜🏆',
      group: 'États-Unis',
      tags: ['femme', 'américain', 'amérique-du-nord', 'attaquant', 'retraité', 'ballon-d-or', 'champion-du-monde', 'ligue-1', 'championnat-américain'],
      clues: ['Joueuse américaine aux cheveux colorés', 'Célébration les bras en croix', 'Double championne du monde', 'Meilleure joueuse du Mondial 2019', 'Ballon d’Or 2019', 'Pinoe, retraitée en 2023'],
    },
    // ── Angleterre ──
    {
      name: 'David Beckham',
      aliases: ['Beckham', 'Becks'],
      emoji: '🇬🇧🎯🌟',
      group: 'Angleterre',
      tags: ['homme', 'anglais', 'europe', 'milieu', 'retraité', 'manchester-united', 'real-madrid', 'psg', 'premier-league', 'liga', 'ligue-1', 'championnat-américain'],
      clues: ['Milieu anglais star planétaire', 'Centres et coups francs parfaits', 'Formé à Manchester United', 'A joué au Real, au Galaxy et au PSG', 'Copropriétaire de l’Inter Miami', 'Becks, marié à une Spice Girl'],
    },
    {
      name: 'Wayne Rooney',
      aliases: ['Rooney', 'Wazza'],
      emoji: '🇬🇧🔴💥',
      group: 'Angleterre',
      tags: ['homme', 'anglais', 'europe', 'attaquant', 'retraité', 'manchester-united', 'premier-league', 'championnat-américain'],
      clues: ['Attaquant anglais puissant', 'Révélé très jeune à Everton', 'Célèbre ciseau retourné contre City', 'Meilleur buteur de Manchester United', 'Ancien record de buts pour l’Angleterre', 'Surnommé Wazza'],
    },
    {
      name: 'Harry Kane',
      aliases: ['Kane', 'Hurricane'],
      emoji: '🇬🇧🎯🔴',
      group: 'Angleterre',
      tags: ['homme', 'anglais', 'europe', 'attaquant', 'en-activité', 'bayern', 'premier-league', 'bundesliga'],
      clues: ['Buteur anglais très complet', 'Meilleur buteur de l’histoire de Tottenham', 'Meilleur buteur de l’histoire de l’Angleterre', 'Parti au Bayern Munich en 2023', 'Capitaine des Three Lions', 'Harry, numéro 9 anglais'],
    },
    {
      name: 'Jude Bellingham',
      aliases: ['Bellingham', 'Jude'],
      emoji: '🇬🇧⚪🙌',
      group: 'Angleterre',
      tags: ['homme', 'anglais', 'europe', 'milieu', 'en-activité', 'real-madrid', 'bundesliga', 'liga'],
      clues: ['Milieu anglais box-to-box', 'Débuts pro à Birmingham à 16 ans', 'Révélé au Borussia Dortmund', 'Célèbre bras écartés', 'Rejoint le Real Madrid en 2023', 'Jude, numéro 5 merengue'],
    },
    {
      name: 'Bukayo Saka',
      aliases: ['Saka', 'Starboy'],
      emoji: '🇬🇧🔴⭐',
      group: 'Angleterre',
      tags: ['homme', 'anglais', 'europe', 'attaquant', 'en-activité', 'arsenal', 'gaucher', 'premier-league'],
      clues: ['Ailier droit gaucher anglais', 'Formé à Hale End', 'Numéro 7 des Gunners', 'Finaliste de l’Euro 2020 et 2024', 'Surnommé « Starboy »', 'Bukayo, pépite d’Arsenal'],
    },
    // ── Allemagne ──
    {
      name: 'Franz Beckenbauer',
      aliases: ['Beckenbauer', 'Der Kaiser', 'Le Kaiser'],
      emoji: '🇩🇪👑🛡️',
      group: 'Allemagne',
      tags: ['homme', 'allemand', 'europe', 'défenseur', 'retraité', 'décédé', 'bayern', 'ballon-d-or', 'champion-du-monde', 'légende', 'bundesliga'],
      clues: ['Défenseur allemand élégant', 'Inventeur du rôle de libéro moderne', 'Champion du monde comme joueur en 1974', 'Champion du monde comme entraîneur en 1990', 'Deux Ballons d’Or', 'Surnommé « der Kaiser »'],
    },
    {
      name: 'Manuel Neuer',
      aliases: ['Neuer', 'Manu'],
      emoji: '🧤🇩🇪🔴',
      group: 'Allemagne',
      tags: ['homme', 'allemand', 'europe', 'gardien', 'bayern', 'champion-du-monde', 'bundesliga'],
      clues: ['Gardien allemand très grand', 'Sort loin de ses buts comme un libéro', 'Formé à Schalke 04', 'Champion du monde 2014', 'Légende du Bayern Munich', 'Manu, capitaine de la Mannschaft'],
    },
    // ── Italie ──
    {
      name: 'Paolo Maldini',
      aliases: ['Maldini'],
      emoji: '🇮🇹🔴⚫🛡️',
      group: 'Italie',
      tags: ['homme', 'italien', 'europe', 'défenseur', 'retraité', 'milan-ac', 'légende', 'serie-a'],
      clues: ['Défenseur italien d’une grande classe', 'Un seul club toute sa carrière', 'Cinq fois champion d’Europe avec son club', 'Plus de 900 matchs officiels', 'Son numéro 3 a été retiré', 'Maldini, légende rossonera'],
    },
    {
      name: 'Gianluigi Buffon',
      aliases: ['Buffon', 'Gigi'],
      emoji: '🧤🇮🇹⚫⚪',
      group: 'Italie',
      tags: ['homme', 'italien', 'europe', 'gardien', 'retraité', 'juventus', 'psg', 'champion-du-monde', 'serie-a', 'ligue-1'],
      clues: ['Gardien italien à la longévité incroyable', 'Révélé à Parme', 'Champion du monde 2006', 'Près de vingt saisons à la Juventus', 'A joué un an au PSG', 'Surnommé Gigi'],
    },
    // ── Pays-Bas ──
    {
      name: 'Johan Cruyff',
      aliases: ['Cruyff', 'Cruijff'],
      emoji: '🇳🇱🟠🌀',
      group: 'Pays-Bas',
      tags: ['homme', 'néerlandais', 'europe', 'attaquant', 'retraité', 'décédé', 'barcelone', 'ballon-d-or', 'légende', 'entraîneur', 'liga'],
      clues: ['Icône du « football total »', 'Star de l’Ajax Amsterdam', 'A donné son nom à un célèbre crochet', 'Trois Ballons d’Or', 'Père spirituel du jeu du Barça', 'Johan, numéro 14 mythique'],
    },
    {
      name: 'Virgil van Dijk',
      aliases: ['Van Dijk', 'VVD', 'Virgil'],
      emoji: '🇳🇱🛡️🔴',
      group: 'Pays-Bas',
      tags: ['homme', 'néerlandais', 'europe', 'défenseur', 'en-activité', 'liverpool', 'premier-league'],
      clues: ['Défenseur central imposant et serein', 'Passé par le Celtic et Southampton', 'Ligue des champions 2019', 'Deuxième du Ballon d’Or 2019', 'Capitaine des Pays-Bas', 'Virgil, capitaine de Liverpool'],
    },
    // ── Reste de l'Europe / Asie ──
    {
      name: 'Luka Modrić',
      aliases: ['Modric', 'Modrić', 'Luka'],
      emoji: '🇭🇷🎩⚪',
      group: 'Croatie',
      tags: ['homme', 'croate', 'europe', 'milieu', 'real-madrid', 'milan-ac', 'ballon-d-or', 'premier-league', 'liga', 'serie-a'],
      clues: ['Milieu frêle au toucher de velours', 'Passes en extérieur du pied', 'Finaliste du Mondial 2018', 'Ballon d’Or 2018', 'Six Ligues des champions au Real', 'Luka, capitaine croate'],
    },
    {
      name: 'Erling Haaland',
      aliases: ['Haaland', 'Erling'],
      emoji: '🇳🇴🤖🧘',
      group: 'Norvège',
      tags: ['homme', 'norvégien', 'europe', 'attaquant', 'en-activité', 'manchester-city', 'gaucher', 'bundesliga', 'premier-league'],
      clues: ['Buteur géant venu du Nord', 'Passé par Salzbourg et Dortmund', 'Célèbre ses buts en méditant', 'Record de buts en une saison de Premier League', 'Triplé historique avec City en 2023', 'Erling, cyborg norvégien'],
    },
    {
      name: 'Robert Lewandowski',
      aliases: ['Lewandowski', 'Lewy'],
      emoji: '🇵🇱🎯🔴',
      group: 'Pologne',
      tags: ['homme', 'polonais', 'europe', 'attaquant', 'bayern', 'barcelone', 'bundesliga', 'liga'],
      clues: ['Buteur polonais redoutable', 'Révélé au Borussia Dortmund', 'Cinq buts en neuf minutes', 'Record de buts en une saison de Bundesliga', 'A rejoint le Barça en 2022', 'Surnommé Lewy'],
    },
    {
      name: 'Kevin De Bruyne',
      aliases: ['De Bruyne', 'KDB'],
      emoji: '🇧🇪🎯🩵',
      group: 'Belgique',
      tags: ['homme', 'belge', 'europe', 'milieu', 'en-activité', 'manchester-city', 'chelsea', 'premier-league', 'bundesliga', 'serie-a'],
      clues: ['Milieu belge aux passes millimétrées', 'Peu utilisé à Chelsea au début', 'Explose à Wolfsburg', 'Dix saisons à Manchester City', 'Part à Naples en 2025', 'Surnommé KDB'],
    },
    {
      name: 'Thibaut Courtois',
      aliases: ['Courtois'],
      emoji: '🧤🇧🇪⚪',
      group: 'Belgique',
      tags: ['homme', 'belge', 'europe', 'gardien', 'en-activité', 'real-madrid', 'chelsea', 'atletico', 'liga', 'premier-league'],
      clues: ['Gardien belge de près de deux mètres', 'Révélé à Genk puis à l’Atlético', 'Passé par Chelsea', 'Homme du match de la finale 2022', 'Gardien du Real Madrid', 'Courtois, dernier rempart des Diables rouges'],
    },
    {
      name: 'Zlatan Ibrahimović',
      aliases: ['Zlatan', 'Ibra', 'Ibrahimovic'],
      emoji: '🇸🇪🦁🥋',
      group: 'Suède',
      tags: ['homme', 'suédois', 'europe', 'attaquant', 'retraité', 'psg', 'barcelone', 'juventus', 'milan-ac', 'serie-a', 'ligue-1', 'championnat-américain'],
      clues: ['Géant suédois pratiquant le taekwondo', 'Parle souvent de lui à la troisième personne', 'Champion dans de nombreux pays', 'Quatre saisons au PSG', 'Célèbre retourné contre l’Angleterre', 'Surnommé Ibra'],
    },
    {
      name: 'Son Heung-min',
      aliases: ['Son', 'Sonny'],
      emoji: '🇰🇷📸⚪',
      group: 'Corée du Sud',
      tags: ['homme', 'sud-coréen', 'asie', 'attaquant', 'en-activité', 'bundesliga', 'premier-league', 'championnat-américain'],
      clues: ['Attaquant asiatique très populaire', 'Célèbre ses buts en mimant une photo', 'Dix saisons à Tottenham', 'Capitaine vainqueur de la Ligue Europa 2025', 'Parti ensuite à Los Angeles', 'Sonny, star de la Corée du Sud'],
    },
    // ── Afrique ──
    {
      name: 'Didier Drogba',
      aliases: ['Drogba', 'Drog', 'DD'],
      emoji: '🇨🇮🐘🔵',
      group: 'Côte d’Ivoire',
      tags: ['homme', 'ivoirien', 'afrique', 'attaquant', 'retraité', 'chelsea', 'marseille', 'ligue-1', 'premier-league', 'championnat-américain'],
      clues: ['Attaquant ivoirien puissant', 'Révélé à Guingamp puis à l’OM', 'Légende de Chelsea', 'Égalise et marque le tir au but en finale 2012', 'Capitaine des Éléphants', 'Didier, meilleur buteur de l’histoire des Éléphants'],
    },
    {
      name: 'Samuel Eto’o',
      aliases: ['Eto’o', 'Etoo', 'Samuel Etoo'],
      emoji: '🇨🇲🦁⚽',
      group: 'Cameroun',
      tags: ['homme', 'camerounais', 'afrique', 'attaquant', 'retraité', 'barcelone', 'inter', 'chelsea', 'liga', 'serie-a', 'premier-league'],
      clues: ['Buteur camerounais très rapide', 'Formé en partie au Real Madrid', 'Deux triplés historiques avec deux clubs', 'Quatre fois Ballon d’Or africain', 'Double champion d’Afrique', 'Samuel, Lion indomptable'],
    },
    {
      name: 'George Weah',
      aliases: ['Weah', 'Mister George'],
      emoji: '🇱🇷🏆🏛️',
      group: 'Liberia',
      tags: ['homme', 'libérien', 'afrique', 'attaquant', 'retraité', 'psg', 'monaco', 'milan-ac', 'ballon-d-or', 'ligue-1', 'serie-a', 'premier-league'],
      clues: ['Attaquant africain des années 1990', 'Révélé en France par Arsène Wenger', 'A joué à Monaco et au PSG', 'Seul Africain Ballon d’Or, en 1995', 'Devenu président de son pays', 'George, légende du Liberia'],
    },
    {
      name: 'Mohamed Salah',
      aliases: ['Salah', 'Mo Salah', 'Momo'],
      emoji: '🇪🇬🔴👑',
      group: 'Égypte',
      tags: ['homme', 'égyptien', 'afrique', 'attaquant', 'en-activité', 'liverpool', 'chelsea', 'gaucher', 'premier-league', 'serie-a'],
      clues: ['Ailier gaucher très rapide', 'Passé par Bâle, Chelsea et la Roma', 'Plusieurs fois meilleur buteur de Premier League', 'Ligue des champions 2019', 'Surnommé « le Roi égyptien »', 'Mo, star de Liverpool'],
    },
    {
      name: 'Sadio Mané',
      aliases: ['Mané', 'Mane', 'Sadio'],
      emoji: '🇸🇳🦁🔴',
      group: 'Sénégal',
      tags: ['homme', 'sénégalais', 'afrique', 'attaquant', 'en-activité', 'liverpool', 'bayern', 'championnat-saoudien', 'ligue-1', 'premier-league', 'bundesliga'],
      clues: ['Attaquant sénégalais généreux', 'Débuts en Europe au FC Metz', 'Triplé le plus rapide de Premier League', 'Ligue des champions 2019', 'Champion d’Afrique 2022 sur penalty', 'Sadio, Lion de la Teranga'],
    },
    {
      name: 'Victor Osimhen',
      aliases: ['Osimhen', 'Osi'],
      emoji: '🇳🇬🎭⚽',
      group: 'Nigeria',
      tags: ['homme', 'nigérian', 'afrique', 'attaquant', 'en-activité', 'ligue-1', 'serie-a', 'bundesliga'],
      clues: ['Attaquant nigérian qui joue masqué', 'Passé par Lille', 'Champion d’Italie 2023 avec Naples', 'Ballon d’Or africain 2023', 'A ensuite joué à Galatasaray', 'Victor, Super Eagle'],
    },
    {
      name: 'Achraf Hakimi',
      aliases: ['Hakimi', 'Achraf'],
      emoji: '🇲🇦🚀🔵',
      group: 'Maroc',
      tags: ['homme', 'marocain', 'afrique', 'défenseur', 'en-activité', 'psg', 'real-madrid', 'inter', 'liga', 'bundesliga', 'serie-a', 'ligue-1'],
      clues: ['Latéral droit ultra-rapide', 'Formé au Real Madrid', 'Panenka décisif contre l’Espagne en 2022', 'Demi-finaliste du Mondial 2022', 'Ligue des champions 2025 avec Paris', 'Achraf, star des Lions de l’Atlas'],
    },
    {
      name: 'Yaya Touré',
      aliases: ['Yaya', 'Touré'],
      emoji: '🇨🇮🐘🩵',
      group: 'Côte d’Ivoire',
      tags: ['homme', 'ivoirien', 'afrique', 'milieu', 'retraité', 'barcelone', 'manchester-city', 'ligue-1', 'liga', 'premier-league'],
      clues: ['Milieu ivoirien puissant et technique', 'Passé par Monaco', 'Vainqueur de la Ligue des champions avec le Barça', 'Légende de Manchester City', 'Quatre fois Ballon d’Or africain', 'Yaya, frère de Kolo'],
    },
    {
      name: 'Roger Milla',
      aliases: ['Milla'],
      emoji: '🇨🇲💃🚩',
      group: 'Cameroun',
      tags: ['homme', 'camerounais', 'afrique', 'attaquant', 'retraité', 'monaco', 'légende', 'ligue-1'],
      clues: ['Attaquant camerounais des années 1980-90', 'A joué en France à Monaco et Bastia', 'Danse près du poteau de corner', 'Star du Mondial 1990', 'Buteur en Coupe du monde à 42 ans', 'Roger, Lion indomptable'],
    },
    {
      name: 'Riyad Mahrez',
      aliases: ['Mahrez', 'Riyad'],
      emoji: '🇩🇿🦊🎯',
      group: 'Algérie',
      tags: ['homme', 'algérien', 'afrique', 'attaquant', 'en-activité', 'manchester-city', 'championnat-saoudien', 'gaucher', 'premier-league'],
      clues: ['Ailier gaucher au dribble soyeux', 'Né à Sarcelles', 'Champion surprise avec Leicester en 2016', 'Champion d’Afrique 2019', 'Triplé historique avec City en 2023', 'Riyad, capitaine des Fennecs'],
    },
    {
      name: 'Yassine Bounou',
      aliases: ['Bounou', 'Bono'],
      emoji: '🧤🇲🇦🦁',
      group: 'Maroc',
      tags: ['homme', 'marocain', 'afrique', 'gardien', 'en-activité', 'championnat-saoudien', 'liga'],
      clues: ['Gardien marocain né au Canada', 'Vainqueur de la Ligue Europa avec Séville', 'Héros des tirs au but contre l’Espagne', 'Demi-finaliste du Mondial 2022', 'Parti à Al-Hilal', 'Surnommé Bono'],
    },
  ],
};
