import type { Pack } from '../types';

export const pack: Pack = {
  id: 'histoire',
  name: 'Personnages historiques',
  emoji: '📜',
  category: 'histoire',
  description: 'Rois, savants, artistes et héros qui ont marqué l’histoire du monde.',
  attributes: [
    { tag: 'femme', question: 'Est-ce une femme ?' },
    { tag: 'français', question: 'Est-il/elle français(e) ?' },
    { tag: 'italien', question: 'Est-il italien ?' },
    { tag: 'américain', question: 'Est-il/elle américain(e) ?' },
    { tag: 'britannique', question: 'Est-il anglais ?' },
    { tag: 'égyptien', question: 'Vient-il/elle de l’Égypte ancienne ?' },
    { tag: 'europe', question: 'Vient-il/elle d’Europe ?' },
    { tag: 'afrique', question: 'Vient-il/elle d’Afrique ?' },
    { tag: 'asie', question: 'Vient-il d’Asie ?' },
    { tag: 'amérique', question: 'Vient-il/elle du continent américain ?' },
    { tag: 'antiquité', question: 'A-t-il/elle vécu dans l’Antiquité ?' },
    { tag: 'moyen-âge', question: 'A-t-il/elle vécu au Moyen Âge ?' },
    { tag: 'renaissance', question: 'A-t-il vécu à la Renaissance ?' },
    { tag: 'temps-modernes', question: 'A-t-il/elle vécu aux XVIIe ou XVIIIe siècles ?' },
    { tag: 'xixe-siècle', question: 'Est-il célèbre pour le XIXe siècle ?' },
    { tag: 'xxe-siècle', question: 'Est-il/elle célèbre pour le XXe siècle ?' },
    { tag: 'souverain', question: 'Était-il/elle roi, reine, empereur ou pharaon ?' },
    { tag: 'conquérant', question: 'Est-ce un grand conquérant ?' },
    { tag: 'chef-militaire', question: 'A-t-il/elle mené des armées ?' },
    { tag: 'politique', question: 'Était-il/elle un(e) dirigeant(e) politique ?' },
    { tag: 'scientifique', question: 'Est-ce un(e) scientifique ?' },
    { tag: 'inventeur', question: 'A-t-il inventé quelque chose ?' },
    { tag: 'artiste', question: 'Est-ce un(e) artiste ?' },
    { tag: 'peintre', question: 'Est-ce un(e) peintre ?' },
    { tag: 'écrivain', question: 'Est-ce un écrivain ?' },
    { tag: 'philosophe', question: 'Est-ce un philosophe ?' },
    { tag: 'explorateur', question: 'Est-ce un explorateur ?' },
    { tag: 'militant', question: 'S’est-il/elle battu(e) pour les droits et libertés ?' },
    { tag: 'empereur', question: 'Était-il empereur ?' },
    { tag: 'bâtisseur', question: 'A-t-il fait bâtir un monument célèbre ?' },
    { tag: 'emprisonné-ou-exilé', question: 'A-t-il/elle été emprisonné(e) ou exilé(e) ?' },
    { tag: 'mort-avant-40-ans', question: 'Est-il/elle mort(e) avant 40 ans ?' },
    { tag: 'espace-astronomie', question: 'Est-il lié à l’espace ou à l’astronomie ?' },
    { tag: 'théâtre', question: 'A-t-il écrit pour le théâtre ?' },
    { tag: 'prix-nobel', question: 'A-t-il/elle reçu un prix Nobel ?' },
    { tag: 'assassiné', question: 'A-t-il été assassiné ?' },
    { tag: 'panthéon', question: 'Repose-t-il/elle au Panthéon ?' },
  ],
  items: [
    // ── Antiquité ──
    {
      name: 'Cléopâtre',
      aliases: ['Cleopatre', 'Cléopâtre VII'],
      emoji: '👑🐍🏺',
      group: 'Antiquité',
      tags: ['femme', 'égyptien', 'afrique', 'antiquité', 'souverain', 'politique', 'pharaon', 'mort-avant-40-ans', 'icône-de-style'],
      clues: ['Reine de l’Égypte antique', 'Dernière souveraine de la dynastie des Ptolémées', 'Alliée de Jules César puis de Marc Antoine', 'Parlait de nombreuses langues', 'Selon la légende, mordue par un aspic', 'Cléopâtre VII'],
    },
    {
      name: 'Jules César',
      aliases: ['César', 'Cesar', 'Julius Caesar'],
      emoji: '🏛️🗡️🌿',
      group: 'Antiquité',
      tags: ['homme', 'romain', 'europe', 'antiquité', 'chef-militaire', 'politique', 'conquérant', 'assassiné', 'écrivain'],
      clues: ['Général et homme politique romain', 'Conquiert la Gaule', 'Franchit le Rubicon', '« Veni, vidi, vici »', 'Assassiné aux ides de mars', 'Jules, allié puis amant de Cléopâtre'],
    },
    {
      name: 'Alexandre le Grand',
      aliases: ['Alexandre', 'Alexandre III de Macédoine'],
      emoji: '🐎⚔️🌍',
      group: 'Antiquité',
      tags: ['homme', 'grec', 'europe', 'antiquité', 'souverain', 'chef-militaire', 'conquérant'],
      clues: ['Roi de Macédoine', 'Élève du philosophe Aristote', 'Empire de la Grèce jusqu’à l’Inde', 'Fonde une grande ville en Égypte', 'Mort à 32 ans à Babylone', 'Son cheval s’appelait Bucéphale'],
    },
    {
      name: 'Toutânkhamon',
      aliases: ['Toutankhamon', 'Tutankhamun'],
      emoji: '👑🏺💀',
      group: 'Antiquité',
      tags: ['homme', 'égyptien', 'afrique', 'antiquité', 'souverain', 'pharaon', 'mort-avant-40-ans'],
      clues: ['Jeune pharaon égyptien', 'Monté sur le trône vers 9 ans', 'Tombeau découvert presque intact en 1922', 'Fouilles d’Howard Carter', 'Célèbre masque funéraire en or', 'Surnommé le pharaon enfant'],
    },
    {
      name: 'Ramsès II',
      aliases: ['Ramsès', 'Ramses II', 'Ramsès le Grand'],
      emoji: '🏜️👑🗿',
      group: 'Antiquité',
      tags: ['homme', 'égyptien', 'afrique', 'antiquité', 'souverain', 'chef-militaire', 'pharaon', 'bâtisseur'],
      clues: ['Pharaon au très long règne', 'Bataille de Qadesh contre les Hittites', 'Temples géants d’Abou Simbel', 'Plus de 60 ans sur le trône', 'Sa momie est venue à Paris en 1976', 'Dit « le Grand »'],
    },
    {
      name: 'Vercingétorix',
      aliases: ['Vercingetorix'],
      emoji: '🛡️🌲⚔️',
      group: 'Antiquité',
      tags: ['homme', 'gaulois', 'français', 'europe', 'antiquité', 'chef-militaire', 'emprisonné-ou-exilé', 'mort-avant-40-ans'],
      clues: ['Chef gaulois', 'Chef du peuple des Arvernes', 'Victoire contre Rome à Gergovie', 'Assiégé puis vaincu à Alésia', 'Se rend à Jules César en 52 av. J.-C.', 'Héros national gaulois'],
    },
    {
      name: 'Hannibal',
      aliases: ['Hannibal Barca'],
      emoji: '🐘🏔️⚔️',
      group: 'Antiquité',
      tags: ['homme', 'carthaginois', 'afrique', 'antiquité', 'chef-militaire', 'conquérant', 'emprisonné-ou-exilé'],
      clues: ['Général de Carthage', 'Ennemi juré de Rome', 'Traverse les Alpes avec des éléphants', 'Victoire à Cannes en 216 av. J.-C.', 'Héros des guerres puniques', 'Hannibal Barca'],
    },
    {
      name: 'Socrate',
      aliases: ['Socrates'],
      emoji: '🏛️🤔🍵',
      group: 'Antiquité',
      tags: ['homme', 'grec', 'europe', 'antiquité', 'philosophe', 'emprisonné-ou-exilé', 'professeur'],
      clues: ['Philosophe grec d’Athènes', 'N’a rien écrit lui-même', 'Maître de Platon', '« Je sais que je ne sais rien »', 'Condamné à boire la ciguë', 'Père de la philosophie occidentale'],
    },
    {
      name: 'Confucius',
      aliases: ['Kongzi', 'Kong Fuzi'],
      emoji: '📜🏯🧘',
      group: 'Antiquité',
      tags: ['homme', 'chinois', 'asie', 'antiquité', 'philosophe', 'professeur', 'politique'],
      clues: ['Penseur chinois de l’Antiquité', 'A vécu il y a environ 2 500 ans', 'Enseigne le respect des aînés et des rites', 'Ses paroles réunies dans les « Entretiens »', 'Sa pensée a marqué toute l’Asie de l’Est', 'Kongzi, « maître Kong »'],
    },
    // ── Moyen Âge ──
    {
      name: 'Charlemagne',
      aliases: ['Charles le Grand', 'Charles Ier'],
      emoji: '👑🧔🏫',
      group: 'Moyen Âge',
      tags: ['homme', 'franc', 'français', 'europe', 'moyen-âge', 'souverain', 'chef-militaire', 'conquérant', 'empereur'],
      clues: ['Roi des Francs', 'Couronné empereur en l’an 800', '« Barbe fleurie » selon la légende', 'Réputé avoir encouragé l’école', 'Capitale à Aix-la-Chapelle', 'Son nom veut dire Charles le Grand'],
    },
    {
      name: 'Jeanne d’Arc',
      aliases: ['Jeanne d\'Arc', 'Jeanne', 'La Pucelle', 'La Pucelle d’Orléans'],
      emoji: '⚔️🔥🇫🇷',
      group: 'Moyen Âge',
      tags: ['femme', 'français', 'europe', 'moyen-âge', 'chef-militaire', 'sainte', 'mort-avant-40-ans', 'emprisonné-ou-exilé'],
      clues: ['Jeune paysanne de Lorraine', 'Dit entendre des voix célestes', 'Libère Orléans en 1429', 'Fait sacrer Charles VII à Reims', 'Brûlée à Rouen en 1431', 'Surnommée la Pucelle d’Orléans'],
    },
    {
      name: 'Soundiata Keïta',
      aliases: ['Soundiata', 'Sundiata Keita', 'Soundiata Keita'],
      emoji: '🦁👑🌍',
      group: 'Moyen Âge',
      tags: ['homme', 'malien', 'afrique', 'moyen-âge', 'souverain', 'chef-militaire', 'conquérant'],
      clues: ['Fondateur de l’Empire du Mali', 'Enfant, il ne pouvait pas marcher selon l’épopée', 'Victoire de Kirina vers 1235', 'Associé à la Charte du Manden', 'Surnommé « le Lion du Manding »', 'Soundiata, héros d’une épopée des griots'],
    },
    {
      name: 'Mansa Moussa',
      aliases: ['Moussa', 'Kankou Moussa', 'Mansa Musa'],
      emoji: '👑💰🕌',
      group: 'Moyen Âge',
      tags: ['homme', 'malien', 'afrique', 'moyen-âge', 'souverain', 'empereur', 'bâtisseur', 'richesse'],
      clues: ['Empereur du Mali au XIVe siècle', 'Souvent présenté comme l’homme le plus riche de l’histoire', 'Pèlerinage à La Mecque en 1324', 'Distribue tant d’or que son cours chute au Caire', 'Fait bâtir une mosquée à Tombouctou', '« Mansa » est un titre signifiant roi'],
    },
    {
      name: 'Gengis Khan',
      aliases: ['Genghis Khan', 'Gengis'],
      emoji: '🐎🏹🏔️',
      group: 'Moyen Âge',
      tags: ['homme', 'mongol', 'asie', 'moyen-âge', 'souverain', 'chef-militaire', 'conquérant', 'empereur'],
      clues: ['Unificateur des tribus des steppes', 'Cavaliers archers redoutables', 'Né sous le nom de Temüjin', 'Fonde l’Empire mongol au XIIIe siècle', 'Plus vaste empire d’un seul tenant', 'Son titre signifie « souverain universel »'],
    },
    {
      name: 'Aliénor d’Aquitaine',
      aliases: ['Aliénor', 'Alienor d\'Aquitaine', 'Éléonore d’Aquitaine'],
      emoji: '👑🎶🏰',
      group: 'Moyen Âge',
      tags: ['femme', 'français', 'europe', 'moyen-âge', 'souverain', 'politique', 'emprisonné-ou-exilé'],
      clues: ['Duchesse d’un grand duché du Sud-Ouest', 'Reine de France puis d’Angleterre', 'Épouse Louis VII puis Henri II', 'Mère de Richard Cœur de Lion', 'Protectrice des troubadours', 'Aliénor, duchesse d’Aquitaine'],
    },
    {
      name: 'Marco Polo',
      aliases: ['Polo', 'Marco'],
      emoji: '🐫🧭🏯',
      group: 'Moyen Âge',
      tags: ['homme', 'italien', 'europe', 'moyen-âge', 'explorateur', 'écrivain', 'emprisonné-ou-exilé'],
      clues: ['Marchand vénitien', 'Voyage jusqu’en Chine', 'Reçu à la cour de Kubilai Khan', 'Parcourt la route de la soie', 'Récit « Le Devisement du monde »', 'Marco, voyageur légendaire'],
    },
    {
      name: 'Guillaume le Conquérant',
      aliases: ['Guillaume', 'Guillaume de Normandie'],
      emoji: '⛵⚔️🏰',
      group: 'Moyen Âge',
      tags: ['homme', 'normand', 'français', 'europe', 'moyen-âge', 'souverain', 'chef-militaire', 'conquérant', 'mer'],
      clues: ['Duc de Normandie', 'Traverse la Manche en 1066', 'Victoire à Hastings', 'Devient roi d’Angleterre', 'Son histoire est brodée sur la tapisserie de Bayeux', 'Guillaume, roi normand d’Angleterre'],
    },
    // ── Renaissance ──
    {
      name: 'Léonard de Vinci',
      aliases: ['Léonard', 'De Vinci', 'Leonardo da Vinci', 'Leonard de Vinci'],
      emoji: '🖼️🪽🔧',
      group: 'Renaissance',
      tags: ['homme', 'italien', 'europe', 'renaissance', 'artiste', 'peintre', 'inventeur', 'scientifique'],
      clues: ['Génie italien de la Renaissance', 'Peintre, ingénieur et inventeur', 'Écrivait en miroir', 'Peint « La Joconde »', 'Mort à Amboise, invité par François Ier', 'Léonard, auteur de « La Cène »'],
    },
    {
      name: 'Christophe Colomb',
      aliases: ['Colomb', 'Christophe', 'Cristoforo Colombo'],
      emoji: '⛵🌎🧭',
      group: 'Renaissance',
      tags: ['homme', 'italien', 'europe', 'renaissance', 'explorateur', 'emprisonné-ou-exilé', 'mer'],
      clues: ['Navigateur génois', 'Au service des Rois catholiques d’Espagne', 'Trois navires, dont la Santa María', 'Atteint les Amériques en 1492', 'Croyait être arrivé aux Indes', 'Christophe, découvreur du Nouveau Monde'],
    },
    {
      name: 'Michel-Ange',
      aliases: ['Michelangelo', 'Michel Ange'],
      emoji: '🗿🎨⛪',
      group: 'Renaissance',
      tags: ['homme', 'italien', 'europe', 'renaissance', 'artiste', 'peintre', 'bâtisseur', 'sculpteur'],
      clues: ['Artiste italien de la Renaissance', 'Sculpteur, peintre et architecte', 'Sculpte le célèbre « David »', 'Peint le plafond de la chapelle Sixtine', 'Rival de Léonard de Vinci', 'Michelangelo en italien'],
    },
    {
      name: 'Gutenberg',
      aliases: ['Johannes Gutenberg'],
      emoji: '📖🖨️🔠',
      group: 'Renaissance',
      tags: ['homme', 'allemand', 'europe', 'renaissance', 'inventeur', 'moyen-âge', 'artisan'],
      clues: ['Inventeur allemand du XVe siècle', 'Originaire de Mayence', 'Imprimerie à caractères mobiles', 'Bible imprimée vers 1455', 'Révolutionne la diffusion des livres', 'Johannes, père de l’imprimerie'],
    },
    {
      name: 'François Ier',
      aliases: ['François 1er', 'Francois Ier'],
      emoji: '👑🦎🏰',
      group: 'Renaissance',
      tags: ['homme', 'français', 'europe', 'renaissance', 'souverain', 'chef-militaire', 'bâtisseur'],
      clues: ['Roi de France de la Renaissance', 'Victoire de Marignan en 1515', 'Accueille Léonard de Vinci', 'Fait construire Chambord', 'Impose le français dans les actes officiels', 'Son emblème : la salamandre'],
    },
    {
      name: 'Galilée',
      aliases: ['Galileo Galilei', 'Galilee'],
      emoji: '🔭🪐☀️',
      group: 'Renaissance',
      tags: ['homme', 'italien', 'europe', 'renaissance', 'scientifique', 'inventeur', 'espace-astronomie', 'professeur', 'emprisonné-ou-exilé'],
      clues: ['Savant italien', 'Perfectionne la lunette astronomique', 'Découvre des lunes de Jupiter', 'Défend l’idée que la Terre tourne autour du Soleil', 'Condamné par l’Inquisition', '« Et pourtant elle tourne »'],
    },
    {
      name: 'William Shakespeare',
      aliases: ['Shakespeare', 'William'],
      emoji: '🎭💀🌹',
      group: 'Renaissance',
      tags: ['homme', 'britannique', 'europe', 'renaissance', 'écrivain', 'artiste', 'théâtre'],
      clues: ['Dramaturge anglais', 'Joué au théâtre du Globe à Londres', 'Auteur de « Roméo et Juliette »', '« Être ou ne pas être »', 'Auteur de « Hamlet »', 'William, le Barde'],
    },
    // ── XVIIe - XVIIIe siècles ──
    {
      name: 'Louis XIV',
      aliases: ['Roi-Soleil', 'Louis 14', 'Roi Soleil'],
      emoji: '☀️👑🏰',
      group: 'Temps modernes',
      tags: ['homme', 'français', 'europe', 'temps-modernes', 'souverain', 'politique', 'bâtisseur'],
      clues: ['Roi de France au très long règne', 'Monte sur le trône à 4 ans', 'Fait construire Versailles', 'Protège Molière et Lully', 'Surnommé le Roi-Soleil', '72 ans de règne, un record'],
    },
    {
      name: 'Molière',
      aliases: ['Moliere', 'Jean-Baptiste Poquelin'],
      emoji: '🎭😂🪶',
      group: 'Temps modernes',
      tags: ['homme', 'français', 'europe', 'temps-modernes', 'écrivain', 'artiste', 'théâtre'],
      clues: ['Dramaturge français du XVIIe siècle', 'Comédien et chef de troupe', 'Protégé de Louis XIV', 'Auteur du « Malade imaginaire »', 'Auteur de « L’Avare » et « Tartuffe »', 'Né Jean-Baptiste Poquelin'],
    },
    {
      name: 'Marie-Antoinette',
      aliases: ['Marie Antoinette'],
      emoji: '👑🍰💎',
      group: 'Temps modernes',
      tags: ['femme', 'autrichien', 'français', 'europe', 'temps-modernes', 'souverain', 'mort-avant-40-ans', 'emprisonné-ou-exilé', 'icône-de-style'],
      clues: ['Reine de France née à Vienne', 'Épouse de Louis XVI', 'Aimait son hameau à Versailles', 'Coiffures et robes très extravagantes', 'Guillotinée en 1793', 'Surnommée « l’Autrichienne »'],
    },
    {
      name: 'Mozart',
      aliases: ['Wolfgang Amadeus Mozart', 'Amadeus'],
      emoji: '🎹🎼🎻',
      group: 'Temps modernes',
      tags: ['homme', 'autrichien', 'europe', 'temps-modernes', 'artiste', 'musicien', 'mort-avant-40-ans'],
      clues: ['Compositeur autrichien', 'Enfant prodige dès 5 ans', 'Né à Salzbourg', 'Opéra « La Flûte enchantée »', '« Une petite musique de nuit »', 'Wolfgang Amadeus'],
    },
    {
      name: 'Isaac Newton',
      aliases: ['Newton', 'Isaac'],
      emoji: '🍎🌍🔭',
      group: 'Temps modernes',
      tags: ['homme', 'britannique', 'europe', 'temps-modernes', 'scientifique', 'inventeur', 'espace-astronomie', 'professeur'],
      clues: ['Savant anglais', 'Une pomme lui serait tombée dessus', 'Loi de la gravitation universelle', 'Décompose la lumière blanche', 'Une unité de force porte son nom', 'Isaac, physicien de génie'],
    },
    {
      name: 'Toussaint Louverture',
      aliases: ['Toussaint', 'Louverture'],
      emoji: '⛓️🇭🇹⚔️',
      group: 'Temps modernes',
      tags: ['homme', 'haïtien', 'amérique', 'temps-modernes', 'chef-militaire', 'politique', 'militant', 'emprisonné-ou-exilé'],
      clues: ['Ancien esclave devenu général', 'Chef de la révolution à Saint-Domingue', 'Ouvre la voie à l’indépendance d’Haïti', 'Arrêté sur ordre de Napoléon', 'Mort au fort de Joux, dans le Jura', 'Surnommé le « Spartacus noir »'],
    },
    {
      name: 'Voltaire',
      aliases: ['François-Marie Arouet'],
      emoji: '🪶📚⚖️',
      group: 'Temps modernes',
      tags: ['homme', 'français', 'europe', 'temps-modernes', 'philosophe', 'écrivain', 'panthéon', 'militant', 'emprisonné-ou-exilé', 'théâtre'],
      clues: ['Philosophe des Lumières', 'Plume ironique et mordante', 'Auteur du conte « Candide »', 'Défenseur de la tolérance', 'A vécu à Ferney, près de Genève', 'Né François-Marie Arouet'],
    },
    {
      name: 'Reine Nzinga',
      aliases: ['Nzinga', 'Njinga', 'Anne Nzinga'],
      emoji: '👑🛡️🌍',
      group: 'Temps modernes',
      tags: ['femme', 'angolais', 'afrique', 'temps-modernes', 'souverain', 'chef-militaire', 'politique'],
      clues: ['Reine d’Afrique centrale au XVIIe siècle', 'Règne sur le Ndongo et le Matamba', 'Résiste aux colons portugais', 'Diplomate redoutable', 'Figure nationale de l’Angola', 'Njinga Mbandé'],
    },
    // ── XIXe siècle ──
    {
      name: 'Napoléon Bonaparte',
      aliases: ['Napoléon', 'Bonaparte', 'Napoléon Ier', 'Napoleon'],
      emoji: '🎩🐎🇫🇷',
      group: 'XIXe siècle',
      tags: ['homme', 'français', 'europe', 'xixe-siècle', 'souverain', 'chef-militaire', 'conquérant', 'politique', 'emprisonné-ou-exilé', 'empereur'],
      clues: ['Général corse devenu empereur', 'Main glissée dans son gilet', 'Sacré à Notre-Dame en 1804', 'Crée le Code civil', 'Battu à Waterloo en 1815', 'Exilé à Sainte-Hélène'],
    },
    {
      name: 'Victor Hugo',
      aliases: ['Hugo', 'Victor'],
      emoji: '📚🔔🧔',
      group: 'XIXe siècle',
      tags: ['homme', 'français', 'europe', 'xixe-siècle', 'écrivain', 'politique', 'panthéon', 'militant', 'emprisonné-ou-exilé', 'théâtre'],
      clues: ['Écrivain français du XIXe siècle', 'Exilé à Guernesey', 'Auteur des « Misérables »', 'Auteur de « Notre-Dame de Paris »', 'Repose au Panthéon', 'Victor, père de Cosette et Quasimodo'],
    },
    {
      name: 'Louis Pasteur',
      aliases: ['Pasteur'],
      emoji: '🔬💉🥛',
      group: 'XIXe siècle',
      tags: ['homme', 'français', 'europe', 'xixe-siècle', 'scientifique', 'inventeur', 'professeur', 'médecine'],
      clues: ['Scientifique français', 'Travaux sur les microbes', 'Méthode de conservation des aliments', 'Vaccin contre la rage en 1885', 'Un institut parisien porte son nom', 'Louis, et la pasteurisation'],
    },
    {
      name: 'Abraham Lincoln',
      aliases: ['Lincoln', 'Abe'],
      emoji: '🎩🇺🇸⛓️',
      group: 'XIXe siècle',
      tags: ['homme', 'américain', 'amérique', 'xixe-siècle', 'politique', 'assassiné', 'militant'],
      clues: ['Président américain', 'Chapeau haut-de-forme et barbe', 'Dirige le pays pendant la guerre de Sécession', 'Abolit l’esclavage', 'Discours de Gettysburg', 'Abe, assassiné au théâtre en 1865'],
    },
    {
      name: 'Jules Verne',
      aliases: ['Verne', 'Jules'],
      emoji: '🐙🎈🌍',
      group: 'XIXe siècle',
      tags: ['homme', 'français', 'europe', 'xixe-siècle', 'écrivain', 'science-fiction', 'aventure'],
      clues: ['Écrivain français d’aventures', 'Né à Nantes', 'Imagine des sous-marins et des voyages lunaires', 'Auteur de « Vingt Mille Lieues sous les mers »', '« Le Tour du monde en 80 jours »', 'Jules, créateur du capitaine Nemo'],
    },
    {
      name: 'Charles Darwin',
      aliases: ['Darwin'],
      emoji: '🐢🐒🌿',
      group: 'XIXe siècle',
      tags: ['homme', 'britannique', 'europe', 'xixe-siècle', 'scientifique', 'explorateur', 'mer'],
      clues: ['Naturaliste anglais', 'Voyage autour du monde à bord du Beagle', 'Étudie les pinsons des Galápagos', 'Théorie de l’évolution des espèces', '« De l’origine des espèces »', 'Charles, barbe blanche célèbre'],
    },
    {
      name: 'Vincent van Gogh',
      aliases: ['Van Gogh', 'Vincent'],
      emoji: '🌻🌌👂',
      group: 'XIXe siècle',
      tags: ['homme', 'néerlandais', 'europe', 'xixe-siècle', 'artiste', 'peintre', 'mort-avant-40-ans'],
      clues: ['Peintre néerlandais', 'Couleurs vives et touches épaisses', 'S’est coupé une partie de l’oreille', 'Peint « La Nuit étoilée »', 'Série des « Tournesols »', 'Vincent, frère de Théo'],
    },
    {
      name: 'Gustave Eiffel',
      aliases: ['Eiffel', 'Gustave'],
      emoji: '🗼🔩🗽',
      group: 'XIXe siècle',
      tags: ['homme', 'français', 'europe', 'xixe-siècle', 'inventeur', 'scientifique', 'bâtisseur'],
      clues: ['Ingénieur français', 'Spécialiste des structures métalliques', 'Charpente interne de la statue de la Liberté', 'Construit pour l’Exposition universelle de 1889', 'Symbole de Paris qui porte son nom', 'Gustave, le roi du fer'],
    },
    // ── XXe siècle ──
    {
      name: 'Marie Curie',
      aliases: ['Curie', 'Marie Skłodowska-Curie'],
      emoji: '⚗️☢️🏅',
      group: 'XXe siècle',
      tags: ['femme', 'polonais', 'français', 'europe', 'xxe-siècle', 'scientifique', 'prix-nobel', 'panthéon'],
      clues: ['Scientifique née à Varsovie', 'Travaux pionniers sur la radioactivité', 'Découvre le polonium et le radium', 'Deux prix Nobel, en physique et chimie', 'Première femme professeure à la Sorbonne', 'Marie, épouse de Pierre'],
    },
    {
      name: 'Albert Einstein',
      aliases: ['Einstein', 'Albert'],
      emoji: '🧠⚛️👅',
      group: 'XXe siècle',
      tags: ['homme', 'allemand', 'europe', 'xxe-siècle', 'scientifique', 'prix-nobel', 'espace-astronomie', 'professeur', 'emprisonné-ou-exilé'],
      clues: ['Physicien né en Allemagne', 'Cheveux ébouriffés, langue tirée en photo', 'Théorie de la relativité', 'Formule E = mc²', 'Prix Nobel de physique 1921', 'Albert, synonyme de génie'],
    },
    {
      name: 'Gandhi',
      aliases: ['Mahatma Gandhi', 'Mohandas Gandhi'],
      emoji: '🕊️🧵🇮🇳',
      group: 'XXe siècle',
      tags: ['homme', 'indien', 'asie', 'xxe-siècle', 'politique', 'militant', 'assassiné', 'emprisonné-ou-exilé'],
      clues: ['Leader de l’indépendance indienne', 'Prône la non-violence', 'Tisse lui-même ses vêtements', 'Marche du sel en 1930', 'Surnommé « Mahatma », grande âme', 'Assassiné en 1948'],
    },
    {
      name: 'Nelson Mandela',
      aliases: ['Mandela', 'Madiba'],
      emoji: '✊🇿🇦🕊️',
      group: 'XXe siècle',
      tags: ['homme', 'sud-africain', 'afrique', 'xxe-siècle', 'politique', 'militant', 'prix-nobel', 'emprisonné-ou-exilé'],
      clues: ['Leader sud-africain', 'Lutte contre l’apartheid', '27 ans passés en prison', 'Prix Nobel de la paix 1993', 'Premier président noir de son pays', 'Surnommé Madiba'],
    },
    {
      name: 'Martin Luther King',
      aliases: ['MLK', 'Martin Luther King Jr'],
      emoji: '✊🎤🇺🇸',
      group: 'XXe siècle',
      tags: ['homme', 'américain', 'amérique', 'xxe-siècle', 'militant', 'prix-nobel', 'assassiné', 'emprisonné-ou-exilé', 'mort-avant-40-ans'],
      clues: ['Pasteur américain', 'Figure du mouvement des droits civiques', 'Prône la non-violence', 'Discours « I have a dream »', 'Prix Nobel de la paix 1964', 'Initiales MLK'],
    },
    {
      name: 'Frida Kahlo',
      aliases: ['Frida', 'Kahlo'],
      emoji: '🌺🎨🇲🇽',
      group: 'XXe siècle',
      tags: ['femme', 'mexicain', 'amérique', 'xxe-siècle', 'artiste', 'peintre', 'icône-de-style'],
      clues: ['Peintre mexicaine', 'Nombreux autoportraits colorés', 'Sourcils joints emblématiques', 'Épouse du muraliste Diego Rivera', 'Maison bleue à Coyoacán', 'Frida, fleurs dans les cheveux'],
    },
    {
      name: 'Neil Armstrong',
      aliases: ['Armstrong', 'Neil'],
      emoji: '🚀🌕👨‍🚀',
      group: 'XXe siècle',
      tags: ['homme', 'américain', 'amérique', 'xxe-siècle', 'explorateur', 'astronaute', 'espace-astronomie'],
      clues: ['Astronaute américain', 'Ancien pilote d’essai', 'Commandant de la mission Apollo 11', 'Premier homme à marcher sur la Lune', '« Un petit pas pour l’homme… »', 'Neil, en juillet 1969'],
    },
    {
      name: 'Charles de Gaulle',
      aliases: ['De Gaulle', 'Général de Gaulle', 'le Général'],
      emoji: '🎖️📻🇫🇷',
      group: 'XXe siècle',
      tags: ['homme', 'français', 'europe', 'xxe-siècle', 'politique', 'chef-militaire', 'écrivain'],
      clues: ['Militaire et homme d’État français', 'Appel du 18 juin 1940 depuis Londres', 'Chef de la France libre', 'Fondateur de la Ve République', 'Président de 1959 à 1969', 'Surnommé « le Général »'],
    },
    {
      name: 'Rosa Parks',
      aliases: ['Parks', 'Rosa'],
      emoji: '🚌✊🇺🇸',
      group: 'XXe siècle',
      tags: ['femme', 'américain', 'amérique', 'xxe-siècle', 'militant', 'emprisonné-ou-exilé', 'couturière'],
      clues: ['Militante américaine', 'Couturière de métier', 'Refuse de céder sa place dans un bus', 'Montgomery, Alabama, en 1955', 'Surnommée « mère des droits civiques »', 'Rosa, symbole de la résistance pacifique'],
    },
    {
      name: 'Simone Veil',
      aliases: ['Veil', 'Simone'],
      emoji: '⚖️🇪🇺🕊️',
      group: 'XXe siècle',
      tags: ['femme', 'français', 'europe', 'xxe-siècle', 'politique', 'militant', 'panthéon'],
      clues: ['Femme politique française', 'Rescapée d’Auschwitz', 'Loi sur l’IVG en 1975', 'Première présidente du Parlement européen élu', 'Entre au Panthéon en 2018', 'Simone, académicienne'],
    },
    {
      name: 'Pablo Picasso',
      aliases: ['Picasso', 'Pablo'],
      emoji: '🎨🟦🐂',
      group: 'XXe siècle',
      tags: ['homme', 'espagnol', 'europe', 'xxe-siècle', 'artiste', 'peintre', 'sculpteur', 'cubisme'],
      clues: ['Peintre espagnol', 'A vécu longtemps en France', 'Cofondateur du cubisme', 'Périodes bleue et rose', 'Peint « Guernica »', 'Pablo, « Les Demoiselles d’Avignon »'],
    },
    {
      name: 'Youri Gagarine',
      aliases: ['Gagarine', 'Youri', 'Yuri Gagarin'],
      emoji: '🚀🌍⭐',
      group: 'XXe siècle',
      tags: ['homme', 'russe', 'europe', 'xxe-siècle', 'explorateur', 'astronaute', 'espace-astronomie', 'mort-avant-40-ans'],
      clues: ['Cosmonaute soviétique', 'Ancien pilote de chasse', 'Vaisseau Vostok 1 en 1961', 'Premier être humain dans l’espace', 'Un tour de la Terre en 108 minutes', 'Youri, héros de l’URSS'],
    },
    {
      name: 'Joséphine Baker',
      aliases: ['Baker', 'Joséphine', 'Josephine Baker'],
      emoji: '💃🍌🎖️',
      group: 'XXe siècle',
      tags: ['femme', 'américain', 'français', 'amérique', 'xxe-siècle', 'artiste', 'musicien', 'militant', 'panthéon', 'icône-de-style'],
      clues: ['Artiste née aux États-Unis', 'Meneuse de revue à Paris', 'Célèbre ceinture de bananes', 'Résistante pendant la guerre', 'Entre au Panthéon en 2021', '« J’ai deux amours »'],
    },
  ],
};
