import type { Pack } from '../types';

export const pack: Pack = {
  id: 'marques',
  name: 'Marques',
  emoji: '🏷️',
  category: 'marques',
  description: 'Les marques que tout le monde connaît : tech, sport, mode, bouffe et jeux.',
  attributes: [
    { tag: 'américain', question: 'Est-ce une marque américaine ?' },
    { tag: 'japonais', question: 'Est-ce une marque japonaise ?' },
    { tag: 'européen', question: 'Est-ce une marque européenne ?' },
    { tag: 'français', question: 'Est-ce une marque française ?' },
    { tag: 'allemand', question: 'Est-ce une marque allemande ?' },
    { tag: 'asiatique', question: 'Est-ce une marque asiatique ?' },
    { tag: 'sport', question: 'Est-ce lié au sport ?' },
    { tag: 'tech', question: 'Est-ce une marque de technologie ?' },
    { tag: 'vêtements', question: 'Vend-elle des vêtements ?' },
    { tag: 'chaussures', question: 'Vend-elle des chaussures ?' },
    { tag: 'nourriture', question: 'Vend-elle de la nourriture ?' },
    { tag: 'boisson', question: 'Vend-elle des boissons ?' },
    { tag: 'fast-food', question: 'Est-ce une chaîne de restauration rapide ?' },
    { tag: 'jeux-vidéo', question: 'Est-ce lié aux jeux vidéo ?' },
    { tag: 'streaming', question: 'Est-ce un service de streaming ?' },
    { tag: 'réseau-social', question: 'Est-ce un réseau social ?' },
    { tag: 'application', question: 'Est-ce surtout une application ?' },
    { tag: 'voiture', question: 'Fabrique-t-elle des voitures ?' },
    { tag: 'luxe', question: 'Est-ce une marque de luxe ?' },
    { tag: 'enfants', question: 'Est-ce très apprécié des enfants ?' },
    { tag: 'rouge', question: 'Son logo est-il rouge ?' },
    { tag: 'noir', question: 'Son logo est-il noir ?' },
    { tag: 'bleu', question: 'Son logo est-il bleu ?' },
    { tag: 'jaune', question: 'Son logo contient-il du jaune ?' },
    { tag: 'logo-animal', question: 'Son logo représente-t-il un animal ?' },
    { tag: 'logo-lettre', question: 'Son logo est-il une lettre ou des initiales ?' },
    { tag: 'téléphone', question: 'Fabrique-t-elle des téléphones ?' },
    { tag: 'vidéo', question: 'Est-ce lié aux vidéos ?' },
    { tag: 'musique', question: 'Est-ce lié à la musique ?' },
    { tag: 'sucré', question: 'Vend-elle des produits sucrés ?' },
    { tag: 'ancien', question: 'La marque a-t-elle plus de 50 ans ?' },
    { tag: 'en-ligne', question: 'L\'utilise-t-on surtout en ligne ?' },
    { tag: 'abonnement', question: 'Paye-t-on souvent un abonnement ?' },
    { tag: 'magasins', question: 'A-t-elle des magasins ou restaurants physiques partout ?' },
    { tag: 'gratuit', question: 'Peut-on l\'utiliser gratuitement ?' },
  ],
  items: [
    // ——— Sport ———
    { name: 'Nike', emoji: '👟✔️🏀', group: 'Sport', tags: ['américain', 'sport', 'vêtements', 'chaussures', 'noir', 'magasins', 'ancien'], clues: ['Marque de sport', 'Porte le nom d\'une déesse grecque', 'Slogan « Just Do It »', 'Chaussures Air Jordan et Air Max', 'Logo en forme de virgule'] },
    { name: 'Adidas', emoji: '👟⚽🔺', group: 'Sport', tags: ['allemand', 'européen', 'sport', 'vêtements', 'chaussures', 'noir', 'ancien', 'magasins'], clues: ['Marque de sport', 'Fondée par Adi Dassler', 'Survêtements iconiques', 'Chaussures Stan Smith et Superstar', 'Trois bandes'] },
    { name: 'Puma', emoji: '🐆👟⚽', group: 'Sport', tags: ['allemand', 'européen', 'sport', 'vêtements', 'chaussures', 'noir', 'logo-animal', 'ancien'], clues: ['Marque de sport allemande', 'Fondée par le frère d\'un concurrent', 'Portée par Usain Bolt', 'Baskets Suede', 'Logo d\'un félin qui bondit'] },
    { name: 'Converse', emoji: '👟⭐🎸', group: 'Sport', tags: ['américain', 'chaussures', 'vêtements', 'noir', 'ancien', 'sport', 'magasins'], clues: ['Marque de chaussures', 'Plus de cent ans d\'histoire', 'Montantes en toile', 'Bout blanc en caoutchouc', 'Modèle Chuck Taylor All Star'] },
    { name: 'Lacoste', emoji: '🐊🎾👕', group: 'Mode', tags: ['français', 'européen', 'vêtements', 'sport', 'logo-animal', 'luxe', 'ancien', 'chaussures', 'magasins'], clues: ['Marque de mode française', 'Créée par un joueur de tennis', 'Polos célèbres', 'Survêtements très populaires', 'Logo : un crocodile vert'] },
    // ——— Tech ———
    { name: 'Apple', emoji: '🍎📱💻', group: 'Tech', tags: ['américain', 'tech', 'téléphone', 'noir', 'luxe', 'musique', 'magasins', 'abonnement'], clues: ['Géant de la tech', 'Fondée dans un garage', 'Steve Jobs', 'iPhone, iPad, Mac', 'Logo : un fruit croqué'] },
    { name: 'Samsung', emoji: '📱📺🇰🇷', group: 'Tech', tags: ['asiatique', 'tech', 'téléphone', 'bleu', 'ancien', 'magasins', 'vidéo'], clues: ['Géant de la tech', 'Entreprise coréenne', 'Télés et frigos aussi', 'Téléphones pliables', 'Smartphones Galaxy'] },
    { name: 'Google', emoji: '🔍🌈🌐', group: 'Tech', tags: ['américain', 'tech', 'en-ligne', 'gratuit', 'téléphone', 'application', 'bleu', 'rouge', 'jaune'], clues: ['Géant d\'Internet', 'Logo multicolore', 'Son nom est devenu un verbe', 'Maps, Gmail, Chrome', 'Moteur de recherche n°1'] },
    { name: 'Microsoft', emoji: '🪟💻🎮', group: 'Tech', tags: ['américain', 'tech', 'jeux-vidéo', 'ancien', 'abonnement', 'bleu', 'rouge', 'jaune'], clues: ['Géant de la tech', 'Fondée par Bill Gates', 'Word, Excel, PowerPoint', 'Possède la Xbox', 'Système Windows'] },
    { name: 'Sony', emoji: '🎮📺🎧', group: 'Tech', tags: ['japonais', 'asiatique', 'tech', 'jeux-vidéo', 'musique', 'ancien', 'noir', 'vidéo'], clues: ['Géant japonais de l\'électronique', 'Walkman dans les années 80', 'Casques audio et appareils photo', 'Studios de cinéma et de musique', 'Fabrique la PlayStation'] },
    { name: 'Xiaomi', emoji: '📱🛴🇨🇳', group: 'Tech', tags: ['asiatique', 'tech', 'téléphone', 'magasins', 'rouge', 'en-ligne', 'voiture'], clues: ['Marque de tech chinoise', 'Réputée pour ses bons prix', 'Trottinettes électriques', 'Logo orange carré', 'Smartphones Redmi'] },
    { name: 'Tesla', emoji: '🚗⚡🔋', group: 'Automobile', tags: ['américain', 'voiture', 'tech', 'rouge', 'luxe', 'logo-lettre', 'en-ligne'], clues: ['Constructeur récent', 'Voitures 100 % électriques', 'Pilote automatique', 'Dirigée par Elon Musk', 'Logo en forme de T'] },
    // ——— Boissons ———
    { name: 'Coca-Cola', aliases: ['Coca'], emoji: '🥤🔴🧊', group: 'Boissons', tags: ['américain', 'boisson', 'sucré', 'rouge', 'ancien', 'magasins', 'sport'], clues: ['Boisson la plus connue du monde', 'Recette secrète', 'Pub de Noël avec le père Noël', 'Bouteille à la forme reconnaissable', 'Logo rouge et blanc en lettres attachées'] },
    { name: 'Pepsi', emoji: '🥤🔵🔴', group: 'Boissons', tags: ['américain', 'boisson', 'sucré', 'bleu', 'rouge', 'ancien', 'sport'], clues: ['Soda américain', 'Éternel rival d\'un autre cola', 'Pubs avec des stars du foot', 'Canette bleue', 'Logo rond rouge, blanc et bleu'] },
    { name: 'Red Bull', emoji: '🐂🥤🏎️', group: 'Boissons', tags: ['européen', 'boisson', 'sucré', 'sport', 'logo-animal', 'rouge', 'bleu', 'jeux-vidéo'], clues: ['Boisson énergisante', 'Marque autrichienne', 'Sponsor de sports extrêmes', 'Écurie de Formule 1', '« Donne des ailes »'] },
    { name: 'Fanta', emoji: '🍊🥤🫧', group: 'Boissons', tags: ['américain', 'boisson', 'sucré', 'jaune', 'bleu', 'ancien', 'enfants'], clues: ['Soda fruité', 'Créé en Allemagne pendant la guerre', 'Appartient à un géant du cola', 'Couleur orange vif', 'Goût orange pétillant'] },
    { name: 'Starbucks', emoji: '☕🧜‍♀️🥤', group: 'Boissons', tags: ['américain', 'boisson', 'sucré', 'magasins', 'fast-food', 'nourriture', 'ancien'], clues: ['Chaîne de cafés', 'Écrivent ton prénom sur le gobelet', 'Frappuccino', 'Logo vert avec une sirène', 'Née à Seattle'] },
    // ——— Fast-food ———
    { name: 'McDonald\'s', aliases: ['McDo', 'Macdo'], emoji: '🍔🍟🤡', group: 'Fast-food', tags: ['américain', 'fast-food', 'nourriture', 'jaune', 'rouge', 'magasins', 'enfants', 'logo-lettre', 'ancien'], clues: ['Plus grande chaîne de fast-food', 'Mascotte clown Ronald', 'Happy Meal', 'Big Mac', 'Grand M jaune'] },
    { name: 'KFC', emoji: '🍗🪣👴', group: 'Fast-food', tags: ['américain', 'fast-food', 'nourriture', 'rouge', 'magasins', 'logo-lettre', 'ancien'], clues: ['Chaîne de fast-food', 'Recette aux 11 épices', 'Seaux à partager', 'Un colonel sur le logo', 'Spécialiste du poulet frit'] },
    { name: 'Burger King', emoji: '👑🍔🔥', group: 'Fast-food', tags: ['américain', 'fast-food', 'nourriture', 'rouge', 'bleu', 'jaune', 'magasins', 'ancien'], clues: ['Chaîne de fast-food', 'Viande grillée à la flamme', 'Couronnes en carton', 'Sandwich Whopper', 'Concurrent direct du M jaune'] },
    { name: 'Subway', emoji: '🥖🥬🚇', group: 'Fast-food', tags: ['américain', 'fast-food', 'nourriture', 'jaune', 'magasins', 'ancien', 'logo-lettre'], clues: ['Chaîne de restauration rapide', 'On compose soi-même', 'Pain de 15 ou 30 cm', 'Logo vert et jaune', 'Sandwichs sur mesure'] },
    { name: 'Domino\'s', aliases: ['Domino\'s Pizza'], emoji: '🍕🛵🎲', group: 'Fast-food', tags: ['américain', 'fast-food', 'nourriture', 'bleu', 'rouge', 'magasins', 'en-ligne'], clues: ['Chaîne de livraison', 'Suivi de commande en direct', 'Offres « 1 achetée = 1 offerte »', 'Logo en forme de pièce de jeu', 'Spécialiste de la pizza'] },
    // ——— Alimentation ———
    { name: 'Nutella', emoji: '🍫🥜🥖', group: 'Alimentation', tags: ['italien', 'européen', 'nourriture', 'sucré', 'enfants', 'noir', 'rouge', 'ancien'], clues: ['Pâte à tartiner', 'Marque italienne', 'Noisettes et cacao', 'Sur les crêpes', 'Pot en verre à couvercle blanc'] },
    { name: 'Haribo', emoji: '🐻🍬🌈', group: 'Alimentation', tags: ['allemand', 'européen', 'nourriture', 'sucré', 'enfants', 'rouge', 'jaune', 'ancien', 'logo-animal'], clues: ['Confiseur allemand', 'Slogan « C\'est beau la vie »', 'Fraises Tagada', 'Nounours dorés', 'Bonbons gélifiés'] },
    { name: 'Kinder', emoji: '🥚🍫🎁', group: 'Alimentation', tags: ['italien', 'européen', 'nourriture', 'sucré', 'enfants', 'rouge', 'ancien'], clues: ['Marque de chocolat pour enfants', 'Son nom veut dire « enfants » en allemand', 'Bueno et Country', 'Jouet caché dedans', 'Œuf Surprise'] },
    // ——— Jeux vidéo ———
    { name: 'PlayStation', aliases: ['PS5', 'Play'], emoji: '🎮🔺⭕', group: 'Jeux vidéo', tags: ['japonais', 'asiatique', 'jeux-vidéo', 'tech', 'bleu', 'noir', 'abonnement', 'enfants'], clues: ['Console de jeux', 'Manette DualSense', 'Symboles triangle, rond, croix, carré', 'God of War et Spider-Man', 'Fabriquée par Sony'] },
    { name: 'Nintendo', emoji: '🎮🍄⭐', group: 'Jeux vidéo', tags: ['japonais', 'asiatique', 'jeux-vidéo', 'tech', 'rouge', 'enfants', 'ancien', 'abonnement'], clues: ['Entreprise de jeux vidéo', 'A commencé avec des cartes à jouer', 'Game Boy et Wii', 'Console Switch', 'Mario et Zelda'] },
    { name: 'Xbox', emoji: '🎮💚❎', group: 'Jeux vidéo', tags: ['américain', 'jeux-vidéo', 'tech', 'abonnement', 'noir', 'logo-lettre', 'enfants'], clues: ['Console de jeux', 'Couleur verte', 'Game Pass', 'Halo et Forza', 'Console de Microsoft'] },
    { name: 'Pokémon', emoji: '⚡🐭🔴', group: 'Jeux vidéo', tags: ['japonais', 'asiatique', 'jeux-vidéo', 'enfants', 'jaune', 'rouge', 'logo-animal', 'vidéo'], clues: ['Franchise japonaise', 'Jeux, cartes et dessins animés', '« Attrapez-les tous »', 'Pokéballs rouges et blanches', 'Pikachu'] },
    { name: 'Fortnite', emoji: '🎮🪂🏗️', group: 'Jeux vidéo', tags: ['américain', 'jeux-vidéo', 'gratuit', 'en-ligne', 'enfants', 'bleu', 'noir'], clues: ['Jeu vidéo gratuit', 'Battle royale à 100 joueurs', 'Danses célèbres', 'On construit des murs', 'Édité par Epic Games'] },
    // ——— Streaming & réseaux ———
    { name: 'Netflix', emoji: '🎬🍿🔴', group: 'Streaming', tags: ['américain', 'streaming', 'vidéo', 'abonnement', 'en-ligne', 'rouge', 'noir', 'logo-lettre', 'application'], clues: ['Plateforme de streaming', 'Au départ, location de DVD', 'Stranger Things et Squid Game', 'Son « tudum »', 'Grand N rouge'] },
    { name: 'Disney', aliases: ['Disney+'], emoji: '🏰🐭✨', group: 'Streaming', tags: ['américain', 'streaming', 'vidéo', 'enfants', 'abonnement', 'ancien', 'bleu', 'magasins'], clues: ['Empire du divertissement', 'Parcs d\'attractions', 'Possède Marvel et Star Wars', 'Château sur le logo', 'Mickey Mouse'] },
    { name: 'YouTube', emoji: '▶️📹🔴', group: 'Streaming', tags: ['américain', 'vidéo', 'streaming', 'réseau-social', 'gratuit', 'en-ligne', 'rouge', 'application', 'musique'], clues: ['Plateforme de vidéos', 'Appartient à Google', 'Créateurs et abonnés', 'Pubs avant les vidéos', 'Bouton lecture rouge'] },
    { name: 'Twitch', emoji: '🟣🎮🔴', group: 'Streaming', tags: ['américain', 'streaming', 'vidéo', 'jeux-vidéo', 'gratuit', 'en-ligne', 'application', 'abonnement'], clues: ['Plateforme de lives', 'Couleur violette', 'Chat en direct', 'Subs et dons', 'Gamers qui streament'] },
    { name: 'Spotify', emoji: '🎧🟢🎶', group: 'Streaming', tags: ['européen', 'musique', 'streaming', 'abonnement', 'gratuit', 'en-ligne', 'application', 'noir'], clues: ['Appli de streaming', 'Entreprise suédoise', 'Playlists et podcasts', 'Bilan de fin d\'année « Wrapped »', 'Logo vert à trois ondes'] },
    { name: 'TikTok', emoji: '🎵📱🕺', group: 'Réseaux sociaux', tags: ['asiatique', 'réseau-social', 'vidéo', 'gratuit', 'en-ligne', 'application', 'musique', 'noir'], clues: ['Réseau social récent', 'Entreprise chinoise', 'Danses et challenges', 'Page « Pour toi »', 'Vidéos courtes verticales'] },
    { name: 'Instagram', aliases: ['Insta'], emoji: '📸💗🤳', group: 'Réseaux sociaux', tags: ['américain', 'réseau-social', 'gratuit', 'en-ligne', 'application', 'vidéo', 'jaune'], clues: ['Réseau social', 'Appartient à Meta', 'Stories et Reels', 'Likes en forme de cœur', 'Logo appareil photo dégradé'] },
    { name: 'Snapchat', emoji: '👻💛📸', group: 'Réseaux sociaux', tags: ['américain', 'réseau-social', 'gratuit', 'en-ligne', 'application', 'jaune', 'vidéo'], clues: ['Réseau social', 'Messages qui disparaissent', 'Flammes des séries', 'Filtres rigolos', 'Petit fantôme sur fond jaune'] },
    { name: 'WhatsApp', emoji: '💬📞🟢', group: 'Réseaux sociaux', tags: ['vidéo', 'américain', 'réseau-social', 'gratuit', 'en-ligne', 'application', 'téléphone'], clues: ['Messagerie', 'Groupes de famille', 'Deux coches bleues', 'Appels gratuits', 'Bulle verte avec téléphone'] },
    { name: 'Discord', emoji: '🎧👾💬', group: 'Réseaux sociaux', tags: ['américain', 'réseau-social', 'gratuit', 'en-ligne', 'application', 'jeux-vidéo', 'bleu', 'abonnement'], clues: ['Messagerie de gamers', 'Serveurs et salons vocaux', 'Abonnement Nitro', 'Mascotte manette violette', 'Logo bleu-violet'] },
    // ——— Commerce ———
    { name: 'Amazon', emoji: '📦🚚😊', group: 'Commerce', tags: ['américain', 'en-ligne', 'tech', 'abonnement', 'streaming', 'noir', 'jaune', 'application'], clues: ['Géant du commerce en ligne', 'Fondé par Jeff Bezos', 'Livraison en un jour', 'Abonnement Prime', 'Flèche en forme de sourire'] },
    { name: 'IKEA', emoji: '🪑🔧🇸🇪', group: 'Commerce', tags: ['européen', 'magasins', 'nourriture', 'bleu', 'jaune', 'ancien', 'logo-lettre'], clues: ['Magasin de meubles', 'Entreprise suédoise', 'Meubles en kit à monter', 'Boulettes de viande au resto', 'Logo bleu et jaune'] },
    { name: 'Uber', emoji: '🚗📱🍔', group: 'Commerce', tags: ['américain', 'application', 'en-ligne', 'voiture', 'nourriture', 'noir', 'téléphone'], clues: ['Application de transport', 'Chauffeurs privés', 'Note de 1 à 5 étoiles', 'Livraison de repas aussi', 'Concurrent des taxis'] },
    // ——— Automobile ———
    { name: 'Ferrari', emoji: '🏎️🐎🔴', group: 'Automobile', tags: ['italien', 'européen', 'voiture', 'luxe', 'rouge', 'jaune', 'logo-animal', 'sport', 'ancien'], clues: ['Constructeur italien', 'Voitures de sport très chères', 'Écurie de Formule 1 légendaire', 'Couleur rouge emblématique', 'Cheval cabré sur fond jaune'] },
    { name: 'Mercedes', aliases: ['Mercedes-Benz'], emoji: '🚗⭐🇩🇪', group: 'Automobile', tags: ['allemand', 'européen', 'voiture', 'luxe', 'noir', 'sport', 'ancien'], clues: ['Constructeur allemand', 'Voitures haut de gamme', 'Écurie de F1 de Lewis Hamilton', 'Classe A, Classe G', 'Étoile à trois branches'] },
    { name: 'BMW', emoji: '🚗🔵⚪', group: 'Automobile', tags: ['allemand', 'européen', 'voiture', 'luxe', 'bleu', 'logo-lettre', 'ancien'], clues: ['Constructeur allemand', 'Né en Bavière', 'Motos aussi', 'Modèles Série 1, M3…', 'Logo rond bleu et blanc'] },
    { name: 'Renault', emoji: '🚗💎🇫🇷', group: 'Automobile', tags: ['français', 'européen', 'voiture', 'jaune', 'ancien', 'sport', 'magasins'], clues: ['Constructeur français', 'Fondé par trois frères', 'Clio et Twingo', 'Mégane et Captur', 'Logo en losange'] },
    { name: 'Peugeot', emoji: '🚗🦁🇫🇷', group: 'Automobile', tags: ['français', 'européen', 'voiture', 'logo-animal', 'ancien', 'bleu', 'sport'], clues: ['Constructeur français', 'Fabriquait des moulins à poivre', 'Modèles 208, 308, 3008', 'Rallye Dakar', 'Logo : un lion'] },
    { name: 'Toyota', emoji: '🚗🇯🇵🔧', group: 'Automobile', tags: ['japonais', 'asiatique', 'voiture', 'rouge', 'ancien', 'sport', 'logo-lettre'], clues: ['Constructeur japonais', 'Plus gros vendeur au monde', 'Réputé très fiable', 'Corolla, Yaris, Prius', 'Logo : trois ellipses'] },
    // ——— Mode & Luxe ———
    { name: 'Louis Vuitton', aliases: ['LV'], emoji: '👜💰🇫🇷', group: 'Mode', tags: ['français', 'européen', 'luxe', 'vêtements', 'logo-lettre', 'ancien', 'magasins', 'chaussures'], clues: ['Maison de luxe française', 'Malles de voyage au départ', 'Motif monogramme marron', 'Sacs très chers', 'Initiales LV'] },
    { name: 'Gucci', emoji: '👜🐍🇮🇹', group: 'Mode', tags: ['italien', 'européen', 'luxe', 'vêtements', 'chaussures', 'logo-lettre', 'ancien', 'magasins'], clues: ['Maison de luxe italienne', 'Née à Florence', 'Bandes vertes et rouges', 'Citée dans beaucoup de raps', 'Deux G entrelacés'] },
    { name: 'Chanel', emoji: '💄👗🇫🇷', group: 'Mode', tags: ['français', 'européen', 'luxe', 'vêtements', 'logo-lettre', 'ancien', 'noir', 'magasins'], clues: ['Maison de luxe française', 'Fondée par Coco', 'Petite robe noire', 'Parfum N°5', 'Deux C entrelacés'] },
    { name: 'Rolex', emoji: '⌚👑💰', group: 'Mode', tags: ['vêtements', 'européen', 'luxe', 'ancien', 'jaune', 'sport', 'magasins'], clues: ['Marque suisse', 'Symbole de réussite', 'Sponsor du tennis', 'Couronne sur le logo', 'Montres de luxe'] },
    { name: 'Zara', emoji: '👗🛍️🇪🇸', group: 'Mode', tags: ['sport', 'européen', 'vêtements', 'chaussures', 'magasins', 'noir', 'en-ligne'], clues: ['Enseigne de mode', 'Marque espagnole', 'Nouvelles collections chaque semaine', 'Soldes très attendues', 'Magasins dans toutes les grandes villes'] },
    // ——— Jouets ———
    { name: 'Lego', emoji: '🧱🧩👷', group: 'Jouets', tags: ['européen', 'enfants', 'rouge', 'jaune', 'ancien', 'magasins', 'jeux-vidéo', 'vidéo'], clues: ['Marque de jouets', 'Entreprise danoise', 'Fait mal quand on marche dessus', 'Petits bonshommes jaunes', 'Briques à assembler'] },
    { name: 'Barbie', emoji: '👱‍♀️💗👠', group: 'Jouets', tags: ['jeux-vidéo', 'américain', 'enfants', 'vêtements', 'ancien', 'vidéo', 'magasins'], clues: ['Jouet star depuis 1959', 'Couleur rose emblématique', 'Son copain s\'appelle Ken', 'Film en 2023', 'Poupée blonde'] },
  ],
};
