import type { Pack } from '../types';

export const pack: Pack = {
  id: 'metiers',
  name: 'Métiers',
  emoji: '👷',
  category: 'metiers',
  description: 'Des métiers de tous les jours, de rêve ou d\'aventure.',
  attributes: [
    { tag: 'uniforme', question: 'Porte-t-on un uniforme ou une tenue spéciale ?' },
    { tag: 'études-longues', question: 'Faut-il faire de longues études ?' },
    { tag: 'bureau', question: 'Travaille-t-on surtout dans un bureau ?' },
    { tag: 'dehors', question: 'Travaille-t-on souvent dehors ?' },
    { tag: 'manuel', question: 'Est-ce un métier manuel ?' },
    { tag: 'ordinateur', question: 'Utilise-t-on beaucoup un ordinateur ?' },
    { tag: 'santé', question: 'Est-ce un métier de la santé ?' },
    { tag: 'sécurité', question: 'Protège-t-on les gens ?' },
    { tag: 'public', question: 'Est-on en contact avec beaucoup de gens ?' },
    { tag: 'enfants', question: 'Travaille-t-on avec des enfants ?' },
    { tag: 'animaux', question: 'Travaille-t-on avec des animaux ?' },
    { tag: 'créatif', question: 'Est-ce un métier créatif ?' },
    { tag: 'célébrité', question: 'Peut-on devenir célèbre avec ce métier ?' },
    { tag: 'voyage', question: 'Voyage-t-on beaucoup ?' },
    { tag: 'danger', question: 'Est-ce un métier dangereux ?' },
    { tag: 'nuit', question: 'Travaille-t-on parfois la nuit ?' },
    { tag: 'véhicule', question: 'Conduit-on un véhicule ?' },
    { tag: 'nourriture', question: 'Est-ce lié à la nourriture ?' },
    { tag: 'argent', question: 'Est-ce lié à l\'argent ?' },
    { tag: 'sport', question: 'Est-ce lié au sport ?' },
    { tag: 'équipe', question: 'Travaille-t-on en équipe ?' },
    { tag: 'outils', question: 'Utilise-t-on des outils ?' },
    { tag: 'scène', question: 'Se produit-on devant un public ?' },
    { tag: 'internet', question: 'Est-ce lié à Internet ?' },
    { tag: 'nature', question: 'Est-ce lié à la nature ?' },
    { tag: 'science', question: 'Est-ce lié aux sciences ?' },
    { tag: 'parle-beaucoup', question: 'Doit-on beaucoup parler ?' },
    { tag: 'aide', question: 'Aide-t-on directement les gens ?' },
    { tag: 'vente', question: 'Vend-on quelque chose ?' },
    { tag: 'fonctionnaire', question: 'Travaille-t-on souvent pour l\'État ?' },
    { tag: 'caméra', question: 'Est-on souvent filmé ou photographié ?' },
    { tag: 'construction', question: 'Est-ce lié à la construction ou aux réparations ?' },
    { tag: 'tôt', question: 'Commence-t-on très tôt le matin ?' },
    { tag: 'indépendant', question: 'Est-on souvent son propre patron ?' },
  ],
  items: [
    // ——— Santé ———
    { name: 'Médecin', aliases: ['Docteur', 'Toubib'], emoji: '👨‍⚕️🩺💊', group: 'Santé', tags: ['santé', 'études-longues', 'public', 'aide', 'bureau', 'uniforme', 'science', 'parle-beaucoup'], clues: ['Métier très respecté', 'Dix ans d\'études minimum', 'Écrit des ordonnances illisibles', 'Stéthoscope autour du cou', 'On le consulte quand on est malade'] },
    { name: 'Infirmier', aliases: ['Infirmière'], emoji: '💉🏥🩹', group: 'Santé', tags: ['santé', 'public', 'aide', 'uniforme', 'nuit', 'équipe', 'fonctionnaire'], clues: ['Métier du soin', 'Horaires de nuit fréquents', 'Fait les piqûres et les pansements', 'Travaille avec les médecins', 'Blouse à l\'hôpital'] },
    { name: 'Chirurgien', emoji: '🔪🏥😷', group: 'Santé', tags: ['santé', 'études-longues', 'uniforme', 'équipe', 'outils', 'science', 'aide', 'nuit', 'manuel'], clues: ['Métier de haute précision', 'Porte un masque et des gants', 'Travaille au bloc', 'Utilise un scalpel', 'Opère les patients'] },
    { name: 'Dentiste', emoji: '🦷😬🪥', group: 'Santé', tags: ['santé', 'études-longues', 'public', 'outils', 'uniforme', 'aide', 'indépendant', 'manuel'], clues: ['Fait peur aux enfants', 'Fauteuil inclinable', 'Petite roulette qui fait du bruit', 'Soigne les caries', 'Travaille dans ta bouche'] },
    { name: 'Vétérinaire', aliases: ['Véto'], emoji: '🐶🩺🐱', group: 'Santé', tags: ['santé', 'animaux', 'études-longues', 'public', 'aide', 'science', 'uniforme', 'indépendant'], clues: ['Soigne sans que le patient parle', 'Clinique ou visite à la ferme', 'Vaccins et stérilisations', 'Patients à quatre pattes', 'Médecin des animaux'] },
    { name: 'Pharmacien', emoji: '💊🏪➕', group: 'Santé', tags: ['santé', 'études-longues', 'public', 'vente', 'science', 'uniforme', 'aide'], clues: ['Métier de la santé en boutique', 'Lit les ordonnances', 'Croix verte lumineuse', 'Conseille sur les médicaments', 'Travaille en officine'] },
    // ——— Sécurité ———
    { name: 'Pompier', emoji: '🚒🔥🧯', group: 'Sécurité', tags: ['sécurité', 'uniforme', 'danger', 'équipe', 'véhicule', 'nuit', 'aide', 'dehors', 'sport', 'fonctionnaire'], clues: ['Héros du quotidien', 'Vend des calendriers', 'Grande échelle et sirène', 'Camion rouge', 'Éteint les incendies'] },
    { name: 'Policier', aliases: ['Flic', 'Policière'], emoji: '👮🚓🚨', group: 'Sécurité', tags: ['sécurité', 'uniforme', 'danger', 'équipe', 'véhicule', 'nuit', 'fonctionnaire', 'public', 'dehors'], clues: ['Travaille pour l\'État', 'Menottes à la ceinture', 'Fait des contrôles', 'Voiture avec gyrophare', 'Arrête les voleurs'] },
    { name: 'Militaire', aliases: ['Soldat'], emoji: '🪖🎖️⚔️', group: 'Sécurité', tags: ['sécurité', 'uniforme', 'danger', 'équipe', 'sport', 'voyage', 'fonctionnaire', 'dehors', 'véhicule'], clues: ['Métier très discipliné', 'Tenue camouflage', 'Obéit aux ordres des gradés', 'Défile le 14 juillet', 'Défend le pays'] },
    { name: 'Garde du corps', emoji: '🕶️💪🎙️', group: 'Sécurité', tags: ['sécurité', 'uniforme', 'danger', 'sport', 'voyage', 'nuit', 'indépendant', 'véhicule'], clues: ['Toujours dans l\'ombre de quelqu\'un', 'Lunettes noires et oreillette', 'Très costaud', 'Accompagne les stars', 'Protège une personnalité'] },
    { name: 'Détective privé', emoji: '🕵️🔍📸', group: 'Sécurité', tags: ['sécurité', 'dehors', 'nuit', 'indépendant', 'véhicule', 'caméra', 'danger'], clues: ['Métier de l\'ombre', 'Fait des filatures', 'Loupe et imperméable', 'Engagé par des particuliers', 'Sherlock Holmes en est un'] },
    // ——— Alimentation ———
    { name: 'Boulanger', aliases: ['Boulangère'], emoji: '🥖👨‍🍳🌾', group: 'Alimentation', tags: ['nourriture', 'manuel', 'tôt', 'vente', 'public', 'indépendant', 'uniforme', 'outils'], clues: ['Se lève en pleine nuit', 'Farine partout', 'Four très chaud', 'Vend des croissants', 'Fait le pain'] },
    { name: 'Cuisinier', aliases: ['Chef', 'Chef cuisinier'], emoji: '👨‍🍳🍳🔪', group: 'Alimentation', tags: ['nourriture', 'manuel', 'créatif', 'équipe', 'uniforme', 'nuit', 'outils', 'célébrité'], clues: ['Travaille dans la chaleur', 'Toque blanche', 'Crie « Service ! »', 'Peut gagner des étoiles', 'Prépare les plats au restaurant'] },
    { name: 'Pâtissier', emoji: '🎂🧁👨‍🍳', group: 'Alimentation', tags: ['nourriture', 'manuel', 'créatif', 'tôt', 'vente', 'uniforme', 'outils', 'indépendant'], clues: ['Métier de précision sucrée', 'Poche à douille', 'Éclairs et macarons', 'Émission Le Meilleur ___', 'Fait des gâteaux'] },
    { name: 'Serveur', aliases: ['Serveuse'], emoji: '🍽️🧾🥂', group: 'Alimentation', tags: ['nourriture', 'public', 'nuit', 'uniforme', 'équipe', 'parle-beaucoup', 'argent'], clues: ['Toujours debout', 'Porte des plateaux', 'Prend les commandes', 'Espère un pourboire', 'Travaille en salle au restaurant'] },
    { name: 'Boucher', emoji: '🥩🔪🐄', group: 'Alimentation', tags: ['nourriture', 'manuel', 'outils', 'vente', 'public', 'tôt', 'uniforme', 'indépendant'], clues: ['Commerçant de quartier', 'Tablier souvent taché', 'Gros couteaux et hachoir', 'Découpe des steaks', 'Vend de la viande'] },
    { name: 'Agriculteur', aliases: ['Fermier', 'Paysan'], emoji: '🚜🌾🐄', group: 'Nature', tags: ['nature', 'dehors', 'manuel', 'tôt', 'animaux', 'nourriture', 'véhicule', 'indépendant', 'outils'], clues: ['Nourrit tout le pays', 'Se lève avec le soleil', 'Conduit un tracteur', 'Cultive les champs', 'Vit dans une ferme'] },
    { name: 'Pêcheur', emoji: '🎣🚤🐟', group: 'Nature', tags: ['nature', 'dehors', 'manuel', 'tôt', 'animaux', 'nourriture', 'véhicule', 'danger', 'indépendant', 'outils'], clues: ['Métier de la mer', 'Part avant l\'aube', 'Filets et cannes', 'Vend sa prise au port', 'Attrape des poissons'] },
    { name: 'Jardinier', emoji: '🌻🪴✂️', group: 'Nature', tags: ['nature', 'dehors', 'manuel', 'outils', 'tôt', 'créatif', 'indépendant'], clues: ['Travaille en plein air', 'Mains dans la terre', 'Taille les haies', 'Tondeuse et râteau', 'S\'occupe des plantes'] },
    // ——— Sciences ———
    { name: 'Astronaute', aliases: ['Spationaute', 'Cosmonaute'], emoji: '👨‍🚀🚀🌕', group: 'Sciences', tags: ['science', 'études-longues', 'danger', 'uniforme', 'voyage', 'équipe', 'célébrité', 'sport', 'véhicule'], clues: ['Métier dont rêvent les enfants', 'Entraînement très dur', 'Flotte en apesanteur', 'Combinaison et casque', 'Part dans l\'espace'] },
    { name: 'Scientifique', aliases: ['Chercheur'], emoji: '🔬🧪🥼', group: 'Sciences', tags: ['science', 'études-longues', 'bureau', 'ordinateur', 'uniforme', 'équipe', 'créatif'], clues: ['Pose des questions sur le monde', 'Fait des expériences', 'Blouse blanche et lunettes', 'Travaille dans un laboratoire', 'Publie des découvertes'] },
    { name: 'Archéologue', emoji: '🏺⛏️🦴', group: 'Sciences', tags: ['science', 'études-longues', 'dehors', 'voyage', 'outils', 'manuel', 'équipe'], clues: ['Étudie le passé', 'Creuse avec des pinceaux', 'Travaille sur des chantiers de fouilles', 'Indiana Jones en est un', 'Trouve des vestiges anciens'] },
    // ——— Numérique ———
    { name: 'Développeur', aliases: ['Programmeur', 'Dev', 'Codeur'], emoji: '👨‍💻⌨️🐛', group: 'Numérique', tags: ['ordinateur', 'bureau', 'internet', 'créatif', 'équipe', 'science', 'indépendant', 'nuit'], clues: ['Métier très demandé', 'Boit beaucoup de café', 'Corrige des bugs', 'Écrit des lignes de code', 'Crée des applis et des sites'] },
    { name: 'Youtubeur', aliases: ['Vidéaste'], emoji: '📹▶️👍', group: 'Numérique', tags: ['internet', 'caméra', 'créatif', 'célébrité', 'ordinateur', 'indépendant', 'parle-beaucoup', 'scène'], clues: ['Métier récent', 'Demande de s\'abonner', 'Monte ses propres vidéos', 'Gagne de l\'argent avec les vues', 'Poste sur la plateforme au bouton rouge'] },
    { name: 'Streamer', aliases: ['Streameur'], emoji: '🎮🎙️🔴', group: 'Numérique', tags: ['internet', 'caméra', 'célébrité', 'ordinateur', 'indépendant', 'parle-beaucoup', 'nuit', 'scène'], clues: ['Métier récent', 'Joue devant des milliers de gens', 'Lit le chat en direct', 'Reçoit des dons et des subs', 'Diffuse en live sur Twitch'] },
    { name: 'Influenceur', aliases: ['Influenceuse'], emoji: '🤳✨📸', group: 'Numérique', tags: ['internet', 'caméra', 'célébrité', 'créatif', 'indépendant', 'vente', 'voyage'], clues: ['Métier très critiqué', 'Partenariats avec des marques', 'Codes promo', 'Des milliers d\'abonnés', 'Poste des stories sur Instagram'] },
    { name: 'Expert en cybersécurité', aliases: ['Hacker éthique'], emoji: '🛡️💻🔐', group: 'Numérique', tags: ['ordinateur', 'internet', 'sécurité', 'bureau', 'science', 'études-longues', 'nuit'], clues: ['Métier de l\'ombre numérique', 'Cherche des failles', 'Protège contre les pirates', 'Sweat à capuche dans les films', 'Défend les systèmes informatiques'] },
    // ——— Justice & Éducation ———
    { name: 'Avocat', aliases: ['Avocate'], emoji: '⚖️👨‍💼📜', group: 'Justice', tags: ['études-longues', 'bureau', 'parle-beaucoup', 'public', 'uniforme', 'aide', 'argent', 'indépendant'], clues: ['Sait très bien argumenter', 'Porte une robe noire', 'Plaide au tribunal', 'Défend ses clients', 'Code civil en main'] },
    { name: 'Juge', emoji: '⚖️🔨👨‍⚖️', group: 'Justice', tags: ['sécurité', 'études-longues', 'bureau', 'uniforme', 'fonctionnaire', 'parle-beaucoup', 'public'], clues: ['Doit rester impartial', 'Porte une robe', 'Tape avec un marteau dans les films', 'Rend des verdicts', 'Préside le tribunal'] },
    { name: 'Professeur', aliases: ['Prof', 'Enseignant'], emoji: '👩‍🏫📚✏️', group: 'Éducation', tags: ['enfants', 'parle-beaucoup', 'études-longues', 'public', 'fonctionnaire', 'aide', 'tôt'], clues: ['A beaucoup de vacances selon certains', 'Corrige des copies', 'Écrit au tableau', 'Donne des devoirs', 'Enseigne au collège ou au lycée'] },
    { name: 'Coach sportif', aliases: ['Entraîneur'], emoji: '🏋️📣⏱️', group: 'Sport', tags: ['sport', 'parle-beaucoup', 'public', 'aide', 'dehors', 'indépendant', 'équipe'], clues: ['Motive les autres', 'Sifflet et chrono', 'Crie « Encore une ! »', 'Travaille en salle ou sur le terrain', 'Fait faire des exercices'] },
    // ——— Art & Spectacle ———
    { name: 'Chanteur', aliases: ['Chanteuse'], emoji: '🎤🎶⭐', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'célébrité', 'caméra', 'voyage', 'nuit', 'public', 'indépendant'], clues: ['Métier artistique', 'Fait des tournées', 'Enregistre en studio', 'Micro à la main', 'Sort des albums'] },
    { name: 'Acteur', aliases: ['Actrice', 'Comédien'], emoji: '🎬🎭⭐', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'célébrité', 'caméra', 'voyage', 'parle-beaucoup', 'équipe'], clues: ['Métier artistique', 'Apprend des textes par cœur', 'Joue des rôles', 'Monte les marches à Cannes', 'Tourne des films'] },
    { name: 'Danseur', aliases: ['Danseuse'], emoji: '💃🩰🎶', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'sport', 'célébrité', 'voyage', 'nuit', 'équipe'], clues: ['Métier très physique', 'Répète devant un miroir', 'Chorégraphies', 'Ballet ou hip-hop', 'Bouge en rythme sur la musique'] },
    { name: 'Peintre', aliases: ['Artiste peintre'], emoji: '🎨🖌️🖼️', group: 'Art & Spectacle', tags: ['dehors', 'créatif', 'manuel', 'outils', 'indépendant', 'célébrité', 'vente'], clues: ['Métier artistique', 'Mains pleines de couleurs', 'Chevalet et toile', 'Expose dans des galeries', 'Picasso en était un'] },
    { name: 'Photographe', emoji: '📷📸🌅', group: 'Art & Spectacle', tags: ['créatif', 'caméra', 'voyage', 'indépendant', 'dehors', 'outils', 'ordinateur'], clues: ['Métier artistique', 'Mariages et shootings', 'Joue avec la lumière', 'Objectifs et trépied', 'Dit « Souriez ! »'] },
    { name: 'DJ', emoji: '🎧🎛️🪩', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'nuit', 'célébrité', 'voyage', 'indépendant', 'public'], clues: ['Fait bouger les foules', 'Travaille la nuit', 'Casque sur une oreille', 'Platines et mix', 'Star des boîtes et festivals'] },
    { name: 'Magicien', emoji: '🎩🐇✨', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'public', 'indépendant', 'célébrité', 'parle-beaucoup', 'enfants'], clues: ['Garde ses secrets', 'Chapeau haut-de-forme', 'Tours de cartes', 'Fait disparaître des objets', 'Sort un lapin d\'un chapeau'] },
    { name: 'Clown', emoji: '🤡🎪🎈', group: 'Art & Spectacle', tags: ['scène', 'créatif', 'enfants', 'public', 'uniforme', 'voyage', 'indépendant'], clues: ['Fait rire les enfants', 'Grandes chaussures', 'Maquillage blanc', 'Travaille au cirque', 'Nez rouge'] },
    { name: 'Écrivain', aliases: ['Auteur', 'Romancier'], emoji: '✍️📖☕', group: 'Art & Spectacle', tags: ['voyage', 'créatif', 'indépendant', 'ordinateur', 'célébrité', 'bureau', 'nuit'], clues: ['Métier solitaire', 'Peur de la page blanche', 'Signe des dédicaces', 'Travaille avec un éditeur', 'Écrit des romans'] },
    { name: 'Mannequin', emoji: '👗📸💃', group: 'Mode & Beauté', tags: ['uniforme', 'caméra', 'célébrité', 'voyage', 'scène', 'indépendant', 'sport'], clues: ['Métier de l\'image', 'Défile sur un podium', 'Fashion week', 'Pose pour les magazines', 'Présente des vêtements'] },
    { name: 'Coiffeur', aliases: ['Coiffeuse'], emoji: '💇✂️💈', group: 'Mode & Beauté', tags: ['public', 'manuel', 'créatif', 'outils', 'parle-beaucoup', 'indépendant', 'vente'], clues: ['On lui raconte sa vie', 'Ciseaux et tondeuse', 'Shampooing et brushing', 'Travaille dans un salon', 'Coupe les cheveux'] },
    { name: 'Styliste', emoji: '👗✂️🧵', group: 'Mode & Beauté', tags: ['créatif', 'célébrité', 'manuel', 'outils', 'bureau', 'voyage', 'équipe'], clues: ['Métier de la mode', 'Dessine des croquis', 'Tissus et machines à coudre', 'Présente ses collections', 'Crée des vêtements'] },
    // ——— Médias ———
    { name: 'Journaliste', emoji: '📰🎙️🗞️', group: 'Médias', tags: ['parle-beaucoup', 'caméra', 'voyage', 'ordinateur', 'bureau', 'danger', 'public'], clues: ['Enquête sur l\'actualité', 'Carte de presse', 'Interviewe des gens', 'Écrit des articles', 'Travaille pour un journal'] },
    { name: 'Présentateur télé', aliases: ['Animateur télé'], emoji: '📺🎙️🎬', group: 'Médias', tags: ['créatif', 'parle-beaucoup', 'caméra', 'célébrité', 'scène', 'équipe', 'public'], clues: ['Visage connu', 'Oreillette et prompteur', 'Présente le JT ou des jeux', 'Toujours souriant', 'Travaille sur un plateau télé'] },
    // ——— Sport ———
    { name: 'Footballeur', aliases: ['Joueur de foot'], emoji: '⚽🏟️👟', group: 'Sport', tags: ['sport', 'équipe', 'célébrité', 'caméra', 'voyage', 'dehors', 'uniforme', 'scène'], clues: ['Métier très bien payé au top niveau', 'Crampons et protège-tibias', 'S\'entraîne tous les jours', 'Transferts et mercato', 'Marque des buts'] },
    { name: 'Arbitre', emoji: '🟨🟥📣', group: 'Sport', tags: ['équipe', 'sport', 'uniforme', 'dehors', 'caméra', 'voyage', 'public'], clues: ['Souvent insulté', 'Doit être impartial', 'Sifflet et cartons', 'Consulte la VAR', 'Fait respecter les règles du match'] },
    // ——— Transport ———
    { name: 'Pilote de ligne', aliases: ['Pilote', 'Commandant de bord'], emoji: '✈️👨‍✈️🌍', group: 'Transport', tags: ['véhicule', 'voyage', 'uniforme', 'études-longues', 'équipe', 'nuit', 'danger'], clues: ['Métier qui fait voyager', 'Casquette et galons', 'Parle aux passagers au micro', 'Travaille dans un cockpit', 'Fait voler les avions'] },
    { name: 'Hôtesse de l\'air', aliases: ['Steward', 'Personnel navigant'], emoji: '✈️🧳🥤', group: 'Transport', tags: ['voyage', 'uniforme', 'public', 'équipe', 'nuit', 'aide', 'sécurité'], clues: ['Voit du pays', 'Montre les consignes de sécurité', 'Pousse un chariot de boissons', 'Toujours souriante', 'Travaille en cabine'] },
    { name: 'Chauffeur de taxi', aliases: ['Taxi', 'Chauffeur VTC'], emoji: '🚕🧭💵', group: 'Transport', tags: ['véhicule', 'public', 'nuit', 'indépendant', 'argent', 'parle-beaucoup', 'dehors'], clues: ['Connaît la ville par cœur', 'Compteur qui tourne', 'Dépose à l\'aéroport', 'Enseigne lumineuse sur le toit', 'Conduit des clients'] },
    { name: 'Facteur', aliases: ['Factrice'], emoji: '📬✉️🚲', group: 'Transport', tags: ['manuel', 'dehors', 'tôt', 'véhicule', 'uniforme', 'fonctionnaire', 'public'], clues: ['Passe tous les jours', 'Vélo ou petite voiture jaune', 'Les chiens ne l\'aiment pas', 'Vend aussi des calendriers', 'Distribue le courrier'] },
    { name: 'Éboueur', emoji: '🚛🗑️♻️', group: 'Transport', tags: ['dehors', 'tôt', 'véhicule', 'uniforme', 'manuel', 'équipe', 'fonctionnaire', 'nuit'], clues: ['Métier indispensable', 'Passe très tôt le matin', 'Gilet fluo', 'Accroché à l\'arrière du camion', 'Ramasse les poubelles'] },
    // ——— Bâtiment ———
    { name: 'Maçon', emoji: '🧱🏗️🪣', group: 'Bâtiment', tags: ['construction', 'manuel', 'dehors', 'outils', 'tôt', 'équipe', 'danger', 'uniforme'], clues: ['Métier du chantier', 'Truelle et ciment', 'Monte des murs', 'Casque de chantier', 'Pose des briques'] },
    { name: 'Électricien', emoji: '⚡🔌🪛', group: 'Bâtiment', tags: ['dehors', 'construction', 'manuel', 'outils', 'danger', 'indépendant', 'science'], clues: ['Artisan', 'Travaille avec des câbles', 'Tournevis testeur', 'Coupe le courant avant d\'intervenir', 'Installe prises et lumières'] },
    { name: 'Plombier', emoji: '🔧🚿💧', group: 'Bâtiment', tags: ['véhicule', 'construction', 'manuel', 'outils', 'indépendant', 'aide', 'uniforme'], clues: ['Artisan appelé en urgence', 'Clé à molette', 'Répare les fuites', 'Débouche les toilettes', 'Mario en est un'] },
    { name: 'Architecte', emoji: '📐🏛️🏗️', group: 'Bâtiment', tags: ['construction', 'créatif', 'études-longues', 'bureau', 'ordinateur', 'indépendant', 'science'], clues: ['Métier créatif et technique', 'Dessine des plans', 'Maquettes', 'Surveille les chantiers', 'Conçoit des bâtiments'] },
    { name: 'Mécanicien', aliases: ['Garagiste'], emoji: '🔧🚗🛠️', group: 'Bâtiment', tags: ['manuel', 'outils', 'véhicule', 'uniforme', 'construction', 'indépendant', 'vente'], clues: ['Mains pleines de cambouis', 'Travaille dans un garage', 'Vidange et pneus', 'Soulève les voitures', 'Répare les moteurs'] },
    // ——— Commerce ———
    { name: 'Caissier', aliases: ['Caissière'], emoji: '🛒💳🧾', group: 'Commerce', tags: ['nourriture', 'vente', 'public', 'argent', 'uniforme', 'équipe', 'parle-beaucoup'], clues: ['Travaille assis', 'Entend « bip » toute la journée', 'Tapis roulant', 'Demande « Vous avez la carte ? »', 'Encaisse au supermarché'] },
    { name: 'Banquier', emoji: '🏦💰📈', group: 'Commerce', tags: ['vente', 'argent', 'bureau', 'ordinateur', 'études-longues', 'parle-beaucoup', 'public'], clues: ['Costume-cravate', 'Parle de prêts et de taux', 'Gère des comptes', 'Travaille dans une agence', 'Conseille sur l\'argent'] },
    { name: 'Vendeur', aliases: ['Vendeuse'], emoji: '🛍️👕💬', group: 'Commerce', tags: ['aide', 'vente', 'public', 'parle-beaucoup', 'argent', 'équipe', 'uniforme'], clues: ['Travaille en boutique', 'Demande « Je peux vous aider ? »', 'Range les rayons', 'Touche des commissions', 'Conseille les clients'] },
  ],
};
