import type { Pack } from '../types';

export const pack: Pack = {
  id: 'musique',
  name: 'Musique',
  emoji: '🎤',
  category: 'musique',
  description: 'Rappeurs, chanteuses, groupes et légendes de la musique d’ici et d’ailleurs.',
  attributes: [
    { tag: 'femme', question: 'Est-ce une chanteuse ?' },
    { tag: 'groupe', question: 'Est-ce un groupe ou un duo ?' },
    { tag: 'français', question: 'Est-il/elle français(e) ?' },
    { tag: 'belge', question: 'Est-il/elle belge ?' },
    { tag: 'américain', question: 'Est-il/elle américain(e) ?' },
    { tag: 'britannique', question: 'Est-il/elle britannique ?' },
    { tag: 'canadien', question: 'Est-il/elle canadien(ne) ?' },
    { tag: 'nigérian', question: 'Est-il/elle nigérian(e) ?' },
    { tag: 'europe', question: 'Vient-il/elle d’Europe ?' },
    { tag: 'amérique-du-nord', question: 'Vient-il/elle d’Amérique du Nord ?' },
    { tag: 'afrique', question: 'Vient-il/elle d’Afrique ?' },
    { tag: 'rap', question: 'Fait-il du rap ?' },
    { tag: 'pop', question: 'Fait-il/elle de la pop ?' },
    { tag: 'r-n-b', question: 'Fait-il/elle du R&B ?' },
    { tag: 'chanson-française', question: 'Est-ce de la chanson française classique ?' },
    { tag: 'électro', question: 'Fait-il de la musique électro ?' },
    { tag: 'rock', question: 'Fait-il du rock ?' },
    { tag: 'afrobeats', question: 'Fait-il/elle de l’afro (afrobeats, rumba…) ?' },
    { tag: 'dj', question: 'Est-ce un DJ ?' },
    { tag: 'chante-en-français', question: 'Chante-t-il/elle en français ?' },
    { tag: 'chante-en-anglais', question: 'Chante-t-il/elle en anglais ?' },
    { tag: 'marseille', question: 'Vient-il de Marseille et sa région ?' },
    { tag: 'décédé', question: 'Est-il/elle décédé(e) ?' },
    { tag: 'grammy', question: 'A-t-il/elle gagné un Grammy Award ?' },
    { tag: 'années-60', question: 'A-t-il/elle percé dans les années 1960 ?' },
    { tag: 'années-80', question: 'A-t-il/elle percé dans les années 1980 ?' },
    { tag: 'années-90', question: 'A-t-il/elle percé dans les années 1990 ?' },
    { tag: 'années-2000', question: 'A-t-il/elle percé dans les années 2000 ?' },
    { tag: 'années-2010', question: 'A-t-il/elle percé dans les années 2010 ?' },
    { tag: 'années-2020', question: 'A-t-il/elle percé dans les années 2020 ?' },
  ],
  items: [
    // ── Rap français ──
    {
      name: 'Jul',
      aliases: ['JuL', 'Julien Mari'],
      emoji: '✌️👽⚽',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'marseille', 'années-2010', 'vivant'],
      clues: ['Rappeur marseillais ultra-prolifique', 'Sort plusieurs albums par an', 'Signe de la main avec deux doigts', 'Artiste le plus certifié de l’histoire en France', 'À l’origine de « Bande organisée »', 'Trois lettres : l’Ovni'],
    },
    {
      name: 'Ninho',
      aliases: ['NI'],
      emoji: '💎🎤🌃',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Rappeur français de l’Essonne', 'Série de mixtapes « M.I.L.S »', 'Album « Destin » certifié diamant', 'Titre « Lettre à une femme »', 'Record de singles certifiés en France', 'Ninho, alias « NI »'],
    },
    {
      name: 'Damso',
      aliases: ['Dems', 'William Kalubi'],
      emoji: '🇧🇪🖤🎤',
      group: 'Rap français',
      tags: ['homme', 'belge', 'europe', 'rap', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Rappeur belge né à Kinshasa', 'Révélé sur le label de Booba', 'Album « Ipséité »', 'Album « QALF »', 'Titre « Macarena »', 'Surnommé Dems'],
    },
    {
      name: 'PNL',
      aliases: ['Ademo et N.O.S', 'Peace N’ Lovés'],
      emoji: '👬🐟🗼',
      group: 'Rap français',
      tags: ['homme', 'groupe', 'français', 'europe', 'rap', 'chante-en-français', 'années-2010'],
      clues: ['Duo de deux frères rappeurs', 'Originaires des Tarterêts à Corbeil-Essonnes', 'Donnent très peu d’interviews', 'Clip tourné en haut de la tour Eiffel', 'Album « Deux frères »', 'Ademo et N.O.S'],
    },
    {
      name: 'Orelsan',
      aliases: ['Orel', 'Aurélien Cotentin'],
      emoji: '🌾🎤🏙️',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-2000', 'vivant'],
      clues: ['Rappeur normand originaire de Caen', 'Duo Casseurs Flowters avec Gringe', 'Album « La fête est finie »', 'Titre « Basique »', 'Album « Civilisation »', 'Orel, de son vrai nom Aurélien'],
    },
    {
      name: 'Booba',
      aliases: ['B2O', 'Le Duc', 'Duc de Boulogne', 'Kopp'],
      emoji: '🦍🎤🌴',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-2000', 'vivant'],
      clues: ['Rappeur de Boulogne-Billancourt', 'Ancien membre du duo Lunatic', 'Fondateur du label 92i', 'Vit à Miami', 'Album « Ouest Side »', 'Surnommé « le Duc de Boulogne »'],
    },
    {
      name: 'Gims',
      aliases: ['Maître Gims', 'GIMS'],
      emoji: '🕶️🎤👑',
      group: 'Rap français',
      tags: ['homme', 'congolais', 'afrique', 'rap', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteur et rappeur né à Kinshasa', 'Toujours avec des lunettes de soleil', 'Ancien de la Sexion d’Assaut', 'Album « Subliminal » et titre « Bella »', 'Album « Mon cœur avait raison »', 'Anciennement « Maître »'],
    },
    {
      name: 'SCH',
      aliases: ['Julien Schwarzer'],
      emoji: '🎩🔫🎤',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'marseille', 'années-2010', 'vivant'],
      clues: ['Rappeur originaire d’Aubagne', 'Voix grave et univers de film mafieux', 'Mixtape « A7 »', 'Trilogie d’albums « JVLIVS »', 'Membre du collectif 13’Organisé', 'Trois lettres, comme un sigle'],
    },
    {
      name: 'Soolking',
      aliases: ['MC Sultan'],
      emoji: '🇩🇿🎤💃',
      group: 'Rap français',
      tags: ['homme', 'algérien', 'afrique', 'rap', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Rappeur et chanteur algérien', 'Ancien membre du groupe Africa Jungle', 'Titre « Liberté », hymne du Hirak', 'Tube « Suavemente »', 'Titre « Dalida »', 'Anciennement MC Sultan'],
    },
    {
      name: 'Soprano',
      aliases: ['Sopra', 'Saïd M’Roumbaba'],
      emoji: '🌌🎤😊',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'pop', 'chante-en-français', 'marseille', 'années-2000', 'vivant'],
      clues: ['Rappeur marseillais d’origine comorienne', 'Ancien du groupe Psy 4 de la Rime', 'Titre « Cosmo »', 'Titre « En feu »', 'Coach dans « The Voice Kids »', 'Sopra, rappeur préféré des familles'],
    },
    {
      name: 'Tiakola',
      aliases: ['Tiako', 'Tiak'],
      emoji: '🎶🌍💫',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'afrobeats', 'chante-en-français', 'années-2020', 'vivant'],
      clues: ['Chanteur et rappeur de La Courneuve', 'Ancien membre du groupe 4Keus', 'Mélodies afro très mélodieuses', 'Album « Mélo »', 'Album commun avec Gazo', 'Tiako, « la Mélo »'],
    },
    {
      name: 'Gazo',
      aliases: ['Gazo Drill'],
      emoji: '🥶🎤🔥',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-2020', 'vivant'],
      clues: ['Rappeur français à la voix grave', 'Pionnier de la drill en France', 'Album « KMT »', 'Album « La Mélo est Gangx » en duo', 'Titre « Die »', 'Gazo, figure de la drill parisienne'],
    },
    {
      name: 'Vald',
      aliases: ['Valentin Le Du'],
      emoji: '🤪🎤🌀',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Rappeur d’Aulnay-sous-Bois', 'Univers absurde et second degré', 'Titre « Désaccordé »', 'Album « Xeu »', 'Invente l’« Eurotrap »', 'Vald, blond peroxydé'],
    },
    {
      name: 'MC Solaar',
      aliases: ['Solaar', 'Claude M’Barali'],
      emoji: '🎩🎷✍️',
      group: 'Rap français',
      tags: ['homme', 'français', 'europe', 'rap', 'chante-en-français', 'années-90', 'vivant'],
      clues: ['Pionnier du rap français', 'Né à Dakar', 'Jeux de mots très poétiques', 'Titre « Caroline »', 'Titre « Bouge de là »', 'Claude, alias Solaar'],
    },
    {
      name: 'IAM',
      aliases: ['Imperial Asiatic Men'],
      emoji: '🏛️🎤🌊',
      group: 'Rap français',
      tags: ['homme', 'groupe', 'français', 'europe', 'rap', 'chante-en-français', 'marseille', 'années-90'],
      clues: ['Groupe de rap marseillais légendaire', 'Imagerie de l’Égypte ancienne', 'Akhenaton et Shurik’n au micro', 'Album « L’École du micro d’argent »', 'Titre « Je danse le Mia »', 'Trois lettres, groupe culte des années 1990'],
    },
    // ── Pop française ──
    {
      name: 'Aya Nakamura',
      aliases: ['Aya', 'Nakamura'],
      emoji: '👑💅🎤',
      group: 'Pop française',
      tags: ['femme', 'français', 'europe', 'pop', 'r-n-b', 'afrobeats', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteuse française née à Bamako', 'A grandi à Aulnay-sous-Bois', 'Tube mondial « Djadja »', 'Chanteuse francophone la plus écoutée au monde', 'A chanté avec la Garde républicaine à Paris 2024', 'Aya, reine de la pop urbaine'],
    },
    {
      name: 'Stromae',
      aliases: ['Paul Van Haver'],
      emoji: '🇧🇪🕺🎩',
      group: 'Pop française',
      tags: ['homme', 'belge', 'europe', 'pop', 'électro', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteur belge au style vestimentaire unique', 'Tube « Alors on danse »', 'Album « Racine carrée »', 'Titre « Papaoutai »', 'Titre « Formidable » filmé dans la rue', 'Paul, « maestro » à l’envers'],
    },
    {
      name: 'Angèle',
      aliases: ['Angèle Van Laeken', 'Angele'],
      emoji: '🇧🇪🌸🎹',
      group: 'Pop française',
      tags: ['femme', 'belge', 'europe', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteuse belge et pianiste', 'Album « Brol »', 'Titre « Balance ton quoi »', 'Duo avec son frère Roméo Elvis', 'Album « Nonante-Cinq »', 'Angèle, star de Bruxelles'],
    },
    {
      name: 'Dadju',
      aliases: ['Dadju Djuna Nsungula'],
      emoji: '💍🎤❤️',
      group: 'Pop française',
      tags: ['homme', 'français', 'europe', 'r-n-b', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteur français de R&B', 'Frère cadet de Gims', 'Titre « Reine »', 'Titre « Jaloux »', 'Ancien du duo The Shin Sekaï', 'Dadju, voix douce'],
    },
    {
      name: 'Vianney',
      aliases: ['Vianney Bureau'],
      emoji: '🎸🧣😊',
      group: 'Pop française',
      tags: ['homme', 'français', 'europe', 'pop', 'chanson-française', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteur français à la guitare', 'Titre « Pas là »', 'Titre « Je m’en vais »', 'Coach dans « The Voice »', 'Fabrique lui-même des guitares', 'Vianney, auteur de « Beau-papa »'],
    },
    {
      name: 'Indila',
      aliases: ['Adila Sedraïa'],
      emoji: '💃🌀🎶',
      group: 'Pop française',
      tags: ['femme', 'français', 'europe', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteuse française discrète', 'Voix très reconnaissable', 'Un seul album, « Mini World »', 'Titre « Tourner dans le vide »', 'Tube mondial « Dernière danse »', 'Indila, « Oh ma douce souffrance »'],
    },
    {
      name: 'Louane',
      aliases: ['Louane Emera'],
      emoji: '🎤👩‍👧🎬',
      group: 'Pop française',
      tags: ['femme', 'français', 'europe', 'pop', 'chante-en-français', 'années-2010', 'vivant'],
      clues: ['Chanteuse française révélée par « The Voice »', 'Rôle principal dans « La Famille Bélier »', 'César du meilleur espoir féminin', 'Titre « Jour 1 »', 'Représente la France à l’Eurovision 2025', 'Louane, chanson « Maman »'],
    },
    {
      name: 'Céline Dion',
      aliases: ['Céline', 'Celine Dion'],
      emoji: '🇨🇦🚢💖',
      group: 'Pop française',
      tags: ['femme', 'canadien', 'amérique-du-nord', 'pop', 'chante-en-français', 'chante-en-anglais', 'grammy', 'années-90', 'vivant'],
      clues: ['Chanteuse québécoise à la voix puissante', 'A gagné l’Eurovision pour la Suisse', 'Chanson du film « Titanic »', 'Longue résidence à Las Vegas', 'A chanté sur la tour Eiffel en 2024', 'Céline, « My Heart Will Go On »'],
    },
    {
      name: 'Mylène Farmer',
      aliases: ['Mylène', 'Mylene Farmer'],
      emoji: '🦋❤️‍🔥🎭',
      group: 'Pop française',
      tags: ['femme', 'français', 'europe', 'pop', 'chante-en-français', 'années-80', 'vivant'],
      clues: ['Chanteuse française rousse et mystérieuse', 'Née au Québec', 'Clips comme des courts métrages', 'Titre « Libertine »', 'Titre « Désenchantée »', 'Mylène, icône des années 1980'],
    },
    {
      name: 'Clara Luciani',
      aliases: ['Clara', 'Luciani'],
      emoji: '💣🎤✨',
      group: 'Pop française',
      tags: ['femme', 'français', 'europe', 'pop', 'chanson-française', 'chante-en-français', 'marseille', 'années-2010', 'vivant'],
      clues: ['Chanteuse française à la frange', 'Originaire de la région de Marseille', 'Titre « La grenade »', 'Titre « Le reste »', 'Album « Cœur »', 'Clara, voix grave et disco'],
    },
    // ── Chanson française ──
    {
      name: 'Édith Piaf',
      aliases: ['Piaf', 'Edith Piaf', 'La Môme'],
      emoji: '🌹🐦🖤',
      group: 'Chanson française',
      tags: ['femme', 'français', 'europe', 'chanson-française', 'chante-en-français', 'décédé', 'légende', 'années-40'],
      clues: ['Chanteuse française à la voix vibrante', 'Toute petite, toujours en robe noire', 'Titre « La Vie en rose »', 'Titre « Non, je ne regrette rien »', 'Morte en 1963', 'Surnommée « la Môme »'],
    },
    {
      name: 'Johnny Hallyday',
      aliases: ['Johnny', 'Hallyday', 'Jojo'],
      emoji: '🎸🏍️🔥',
      group: 'Chanson française',
      tags: ['homme', 'français', 'europe', 'rock', 'chanson-française', 'chante-en-français', 'décédé', 'légende', 'années-60'],
      clues: ['Rockeur français légendaire', 'Idole des jeunes dans les années 1960', 'Fan de grosses motos', 'Titre « Allumer le feu »', 'Titre « Que je t’aime »', 'Johnny, mort en 2017'],
    },
    {
      name: 'Charles Aznavour',
      aliases: ['Aznavour'],
      emoji: '🎩🎹🇦🇲',
      group: 'Chanson française',
      tags: ['homme', 'français', 'europe', 'chanson-française', 'chante-en-français', 'décédé', 'légende', 'années-60'],
      clues: ['Chanteur français d’origine arménienne', 'Carrière de plus de 70 ans', 'Titre « Emmenez-moi »', 'Titre « La Bohème »', 'Mort en 2018', 'Charles, géant de la chanson'],
    },
    {
      name: 'Jacques Brel',
      aliases: ['Brel'],
      emoji: '🇧🇪🌊🎭',
      group: 'Chanson française',
      tags: ['homme', 'belge', 'europe', 'chanson-française', 'chante-en-français', 'décédé', 'légende', 'années-60'],
      clues: ['Chanteur belge très expressif sur scène', 'A fini sa vie aux îles Marquises', 'Titre « Amsterdam »', 'Titre « Ne me quitte pas »', 'Mort en 1978', 'Jacques, poète du plat pays'],
    },
    {
      name: 'Claude François',
      aliases: ['Cloclo', 'Claude'],
      emoji: '🕺💃✨',
      group: 'Chanson française',
      tags: ['homme', 'français', 'europe', 'pop', 'chanson-française', 'chante-en-français', 'décédé', 'légende', 'années-60'],
      clues: ['Chanteur français né en Égypte', 'Danseuses appelées les Clodettes', 'Écrit « Comme d’habitude », devenu « My Way »', 'Titre « Alexandrie Alexandra »', 'Mort en 1978', 'Surnommé Cloclo'],
    },
    {
      name: 'Jean-Jacques Goldman',
      aliases: ['Goldman', 'JJG'],
      emoji: '🎸✍️🕊️',
      group: 'Chanson française',
      tags: ['homme', 'français', 'europe', 'pop', 'chanson-française', 'chante-en-français', 'légende', 'années-80', 'vivant'],
      clues: ['Chanteur français très discret', 'Souvent élu personnalité préférée des Français', 'A écrit un album entier pour Céline Dion', 'Titre « Envole-moi »', 'Hymne des Restos du cœur', 'Initiales JJG'],
    },
    // ── Électro ──
    {
      name: 'Daft Punk',
      aliases: ['Daft'],
      emoji: '🤖🪖🎧',
      group: 'Électro',
      tags: ['homme', 'groupe', 'français', 'europe', 'électro', 'dj', 'chante-en-anglais', 'grammy', 'années-90'],
      clues: ['Duo français toujours casqué', 'Figures de la « French Touch »', 'Titre « Around the World »', 'Titre « One More Time »', 'Tube « Get Lucky » avec Pharrell', 'Robots séparés en 2021'],
    },
    {
      name: 'David Guetta',
      aliases: ['Guetta'],
      emoji: '🎧🌍🔊',
      group: 'Électro',
      tags: ['homme', 'français', 'europe', 'électro', 'dj', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['DJ français star mondiale', 'Ancien roi des nuits parisiennes', 'Titre « Titanium »', 'Titre « When Love Takes Over »', 'Hymne de l’Euro 2016', 'David, DJ numéro 1 mondial'],
    },
    {
      name: 'DJ Snake',
      aliases: ['Snake', 'William Grigahcine'],
      emoji: '🐍🎧🔥',
      group: 'Électro',
      tags: ['homme', 'français', 'europe', 'électro', 'dj', 'chante-en-anglais', 'années-2010', 'vivant'],
      clues: ['DJ et producteur français', 'Originaire d’Ermont dans le Val-d’Oise', 'Tube « Turn Down for What »', 'Titre « Lean On » avec Major Lazer', 'Projet « Disco Maghreb »', 'Serpent des platines'],
    },
    // ── Pop internationale ──
    {
      name: 'Michael Jackson',
      aliases: ['MJ', 'Jackson', 'King of Pop'],
      emoji: '🕺🧤👑',
      group: 'Pop internationale',
      tags: ['homme', 'américain', 'amérique-du-nord', 'pop', 'chante-en-anglais', 'grammy', 'décédé', 'légende', 'années-80'],
      clues: ['Star américaine de la pop', 'Débute enfant avec ses frères', 'Gant blanc et chapeau', 'Invente le moonwalk', 'Album « Thriller », le plus vendu de l’histoire', 'Surnommé « le Roi de la pop »'],
    },
    {
      name: 'Beyoncé',
      aliases: ['Queen B', 'Beyonce', 'Queen Bey'],
      emoji: '🐝👑💃',
      group: 'Pop internationale',
      tags: ['femme', 'américain', 'amérique-du-nord', 'pop', 'r-n-b', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse américaine née à Houston', 'Ancienne leader des Destiny’s Child', 'Titre « Crazy in Love »', 'Titre « Single Ladies »', 'Recordwoman de Grammy Awards', 'Surnommée « Queen B »'],
    },
    {
      name: 'Taylor Swift',
      aliases: ['Taylor', 'Swift', 'Tay'],
      emoji: '✨🎸💌',
      group: 'Pop internationale',
      tags: ['femme', 'américain', 'amérique-du-nord', 'pop', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse américaine partie de la country', 'Fans appelés les « Swifties »', 'Réenregistre ses anciens albums', 'Titre « Shake It Off »', 'Tournée record « The Eras Tour »', 'Taylor, « Taylor’s Version »'],
    },
    {
      name: 'Ed Sheeran',
      aliases: ['Sheeran', 'Ed'],
      emoji: '🎸🦰➕',
      group: 'Pop internationale',
      tags: ['homme', 'britannique', 'europe', 'pop', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur britannique roux', 'Joue avec une pédale de boucles', 'Albums nommés par des symboles maths', 'Titre « Perfect »', 'Tube « Shape of You »', 'Ed, guitare et bonne humeur'],
    },
    {
      name: 'Billie Eilish',
      aliases: ['Billie', 'Eilish'],
      emoji: '💚🕷️🎧',
      group: 'Pop internationale',
      tags: ['femme', 'américain', 'amérique-du-nord', 'pop', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteuse américaine révélée ado', 'Compose avec son frère Finneas', 'Tube « Bad Guy »', 'Chanson du James Bond « Mourir peut attendre »', 'Oscar pour une chanson de « Barbie »', 'Billie, voix chuchotée'],
    },
    {
      name: 'Adele',
      aliases: ['Adèle', 'Adele Adkins'],
      emoji: '🎤💔🇬🇧',
      group: 'Pop internationale',
      tags: ['femme', 'britannique', 'europe', 'pop', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse britannique à la voix soul', 'Albums nommés selon son âge', 'Titre « Someone Like You »', 'Chanson du James Bond « Skyfall »', 'Titre « Hello »', 'Adele, originaire de Londres'],
    },
    {
      name: 'Bruno Mars',
      aliases: ['Bruno', 'Mars'],
      emoji: '🕺🎩🌺',
      group: 'Pop internationale',
      tags: ['homme', 'américain', 'amérique-du-nord', 'pop', 'r-n-b', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur américain né à Hawaï', 'Style funk et rétro', 'Tube « Uptown Funk »', 'Duo Silk Sonic', 'Titre « Just the Way You Are »', 'Bruno, porte le nom d’une planète'],
    },
    {
      name: 'Lady Gaga',
      aliases: ['Gaga'],
      emoji: '⚡💄🥩',
      group: 'Pop internationale',
      tags: ['femme', 'américain', 'amérique-du-nord', 'pop', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse américaine aux tenues extravagantes', 'A porté une robe en viande', 'Titre « Poker Face »', 'Actrice dans « A Star Is Born »', 'A chanté en français à Paris 2024', 'Gaga, « Bad Romance »'],
    },
    {
      name: 'Dua Lipa',
      aliases: ['Dua'],
      emoji: '💃🪩🌙',
      group: 'Pop internationale',
      tags: ['femme', 'britannique', 'europe', 'pop', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteuse britannique d’origine kosovare', 'Pop disco dansante', 'Titre « New Rules »', 'Titre « Levitating »', 'Chanson du film « Barbie »', 'Dua, « Don’t Start Now »'],
    },
    {
      name: 'Rihanna',
      aliases: ['RiRi', 'Robyn Fenty'],
      emoji: '☂️💎💄',
      group: 'Pop internationale',
      tags: ['femme', 'barbadien', 'amérique-du-nord', 'pop', 'r-n-b', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse née à la Barbade', 'Fondatrice de Fenty Beauty', 'Tube « Umbrella »', 'Titre « Diamonds »', 'Show du Super Bowl 2023', 'Surnommée RiRi'],
    },
    {
      name: 'The Weeknd',
      aliases: ['Weeknd', 'Abel Tesfaye'],
      emoji: '🌃🔴🕶️',
      group: 'Pop internationale',
      tags: ['homme', 'canadien', 'amérique-du-nord', 'r-n-b', 'pop', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur canadien de Toronto', 'Origines éthiopiennes', 'Costume rouge et visage bandé', 'Tube « Blinding Lights »', 'Show du Super Bowl 2021', 'De son vrai nom Abel Tesfaye'],
    },
    {
      name: 'Drake',
      aliases: ['Drizzy', 'Aubrey Graham'],
      emoji: '🦉🇨🇦🎤',
      group: 'Rap international',
      tags: ['homme', 'canadien', 'amérique-du-nord', 'rap', 'r-n-b', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Rappeur canadien de Toronto', 'Ancien acteur de série ado', 'Label symbolisé par un hibou', 'Titre « Hotline Bling »', 'Titre « God’s Plan »', 'Surnommé Drizzy'],
    },
    {
      name: 'Eminem',
      aliases: ['Slim Shady', 'Marshall Mathers', 'Em'],
      emoji: '🎤🍝🧢',
      group: 'Rap international',
      tags: ['homme', 'américain', 'amérique-du-nord', 'rap', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Rappeur américain de Detroit', 'Débit de parole ultra-rapide', 'Alter ego provocateur', 'Joue dans le film « 8 Mile »', 'Oscar pour « Lose Yourself »', 'Alias Slim Shady'],
    },
    {
      name: 'Bad Bunny',
      aliases: ['Benito', 'Bad Bunny Baby'],
      emoji: '🐰🇵🇷🌴',
      group: 'Latino',
      tags: ['homme', 'portoricain', 'amérique-latine', 'reggaeton', 'pop', 'chante-en-espagnol', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur portoricain', 'Chante surtout en espagnol', 'Star du reggaeton', 'Artiste le plus écouté sur Spotify plusieurs années', 'Titre « Dákiti »', 'Un lapin pas très sage'],
    },
    {
      name: 'Shakira',
      aliases: ['Shak'],
      emoji: '💃🇨🇴⚽',
      group: 'Latino',
      tags: ['femme', 'colombien', 'amérique-latine', 'pop', 'reggaeton', 'chante-en-espagnol', 'chante-en-anglais', 'grammy', 'années-2000', 'vivant'],
      clues: ['Chanteuse colombienne', 'Danse du ventre sur scène', 'Titre « Hips Don’t Lie »', 'Hymne de la Coupe du monde 2010', 'Tube « Waka Waka »', 'Shakira, née à Barranquilla'],
    },
    {
      name: 'BTS',
      aliases: ['Bangtan Boys', 'Bangtan Sonyeondan'],
      emoji: '💜🇰🇷🕺',
      group: 'K-pop',
      tags: ['homme', 'groupe', 'sud-coréen', 'asie', 'pop', 'années-2010', 'k-pop', 'chante-en-coréen'],
      clues: ['Groupe sud-coréen de sept membres', 'Fans appelés l’ARMY', 'Discours aux Nations unies', 'Tube « Dynamite »', 'Groupe de K-pop le plus célèbre', 'Trois lettres : Bangtan Boys'],
    },
    // ── Rock & légendes ──
    {
      name: 'Queen',
      aliases: ['Freddie Mercury'],
      emoji: '👑🎸🎤',
      group: 'Rock',
      tags: ['homme', 'groupe', 'britannique', 'europe', 'rock', 'chante-en-anglais', 'légende', 'années-70'],
      clues: ['Groupe de rock britannique', 'Chanteur moustachu à la voix immense', 'Concert légendaire au Live Aid 1985', 'Titre « Bohemian Rhapsody »', 'Titre « We Will Rock You »', 'Groupe de Freddie Mercury'],
    },
    {
      name: 'Elvis Presley',
      aliases: ['Elvis', 'The King'],
      emoji: '🕺🎸👑',
      group: 'Rock',
      tags: ['homme', 'américain', 'amérique-du-nord', 'rock', 'chante-en-anglais', 'grammy', 'décédé', 'légende', 'années-50'],
      clues: ['Chanteur américain des années 1950', 'Déhanché célèbre', 'Surnommé « le King »', 'Vivait à Graceland', 'Titre « Jailhouse Rock »', 'Elvis, roi du rock’n’roll'],
    },
    {
      name: 'The Beatles',
      aliases: ['Beatles', 'Les Beatles'],
      emoji: '🪲🎸🇬🇧',
      group: 'Rock',
      tags: ['homme', 'groupe', 'britannique', 'europe', 'rock', 'pop', 'chante-en-anglais', 'grammy', 'légende', 'années-60'],
      clues: ['Groupe britannique de quatre musiciens', 'Originaires de Liverpool', 'Photo culte sur un passage piéton', 'Titre « Hey Jude »', 'Titre « Yesterday »', 'Les « Fab Four »'],
    },
    {
      name: 'Bob Marley',
      aliases: ['Marley'],
      emoji: '🇯🇲🎸🦁',
      group: 'Reggae',
      tags: ['homme', 'jamaïcain', 'amérique-du-nord', 'reggae', 'chante-en-anglais', 'décédé', 'légende', 'années-70'],
      clues: ['Chanteur jamaïcain aux dreadlocks', 'Groupe The Wailers', 'Messages de paix et d’unité', 'Titre « No Woman, No Cry »', 'Titre « One Love »', 'Bob, roi du reggae'],
    },
    // ── Musique africaine ──
    {
      name: 'Burna Boy',
      aliases: ['Burna', 'African Giant'],
      emoji: '🇳🇬🔥🦁',
      group: 'Musique africaine',
      tags: ['homme', 'nigérian', 'afrique', 'afrobeats', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur nigérian', 'Titre « Ye »', 'Grammy du meilleur album de musique du monde', 'Titre « Last Last »', 'Se surnomme « African Giant »', 'Burna, star de l’afrofusion'],
    },
    {
      name: 'Wizkid',
      aliases: ['Wiz', 'Starboy', 'Big Wiz'],
      emoji: '🇳🇬⭐🎤',
      group: 'Musique africaine',
      tags: ['homme', 'nigérian', 'afrique', 'afrobeats', 'chante-en-anglais', 'grammy', 'années-2010', 'vivant'],
      clues: ['Chanteur nigérian de Lagos', 'Tube « Essence » avec Tems', 'En featuring sur « One Dance » de Drake', 'Album « Made in Lagos »', 'Surnommé « Starboy »', 'Wiz, pionnier de l’afrobeats'],
    },
    {
      name: 'Rema',
      aliases: ['Divine Ikubor'],
      emoji: '🇳🇬🌙💫',
      group: 'Musique africaine',
      tags: ['homme', 'nigérian', 'afrique', 'afrobeats', 'chante-en-anglais', 'années-2020', 'vivant'],
      clues: ['Jeune chanteur nigérian né en 2000', 'Style qu’il appelle « afrorave »', 'Titre « Dumebi »', 'Remix avec Selena Gomez', 'Tube mondial « Calm Down »', 'Rema, originaire de Benin City'],
    },
    {
      name: 'Davido',
      aliases: ['OBO', 'David Adeleke'],
      emoji: '🇳🇬💰🎶',
      group: 'Musique africaine',
      tags: ['homme', 'nigérian', 'afrique', 'afrobeats', 'chante-en-anglais', 'années-2010', 'vivant'],
      clues: ['Chanteur nigérian né à Atlanta', 'Tube « Unavailable »', 'Titre « Fall »', 'Titre « If »', 'Surnommé OBO', 'De son vrai nom David Adeleke'],
    },
    {
      name: 'Tems',
      aliases: ['Temilade Openiyi'],
      emoji: '🇳🇬🎙️🌿',
      group: 'Musique africaine',
      tags: ['femme', 'nigérian', 'afrique', 'afrobeats', 'r-n-b', 'chante-en-anglais', 'grammy', 'années-2020', 'vivant'],
      clues: ['Chanteuse nigériane à la voix grave', 'Duo « Essence » avec Wizkid', 'Coécrit une chanson de Rihanna pour Marvel', 'Titre « Free Mind »', 'Titre « Love Me JeJe »', 'Tems, star du R&B africain'],
    },
    {
      name: 'Fally Ipupa',
      aliases: ['Fally', 'Dicap La Merveille'],
      emoji: '🇨🇩💃🎸',
      group: 'Musique africaine',
      tags: ['homme', 'congolais', 'afrique', 'afrobeats', 'r-n-b', 'chante-en-lingala', 'années-2000', 'vivant'],
      clues: ['Chanteur congolais de Kinshasa', 'Star de la rumba congolaise', 'Ancien membre du groupe de Koffi Olomidé', 'Album « Formule 7 »', 'A rempli La Défense Arena', 'Fally, « Eloko Oyo »'],
    },
    {
      name: 'Magic System',
      aliases: ['Magic Système'],
      emoji: '🇨🇮🎉🎶',
      group: 'Musique africaine',
      tags: ['homme', 'groupe', 'ivoirien', 'afrique', 'afrobeats', 'chante-en-français', 'années-2000'],
      clues: ['Groupe ivoirien festif', 'Chanteur principal : A’Salfo', 'Style zouglou', 'Tube « Premier Gaou »', 'Titre « Magic in the Air »', 'Ambiance garantie dans les stades'],
    },
    {
      name: 'Youssou N’Dour',
      aliases: ['Youssou', 'Youssou Ndour'],
      emoji: '🇸🇳🎤🥁',
      group: 'Musique africaine',
      tags: ['homme', 'sénégalais', 'afrique', 'afrobeats', 'grammy', 'légende', 'années-80', 'vivant'],
      clues: ['Chanteur sénégalais légendaire', 'Roi du mbalax', 'Duo « 7 Seconds » avec Neneh Cherry', 'Ancien ministre dans son pays', 'Grammy Award en 2005', 'Youssou, voix d’or de Dakar'],
    },
  ],
};
