import type { Pack } from '../types';

export const pack: Pack = {
  id: 'nourriture',
  name: 'Nourriture',
  emoji: '🍽️',
  category: 'nourriture',
  description: 'Plats, fruits, desserts et boissons d\'ici et d\'ailleurs.',
  attributes: [
    { tag: 'sucré', question: 'Est-ce sucré ?' },
    { tag: 'salé', question: 'Est-ce salé ?' },
    { tag: 'chaud', question: 'Est-ce que ça se mange (ou se boit) chaud ?' },
    { tag: 'froid', question: 'Est-ce que ça se mange (ou se boit) froid ?' },
    { tag: 'africain', question: 'Est-ce une spécialité africaine ?' },
    { tag: 'français', question: 'Est-ce une spécialité française ?' },
    { tag: 'asiatique', question: 'Est-ce une spécialité asiatique ?' },
    { tag: 'italien', question: 'Est-ce une spécialité italienne ?' },
    { tag: 'américain', question: 'Est-ce d\'origine américaine ?' },
    { tag: 'fruit', question: 'Est-ce un fruit ?' },
    { tag: 'légume', question: 'Est-ce un légume ?' },
    { tag: 'boisson', question: 'Est-ce une boisson ?' },
    { tag: 'dessert', question: 'Est-ce un dessert ou une douceur ?' },
    { tag: 'fast-food', question: 'Est-ce qu\'on en trouve dans les fast-foods ?' },
    { tag: 'viande', question: 'Y a-t-il de la viande dedans ?' },
    { tag: 'poisson', question: 'Y a-t-il du poisson ou des fruits de mer ?' },
    { tag: 'végétarien', question: 'Est-ce végétarien ?' },
    { tag: 'rouge', question: 'Est-ce plutôt rouge ?' },
    { tag: 'jaune', question: 'Est-ce plutôt jaune ou orangé ?' },
    { tag: 'vert', question: 'Est-ce plutôt vert ?' },
    { tag: 'marron', question: 'Est-ce plutôt marron ?' },
    { tag: 'épicé', question: 'Est-ce épicé ou relevé ?' },
    { tag: 'riz', question: 'Y a-t-il du riz ?' },
    { tag: 'fromage', question: 'Y a-t-il du fromage ?' },
    { tag: 'pâte', question: 'Est-ce fait avec une pâte ou de la farine ?' },
    { tag: 'sauce', question: 'Est-ce servi avec une sauce ?' },
    { tag: 'mains', question: 'Est-ce qu\'on le mange souvent avec les mains ?' },
    { tag: 'petit-déjeuner', question: 'Est-ce qu\'on en prend au petit-déjeuner ?' },
    { tag: 'tropical', question: 'Est-ce que ça vient des pays chauds ?' },
    { tag: 'frit', question: 'Est-ce frit ?' },
    { tag: 'chocolat', question: 'Y a-t-il du chocolat ?' },
    { tag: 'lait', question: 'Y a-t-il du lait ou de la crème ?' },
    { tag: 'plat-complet', question: 'Est-ce un plat principal complet ?' },
    { tag: 'rond', question: 'Est-ce de forme ronde ?' },
    { tag: 'partage', question: 'Est-ce qu\'on le partage souvent à plusieurs ?' },
  ],
  items: [
    // ——— Plats ———
    { name: 'Pizza', emoji: '🍕🇮🇹🧀', group: 'Plat', tags: ['salé', 'chaud', 'italien', 'fromage', 'pâte', 'fast-food', 'mains', 'rond', 'partage', 'rouge'], clues: ['Plat qu\'on commande souvent le soir', 'Cuite au four', 'Découpée en parts triangulaires', 'Recette Margherita', 'Spécialité de Naples'] },
    { name: 'Sushi', aliases: ['Sushis'], emoji: '🍣🥢🇯🇵', group: 'Plat', tags: ['salé', 'froid', 'asiatique', 'poisson', 'riz', 'mains', 'partage', 'sauce'], clues: ['Spécialité asiatique', 'Se mange avec des baguettes', 'Algue nori et vinaigre', 'Saumon cru sur du riz', 'Plat japonais'] },
    { name: 'Couscous', emoji: '🥘🍗🥕', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'viande', 'légume', 'épicé', 'sauce', 'plat-complet', 'partage'], clues: ['Plat familial du dimanche', 'Graines de semoule', 'Bouillon de légumes et pois chiches', 'Souvent avec merguez', 'Spécialité du Maghreb'] },
    { name: 'Thiéboudienne', aliases: ['Thieb', 'Ceebu jën', 'Riz au poisson'], emoji: '🐟🍚🇸🇳', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'poisson', 'riz', 'légume', 'épicé', 'plat-complet', 'partage', 'rouge'], clues: ['Plat familial africain', 'Mangé autour d\'un grand plat commun', 'Riz rouge à la tomate', 'Poisson farci et légumes', 'Plat national du Sénégal'] },
    { name: 'Attiéké', emoji: '🐟🌿🇨🇮', group: 'Plat', tags: ['salé', 'africain', 'végétarien', 'poisson', 'mains', 'tropical', 'épicé', 'froid'], clues: ['Accompagnement africain', 'Petites graines blanches', 'Fait à partir de manioc', 'Souvent avec du poisson braisé', 'Star de la Côte d\'Ivoire'] },
    { name: 'Poulet yassa', aliases: ['Yassa'], emoji: '🍗🧅🍋', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'viande', 'riz', 'sauce', 'épicé', 'plat-complet', 'partage'], clues: ['Plat africain mijoté', 'Beaucoup d\'oignons', 'Mariné au citron', 'Servi avec du riz blanc', 'Spécialité de Casamance'] },
    { name: 'Mafé', emoji: '🥜🍖🍚', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'viande', 'riz', 'sauce', 'marron', 'plat-complet', 'partage'], clues: ['Plat mijoté africain', 'Sauce épaisse et onctueuse', 'Couleur marron', 'À base de pâte d\'arachide', 'Populaire au Mali et au Sénégal'] },
    { name: 'Riz jollof', aliases: ['Jollof'], emoji: '🍚🌶️🍅', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'riz', 'épicé', 'rouge', 'viande', 'plat-complet', 'partage'], clues: ['Plat de fête africain', 'Riz cuit dans une sauce tomate', 'Débat éternel entre deux pays', 'Nigeria contre Ghana', 'Riz rouge et pimenté'] },
    { name: 'Alloco', emoji: '🍌🔥🌶️', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'frit', 'végétarien', 'tropical', 'jaune', 'mains'], clues: ['Street-food africaine', 'Petits morceaux dorés', 'Souvent avec du piment', 'Banane plantain frite', 'Très populaire à Abidjan'] },
    { name: 'Ndolé', emoji: '🌿🥜🦐', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'vert', 'viande', 'poisson', 'sauce', 'plat-complet'], clues: ['Plat mijoté africain', 'Feuilles amères', 'Arachides et crevettes', 'Accompagné de plantain', 'Plat national du Cameroun'] },
    { name: 'Tajine', emoji: '🍲🫒🍋', group: 'Plat', tags: ['salé', 'chaud', 'africain', 'viande', 'légume', 'épicé', 'sauce', 'plat-complet', 'partage'], clues: ['Plat mijoté longtemps', 'Plat en terre au couvercle pointu', 'Citron confit et olives', 'Épices comme le cumin', 'Spécialité marocaine'] },
    { name: 'Raclette', emoji: '🧀🥔🔥', group: 'Plat', tags: ['salé', 'chaud', 'français', 'fromage', 'viande', 'partage', 'plat-complet', 'lait'], clues: ['Repas d\'hiver entre amis', 'Appareil posé au milieu de la table', 'Pommes de terre et charcuterie', 'Fromage fondu dans des poêlons', 'Tradition savoyarde'] },
    { name: 'Bœuf bourguignon', emoji: '🥩🍷🥕', group: 'Plat', tags: ['salé', 'chaud', 'français', 'viande', 'sauce', 'marron', 'plat-complet', 'partage'], clues: ['Plat de grand-mère', 'Mijote pendant des heures', 'Carottes et champignons', 'Viande dans une sauce au vin', 'Spécialité de Bourgogne'] },
    { name: 'Gratin dauphinois', emoji: '🥔🧀🔥', group: 'Plat', tags: ['salé', 'chaud', 'français', 'végétarien', 'lait', 'légume', 'fromage', 'partage'], clues: ['Accompagnement réconfortant', 'Cuit au four', 'Tranches fines et crème', 'Dessus bien doré', 'Pommes de terre à la crème'] },
    { name: 'Quiche lorraine', emoji: '🥧🥓🥚', group: 'Plat', tags: ['salé', 'chaud', 'français', 'pâte', 'viande', 'lait', 'rond', 'partage'], clues: ['Plat servi en parts', 'Pâte brisée', 'Œufs et crème', 'Lardons dedans', 'Spécialité de l\'Est de la France'] },
    { name: 'Lasagnes', emoji: '🍝🧀🍅', group: 'Plat', tags: ['salé', 'chaud', 'italien', 'viande', 'fromage', 'pâte', 'sauce', 'plat-complet', 'partage', 'rouge'], clues: ['Plat cuit au four', 'Couches superposées', 'Béchamel et sauce tomate', 'Plat préféré de Garfield', 'Pâtes en feuilles'] },
    { name: 'Spaghetti bolognaise', aliases: ['Spaghetti', 'Bolo'], emoji: '🍝🍅🥩', group: 'Plat', tags: ['salé', 'chaud', 'italien', 'viande', 'pâte', 'sauce', 'rouge', 'plat-complet'], clues: ['Plat simple et populaire', 'On l\'enroule sur la fourchette', 'Sauce tomate et viande hachée', 'Parmesan râpé dessus', 'Pâtes longues'] },
    { name: 'Paella', emoji: '🥘🦐🍋', group: 'Plat', tags: ['salé', 'chaud', 'riz', 'poisson', 'viande', 'jaune', 'plat-complet', 'partage'], clues: ['Plat servi dans une grande poêle', 'Couleur jaune au safran', 'Fruits de mer et poulet', 'Plat à base de riz', 'Spécialité de Valence'] },
    { name: 'Ramen', emoji: '🍜🥚🥢', group: 'Plat', tags: ['salé', 'chaud', 'asiatique', 'pâte', 'viande', 'plat-complet', 'sauce', 'épicé'], clues: ['Bol fumant', 'Bouillon savoureux', 'Œuf mollet et porc', 'Mangé par Naruto chez Ichiraku', 'Nouilles japonaises'] },
    { name: 'Pad thaï', emoji: '🍜🥜🦐', group: 'Plat', tags: ['salé', 'chaud', 'asiatique', 'pâte', 'poisson', 'épicé', 'plat-complet', 'sauce'], clues: ['Street-food asiatique', 'Nouilles de riz sautées', 'Cacahuètes et citron vert', 'Crevettes ou poulet', 'Plat thaïlandais'] },
    { name: 'Curry', emoji: '🍛🌶️🍚', group: 'Plat', tags: ['salé', 'chaud', 'asiatique', 'épicé', 'sauce', 'riz', 'viande', 'jaune', 'plat-complet'], clues: ['Plat en sauce', 'Mélange d\'épices', 'Couleur jaune ou orange', 'Servi avec du riz ou du naan', 'Très populaire en Inde'] },
    { name: 'Omelette', emoji: '🍳🥚🧂', group: 'Plat', tags: ['salé', 'chaud', 'végétarien', 'jaune', 'petit-déjeuner', 'rond', 'fromage', 'français'], clues: ['Plat rapide', 'Se cuit à la poêle', 'On peut y mettre du fromage', 'Il faut casser des œufs', 'Œufs battus'] },
    // ——— Fast-food ———
    { name: 'Burger', aliases: ['Hamburger'], emoji: '🍔🍟🥤', group: 'Fast-food', tags: ['salé', 'chaud', 'américain', 'fast-food', 'viande', 'pâte', 'mains', 'fromage', 'sauce', 'rond'], clues: ['Star des fast-foods', 'Pain rond avec sésame', 'Steak, cheddar et salade', 'Servi avec frites', 'Big Mac ou Whopper'] },
    { name: 'Tacos français', aliases: ['Tacos'], emoji: '🌯🍟🧀', group: 'Fast-food', tags: ['salé', 'chaud', 'français', 'fast-food', 'viande', 'fromage', 'sauce', 'mains', 'frit'], clues: ['Spécialité fast-food lyonnaise', 'Galette pliée et grillée', 'Sauce fromagère', 'Des frites à l\'intérieur', 'Taille M, L ou XL'] },
    { name: 'Kebab', emoji: '🥙🥩🧅', group: 'Fast-food', tags: ['salé', 'chaud', 'fast-food', 'viande', 'sauce', 'mains', 'pâte', 'épicé'], clues: ['Snack de fin de soirée', 'Viande coupée sur une broche', 'Salade-tomate-oignon', 'Sauce blanche ou samouraï', 'Dans un pain ou une galette'] },
    { name: 'Frites', emoji: '🍟🥔🧂', group: 'Fast-food', tags: ['salé', 'chaud', 'fast-food', 'frit', 'végétarien', 'jaune', 'mains', 'légume', 'partage'], clues: ['Accompagnement préféré des enfants', 'Bâtonnets dorés', 'Ketchup ou mayo', 'Les Belges en sont fiers', 'Pommes de terre frites'] },
    { name: 'Hot-dog', emoji: '🌭🇺🇸🟡', group: 'Fast-food', tags: ['salé', 'chaud', 'américain', 'fast-food', 'viande', 'pâte', 'mains', 'sauce'], clues: ['Vendu dans les stades', 'Pain long et moelleux', 'Moutarde et ketchup', 'Star des rues de New York', 'Saucisse dans un pain'] },
    { name: 'Nuggets', emoji: '🍗🟫🥫', group: 'Fast-food', tags: ['salé', 'chaud', 'américain', 'fast-food', 'viande', 'frit', 'mains', 'sauce', 'partage'], clues: ['Menu enfant classique', 'Petits morceaux panés', 'Trempés dans une sauce', 'Boîte de 6, 9 ou 20', 'Poulet pané et frit'] },
    { name: 'Croque-monsieur', emoji: '🥪🧀🔥', group: 'Fast-food', tags: ['salé', 'chaud', 'français', 'fromage', 'viande', 'pâte', 'mains', 'lait'], clues: ['Snack de brasserie', 'Pain de mie grillé', 'Béchamel parfois', 'Jambon et fromage fondu', 'Sa version avec œuf s\'appelle « madame »'] },
    { name: 'Fish and chips', emoji: '🐟🍟🇬🇧', group: 'Fast-food', tags: ['salé', 'chaud', 'fast-food', 'poisson', 'frit', 'mains', 'sauce', 'jaune'], clues: ['Street-food britannique', 'Servi dans du papier', 'Vinaigre dessus', 'Poisson pané et frit', 'Avec des frites'] },
    // ——— Fruits ———
    { name: 'Mangue', emoji: '🥭☀️🟠', group: 'Fruit', tags: ['fruit', 'sucré', 'tropical', 'jaune', 'végétarien', 'froid', 'dessert', 'mains'], clues: ['Fruit des pays chauds', 'Gros noyau plat', 'Chair orange et juteuse', 'Saison en été en Afrique de l\'Ouest', 'Délicieuse en lassi'] },
    { name: 'Avocat', emoji: '🥑🌮🟢', group: 'Fruit', tags: ['fruit', 'vert', 'tropical', 'végétarien', 'salé', 'froid', 'petit-déjeuner', 'légume'], clues: ['Fruit qu\'on prend pour un légume', 'Gros noyau rond', 'Peau sombre et rugueuse', 'Ingrédient du guacamole', 'Star des toasts healthy'] },
    { name: 'Banane', emoji: '🍌🐒🟡', group: 'Fruit', tags: ['fruit', 'sucré', 'jaune', 'tropical', 'végétarien', 'petit-déjeuner', 'mains', 'dessert'], clues: ['Fruit courbé', 'Se pèle facilement', 'Adorée des singes', 'Pleine de potassium', 'Jaune et allongée'] },
    { name: 'Fraise', emoji: '🍓❤️🍰', group: 'Fruit', tags: ['fruit', 'sucré', 'rouge', 'végétarien', 'froid', 'dessert', 'mains', 'lait'], clues: ['Petit fruit de printemps', 'Graines à l\'extérieur', 'En tarte ou avec de la chantilly', 'Parfum star des bonbons', 'Rouge avec une collerette verte'] },
    { name: 'Pomme', emoji: '🍎🌳🧑‍🏫', group: 'Fruit', tags: ['fruit', 'sucré', 'rouge', 'vert', 'végétarien', 'rond', 'mains', 'dessert', 'français'], clues: ['Fruit du verger', 'Elle croque', 'Tombée sur la tête de Newton', 'Blanche-Neige s\'en méfie', 'Golden, Granny ou Pink Lady'] },
    { name: 'Ananas', emoji: '🍍🌴☀️', group: 'Fruit', tags: ['fruit', 'sucré', 'tropical', 'jaune', 'végétarien', 'froid', 'dessert', 'partage'], clues: ['Fruit exotique', 'Peau épineuse', 'Couronne de feuilles', 'Débat : sur la pizza ou pas ?', 'Maison de Bob l\'éponge'] },
    { name: 'Pastèque', emoji: '🍉☀️💦', group: 'Fruit', tags: ['fruit', 'sucré', 'rouge', 'vert', 'froid', 'végétarien', 'rond', 'partage', 'tropical'], clues: ['Fruit d\'été rafraîchissant', 'Énorme et lourd', 'Pleine de pépins noirs', 'Rouge dedans, vert dehors', 'Presque que de l\'eau'] },
    { name: 'Orange', emoji: '🍊🧃☀️', group: 'Fruit', tags: ['fruit', 'sucré', 'jaune', 'rond', 'végétarien', 'petit-déjeuner', 'froid', 'mains'], clues: ['Agrume', 'Pleine de vitamine C', 'Se mange en quartiers', 'Pressée au petit-déjeuner', 'Même nom que sa couleur'] },
    { name: 'Citron', emoji: '🍋😖💛', group: 'Fruit', tags: ['fruit', 'jaune', 'végétarien', 'froid', 'rond', 'boisson', 'poisson', 'sauce'], clues: ['Agrume', 'Fait grimacer', 'On le presse sur le poisson', 'Indispensable pour une limonade', 'Jaune et très acide'] },
    { name: 'Noix de coco', aliases: ['Coco'], emoji: '🥥🌴🏝️', group: 'Fruit', tags: ['fruit', 'sucré', 'tropical', 'végétarien', 'rond', 'lait', 'boisson', 'dessert'], clues: ['Fruit des plages', 'Tombe des palmiers', 'Coque dure et poilue', 'Contient une eau sucrée', 'Chair blanche râpée'] },
    { name: 'Cerise', emoji: '🍒❤️🌸', group: 'Fruit', tags: ['fruit', 'sucré', 'rouge', 'rond', 'végétarien', 'dessert', 'mains', 'froid'], clues: ['Petit fruit d\'été', 'Pousse par deux', 'Noyau qu\'on crache', 'Posée sur le gâteau', 'Rouge avec une queue'] },
    { name: 'Kiwi', emoji: '🥝🟢🥄', group: 'Fruit', tags: ['fruit', 'sucré', 'vert', 'végétarien', 'rond', 'petit-déjeuner', 'froid', 'dessert'], clues: ['Petit fruit ovale', 'Peau marron et poilue', 'Petits grains noirs à l\'intérieur', 'Se mange à la petite cuillère', 'Même nom qu\'un oiseau'] },
    // ——— Légumes ———
    { name: 'Tomate', emoji: '🍅🥗❤️', group: 'Légume', tags: ['légume', 'fruit', 'rouge', 'rond', 'végétarien', 'froid', 'salé', 'sauce'], clues: ['Star des salades', 'Pousse en été', 'Base du ketchup', 'Techniquement un fruit', 'Rouge et ronde'] },
    { name: 'Carotte', emoji: '🥕🐰🧡', group: 'Légume', tags: ['légume', 'jaune', 'végétarien', 'salé', 'froid', 'chaud', 'mains'], clues: ['Pousse sous la terre', 'Bonne pour la vue selon la légende', 'Nez du bonhomme de neige', 'Adorée des lapins', 'Orange et pointue'] },
    { name: 'Brocoli', emoji: '🥦🌳💚', group: 'Légume', tags: ['légume', 'vert', 'végétarien', 'salé', 'chaud', 'froid', 'asiatique'], clues: ['Légume détesté des enfants', 'Ressemble à un petit arbre', 'Cuit à la vapeur', 'Plein de vitamines', 'Vert et en bouquets'] },
    { name: 'Pomme de terre', aliases: ['Patate'], emoji: '🥔🍟🌱', group: 'Légume', tags: ['légume', 'végétarien', 'salé', 'chaud', 'marron', 'frit', 'rond', 'français'], clues: ['Pousse sous la terre', 'Mille façons de la cuisiner', 'Base de la purée', 'Devient frites ou chips', 'Aussi appelée tubercule'] },
    { name: 'Piment', emoji: '🌶️🔥🥵', group: 'Légume', tags: ['légume', 'épicé', 'rouge', 'vert', 'végétarien', 'africain', 'sauce', 'tropical'], clues: ['Petit mais redoutable', 'Fait pleurer et transpirer', 'Rouge ou vert', 'Donne du feu aux sauces', 'Mesuré en unités Scoville'] },
    { name: 'Maïs', emoji: '🌽🍿🌾', group: 'Légume', tags: ['légume', 'jaune', 'végétarien', 'sucré', 'chaud', 'américain', 'mains'], clues: ['Céréale en épis', 'Grains jaunes', 'Grillé en épi au barbecue', 'Donne le pop-corn', 'Base des tortillas'] },
    // ——— Desserts & douceurs ———
    { name: 'Croissant', emoji: '🥐☕🇫🇷', group: 'Dessert', tags: ['sucré', 'français', 'pâte', 'petit-déjeuner', 'mains', 'jaune', 'lait', 'chaud'], clues: ['Viennoiserie', 'Pâte feuilletée au beurre', 'Trempé dans le café', 'Forme de lune', 'Star des boulangeries'] },
    { name: 'Pain au chocolat', aliases: ['Chocolatine'], emoji: '🥐🍫🥖', group: 'Dessert', tags: ['sucré', 'français', 'pâte', 'chocolat', 'petit-déjeuner', 'mains', 'lait', 'chaud'], clues: ['Viennoiserie', 'Pâte feuilletée', 'Deux barres de chocolat dedans', 'Débat sur son nom en France', 'Chocolatine pour le Sud-Ouest'] },
    { name: 'Crêpe', emoji: '🥞🍫🍓', group: 'Dessert', tags: ['sucré', 'chaud', 'français', 'pâte', 'lait', 'dessert', 'rond', 'chocolat', 'petit-déjeuner'], clues: ['Se fait à la poêle', 'Pâte très fine', 'On la fait sauter à la Chandeleur', 'Nutella ou sucre', 'Spécialité bretonne'] },
    { name: 'Chocolat', emoji: '🍫😋🍬', group: 'Dessert', tags: ['sucré', 'chocolat', 'dessert', 'marron', 'lait', 'africain', 'mains', 'partage'], clues: ['Douceur adorée', 'Vient d\'une fève', 'Noir, au lait ou blanc', 'Fond dans la main', 'Tablettes et œufs de Pâques'] },
    { name: 'Glace', aliases: ['Crème glacée'], emoji: '🍦🍨☀️', group: 'Dessert', tags: ['sucré', 'froid', 'dessert', 'lait', 'chocolat', 'mains', 'italien'], clues: ['Dessert d\'été', 'Fond vite au soleil', 'En cornet ou en pot', 'Vanille, fraise ou chocolat', 'Gelato en italien'] },
    { name: 'Tiramisu', emoji: '☕🍰🇮🇹', group: 'Dessert', tags: ['sucré', 'froid', 'dessert', 'italien', 'lait', 'chocolat', 'marron', 'partage'], clues: ['Dessert en couches', 'Biscuits trempés dans le café', 'Crème au mascarpone', 'Cacao saupoudré dessus', 'Dessert italien'] },
    { name: 'Macaron', emoji: '🍬🌈🇫🇷', group: 'Dessert', tags: ['sucré', 'français', 'dessert', 'rond', 'mains', 'froid', 'chocolat'], clues: ['Petite pâtisserie colorée', 'Deux coques et une ganache', 'Croquant puis fondant', 'Célèbre chez Ladurée', 'Poudre d\'amande'] },
    { name: 'Gâteau au chocolat', emoji: '🎂🍫🕯️', group: 'Dessert', tags: ['sucré', 'dessert', 'chocolat', 'marron', 'pâte', 'partage', 'rond', 'français'], clues: ['Dessert d\'anniversaire classique', 'Cuit au four', 'Fondant au milieu', 'On y plante des bougies', 'Couleur marron foncé'] },
    { name: 'Beignet', emoji: '🍩🤎🇨🇲', group: 'Dessert', tags: ['sucré', 'frit', 'pâte', 'dessert', 'mains', 'africain', 'rond', 'chaud', 'petit-déjeuner'], clues: ['Petite douceur dorée', 'Pâte frite dans l\'huile', 'Vendu au coin de la rue', 'Souvent avec de la bouillie', 'Beignets-haricots au Cameroun'] },
    { name: 'Donut', emoji: '🍩💗🇺🇸', group: 'Dessert', tags: ['sucré', 'frit', 'pâte', 'américain', 'dessert', 'rond', 'mains', 'chocolat', 'fast-food'], clues: ['Douceur américaine', 'Un trou au milieu', 'Glaçage rose et vermicelles', 'Préféré d\'Homer Simpson', 'Beignet en anneau'] },
    { name: 'Tarte aux pommes', emoji: '🥧🍎👵', group: 'Dessert', tags: ['sucré', 'dessert', 'français', 'pâte', 'fruit', 'rond', 'partage', 'chaud'], clues: ['Dessert de grand-mère', 'Pâte brisée ou feuilletée', 'Lamelles de fruit en rosace', 'Version renversée : tatin', 'Fruit du verger dessus'] },
    // ——— Boissons ———
    { name: 'Bissap', aliases: ['Jus d\'hibiscus'], emoji: '🌺🥤🇸🇳', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'africain', 'rouge', 'végétarien', 'tropical', 'partage'], clues: ['Boisson africaine', 'Couleur rouge foncé', 'Servi bien frais', 'Fait avec des fleurs', 'Jus d\'hibiscus'] },
    { name: 'Jus de gingembre', aliases: ['Gnamakoudji'], emoji: '🫚🥤🔥', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'africain', 'épicé', 'jaune', 'végétarien', 'tropical'], clues: ['Boisson africaine', 'Ça pique la gorge', 'Racine râpée', 'Souvent avec citron et ananas', 'Gnamakoudji en Côte d\'Ivoire'] },
    { name: 'Thé à la menthe', emoji: '🍵🌿🫖', group: 'Boisson', tags: ['boisson', 'sucré', 'chaud', 'africain', 'vert', 'végétarien', 'partage'], clues: ['Boisson de l\'hospitalité', 'Versée de très haut', 'Petits verres décorés', 'Feuilles fraîches', 'Tradition du Maghreb'] },
    { name: 'Café', emoji: '☕🫘⏰', group: 'Boisson', tags: ['boisson', 'chaud', 'marron', 'petit-déjeuner', 'végétarien', 'italien', 'lait'], clues: ['Boisson du réveil', 'Grains torréfiés', 'Expresso ou latte', 'Plein de caféine', 'Noir et amer'] },
    { name: 'Chocolat chaud', emoji: '☕🍫❄️', group: 'Boisson', tags: ['boisson', 'sucré', 'chaud', 'chocolat', 'lait', 'marron', 'petit-déjeuner'], clues: ['Boisson d\'hiver', 'Réconfortant', 'Parfois avec des marshmallows', 'Du lait chaud dedans', 'Cacao en poudre'] },
    { name: 'Jus d\'orange', emoji: '🧃🍊☀️', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'fruit', 'jaune', 'petit-déjeuner', 'végétarien'], clues: ['Boisson du matin', 'Avec ou sans pulpe', 'Plein de vitamine C', 'Fruit pressé', 'Agrume en jus'] },
    { name: 'Soda au cola', aliases: ['Cola', 'Coca'], emoji: '🥤🧊🫧', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'marron', 'fast-food', 'américain', 'végétarien', 'partage'], clues: ['Boisson gazeuse', 'Très sucrée', 'Avec des glaçons', 'Recette secrète', 'Marron foncé et pétillant'] },
    { name: 'Bubble tea', emoji: '🧋🟤🇹🇼', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'asiatique', 'lait', 'végétarien', 'fast-food'], clues: ['Boisson à la mode', 'Grosse paille', 'Des billes au fond', 'Perles de tapioca', 'Originaire de Taïwan'] },
    { name: 'Smoothie', emoji: '🥤🍓🍌', group: 'Boisson', tags: ['boisson', 'sucré', 'froid', 'fruit', 'végétarien', 'petit-déjeuner', 'lait'], clues: ['Boisson healthy', 'Mixée au blender', 'Épaisse et onctueuse', 'Banane-fraise classique', 'Fruits mixés'] },
    // ——— Autres ———
    { name: 'Baguette', emoji: '🥖🇫🇷🧈', group: 'Boulangerie', tags: ['français', 'pâte', 'salé', 'petit-déjeuner', 'mains', 'végétarien', 'partage', 'jaune'], clues: ['Achetée tous les jours', 'Croûte croustillante', 'On mange souvent le bout en rentrant', 'Sous le bras', 'Pain long français'] },
    { name: 'Camembert', emoji: '🧀🐄🇫🇷', group: 'Fromage', tags: ['français', 'fromage', 'salé', 'lait', 'rond', 'végétarien', 'partage'], clues: ['Produit laitier', 'Boîte ronde en bois', 'Croûte blanche', 'Sent assez fort', 'Fromage de Normandie'] },
    { name: 'Miel', emoji: '🍯🐝🌼', group: 'Épicerie', tags: ['sucré', 'jaune', 'marron', 'petit-déjeuner', 'végétarien', 'dessert', 'sauce'], clues: ['Produit naturel', 'Doré et collant', 'Dans un pot', 'Winnie l\'Ourson l\'adore', 'Fabriqué par les abeilles'] },
  ],
};
