import type { Pack } from '../types';

export const pack: Pack = {
  id: 'objets',
  name: 'Objets du quotidien',
  emoji: '🔑',
  category: 'objets',
  description: 'Les objets qu\'on utilise tous les jours, à la maison, à l\'école ou dehors.',
  attributes: [
    { tag: 'électrique', question: 'Est-ce que ça fonctionne à l\'électricité ou sur batterie ?' },
    { tag: 'écran', question: 'Y a-t-il un écran ?' },
    { tag: 'plastique', question: 'Est-ce souvent en plastique ?' },
    { tag: 'métal', question: 'Est-ce souvent en métal ?' },
    { tag: 'bois', question: 'Est-ce souvent en bois ?' },
    { tag: 'tissu', question: 'Est-ce en tissu ?' },
    { tag: 'verre', question: 'Y a-t-il du verre ?' },
    { tag: 'papier', question: 'Est-ce en papier ?' },
    { tag: 'petit', question: 'Est-ce que ça tient dans une main ?' },
    { tag: 'grand', question: 'Est-ce plus grand qu\'une chaise ?' },
    { tag: 'poche', question: 'Est-ce que ça rentre dans une poche ?' },
    { tag: 'cuisine', question: 'Le trouve-t-on dans la cuisine ?' },
    { tag: 'salle-de-bain', question: 'Le trouve-t-on dans la salle de bain ?' },
    { tag: 'chambre', question: 'Le trouve-t-on dans la chambre ?' },
    { tag: 'salon', question: 'Le trouve-t-on dans le salon ?' },
    { tag: 'école', question: 'L\'utilise-t-on à l\'école ou au bureau ?' },
    { tag: 'tech', question: 'Est-ce un objet high-tech ?' },
    { tag: 'vêtement', question: 'Est-ce un vêtement ou un accessoire qu\'on porte ?' },
    { tag: 'coupant', question: 'Est-ce que ça coupe ou ça pique ?' },
    { tag: 'chaud', question: 'Est-ce que ça chauffe ou sert à avoir chaud ?' },
    { tag: 'eau', question: 'Est-ce en lien avec l\'eau ?' },
    { tag: 'lumière', question: 'Est-ce que ça fait de la lumière ?' },
    { tag: 'bruit', question: 'Est-ce que ça fait du bruit ou du son ?' },
    { tag: 'rond', question: 'Est-ce rond ?' },
    { tag: 'loisir', question: 'Est-ce que ça sert à s\'amuser ?' },
    { tag: 'outil', question: 'Est-ce un outil ?' },
    { tag: 'nettoyage', question: 'Est-ce que ça sert à nettoyer ?' },
    { tag: 'hygiène', question: 'Est-ce lié à l\'hygiène ?' },
    { tag: 'dehors', question: 'L\'utilise-t-on surtout dehors ?' },
    { tag: 'nourriture', question: 'Est-ce lié à la nourriture ?' },
    { tag: 'quotidien', question: 'L\'utilise-t-on tous les jours ?' },
    { tag: 'paire', question: 'Est-ce que ça va par deux ?' },
    { tag: 'musique', question: 'Est-ce lié à la musique ou au son ?' },
    { tag: 'dormir', question: 'Est-ce lié au sommeil ?' },
    { tag: 'transport', question: 'Est-ce que ça sert à se déplacer ou à transporter ?' },
  ],
  items: [
    // ——— Tech ———
    { name: 'Téléphone', aliases: ['Smartphone', 'Portable'], emoji: '📱📞🔋', group: 'Tech', tags: ['électrique', 'écran', 'tech', 'petit', 'poche', 'quotidien', 'bruit', 'verre', 'musique'], clues: ['Objet qu\'on regarde 100 fois par jour', 'Tient dans la main', 'Doit être rechargé', 'Sert à envoyer des messages', 'iPhone ou Android'] },
    { name: 'Casque audio', aliases: ['Casque'], emoji: '🎧🎶🔊', group: 'Tech', tags: ['électrique', 'tech', 'musique', 'bruit', 'plastique', 'chambre', 'paire', 'quotidien'], clues: ['Se met sur la tête', 'Isole du bruit', 'Filaire ou sans fil', 'Deux coussinets', 'Pour écouter de la musique'] },
    { name: 'Écouteurs', emoji: '🎵👂🔋', group: 'Tech', tags: ['électrique', 'tech', 'musique', 'bruit', 'petit', 'poche', 'paire', 'plastique', 'quotidien'], clues: ['Minuscules', 'On en perd souvent un', 'Petit boîtier de recharge', 'Se mettent dans les oreilles', 'AirPods par exemple'] },
    { name: 'Manette', aliases: ['Manette de jeu'], emoji: '🎮🕹️🔋', group: 'Tech', tags: ['électrique', 'tech', 'loisir', 'plastique', 'petit', 'salon', 'chambre', 'paire'], clues: ['Se tient à deux mains', 'Joysticks et gâchettes', 'Vibre parfois', 'Reliée à une console', 'Sert à jouer aux jeux vidéo'] },
    { name: 'Télécommande', emoji: '📺🔘🔋', group: 'Tech', tags: ['électrique', 'tech', 'petit', 'salon', 'plastique', 'quotidien', 'loisir'], clues: ['Toujours perdue dans le canapé', 'Plein de boutons', 'Marche avec des piles', 'On zappe avec', 'Contrôle la télé'] },
    { name: 'Télévision', aliases: ['Télé', 'TV'], emoji: '📺🛋️🍿', group: 'Tech', tags: ['électrique', 'écran', 'tech', 'grand', 'salon', 'bruit', 'loisir', 'quotidien', 'lumière'], clues: ['Au centre du salon', 'Écran plat de plus en plus grand', 'Chaînes et programmes', 'On regarde les matchs dessus', 'Allumée avec une télécommande'] },
    { name: 'Ordinateur portable', aliases: ['Ordinateur', 'PC portable', 'Laptop'], emoji: '💻⌨️🖱️', group: 'Tech', tags: ['électrique', 'écran', 'tech', 'école', 'plastique', 'métal', 'quotidien', 'loisir', 'bruit'], clues: ['Se plie en deux', 'Clavier et pavé tactile', 'Sert aux devoirs et au travail', 'Se recharge sur secteur', 'MacBook par exemple'] },
    { name: 'Tablette', emoji: '📲👆🎬', group: 'Tech', tags: ['électrique', 'écran', 'tech', 'loisir', 'verre', 'salon', 'chambre', 'bruit'], clues: ['Plus grande qu\'un téléphone', 'Écran tactile', 'Les enfants adorent', 'Pour regarder des vidéos', 'iPad par exemple'] },
    { name: 'Chargeur', emoji: '🔌🔋⚡', group: 'Tech', tags: ['électrique', 'tech', 'petit', 'plastique', 'chambre', 'quotidien', 'poche'], clues: ['On l\'emprunte souvent aux amis', 'Câble et prise', 'Branché au mur', 'Indispensable à 1 % de batterie', 'Recharge le téléphone'] },
    { name: 'Enceinte Bluetooth', aliases: ['Enceinte'], emoji: '🔊🎶📶', group: 'Tech', tags: ['électrique', 'tech', 'musique', 'bruit', 'plastique', 'loisir', 'dehors', 'petit'], clues: ['Met l\'ambiance', 'Sans fil', 'On la connecte au téléphone', 'Emportée à la plage ou en soirée', 'Diffuse la musique fort'] },
    { name: 'Appareil photo', emoji: '📷📸🎞️', group: 'Tech', tags: ['électrique', 'tech', 'écran', 'verre', 'loisir', 'dehors', 'petit', 'bruit'], clues: ['Emporté en voyage', 'Objectif et flash', 'Fait « clic »', 'Remplacé par le téléphone', 'Sert à prendre des photos'] },
    { name: 'Clé USB', emoji: '💾🔌🗂️', group: 'Tech', tags: ['électrique', 'tech', 'petit', 'poche', 'plastique', 'métal', 'école'], clues: ['Minuscule', 'Se branche sur l\'ordinateur', 'On ne la met jamais dans le bon sens', 'Stocke des fichiers', 'Mémoire portable'] },
    // ——— Accessoires & vêtements ———
    { name: 'Parapluie', emoji: '☂️🌧️💧', group: 'Accessoires', tags: ['dehors', 'eau', 'tissu', 'métal', 'transport', 'vêtement', 'grand'], clues: ['On l\'oublie partout', 'S\'ouvre et se ferme', 'Se retourne avec le vent', 'Mary Poppins vole avec', 'Protège de la pluie'] },
    { name: 'Clé', aliases: ['Clés'], emoji: '🔑🚪🔒', group: 'Accessoires', tags: ['plastique', 'métal', 'petit', 'poche', 'quotidien', 'outil', 'dehors'], clues: ['Petit objet en métal', 'On la cherche avant de partir', 'Souvent en trousseau', 'Tourne dans une serrure', 'Ouvre la porte'] },
    { name: 'Portefeuille', emoji: '👛💳💶', group: 'Accessoires', tags: ['plastique', 'petit', 'poche', 'quotidien', 'vêtement', 'tissu', 'dehors'], clues: ['Toujours sur soi', 'Cuir ou tissu', 'Contient des cartes', 'Pièces et billets', 'Range l\'argent'] },
    { name: 'Montre', emoji: '⌚⏰💎', group: 'Accessoires', tags: ['vêtement', 'petit', 'métal', 'verre', 'quotidien', 'rond', 'tech'], clues: ['Se porte au poignet', 'Bracelet', 'Aiguilles ou écran', 'Rolex ou connectée', 'Donne l\'heure'] },
    { name: 'Lunettes', emoji: '👓👀🕶️', group: 'Accessoires', tags: ['vêtement', 'verre', 'petit', 'paire', 'quotidien', 'plastique', 'métal'], clues: ['Se posent sur le nez', 'Branches et verres', 'Se rangent dans un étui', 'De vue ou de soleil', 'Aident à mieux voir'] },
    { name: 'Sac à dos', emoji: '🎒📚🏕️', group: 'Accessoires', tags: ['tissu', 'école', 'transport', 'quotidien', 'vêtement', 'dehors', 'grand'], clues: ['Se porte sur les épaules', 'Plein de poches', 'Emporté en randonnée', 'Trop lourd à la rentrée', 'Cartable des grands'] },
    { name: 'Chaussette', aliases: ['Chaussettes'], emoji: '🧦👣🧺', group: 'Vêtements', tags: ['vêtement', 'tissu', 'paire', 'petit', 'quotidien', 'chaud', 'chambre'], clues: ['Vêtement discret', 'Disparaît dans la machine à laver', 'Va par deux', 'Se met avant les chaussures', 'Couvre le pied'] },
    { name: 'Baskets', aliases: ['Chaussures', 'Sneakers'], emoji: '👟🏃👣', group: 'Vêtements', tags: ['vêtement', 'paire', 'tissu', 'plastique', 'quotidien', 'dehors', 'transport'], clues: ['Collectionnées par certains', 'Lacets', 'Semelles en caoutchouc', 'Nike ou Adidas', 'Se portent aux pieds'] },
    { name: 'Casquette', emoji: '🧢☀️😎', group: 'Vêtements', tags: ['sport', 'vêtement', 'tissu', 'dehors', 'petit', 'quotidien', 'loisir'], clues: ['Accessoire de tête', 'Portée à l\'envers par certains', 'Protège du soleil', 'Logo souvent devant', 'A une visière'] },
    { name: 'Écharpe', emoji: '🧣❄️🧶', group: 'Vêtements', tags: ['quotidien', 'loisir', 'vêtement', 'tissu', 'chaud', 'dehors', 'petit'], clues: ['Accessoire d\'hiver', 'Souvent en laine', 'Supporters au stade', 'S\'enroule', 'Autour du cou'] },
    { name: 'Gants', emoji: '🧤❄️✋', group: 'Vêtements', tags: ['vêtement', 'tissu', 'chaud', 'paire', 'dehors', 'petit', 'nettoyage'], clues: ['Accessoire d\'hiver', 'Cinq doigts', 'On en perd souvent un', 'Protège du froid ou de la saleté', 'Se portent sur les mains'] },
    { name: 'Ceinture', emoji: '👖🔗🟫', group: 'Vêtements', tags: ['chambre', 'outil', 'vêtement', 'métal', 'quotidien', 'petit', 'tissu'], clues: ['Accessoire de pantalon', 'Boucle métallique', 'Des trous pour régler', 'Aussi grade au judo', 'Tient le pantalon'] },
    // ——— École / Bureau ———
    { name: 'Stylo', aliases: ['Bic'], emoji: '🖊️📝✍️', group: 'École', tags: ['métal', 'école', 'petit', 'poche', 'plastique', 'quotidien', 'outil'], clues: ['Objet qu\'on mâchouille', 'On le prête et ne le revoit jamais', 'Bleu, rouge, noir ou vert', 'Contient de l\'encre', 'Sert à écrire'] },
    { name: 'Cahier', emoji: '📓✏️🏫', group: 'École', tags: ['plastique', 'outil', 'école', 'papier', 'petit', 'quotidien', 'chambre'], clues: ['Fourniture scolaire', 'Grands ou petits carreaux', 'Couverture plastique colorée', 'On y prend des notes', 'Pages reliées'] },
    { name: 'Ciseaux', emoji: '✂️📄🔪', group: 'École', tags: ['école', 'coupant', 'métal', 'plastique', 'petit', 'outil', 'cuisine'], clues: ['Deux lames', 'On ne court pas avec', 'Anneaux pour les doigts', 'Pierre-feuille-___', 'Sert à couper le papier'] },
    { name: 'Calculatrice', emoji: '🧮➕🔢', group: 'École', tags: ['école', 'électrique', 'écran', 'tech', 'petit', 'plastique', 'outil'], clues: ['Interdite à certains examens', 'Touches avec des chiffres', 'Petit écran', 'Casio ou Texas', 'Fait les calculs'] },
    { name: 'Gomme', emoji: '🧽✏️🩷', group: 'École', tags: ['rond', 'école', 'petit', 'poche', 'plastique', 'nettoyage', 'outil'], clues: ['Fourniture scolaire', 'Petit bloc souple', 'Laisse des miettes', 'Parfois parfumée', 'Efface le crayon'] },
    { name: 'Livre', emoji: '📖📚🤓', group: 'École', tags: ['quotidien', 'école', 'papier', 'loisir', 'chambre', 'salon', 'petit'], clues: ['Objet plein d\'histoires', 'Couverture et pages', 'On le range dans une bibliothèque', 'Marque-page', 'Se lit'] },
    // ——— Chambre ———
    { name: 'Oreiller', aliases: ['Coussin'], emoji: '🛏️😴☁️', group: 'Chambre', tags: ['salon', 'chambre', 'dormir', 'tissu', 'quotidien', 'chaud', 'grand'], clues: ['Objet très doux', 'Bataille lors des soirées pyjama', 'Taie qu\'on lave', 'On le retourne côté frais', 'Sous la tête la nuit'] },
    { name: 'Couette', emoji: '🛏️❄️😴', group: 'Chambre', tags: ['salon', 'chambre', 'dormir', 'tissu', 'chaud', 'grand', 'quotidien'], clues: ['Difficile de la quitter le matin', 'Housse à changer', 'Très moelleuse', 'Garde au chaud l\'hiver', 'Sur le lit'] },
    { name: 'Réveil', emoji: '⏰😫🔔', group: 'Chambre', tags: ['chambre', 'dormir', 'bruit', 'électrique', 'petit', 'quotidien', 'rond'], clues: ['Objet détesté le matin', 'Posé sur la table de nuit', 'Bouton « snooze »', 'Sonne très fort', 'Réveille à l\'heure'] },
    { name: 'Lampe', aliases: ['Lampe de chevet'], emoji: '💡🛋️🌙', group: 'Chambre', tags: ['petit', 'lumière', 'électrique', 'chambre', 'salon', 'verre', 'quotidien'], clues: ['Objet de décoration utile', 'Abat-jour', 'Interrupteur', 'Contient une ampoule', 'Éclaire la pièce'] },
    { name: 'Bougie', emoji: '🕯️🔥🎂', group: 'Salon', tags: ['chambre', 'lumière', 'chaud', 'salon', 'petit', 'rond', 'loisir'], clues: ['Crée une ambiance', 'Cire qui coule', 'Parfois parfumée', 'On la souffle aux anniversaires', 'Mèche allumée'] },
    { name: 'Miroir', emoji: '🪞✨👀', group: 'Salle de bain', tags: ['métal', 'verre', 'salle-de-bain', 'chambre', 'quotidien', 'grand', 'hygiène'], clues: ['Objet fragile', 'Casser porte malheur', '« Dis-moi qui est la plus belle »', 'On s\'y regarde', 'Reflète l\'image'] },
    // ——— Salle de bain ———
    { name: 'Brosse à dents', emoji: '🪥🦷✨', group: 'Salle de bain', tags: ['salle-de-bain', 'hygiène', 'petit', 'plastique', 'quotidien', 'eau', 'nettoyage'], clues: ['S\'utilise matin et soir', 'Petits poils', 'Électrique ou manuelle', 'À changer tous les 3 mois', 'Avec du dentifrice'] },
    { name: 'Dentifrice', emoji: '🦷🪥🌿', group: 'Salle de bain', tags: ['salle-de-bain', 'hygiène', 'petit', 'plastique', 'quotidien', 'nettoyage', 'eau'], clues: ['Goût mentholé', 'Dans un tube', 'On presse du milieu ou du bout', 'Fait de la mousse', 'Pâte pour les dents'] },
    { name: 'Savon', emoji: '🧼🫧🤲', group: 'Salle de bain', tags: ['salle-de-bain', 'hygiène', 'nettoyage', 'eau', 'petit', 'quotidien', 'cuisine'], clues: ['Sent bon', 'Glisse des mains', 'Fait des bulles', 'Liquide ou en pain', 'Pour se laver les mains'] },
    { name: 'Serviette', aliases: ['Serviette de bain'], emoji: '🛁🏖️🧺', group: 'Salle de bain', tags: ['salle-de-bain', 'tissu', 'hygiène', 'eau', 'quotidien', 'grand', 'dehors'], clues: ['Objet moelleux', 'Accrochée à un crochet', 'Emportée à la plage', 'On s\'enroule dedans', 'Sert à se sécher'] },
    { name: 'Sèche-cheveux', emoji: '💨💇🔌', group: 'Salle de bain', tags: ['salle-de-bain', 'électrique', 'chaud', 'bruit', 'hygiène', 'plastique', 'petit'], clues: ['Fait beaucoup de bruit', 'Souffle très fort', 'Air chaud ou froid', 'Branché près du miroir', 'Pour sécher ses cheveux'] },
    { name: 'Peigne', aliases: ['Brosse à cheveux'], emoji: '💇🪮✨', group: 'Salle de bain', tags: ['métal', 'salle-de-bain', 'hygiène', 'petit', 'poche', 'plastique', 'quotidien'], clues: ['Petit accessoire', 'Dents fines', 'Démêle les nœuds', 'Rangé dans la trousse de toilette', 'Coiffe les cheveux'] },
    { name: 'Papier toilette', aliases: ['PQ'], emoji: '🧻🚽😅', group: 'Salle de bain', tags: ['petit', 'salle-de-bain', 'hygiène', 'papier', 'quotidien', 'rond', 'nettoyage'], clues: ['Acheté en gros paquets', 'Rouleau', 'Pénurie célèbre en 2020', 'Double épaisseur', 'Indispensable aux WC'] },
    // ——— Cuisine ———
    { name: 'Frigo', aliases: ['Réfrigérateur', 'Frigidaire'], emoji: '🧊🥛🥶', group: 'Cuisine', tags: ['cuisine', 'électrique', 'grand', 'nourriture', 'quotidien', 'bruit', 'lumière', 'métal'], clues: ['Gros appareil de la cuisine', 'On l\'ouvre en cherchant quoi manger', 'Aimants sur la porte', 'Une lumière s\'allume dedans', 'Garde la nourriture au frais'] },
    { name: 'Micro-ondes', emoji: '♨️🍲⏲️', group: 'Cuisine', tags: ['cuisine', 'électrique', 'chaud', 'nourriture', 'bruit', 'lumière', 'quotidien', 'verre'], clues: ['Appareil de cuisine', 'Plateau qui tourne', 'Fait « ding » à la fin', 'Ne jamais y mettre de métal', 'Réchauffe les plats'] },
    { name: 'Four', emoji: '🔥🍕🍗', group: 'Cuisine', tags: ['cuisine', 'électrique', 'chaud', 'nourriture', 'grand', 'métal', 'verre', 'lumière'], clues: ['Appareil de cuisine', 'Très chaud', 'Porte vitrée', 'On y met un gratin', 'Cuit les gâteaux'] },
    { name: 'Bouilloire', emoji: '🫖💨☕', group: 'Cuisine', tags: ['cuisine', 'électrique', 'chaud', 'eau', 'bruit', 'plastique', 'quotidien'], clues: ['Appareil de cuisine', 'Siffle ou fait « clic »', 'Pour le thé ou les nouilles', 'Fait de la vapeur', 'Fait bouillir l\'eau'] },
    { name: 'Poêle', emoji: '🍳🔥🥞', group: 'Cuisine', tags: ['cuisine', 'métal', 'chaud', 'nourriture', 'outil', 'rond', 'quotidien'], clues: ['Ustensile de cuisine', 'Long manche', 'Revêtement antiadhésif', 'Arme de Raiponce', 'Pour cuire les crêpes'] },
    { name: 'Fourchette', emoji: '🍴🍝🥗', group: 'Cuisine', tags: ['cuisine', 'métal', 'nourriture', 'petit', 'coupant', 'quotidien', 'outil'], clues: ['Couvert', 'Posée à gauche de l\'assiette', 'Quatre dents', 'Pique les aliments', 'On enroule les spaghettis avec'] },
    { name: 'Couteau', emoji: '🔪🥩🧈', group: 'Cuisine', tags: ['cuisine', 'métal', 'coupant', 'nourriture', 'petit', 'outil', 'quotidien'], clues: ['Couvert', 'Posé à droite de l\'assiette', 'Lame', 'Dangereux pour les enfants', 'Sert à couper'] },
    { name: 'Tasse', aliases: ['Mug'], emoji: '☕🫖🍵', group: 'Cuisine', tags: ['cuisine', 'nourriture', 'petit', 'quotidien', 'chaud', 'rond', 'verre'], clues: ['Objet du petit-déjeuner', 'Possède une anse', 'Souvent en céramique', 'Cadeau souvent personnalisé', 'Pour boire le café'] },
    { name: 'Assiette', emoji: '🍽️🥘🍰', group: 'Cuisine', tags: ['plastique', 'cuisine', 'nourriture', 'rond', 'verre', 'quotidien', 'petit'], clues: ['Vaisselle', 'Plate ou creuse', 'Se casse si on la fait tomber', 'On la met au lave-vaisselle', 'On y sert le repas'] },
    { name: 'Bouteille d\'eau', aliases: ['Gourde'], emoji: '🍼💧🥤', group: 'Cuisine', tags: ['eau', 'plastique', 'nourriture', 'quotidien', 'transport', 'dehors', 'petit', 'sport'], clues: ['Toujours dans le sac', 'Bouchon qui se visse', 'Réutilisable, c\'est mieux', 'Emportée au sport', 'Pour boire'] },
    // ——— Salon / Maison ———
    { name: 'Canapé', emoji: '🛋️📺😴', group: 'Salon', tags: ['salon', 'grand', 'tissu', 'dormir', 'quotidien', 'loisir', 'bois'], clues: ['Meuble confortable', 'Coussins dessus', 'Peut devenir un lit', 'La télécommande tombe entre les coussins', 'On s\'y affale devant la télé'] },
    { name: 'Chaise', emoji: '🪑🍽️🏫', group: 'Salon', tags: ['grand', 'salon', 'cuisine', 'école', 'bois', 'quotidien', 'plastique'], clues: ['Meuble très courant', 'Quatre pieds', 'Un dossier', 'Jeu des ___ musicales', 'Sert à s\'asseoir'] },
    { name: 'Ventilateur', emoji: '🌀💨☀️', group: 'Salon', tags: ['électrique', 'bruit', 'chambre', 'salon', 'plastique', 'rond', 'grand'], clues: ['Objet d\'été', 'Pales qui tournent', 'On parle devant pour faire une voix robot', 'Au plafond ou sur pied', 'Rafraîchit l\'air'] },
    { name: 'Aspirateur', emoji: '🧹💨🔌', group: 'Ménage', tags: ['électrique', 'nettoyage', 'bruit', 'grand', 'plastique', 'salon', 'outil'], clues: ['Appareil de ménage', 'Très bruyant', 'Long tuyau', 'Parfois robot', 'Aspire la poussière'] },
    { name: 'Balai', emoji: '🧹🧙‍♀️🗑️', group: 'Ménage', tags: ['quotidien', 'nettoyage', 'bois', 'plastique', 'outil', 'grand', 'cuisine'], clues: ['Objet de ménage', 'Long manche', 'Poils en bas', 'Moyen de transport des sorcières', 'Sert à balayer'] },
    { name: 'Machine à laver', aliases: ['Lave-linge'], emoji: '🧺🌀💧', group: 'Ménage', tags: ['électrique', 'nettoyage', 'eau', 'bruit', 'grand', 'salle-de-bain', 'rond', 'tissu'], clues: ['Gros appareil', 'Hublot rond', 'Tourne et essore', 'Mange les chaussettes', 'Lave le linge'] },
    { name: 'Fer à repasser', emoji: '👔♨️💨', group: 'Ménage', tags: ['électrique', 'chaud', 'tissu', 'vêtement', 'eau', 'outil', 'petit'], clues: ['Appareil de ménage', 'Semelle très chaude', 'Fait de la vapeur', 'Sur une planche', 'Enlève les plis'] },
    // ——— Outils ———
    { name: 'Marteau', emoji: '🔨🪚🧰', group: 'Outils', tags: ['plastique', 'dehors', 'outil', 'métal', 'bois', 'bruit', 'petit'], clues: ['Dans la caisse à outils', 'Manche et tête lourde', 'Fait « bang »', 'Arme de Thor', 'Enfonce les clous'] },
    { name: 'Tournevis', emoji: '🪛🔩🧰', group: 'Outils', tags: ['école', 'outil', 'métal', 'plastique', 'petit', 'coupant', 'poche'], clues: ['Dans la caisse à outils', 'Plat ou cruciforme', 'Se tourne', 'Le Docteur en a un « sonique »', 'Visse et dévisse'] },
    { name: 'Cadenas', emoji: '🔒🔑🚲', group: 'Outils', tags: ['école', 'poche', 'métal', 'petit', 'dehors', 'outil', 'transport'], clues: ['Objet de sécurité', 'Anse en métal', 'À code ou à clé', 'Accroché au casier', 'Protège le vélo'] },
    // ——— Loisirs & dehors ———
    { name: 'Ballon', aliases: ['Ballon de foot'], emoji: '⚽🏀🏐', group: 'Loisirs', tags: ['grand', 'loisir', 'sport', 'rond', 'dehors', 'plastique', 'tissu'], clues: ['Objet de cour de récré', 'Se gonfle', 'Rebondit', 'On tape dedans', 'Rond et sportif'] },
    { name: 'Vélo', aliases: ['Bicyclette'], emoji: '🚲🚴🔔', group: 'Loisirs', tags: ['transport', 'dehors', 'sport', 'métal', 'loisir', 'grand', 'paire', 'rond'], clues: ['Moyen de transport écolo', 'Guidon et pédales', 'Deux roues', 'On l\'apprend petit', 'Tour de France'] },
    { name: 'Trottinette', emoji: '🛴💨🏙️', group: 'Loisirs', tags: ['plastique', 'transport', 'dehors', 'métal', 'loisir', 'électrique', 'grand'], clues: ['Moyen de transport urbain', 'Un pied dessus', 'Guidon et plateau', 'Souvent électrique', 'Deux petites roues'] },
  ],
};
