import type { Pack } from '../types';

export const pack: Pack = {
  id: 'sport',
  name: 'Stars du sport',
  emoji: '🏅',
  category: 'sport',
  description: 'Basket, tennis, F1, athlétisme, combat… les grands champions de tous les sports.',
  attributes: [
    { tag: 'femme', question: 'Est-ce une femme ?' },
    { tag: 'français', question: 'Est-il/elle français(e) ?' },
    { tag: 'américain', question: 'Est-il/elle américain(e) ?' },
    { tag: 'europe', question: 'Vient-il/elle d’Europe ?' },
    { tag: 'amérique-du-nord', question: 'Vient-il/elle d’Amérique du Nord ?' },
    { tag: 'afrique', question: 'Vient-il d’Afrique ?' },
    { tag: 'sport-collectif', question: 'Pratique-t-il/elle un sport collectif ?' },
    { tag: 'sport-individuel', question: 'Pratique-t-il/elle un sport individuel ?' },
    { tag: 'basket', question: 'Joue-t-il au basket ?' },
    { tag: 'nba', question: 'A-t-il joué en NBA ?' },
    { tag: 'tennis', question: 'Joue-t-il/elle au tennis ?' },
    { tag: 'athlétisme', question: 'Fait-il/elle de l’athlétisme ?' },
    { tag: 'formule-1', question: 'Est-ce un pilote de Formule 1 ?' },
    { tag: 'sport-de-combat', question: 'Pratique-t-il/elle un sport de combat ?' },
    { tag: 'boxe', question: 'A-t-il/elle boxé ?' },
    { tag: 'mma', question: 'Fait-il du MMA ?' },
    { tag: 'natation', question: 'Est-ce un(e) nageur(se) ?' },
    { tag: 'judo', question: 'Fait-il/elle du judo ?' },
    { tag: 'rugby', question: 'Joue-t-il au rugby ?' },
    { tag: 'cyclisme', question: 'Est-ce un cycliste ?' },
    { tag: 'retraité', question: 'A-t-il/elle pris sa retraite ?' },
    { tag: 'en-activité', question: 'Est-il/elle encore en activité ?' },
    { tag: 'décédé', question: 'Est-il décédé ?' },
    { tag: 'champion-olympique', question: 'A-t-il/elle été champion(ne) olympique ?' },
    { tag: 'médaillé-paris-2024', question: 'A-t-il/elle gagné une médaille à Paris 2024 ?' },
    { tag: 'record-du-monde', question: 'A-t-il/elle battu un record du monde ?' },
    { tag: 'champion-du-monde', question: 'A-t-il/elle été champion(ne) du monde ?' },
    { tag: 'numéro-1-mondial', question: 'A-t-il/elle été numéro 1 mondial(e) ?' },
    { tag: 'nouvelle-génération', question: 'Est-il/elle né(e) après 1995 ?' },
  ],
  items: [
    // ── Basket ──
    {
      name: 'LeBron James',
      aliases: ['LeBron', 'King James', 'Lebron James'],
      emoji: '👑🏀💜',
      group: 'Basket',
      tags: ['homme', 'américain', 'amérique-du-nord', 'basket', 'nba', 'sport-collectif', 'champion-olympique', 'médaillé-paris-2024'],
      clues: ['Basketteur américain né à Akron, dans l’Ohio', 'Drafté directement après le lycée en 2003', 'Titres NBA avec Miami, Cleveland et Los Angeles', 'Meilleur marqueur de l’histoire de la NBA', 'Champion olympique à Paris en 2024', 'Surnommé « King James »'],
    },
    {
      name: 'Michael Jordan',
      aliases: ['Jordan', 'MJ', 'Air Jordan'],
      emoji: '🐐🏀🐂',
      group: 'Basket',
      tags: ['homme', 'américain', 'amérique-du-nord', 'basket', 'nba', 'sport-collectif', 'retraité', 'champion-olympique', 'légende'],
      clues: ['Légende du basket des années 1990', 'Six titres NBA avec les Chicago Bulls', 'Numéro 23 mythique', 'Membre de la « Dream Team » 1992', 'Sa marque de baskets porte son nom', 'Surnommé « Air » ou MJ'],
    },
    {
      name: 'Kobe Bryant',
      aliases: ['Kobe', 'Black Mamba'],
      emoji: '🐍🏀💛',
      group: 'Basket',
      tags: ['homme', 'américain', 'amérique-du-nord', 'basket', 'nba', 'sport-collectif', 'retraité', 'décédé', 'champion-olympique'],
      clues: ['Basketteur américain ayant grandi en Italie', 'Vingt saisons avec les Lakers', 'Cinq titres NBA', 'Match à 81 points en 2006', 'Surnommé « Black Mamba »', 'Kobe, décédé en 2020'],
    },
    {
      name: 'Stephen Curry',
      aliases: ['Curry', 'Steph Curry', 'Steph'],
      emoji: '🎯🏀💙',
      group: 'Basket',
      tags: ['homme', 'américain', 'amérique-du-nord', 'basket', 'nba', 'sport-collectif', 'en-activité', 'champion-olympique', 'médaillé-paris-2024'],
      clues: ['Meneur américain au tir redoutable', 'Fidèle aux Golden State Warriors', 'Recordman de paniers à trois points', 'Quatre titres NBA', 'Champion olympique à Paris en 2024', 'Steph, surnommé « Chef Curry »'],
    },
    {
      name: 'Tony Parker',
      aliases: ['Parker', 'TP'],
      emoji: '🇫🇷🏀⚡',
      group: 'Basket',
      tags: ['homme', 'français', 'europe', 'basket', 'nba', 'sport-collectif', 'retraité'],
      clues: ['Meneur français très rapide', 'Quatre titres NBA avec San Antonio', 'MVP des Finales NBA 2007', 'Champion d’Europe 2013 avec les Bleus', 'Président du club de l’ASVEL', 'TP, numéro 9 des Spurs'],
    },
    {
      name: 'Victor Wembanyama',
      aliases: ['Wembanyama', 'Wemby', 'Victor'],
      emoji: '👽🏀🇫🇷',
      group: 'Basket',
      tags: ['homme', 'français', 'europe', 'basket', 'nba', 'sport-collectif', 'en-activité', 'médaillé-paris-2024', 'nouvelle-génération'],
      clues: ['Basketteur français de plus de 2,20 m', 'Formé à Nanterre', 'Premier choix de la draft NBA 2023', 'Rookie de l’année avec les Spurs', 'Vice-champion olympique à Paris 2024', 'Surnommé « l’Alien »'],
    },
    {
      name: 'Rudy Gobert',
      aliases: ['Gobert'],
      emoji: '🗼🏀🖐️',
      group: 'Basket',
      tags: ['homme', 'français', 'europe', 'basket', 'nba', 'sport-collectif', 'en-activité', 'médaillé-paris-2024'],
      clues: ['Pivot français géant', 'Spécialiste des contres', 'Quatre fois meilleur défenseur de la NBA', 'Longtemps au Utah Jazz', 'Joue ensuite à Minnesota', 'Surnommé « Stifle Tower »'],
    },
    {
      name: 'Shaquille O’Neal',
      aliases: ['Shaq', 'Shaquille', 'O’Neal'],
      emoji: '💪🏀🦍',
      group: 'Basket',
      tags: ['homme', 'américain', 'amérique-du-nord', 'basket', 'nba', 'sport-collectif', 'retraité', 'champion-olympique'],
      clues: ['Pivot américain colossal', 'Trois titres de suite avec les Lakers', 'Champion olympique en 1996', 'Duo mythique avec Kobe Bryant', 'A aussi sorti des albums de rap', 'Surnommé Shaq'],
    },
    {
      name: 'Giannis Antetokounmpo',
      aliases: ['Giannis', 'Greek Freak', 'Antetokounmpo'],
      emoji: '🇬🇷🦌🏀',
      group: 'Basket',
      tags: ['homme', 'grec', 'europe', 'basket', 'nba', 'sport-collectif', 'en-activité'],
      clues: ['Ailier fort grec d’origine nigériane', 'Vendait des objets dans la rue enfant', 'Longtemps à Milwaukee', 'Titre NBA 2021', 'Deux fois MVP de la saison', 'Surnommé « Greek Freak »'],
    },
    // ── Tennis ──
    {
      name: 'Serena Williams',
      aliases: ['Serena'],
      emoji: '🎾👑🇺🇸',
      group: 'Tennis',
      tags: ['femme', 'américain', 'amérique-du-nord', 'tennis', 'sport-individuel', 'retraité', 'champion-olympique', 'numéro-1-mondial', 'grand-chelem', 'légende'],
      clues: ['Joueuse de tennis américaine surpuissante', 'Joue souvent en double avec sa sœur', '23 titres du Grand Chelem en simple', 'Championne olympique en 2012', 'Retraitée en 2022', 'Sœur de Venus'],
    },
    {
      name: 'Rafael Nadal',
      aliases: ['Nadal', 'Rafa'],
      emoji: '🎾🧱🐂',
      group: 'Tennis',
      tags: ['homme', 'espagnol', 'europe', 'tennis', 'sport-individuel', 'retraité', 'champion-olympique', 'gaucher', 'numéro-1-mondial', 'grand-chelem'],
      clues: ['Tennisman espagnol gaucher', 'Né sur l’île de Majorque', 'Mord ses trophées pour les photos', '14 titres à Roland-Garros', 'Statue à la porte d’Auteuil', 'Rafa, retraité en 2024'],
    },
    {
      name: 'Roger Federer',
      aliases: ['Federer', 'RF', 'Rodgeur'],
      emoji: '🎾🇨🇭🍫',
      group: 'Tennis',
      tags: ['homme', 'suisse', 'europe', 'tennis', 'sport-individuel', 'retraité', 'champion-olympique', 'numéro-1-mondial', 'grand-chelem', 'légende'],
      clues: ['Tennisman suisse au style élégant', 'Revers à une main magnifique', 'Huit titres à Wimbledon', '20 titres du Grand Chelem', 'Retraité en 2022', 'Surnommé RF, le Maestro'],
    },
    {
      name: 'Novak Djokovic',
      aliases: ['Djokovic', 'Djoko', 'Nole'],
      emoji: '🎾🇷🇸🤸',
      group: 'Tennis',
      tags: ['homme', 'serbe', 'europe', 'tennis', 'sport-individuel', 'champion-olympique', 'médaillé-paris-2024', 'numéro-1-mondial', 'grand-chelem'],
      clues: ['Tennisman serbe à la souplesse incroyable', 'Recordman de titres du Grand Chelem', 'Roi de l’Open d’Australie', 'Champion olympique à Paris 2024', 'Record de semaines comme numéro 1', 'Surnommé Djoko ou Nole'],
    },
    {
      name: 'Carlos Alcaraz',
      aliases: ['Alcaraz', 'Carlitos'],
      emoji: '🎾🇪🇸🔥',
      group: 'Tennis',
      tags: ['homme', 'espagnol', 'europe', 'tennis', 'sport-individuel', 'en-activité', 'médaillé-paris-2024', 'nouvelle-génération', 'numéro-1-mondial', 'grand-chelem'],
      clues: ['Jeune tennisman espagnol explosif', 'Né près de Murcie en 2003', 'Plus jeune numéro 1 mondial de l’histoire', 'Vainqueur de Roland-Garros et de Wimbledon', 'Vice-champion olympique à Paris 2024', 'Surnommé Carlitos'],
    },
    {
      name: 'Jannik Sinner',
      aliases: ['Sinner', 'Jannik'],
      emoji: '🎾🇮🇹🦊',
      group: 'Tennis',
      tags: ['homme', 'italien', 'europe', 'tennis', 'sport-individuel', 'en-activité', 'nouvelle-génération', 'numéro-1-mondial', 'grand-chelem'],
      clues: ['Tennisman italien aux cheveux roux', 'Ancien espoir du ski dans les Dolomites', 'Vainqueur de l’Open d’Australie 2024', 'Numéro 1 mondial dès 2024', 'Vainqueur de Wimbledon 2025', 'Jannik, rival d’Alcaraz'],
    },
    {
      name: 'Yannick Noah',
      aliases: ['Noah', 'Yannick'],
      emoji: '🎾🇫🇷🎤',
      group: 'Tennis',
      tags: ['homme', 'français', 'europe', 'tennis', 'sport-individuel', 'retraité', 'grand-chelem'],
      clues: ['Tennisman français aux dreadlocks', 'Repéré par Arthur Ashe au Cameroun', 'Vainqueur de Roland-Garros en 1983', 'Capitaine vainqueur de la Coupe Davis', 'Devenu chanteur populaire', 'Yannick, père d’un joueur NBA'],
    },
    // ── Athlétisme ──
    {
      name: 'Usain Bolt',
      aliases: ['Bolt', 'Lightning Bolt'],
      emoji: '⚡🏃‍♂️🇯🇲',
      group: 'Athlétisme',
      tags: ['homme', 'jamaïcain', 'amérique-du-nord', 'athlétisme', 'sport-individuel', 'retraité', 'champion-olympique', 'record-du-monde', 'champion-du-monde'],
      clues: ['Sprinteur jamaïcain très grand', 'Pose de l’éclair après ses victoires', 'Record du monde du 100 m en 9 s 58', 'Huit titres olympiques', 'Doublé 100-200 m sur trois Jeux', 'Surnommé « Lightning »'],
    },
    {
      name: 'Carl Lewis',
      aliases: ['Lewis'],
      emoji: '🏃‍♂️🦘🇺🇸',
      group: 'Athlétisme',
      tags: ['homme', 'américain', 'amérique-du-nord', 'athlétisme', 'sport-individuel', 'retraité', 'champion-olympique', 'record-du-monde', 'champion-du-monde'],
      clues: ['Athlète américain des années 1980-90', 'Excellait au sprint et au saut en longueur', 'Neuf médailles d’or olympiques', 'Quatre titres aux JO de Los Angeles 1984', 'Surnommé « le Fils du vent »', 'Carl, roi de la longueur'],
    },
    {
      name: 'Marie-José Pérec',
      aliases: ['Pérec', 'Perec', 'Marie-Jo'],
      emoji: '🦌🏃‍♀️🇫🇷',
      group: 'Athlétisme',
      tags: ['femme', 'français', 'europe', 'athlétisme', 'sport-individuel', 'retraité', 'champion-olympique', 'champion-du-monde'],
      clues: ['Athlète française à la foulée immense', 'Née en Guadeloupe', 'Doublé 200-400 m à Atlanta en 1996', 'Triple championne olympique', 'Surnommée « la Gazelle »', 'Marie-Jo, dernière relayeuse de la flamme en 2024'],
    },
    {
      name: 'Armand Duplantis',
      aliases: ['Duplantis', 'Mondo', 'Mondo Duplantis'],
      emoji: '🦘📏🇸🇪',
      group: 'Athlétisme',
      tags: ['homme', 'suédois', 'europe', 'athlétisme', 'sport-individuel', 'en-activité', 'champion-olympique', 'record-du-monde', 'champion-du-monde', 'médaillé-paris-2024', 'nouvelle-génération'],
      clues: ['Perchiste suédois né aux États-Unis', 'Bat son record centimètre par centimètre', 'Double champion olympique', 'Record du monde au Stade de France en 2024', 'Premier à franchir plus de 6,20 m', 'Surnommé « Mondo »'],
    },
    {
      name: 'Eliud Kipchoge',
      aliases: ['Kipchoge', 'Eliud'],
      emoji: '🏃‍♂️🇰🇪⏱️',
      group: 'Athlétisme',
      tags: ['homme', 'kényan', 'afrique', 'athlétisme', 'sport-individuel', 'champion-olympique', 'record-du-monde', 'champion-du-monde'],
      clues: ['Coureur kényan légendaire', 'Spécialiste de la course sur route', 'Premier à courir un marathon en moins de 2 h', 'Double champion olympique du marathon', 'Ancien recordman du monde du marathon', 'Eliud, souriant même dans l’effort'],
    },
    // ── Formule 1 ──
    {
      name: 'Lewis Hamilton',
      aliases: ['Hamilton', 'Sir Lewis'],
      emoji: '🏎️🇬🇧🏆',
      group: 'Formule 1',
      tags: ['homme', 'britannique', 'europe', 'formule-1', 'sport-individuel', 'en-activité', 'champion-du-monde'],
      clues: ['Pilote britannique', 'Sept titres de champion du monde', 'Recordman de victoires en Grand Prix', 'Six titres avec Mercedes', 'Rejoint Ferrari en 2025', 'Lewis, anobli « Sir »'],
    },
    {
      name: 'Michael Schumacher',
      aliases: ['Schumacher', 'Schumi'],
      emoji: '🏎️🇩🇪🔴',
      group: 'Formule 1',
      tags: ['homme', 'allemand', 'europe', 'formule-1', 'sport-individuel', 'retraité', 'champion-du-monde'],
      clues: ['Pilote allemand des années 1990-2000', 'Sept titres de champion du monde', 'Cinq titres consécutifs avec Ferrari', 'Surnommé « le Baron rouge »', 'Son fils Mick a aussi piloté en F1', 'Surnommé Schumi'],
    },
    {
      name: 'Ayrton Senna',
      aliases: ['Senna', 'Ayrton'],
      emoji: '🏎️🇧🇷🌧️',
      group: 'Formule 1',
      tags: ['homme', 'brésilien', 'amérique-du-sud', 'formule-1', 'sport-individuel', 'décédé', 'champion-du-monde', 'légende'],
      clues: ['Pilote brésilien de légende', 'Trois titres de champion du monde', 'Rivalité mythique avec Alain Prost', 'Roi de la pluie et de Monaco', 'Décédé à Imola en 1994', 'Ayrton, casque jaune'],
    },
    {
      name: 'Max Verstappen',
      aliases: ['Verstappen', 'Max', 'Mad Max'],
      emoji: '🏎️🇳🇱🐂',
      group: 'Formule 1',
      tags: ['homme', 'néerlandais', 'europe', 'formule-1', 'sport-individuel', 'en-activité', 'champion-du-monde', 'nouvelle-génération'],
      clues: ['Pilote néerlandais très offensif', 'Plus jeune vainqueur d’un Grand Prix', 'Fils d’un ancien pilote de F1', 'Quatre titres mondiaux avec Red Bull', 'Soutenu par une marée orange', 'Surnommé « Mad Max »'],
    },
    {
      name: 'Alain Prost',
      aliases: ['Prost', 'le Professeur'],
      emoji: '🏎️🇫🇷🧠',
      group: 'Formule 1',
      tags: ['homme', 'français', 'europe', 'formule-1', 'sport-individuel', 'retraité', 'champion-du-monde'],
      clues: ['Pilote français des années 1980', 'Quatre titres de champion du monde', 'Pilotage calculateur et précis', 'Rivalité mythique avec Senna', 'Surnommé « le Professeur »', 'Alain, dernier Français champion du monde de F1'],
    },
    {
      name: 'Charles Leclerc',
      aliases: ['Leclerc', 'Charles'],
      emoji: '🏎️🇲🇨🔴',
      group: 'Formule 1',
      tags: ['homme', 'monégasque', 'europe', 'formule-1', 'sport-individuel', 'en-activité', 'nouvelle-génération'],
      clues: ['Pilote né en Principauté', 'Formé par l’académie Ferrari', 'Victoire à Monza dès 2019', 'Gagne enfin à domicile en 2024', 'Pilote de la Scuderia Ferrari', 'Charles, héros de Monaco'],
    },
    // ── Sports de combat ──
    {
      name: 'Muhammad Ali',
      aliases: ['Ali', 'Cassius Clay'],
      emoji: '🥊🦋🐝',
      group: 'Sports de combat',
      tags: ['homme', 'américain', 'amérique-du-nord', 'boxe', 'sport-de-combat', 'sport-individuel', 'décédé', 'champion-olympique', 'champion-du-monde', 'légende'],
      clues: ['Boxeur américain légendaire', 'Champion olympique en 1960', '« Vole comme un papillon, pique comme une abeille »', 'Combat mythique à Kinshasa en 1974', 'Surnommé « The Greatest »', 'Né Cassius Clay'],
    },
    {
      name: 'Francis Ngannou',
      aliases: ['Ngannou', 'The Predator'],
      emoji: '👊🇨🇲💥',
      group: 'Sports de combat',
      tags: ['homme', 'camerounais', 'afrique', 'mma', 'boxe', 'sport-de-combat', 'sport-individuel', 'champion-du-monde'],
      clues: ['Combattant né au Cameroun', 'A commencé la boxe à Paris', 'Ancien champion poids lourd de l’UFC', 'Frappe parmi les plus puissantes jamais mesurées', 'A affronté Tyson Fury en boxe', 'Surnommé « The Predator »'],
    },
    {
      name: 'Ciryl Gane',
      aliases: ['Gane', 'Bon Gamin'],
      emoji: '🥋🇫🇷👊',
      group: 'Sports de combat',
      tags: ['homme', 'français', 'europe', 'mma', 'sport-de-combat', 'sport-individuel', 'en-activité'],
      clues: ['Combattant français de MMA', 'Ancien pratiquant de muay-thaï', 'Champion intérimaire poids lourd UFC', 'Combat pour le titre contre Jon Jones', 'Surnommé « Bon Gamin »', 'Ciryl, originaire de Vendée'],
    },
    {
      name: 'Khabib Nurmagomedov',
      aliases: ['Khabib', 'The Eagle'],
      emoji: '🦅🤼‍♂️🇷🇺',
      group: 'Sports de combat',
      tags: ['homme', 'russe', 'europe', 'mma', 'sport-de-combat', 'sport-individuel', 'retraité', 'champion-du-monde'],
      clues: ['Combattant russe du Daghestan', 'Lutteur redoutable depuis l’enfance', 'Invaincu : 29 victoires en carrière', 'Champion des poids légers de l’UFC', 'Porte un bonnet traditionnel', 'Surnommé « The Eagle »'],
    },
    {
      name: 'Estelle Mossely',
      aliases: ['Mossely'],
      emoji: '🥊🇫🇷🥇',
      group: 'Sports de combat',
      tags: ['femme', 'français', 'europe', 'boxe', 'sport-de-combat', 'sport-individuel', 'champion-olympique', 'champion-du-monde'],
      clues: ['Boxeuse française', 'Championne du monde amateur en 2016', 'Championne olympique à Rio en 2016', 'Titrée le même soir que son compagnon', 'Première Française championne olympique de boxe', 'Estelle, compagne du boxeur Tony Yoka'],
    },
    // ── Natation ──
    {
      name: 'Michael Phelps',
      aliases: ['Phelps'],
      emoji: '🏊‍♂️🦈🥇',
      group: 'Natation',
      tags: ['homme', 'américain', 'amérique-du-nord', 'natation', 'sport-individuel', 'retraité', 'champion-olympique', 'record-du-monde', 'champion-du-monde'],
      clues: ['Nageur américain à l’envergure immense', 'Athlète le plus médaillé des JO', '23 médailles d’or olympiques', 'Huit titres aux JO de Pékin 2008', 'Surnommé « le Requin de Baltimore »', 'Michael, entraîné par Bob Bowman'],
    },
    {
      name: 'Léon Marchand',
      aliases: ['Marchand', 'Léon'],
      emoji: '🏊‍♂️🇫🇷🥇',
      group: 'Natation',
      tags: ['homme', 'français', 'europe', 'natation', 'sport-individuel', 'en-activité', 'champion-olympique', 'médaillé-paris-2024', 'record-du-monde', 'champion-du-monde', 'nouvelle-génération'],
      clues: ['Nageur français né à Toulouse', 'Entraîné aux États-Unis par Bob Bowman', 'Spécialiste des quatre nages', 'Quatre titres olympiques à Paris 2024', 'Idole de La Défense Arena', 'Léon, fils de nageurs olympiques'],
    },
    {
      name: 'Florent Manaudou',
      aliases: ['Florent', 'F. Manaudou'],
      emoji: '🏊‍♂️🇫🇷💪',
      group: 'Natation',
      tags: ['homme', 'français', 'europe', 'natation', 'sport-individuel', 'champion-olympique', 'médaillé-paris-2024', 'champion-du-monde'],
      clues: ['Sprinteur français des bassins', 'Champion olympique du 50 m en 2012', 'Médaillé sur quatre Jeux différents', 'Porte-drapeau à Paris 2024', 'Frère d’une championne olympique', 'Florent, géant du 50 m'],
    },
    {
      name: 'Laure Manaudou',
      aliases: ['Laure'],
      emoji: '🏊‍♀️🇫🇷🥇',
      group: 'Natation',
      tags: ['femme', 'français', 'europe', 'natation', 'sport-individuel', 'retraité', 'champion-olympique', 'record-du-monde', 'champion-du-monde'],
      clues: ['Nageuse française des années 2000', 'Entraînée par Philippe Lucas', 'Championne olympique du 400 m à Athènes', 'Record du monde du 400 m libre', 'Sœur d’un champion olympique', 'Laure, star de la natation française'],
    },
    {
      name: 'Katie Ledecky',
      aliases: ['Ledecky', 'Katie'],
      emoji: '🏊‍♀️🇺🇸🥇',
      group: 'Natation',
      tags: ['femme', 'américain', 'amérique-du-nord', 'natation', 'sport-individuel', 'en-activité', 'champion-olympique', 'médaillé-paris-2024', 'record-du-monde', 'champion-du-monde', 'nouvelle-génération'],
      clues: ['Nageuse américaine de demi-fond', 'Championne olympique à 15 ans en 2012', 'Reine du 800 m nage libre', 'Titres sur quatre Jeux consécutifs', 'Nageuse la plus titrée de l’histoire', 'Katie, recordwoman du 1500 m'],
    },
    // ── Judo ──
    {
      name: 'Teddy Riner',
      aliases: ['Riner', 'Teddy', 'Big Ted'],
      emoji: '🥋🇫🇷🐻',
      group: 'Judo',
      tags: ['homme', 'français', 'europe', 'judo', 'sport-de-combat', 'sport-individuel', 'en-activité', 'champion-olympique', 'médaillé-paris-2024', 'champion-du-monde'],
      clues: ['Judoka français de plus de deux mètres', 'Plus de dix titres de champion du monde', 'Invaincu pendant près de dix ans', 'Champion olympique en 2012, 2016 et 2024', 'A allumé la vasque à Paris 2024', 'Surnommé Teddy Bear'],
    },
    {
      name: 'Clarisse Agbégnénou',
      aliases: ['Agbégnénou', 'Agbegnenou', 'Clarisse'],
      emoji: '🥋🇫🇷💥',
      group: 'Judo',
      tags: ['femme', 'français', 'europe', 'judo', 'sport-de-combat', 'sport-individuel', 'champion-olympique', 'champion-du-monde'],
      clues: ['Judokate française explosive', 'Combat chez les moins de 63 kg', 'Six fois championne du monde', 'Double championne olympique à Tokyo', 'Porte-drapeau des Bleus à Tokyo', 'Clarisse, reine du tatami'],
    },
    {
      name: 'David Douillet',
      aliases: ['Douillet'],
      emoji: '🥋🇫🇷🏛️',
      group: 'Judo',
      tags: ['homme', 'français', 'europe', 'judo', 'sport-de-combat', 'sport-individuel', 'retraité', 'champion-olympique', 'champion-du-monde'],
      clues: ['Judoka français poids lourd', 'Star du judo des années 1990', 'Champion olympique en 1996 et 2000', 'Quatre fois champion du monde', 'Devenu ministre des Sports', 'David, géant normand'],
    },
    // ── Rugby ──
    {
      name: 'Antoine Dupont',
      aliases: ['Dupont', 'Toto'],
      emoji: '🏉🇫🇷🥇',
      group: 'Rugby',
      tags: ['homme', 'français', 'europe', 'rugby', 'sport-collectif', 'en-activité', 'champion-olympique', 'médaillé-paris-2024', 'nouvelle-génération'],
      clues: ['Rugbyman français, demi de mêlée', 'Joue au Stade toulousain', 'Élu meilleur joueur du monde', 'Champion olympique de rugby à 7 en 2024', 'Capitaine du XV de France', 'Antoine, originaire du Gers'],
    },
    {
      name: 'Jonah Lomu',
      aliases: ['Lomu'],
      emoji: '🏉🇳🇿🦏',
      group: 'Rugby',
      tags: ['homme', 'néo-zélandais', 'océanie', 'rugby', 'sport-collectif', 'retraité', 'décédé'],
      clues: ['Ailier néo-zélandais colossal', 'Star de la Coupe du monde 1995', 'Quatre essais face à l’Angleterre en demi-finale', 'Joueur des All Blacks', 'Décédé en 2015', 'Jonah, premier phénomène du rugby pro'],
    },
    {
      name: 'Sébastien Chabal',
      aliases: ['Chabal', 'l’Homme des cavernes'],
      emoji: '🏉🧔🇫🇷',
      group: 'Rugby',
      tags: ['homme', 'français', 'europe', 'rugby', 'sport-collectif', 'retraité', 'consultant-tv'],
      clues: ['Rugbyman français barbu et chevelu', 'A joué à Sale, en Angleterre', 'Avant puissant du XV de France', 'Star du Mondial 2007 en France', 'Surnommé « l’Homme des cavernes »', 'Sébastien, devenu consultant télé'],
    },
    {
      name: 'Jonny Wilkinson',
      aliases: ['Wilkinson', 'Wilko'],
      emoji: '🏉🇬🇧🦶',
      group: 'Rugby',
      tags: ['homme', 'britannique', 'europe', 'rugby', 'sport-collectif', 'retraité', 'champion-du-monde'],
      clues: ['Ouvreur anglais au pied magique', 'Drop décisif en finale du Mondial 2003', 'Champion du monde avec l’Angleterre', 'A fini sa carrière à Toulon', 'Double champion d’Europe avec le RCT', 'Surnommé Wilko'],
    },
    {
      name: 'Siya Kolisi',
      aliases: ['Kolisi', 'Siya'],
      emoji: '🏉🇿🇦🏆',
      group: 'Rugby',
      tags: ['homme', 'sud-africain', 'afrique', 'rugby', 'sport-collectif', 'en-activité', 'champion-du-monde'],
      clues: ['Troisième ligne sud-africain', 'Premier capitaine noir des Springboks', 'Champion du monde 2019 et 2023', 'A joué au Racing 92', 'A grandi près de Port Elizabeth', 'Siya, capitaine emblématique'],
    },
    // ── Cyclisme ──
    {
      name: 'Tadej Pogačar',
      aliases: ['Pogačar', 'Pogacar', 'Pogi'],
      emoji: '🚴‍♂️🇸🇮💛',
      group: 'Cyclisme',
      tags: ['homme', 'slovène', 'europe', 'cyclisme', 'sport-individuel', 'en-activité', 'champion-du-monde', 'nouvelle-génération'],
      clues: ['Cycliste slovène', 'Vainqueur du Tour de France à 21 ans', 'Doublé Giro-Tour en 2024', 'Champion du monde sur route 2024', 'Attaques de très loin', 'Surnommé Pogi'],
    },
    {
      name: 'Bernard Hinault',
      aliases: ['Hinault', 'le Blaireau'],
      emoji: '🚴‍♂️🦡🇫🇷',
      group: 'Cyclisme',
      tags: ['homme', 'français', 'europe', 'cyclisme', 'sport-individuel', 'retraité', 'champion-du-monde'],
      clues: ['Cycliste breton', 'Cinq victoires au Tour de France', 'Dernier Français vainqueur du Tour, en 1985', 'Champion du monde en 1980', 'Surnommé « le Blaireau »', 'Bernard, caractère bien trempé'],
    },
    {
      name: 'Eddy Merckx',
      aliases: ['Merckx', 'le Cannibale'],
      emoji: '🚴‍♂️🇧🇪🍴',
      group: 'Cyclisme',
      tags: ['homme', 'belge', 'europe', 'cyclisme', 'sport-individuel', 'retraité', 'champion-du-monde', 'légende'],
      clues: ['Cycliste belge légendaire', 'Cinq Tours de France gagnés', 'Cinq Tours d’Italie également', 'Record de victoires professionnelles', 'Surnommé « le Cannibale »', 'Eddy, star des années 1970'],
    },
    // ── Autres ──
    {
      name: 'Tiger Woods',
      aliases: ['Tiger', 'Woods'],
      emoji: '⛳🐯🇺🇸',
      group: 'Golf',
      tags: ['homme', 'américain', 'amérique-du-nord', 'golf', 'sport-individuel', 'numéro-1-mondial', 'légende'],
      clues: ['Golfeur américain légendaire', 'Joue en polo rouge le dimanche', 'Quinze tournois majeurs gagnés', 'Victoire au Masters 2019 après des blessures', 'Prénom de naissance : Eldrick', 'Surnommé Tiger'],
    },
    {
      name: 'Nikola Karabatic',
      aliases: ['Karabatic', 'Niko'],
      emoji: '🤾‍♂️🇫🇷🏆',
      group: 'Handball',
      tags: ['homme', 'français', 'europe', 'handball', 'sport-collectif', 'retraité', 'champion-olympique', 'champion-du-monde'],
      clues: ['Handballeur français', 'Trois fois champion olympique', 'Quatre titres de champion du monde', 'Élu trois fois meilleur joueur du monde', 'Retraité après Paris 2024', 'Niko, frère de Luka'],
    },
    {
      name: 'Martin Fourcade',
      aliases: ['Fourcade'],
      emoji: '🎿🎯🇫🇷',
      group: 'Biathlon',
      tags: ['homme', 'français', 'europe', 'biathlon', 'sport-d-hiver', 'sport-individuel', 'retraité', 'champion-olympique', 'champion-du-monde'],
      clues: ['Biathlète français', 'Ski de fond et tir à la carabine', 'Cinq titres olympiques', 'Sept gros globes de cristal consécutifs', 'Originaire des Pyrénées', 'Martin, retraité en 2020'],
    },
    {
      name: 'Simone Biles',
      aliases: ['Biles', 'Simone'],
      emoji: '🤸‍♀️🐐🇺🇸',
      group: 'Gymnastique',
      tags: ['femme', 'américain', 'amérique-du-nord', 'gymnastique', 'sport-individuel', 'champion-olympique', 'médaillé-paris-2024', 'champion-du-monde', 'nouvelle-génération'],
      clues: ['Gymnaste américaine', 'Plusieurs figures portent son nom', 'Gymnaste la plus titrée de l’histoire', 'A mis en avant la santé mentale à Tokyo', 'Retour en or à Paris 2024', 'Simone, 1,42 m de puissance'],
    },
  ],
};
